/**
 * One shared word inside a sentence of the learner's own is not a choice
 * (2026-09-28, physics certification, phys.mech.work-energy-theorem r1 s5).
 * With "State the work–energy theorem" on screen, the learner typed the
 * misconception "I think it is at rest — zero work means zero kinetic energy".
 * Rule 4a matched "kinetic" (only the correct option says it), banked a correct
 * answer and the tutor replied "That's right."
 */
import { describe, it, expect } from 'vitest'
import { gradeMcqAnswer, type TutorMCQ } from '@/lib/teaching/mcq'

const THEOREM: TutorMCQ = {
  question: 'State the work–energy theorem.',
  options: [
    'The net work done on an object equals its total energy',
    'The net work done on an object equals the change in its potential energy',
    'The net work done on an object equals its change in momentum',
    'The NET work done on an object equals the change in its kinetic energy',
  ],
  correctIndex: 3,
}
const SHM: TutorMCQ = {
  question: 'Where is the pendulum fastest?',
  options: ['At the highest point on the left', 'At the highest point on the right', 'At the LOWEST point in the MIDDLE', 'It moves at a constant speed'],
  correctIndex: 2,
}

describe('rule 4a', () => {
  it('the production misconception is not graded as the correct option', () => {
    expect(gradeMcqAnswer('I think it is at rest — zero work means zero kinetic energy', THEOREM))
      .toEqual({ chosenIndex: null, correct: null })
  })
  it('the short answer rule 4a was written for still grades', () => {
    expect(gradeMcqAnswer('i think it is the lowest point sir', SHM)).toEqual({ chosenIndex: 2, correct: true })
  })
  it('stronger rules are untouched: quoting the option grades', () => {
    expect(gradeMcqAnswer('the net work done on an object equals the change in its kinetic energy', THEOREM).correct).toBe(true)
  })
})

describe('rule 4: two shared words inside an unrelated claim (phys.mech.poisson-brackets r1 s5)', () => {
  const LZ: TutorMCQ = {
    question: 'For a central-force problem, {L_z,H}=0. What does this bracket vanishing actually mean?',
    options: [
      'L_z is conserved under the Hamiltonian flow generated by H — the bracket vanishing is a statement about dynamics (L_z does not change over time), not about L_z and H being unrelated',
      'L_z and H are independent, unrelated functions that do not interact with each other',
    ],
    correctIndex: 0,
  }
  it('the misconception about a different bracket is not graded', () => {
    expect(gradeMcqAnswer('I think {x,p}={p,x}, since the Poisson bracket is symmetric like a dot product, so order of arguments does not matter', LZ).chosenIndex).toBeNull()
  })
  it('a paraphrase of the option still grades', () => {
    expect(gradeMcqAnswer('L_z is conserved — the bracket vanishing means it does not change over time under the flow', LZ)).toEqual({ chosenIndex: 0, correct: true })
  })
})

describe('rule 5: a number word inside a sentence is not a value answer (phys.mech.cyclic-coordinates-conservation-laws r2 s5)', () => {
  const NOETHER: TutorMCQ = {
    question: 'A free particle moving in 1D has L=½mẋ². Does it have a Noether symmetry leading to a conserved quantity?',
    options: [
      'No — Noether symmetries require the system to look geometrically symmetric (spherical or cylindrical), and a point particle has no such shape',
      "Yes — L is independent of x (∂L/∂x=0), a genuine translational symmetry, so p_x is conserved by Noether's theorem, regardless of the absence of visible shape",
    ],
    correctIndex: 1,
  }
  it('"… that coordinate is zero or held constant …" is not graded', () => {
    expect(gradeMcqAnswer('I think a cyclic coordinate means that coordinate is zero or held constant throughout the motion', NOETHER).chosenIndex).toBeNull()
  })
  it('a bare value still grades', () => {
    const Q: TutorMCQ = { question: 'Net torque?', options: ['5 N·m', '10 N·m', '0 N·m'], correctIndex: 0 }
    expect(gradeMcqAnswer('i think 5', Q)).toEqual({ chosenIndex: 0, correct: true })
  })
})
