/**
 * Lesson completion (P6.6) — answering exactly one question:
 * "Has every required concept in this lesson been closed?"
 *
 * WHERE THE LESSON -> CONCEPT MAPPING COMES FROM (the mandatory first job):
 *
 * It already exists, in the canonical Knowledge Graph. The chat route builds
 * `syntheticLessons` from getKnowledgeGraph(subjectCode) by flattening
 * modules -> nodes, and each KG NODE becomes exactly one lesson:
 *
 *     module.nodes.map((node, i) => ({ lesson: i + 1, lessonTitle: node.title,
 *                                      topicSlug: node.slug, ... }))
 *     resolvedConceptId = currentLesson.topicSlug
 *
 * So in this runtime a lesson IS a concept — the mapping is 1:1 and the KG is
 * its owner. That is why no lesson->concept structure is invented here: there
 * is nothing to invent, only something to read. requiredConceptsForLesson()
 * returns a LIST rather than a single id purely so a future multi-concept
 * lesson needs no signature change; it does not imply a second structure.
 *
 * Pure functions only. Completion is decided from the persisted LessonAttempt
 * evidence (P6.5) — never heuristically, never from model output, never from
 * the client.
 */

import type { LessonAttemptOutcome } from './lessonAttempt'
import type { LessonSummary } from './lessonSummary'

/**
 * The concepts a lesson requires. Sourced from the caller's already-resolved
 * lesson identity (the KG node behind this lesson), so this never re-derives
 * curriculum structure.
 *
 * Returns [] when no concept is resolved — and an empty requirement can never
 * complete a lesson (see areAllRequiredConceptsClosed), which is what stops an
 * unresolved lesson from being marked complete by accident.
 */
export function requiredConceptsForLesson(resolvedConceptId: string | null | undefined): string[] {
  const id = resolvedConceptId?.trim()
  return id ? [id] : []
}

/** Every concept the attempt has closed — mastered or budget-spent. Both count
 *  as closed; that is the P6 definition and it is not re-decided here. */
export function closedConceptIds(attempt: LessonAttemptOutcome): string[] {
  return [...attempt.conceptsMastered, ...attempt.conceptsNeedingReview]
}

/**
 * The completion test. True only when the lesson has at least one required
 * concept AND every one of them appears in the attempt's closed evidence.
 *
 * Deliberately NOT satisfied by an empty requirement list: "no concepts
 * required" must never read as "all concepts done", or an unresolved lesson
 * would silently complete itself.
 */
export function areAllRequiredConceptsClosed(
  required: string[],
  attempt: LessonAttemptOutcome,
): boolean {
  if (required.length === 0) return false
  const closed = new Set(closedConceptIds(attempt))
  return required.every((id) => closed.has(id))
}

/**
 * Should this turn finalize the lesson? Combines the completion test with the
 * idempotence guard, so a second closing turn on an already-completed lesson
 * cannot finalize twice.
 */
export function shouldFinalizeLesson(
  required: string[],
  attempt: LessonAttemptOutcome,
): boolean {
  if (attempt.status === 'COMPLETED') return false
  return areAllRequiredConceptsClosed(required, attempt)
}

/** What the client needs to render the completion screen. */
export interface LessonCompletionPayload {
  complete: true
  lessonKey: string
  lessonTitle: string | null
  durationSeconds: number | null
  completedAt: string | null
  mastered: string[]
  needsReview: string[]
  corrected: string[]
  /** The lesson order to unlock next, when the lesson is curriculum-ordered. */
  nextLessonOrder: number | null
  /** True when every concept was mastered (nothing left for review). */
  fullyMastered: boolean
}

/**
 * Build the completion payload from the FINALISED attempt and the summary
 * that was built from its persisted evidence (P6.5). Nothing here is
 * regenerated by the model or recomputed from conversation memory.
 */
export function buildCompletionPayload(
  attempt: LessonAttemptOutcome,
  summary: LessonSummary,
  currentLessonOrder: number | null,
): LessonCompletionPayload {
  return {
    complete: true,
    lessonKey: attempt.lessonKey,
    lessonTitle: attempt.lessonTitle,
    durationSeconds: attempt.durationSeconds,
    completedAt: attempt.completedAt ? attempt.completedAt.toISOString() : null,
    mastered: summary.mastered.map((o) => o.conceptId),
    needsReview: summary.needsReview.map((o) => o.conceptId),
    corrected: summary.corrected.map((o) => o.conceptId),
    nextLessonOrder:
      typeof currentLessonOrder === 'number' && Number.isFinite(currentLessonOrder) && currentLessonOrder > 0
        ? currentLessonOrder + 1
        : null,
    fullyMastered: summary.complete,
  }
}

/**
 * The lesson close, rendered deterministically from persisted evidence.
 *
 * WHY THIS IS A RUNTIME VALUE AND NOT A PROMPT INSTRUCTION. The completion
 * GATE (`lessonCompleted` -> D-0a -> SERVE_LESSON_COMPLETE) is read at the
 * START of a turn from the previously-persisted attempt, but the completion
 * EVENT happens at the END of a turn, once this turn's evidence has been
 * folded. On the turn that actually finalises a lesson the gate was therefore
 * still false, the turn ran as an ordinary teaching turn, and the model had
 * already produced a new question by the time completion was decided — so the
 * response carried "lesson finished" AND another teaching question together.
 * buildLessonCompleteBlock() below could not prevent that: it is prompt text,
 * it is only injected on LATER turns, and a prompt instruction is advisory.
 *
 * The caller replaces the outgoing text with this on the finalising turn, so
 * the close is enforced by the runtime rather than requested from the model.
 *
 * Single owner: this is also what the already-complete serve path renders, so
 * the two cannot drift into two different closes.
 */
export function buildLessonCloseText(
  lessonTitle: string | null | undefined,
  summary: Pick<LessonSummary, 'mastered' | 'needsReview'>,
  opts?: { alreadyFinished?: boolean },
): string {
  const title = lessonTitle?.trim() || 'this lesson'
  const parts: string[] = [
    opts?.alreadyFinished
      ? `You've already finished ${title}.`
      : `That's ${title} finished — nice work.`,
  ]
  if (summary.mastered.length > 0) {
    parts.push(`You mastered: ${summary.mastered.map((o) => o.title).join(', ')}.`)
  }
  if (summary.needsReview.length > 0) {
    parts.push(`Worth another look later: ${summary.needsReview.map((o) => o.title).join(', ')}.`)
  }
  parts.push('Press "Start next lesson" whenever you\'re ready to carry on.')
  return parts.join(' ')
}

/**
 * The prompt contract for a turn that completes the lesson. The tutor delivers
 * the close and STOPS — it must not open new content, because the lesson is
 * over. This is what prevents the "Lesson complete... let's continue" failure.
 */
export function buildLessonCompleteBlock(): string {
  return (
    '\n\nLESSON COMPLETE (mandatory): this lesson is finished. Deliver the '
    + 'summary above, congratulate them briefly and specifically, and STOP. Do '
    + 'NOT teach anything new, do NOT ask another question, do NOT start the '
    + 'next concept, and do NOT say anything like "let\'s continue" — the '
    + 'learner chooses when to start the next lesson.'
  )
}
