/**
 * Lesson completion (P6.6) — answering exactly one question:
 * "Has every required concept in this lesson been closed?"
 *
 * WHERE THE LESSON -> CONCEPT MAPPING COMES FROM (the mandatory first job):
 *
 * It already exists, in the canonical Knowledge Graph. The chat route builds
 * `syntheticLessons` from getKnowledgeGraph(subjectCode) by flattening
 * modules -> nodes, and each KG NODE becomes exactly one lesson:
 *
 *     module.nodes.map((node, i) => ({ lesson: i + 1, lessonTitle: node.title,
 *                                      topicSlug: node.slug, ... }))
 *     resolvedConceptId = currentLesson.topicSlug
 *
 * So in this runtime a lesson IS a concept — the mapping is 1:1 and the KG is
 * its owner. That is why no lesson->concept structure is invented here: there
 * is nothing to invent, only something to read. requiredConceptsForLesson()
 * returns a LIST rather than a single id purely so a future multi-concept
 * lesson needs no signature change; it does not imply a second structure.
 *
 * Pure functions only. Completion is decided from the persisted LessonAttempt
 * evidence (P6.5) — never heuristically, never from model output, never from
 * the client.
 */

import type { LessonAttemptOutcome } from './lessonAttempt'
import type { LessonSummary } from './lessonSummary'
import { t, type Lang } from '@/lib/i18n'
import { safeConceptTitle } from '@/lib/curriculum/knowledgeGraph'

/**
 * The concepts a lesson requires. Sourced from the caller's already-resolved
 * lesson identity (the KG node behind this lesson), so this never re-derives
 * curriculum structure.
 *
 * Returns [] when no concept is resolved — and an empty requirement can never
 * complete a lesson (see areAllRequiredConceptsClosed), which is what stops an
 * unresolved lesson from being marked complete by accident.
 */
export function requiredConceptsForLesson(resolvedConceptId: string | null | undefined): string[] {
  const id = resolvedConceptId?.trim()
  return id ? [id] : []
}

/** Every concept the attempt has closed — mastered or budget-spent. Both count
 *  as closed; that is the P6 definition and it is not re-decided here. */
export function closedConceptIds(attempt: LessonAttemptOutcome): string[] {
  return [...attempt.conceptsMastered, ...attempt.conceptsNeedingReview]
}

/**
 * The completion test. True only when the lesson has at least one required
 * concept AND every one of them appears in the attempt's closed evidence.
 *
 * Deliberately NOT satisfied by an empty requirement list: "no concepts
 * required" must never read as "all concepts done", or an unresolved lesson
 * would silently complete itself.
 */
export function areAllRequiredConceptsClosed(
  required: string[],
  attempt: LessonAttemptOutcome,
): boolean {
  if (required.length === 0) return false
  const closed = new Set(closedConceptIds(attempt))
  return required.every((id) => closed.has(id))
}

/**
 * Should this turn finalize the lesson? Combines the completion test with the
 * idempotence guard, so a second closing turn on an already-completed lesson
 * cannot finalize twice.
 */
export function shouldFinalizeLesson(
  required: string[],
  attempt: LessonAttemptOutcome,
): boolean {
  if (attempt.status === 'COMPLETED') return false
  return areAllRequiredConceptsClosed(required, attempt)
}

/** What the client needs to render the completion screen. */
export interface LessonCompletionPayload {
  complete: true
  lessonKey: string
  lessonTitle: string | null
  durationSeconds: number | null
  completedAt: string | null
  mastered: string[]
  needsReview: string[]
  corrected: string[]
  /** The lesson order to unlock next, when the lesson is curriculum-ordered. */
  nextLessonOrder: number | null
  /** True when every concept was mastered (nothing left for review). */
  fullyMastered: boolean
}

/**
 * Build the completion payload from the FINALISED attempt and the summary
 * that was built from its persisted evidence (P6.5). Nothing here is
 * regenerated by the model or recomputed from conversation memory.
 */
export function buildCompletionPayload(
  attempt: LessonAttemptOutcome,
  summary: LessonSummary,
  currentLessonOrder: number | null,
  /** Learner's language + resolved concept, so the completion CARD renders a
   *  localized lesson name. Optional: omitting them reproduces the previous
   *  English-title behaviour exactly, so existing callers are unchanged. */
  opts?: { lang?: Lang; conceptId?: string | null },
): LessonCompletionPayload {
  const lang: Lang = opts?.lang ?? 'en'
  return {
    complete: true,
    lessonKey: attempt.lessonKey,
    // The card rendered "Урок завершён — Nature of Matter": its Russian half
    // is a UI string from i18n, its title half came straight from the KG in
    // English. Same resolver as the close text, so card and message can never
    // disagree — and an internal id can reach neither.
    lessonTitle: safeConceptTitle(opts?.conceptId, attempt.lessonTitle, lang) ?? attempt.lessonTitle,
    durationSeconds: attempt.durationSeconds,
    completedAt: attempt.completedAt ? attempt.completedAt.toISOString() : null,
    mastered: summary.mastered.map((o) => o.conceptId),
    needsReview: summary.needsReview.map((o) => o.conceptId),
    corrected: summary.corrected.map((o) => o.conceptId),
    nextLessonOrder:
      typeof currentLessonOrder === 'number' && Number.isFinite(currentLessonOrder) && currentLessonOrder > 0
        ? currentLessonOrder + 1
        : null,
    fullyMastered: summary.complete,
  }
}

/**
 * The lesson close, rendered deterministically from persisted evidence.
 *
 * WHY THIS IS A RUNTIME VALUE AND NOT A PROMPT INSTRUCTION. The completion
 * GATE (`lessonCompleted` -> D-0a -> SERVE_LESSON_COMPLETE) is read at the
 * START of a turn from the previously-persisted attempt, but the completion
 * EVENT happens at the END of a turn, once this turn's evidence has been
 * folded. On the turn that actually finalises a lesson the gate was therefore
 * still false, the turn ran as an ordinary teaching turn, and the model had
 * already produced a new question by the time completion was decided — so the
 * response carried "lesson finished" AND another teaching question together.
 * buildLessonCompleteBlock() below could not prevent that: it is prompt text,
 * it is only injected on LATER turns, and a prompt instruction is advisory.
 *
 * The caller replaces the outgoing text with this on the finalising turn, so
 * the close is enforced by the runtime rather than requested from the model.
 *
 * Single owner: this is also what the already-complete serve path renders, so
 * the two cannot drift into two different closes.
 */
export function buildLessonCloseText(
  lessonTitle: string | null | undefined,
  summary: Pick<LessonSummary, 'mastered' | 'needsReview'>,
  opts?: { alreadyFinished?: boolean; lang?: Lang; conceptId?: string | null },
): string {
  // WHY THIS TEXT WAS ENGLISH FOR RUSSIAN LEARNERS, AND WHY NO PROMPT FIX
  // COULD HAVE REACHED IT. Everything above in this file is deliberately
  // deterministic: the close is rendered by the RUNTIME from persisted
  // evidence and REPLACES the model's outgoing text (see the note on this
  // function above). That design is correct and is not changed here — but it
  // also means the close never passes through the LLM, so the system-prompt
  // language contract has no effect on it. It was the one learner-facing
  // string in the teaching path authored entirely in code, which is exactly
  // why it survived the language work that fixed everything around it.
  const lang: Lang = opts?.lang ?? 'en'

  // Localized lesson name; never an internal curriculum id.
  const title = safeConceptTitle(opts?.conceptId, lessonTitle, lang)

  const parts: string[] = [
    opts?.alreadyFinished
      ? title
        ? t(lang, 'lesson_close_already').replace('{title}', title)
        : t(lang, 'lesson_close_already_untitled')
      : title
        ? t(lang, 'lesson_close_done').replace('{title}', title)
        : t(lang, 'lesson_close_done_untitled'),
  ]
  if (summary.mastered.length > 0) {
    parts.push(t(lang, 'lesson_close_mastered').replace('{items}', conceptNames(summary.mastered, lang)))
  }
  if (summary.needsReview.length > 0) {
    parts.push(t(lang, 'lesson_close_review').replace('{items}', conceptNames(summary.needsReview, lang)))
  }
  parts.push(t(lang, 'lesson_close_next'))
  return parts.join(' ')
}

/** Concept names for the close, resolved through the same id-rejecting
 *  resolver the summary uses, so neither surface can leak an id. */
function conceptNames(outcomes: { conceptId: string; title: string }[], lang: Lang): string {
  return outcomes
    .map((o) => safeConceptTitle(o.conceptId, o.title, lang) ?? t(lang, 'lesson_close_generic_concept'))
    .join(', ')
}

/**
 * The prompt contract for a turn that completes the lesson. The tutor delivers
 * the close and STOPS — it must not open new content, because the lesson is
 * over. This is what prevents the "Lesson complete... let's continue" failure.
 */
export function buildLessonCompleteBlock(): string {
  return (
    '\n\nLESSON COMPLETE (mandatory): this lesson is finished. Deliver the '
    + 'summary above, congratulate them briefly and specifically, and STOP. Do '
    + 'NOT teach anything new, do NOT ask another question, do NOT start the '
    + 'next concept, and do NOT say anything like "let\'s continue" — the '
    + 'learner chooses when to start the next lesson.'
  )
}

/**
 * Root-cause fix (completion-lock investigation): appended AFTER
 * buildLessonCompleteBlock() above, ONLY on a turn where the runtime has
 * already determined (route.ts's excursion decision + genuine-question
 * detection, mirrored into the CUE as `newIntentAfterCompletion`) that the
 * learner's new message is genuine new intent — a real question, a
 * different topic, a different concept — rather than an acknowledgement or
 * a request to review/continue the completed lesson.
 *
 * The block above still stands (the lesson genuinely is finished and must
 * never be re-taught as unfinished), but this addendum lifts its blanket
 * "do NOT teach, do NOT ask another question" instruction specifically for
 * the learner's new request, so a valid follow-up or an unrelated question
 * actually gets answered instead of being silently refused or replaced with
 * filler. This is the LAST block appended for lesson-completion state, so
 * it is the instruction closest to the model's attention.
 */
export function buildLessonCompleteContinuationOverrideBlock(): string {
  return (
    '\n\nNEW REQUEST AFTER COMPLETION (overrides the "do NOT teach/ask" line '
    + 'above for THIS specific request only): the learner\'s latest message is '
    + 'a genuine question or a request about something else, not an '
    + 'acknowledgement of the close. Answer it directly and helpfully — do NOT '
    + 'refuse it, do NOT repeat the completion notice, do NOT ignore it and ask '
    + 'a generic reflection question instead. At the same time: do NOT treat '
    + 'the completed lesson as unfinished, do NOT reopen its mastery tracking, '
    + 'and do NOT present this as continuing the completed lesson unless the '
    + 'learner is specifically asking to review or continue it.'
  )
}

/**
 * F2 fix (completion-lock investigation, round 2): a narrow, deliberately
 * scoped gap-filler for the new-intent check above.
 *
 * PRODUCTION EVIDENCE (real account, real conversation, both a
 * pre-existing-completion lesson and one completed fresh in the same
 * session): "I still dont understand this", "hmm i dont understand this",
 * "i dont understand this", and "I have one question" were each served the
 * byte-identical canned reflection question — "Let me ask you something
 * concrete about {Lesson}: what's one thing you notice or find surprising
 * about what we just covered?" — instead of being treated as new intent.
 *
 * Three of those four ("I dont understand this" and its variants, "I'm
 * confused") are ALREADY correctly classified by the Recovery Engine's
 * `detectFailureState()` (recoveryGuard.ts) as `dont_understand` / `confused`
 * — a distress/help-seeking utterance, computed every turn regardless of
 * completion state (`recoveryKeyHoisted`). That existing, heavily-tested
 * signal is reused directly at the call site rather than re-detected here;
 * no new phrase list was needed for that class of failure.
 *
 * "I have one question" is different in kind — not a confusion statement
 * (recoveryGuard would not and should not fire on it) and not itself
 * interrogative (isGenuineQuestion would not and should not fire on it
 * either, since neither ends with "?" nor opens with a WH-word). It is an
 * explicit ANNOUNCEMENT that a question is coming. No existing primitive in
 * this codebase models that speech act, so this is a genuinely new, narrow
 * detector — deliberately scoped to exactly that announcement shape, and
 * used ONLY by the completion-continuation decision (never by
 * isGenuineQuestion or any other shared reader), so it cannot change
 * behavior anywhere else in the app.
 *
 * Explicitly excluded by design (verified against the negative-control
 * requirement — an acknowledgement must still lock the conversation):
 * "ok", "thanks", "got it", "okay, understood" — none contain "question" in
 * this announcement shape, so none match.
 */
const QUESTION_ANNOUNCEMENT_RE = /\bi\s*(?:'ve(?:\s+got)?|\s+have|\s+got)\s+(?:a|one|some)\s+questions?\b/i

export function isQuestionAnnouncement(message: string): boolean {
  return QUESTION_ANNOUNCEMENT_RE.test((message ?? '').trim())
}
