/**
 * IDEMPOTENT MASTERY-EVIDENCE WRITE.
 *
 * Why this module exists. The Library-mode checkpoint at
 * `/api/learn/chat` folded a graded SIGNAL into TopicProgress with
 * `attempts: { increment: 1 }`, fire-and-forget, unwrapped, ending in
 * `.catch(() => {})`. On 2026-08-16 a Prisma P1008 socket timeout ate one such
 * write in production and the learner's answer left no trace.
 *
 * The obvious repair — wrap it in `withRetry` — is WRONG on its own: a socket
 * timeout does not say whether the statement committed, so retrying a blind
 * increment can count one answer twice. Corrupting the evidence ledger in the
 * other direction is not an improvement.
 *
 * So the write is made idempotent FIRST, then retried.
 *
 * The identity is the learner's own `Message` row id — the utterance that
 * produced the evidence. It already exists, is generated by the database, and
 * is stable across every retry of the same turn, so nothing here invents a
 * second source of truth. It is stamped on the TopicProgress row it protects
 * (`lastEvidenceMessageId`), so the marker and the counter it guards commit in
 * the SAME row write and cannot disagree.
 *
 * Idempotency is enforced by the database, not by any in-memory flag:
 *
 *   UPDATE topic_progress
 *      SET attempts = attempts + 1, ..., lastEvidenceMessageId = $event
 *    WHERE (user, subject, topic) = ...
 *      AND (lastEvidenceMessageId IS NULL OR lastEvidenceMessageId <> $event)
 *      AND status NOT IN ('MASTERED','COMPLETED')
 *
 * One statement: the guard and the increment are evaluated under the row lock,
 * so a concurrent duplicate serialises behind it, re-reads the stamped marker
 * and matches zero rows. There is no read-then-write window to lose.
 *
 * What this deliberately does NOT change: the score values (65/25), the
 * never-certify rule (never writes MASTERED/COMPLETED), the MASTERED/COMPLETED
 * guard, or any mastery threshold, phase or counter meaning. The ladder is
 * untouched — this only stops one event being counted zero or twice.
 */

export type EvidenceApplyResult =
  /** The event was applied exactly now: attempts incremented by one. */
  | 'applied'
  /** This same event had already been applied — counted once, not twice. */
  | 'duplicate'
  /** The concept is already MASTERED/COMPLETED; conversational evidence may
   *  never overwrite a certified state (assessment/05 §3). */
  | 'locked'

export interface TopicProgressEvidenceArgs {
  userId: string
  subjectSlug: string
  topicSlug: string
  /** 65 for a correct signal, 25 otherwise — the school checkpoint's values,
   *  unchanged. */
  score: number
  /** Stable per-utterance identity. The learner Message row id. */
  eventId: string
}

/** The subset of Prisma this needs, so tests can drive it without a database. */
export interface TopicProgressDb {
  topicProgress: {
    updateMany(args: unknown): Promise<{ count: number }>
    /**
     * ON CONFLICT DO NOTHING, and the reason it replaced `create` here.
     *
     * MEASURED (production runtime logs, 2026-09-01): once a topic is
     * CERTIFIED, every subsequent turn on it ran updateMany (0 rows, the
     * guard excludes CERTIFIED) -> create -> UNIQUE VIOLATION -> catch. The
     * exception was always caught and the outcome was always the correct
     * 'locked', so nothing was broken — but Prisma logs the failed statement
     * itself, so a healthy lesson emitted
     *
     *   prisma:error Invalid `prisma.topicProgress.create()` invocation:
     *   Unique constraint failed on the fields: (`userId`,`subjectSlug`,`topicSlug`)
     *
     * on EVERY turn. That is not free: it is a benign error printed beside
     * real ones, and it cost real time twice in one day — I read it as a
     * defect, investigated it, and found it working as designed both times.
     * An error log should mean something is wrong.
     *
     * `createMany` with skipDuplicates reaches the identical decision without
     * raising: count 1 means this call inserted the row, count 0 means it was
     * already there. Every branch below is unchanged.
     */
    createMany(args: unknown): Promise<{ count: number }>
    findUnique(args: unknown): Promise<{ status: string } | null>
  }
}

const CERTIFIED = ['MASTERED', 'COMPLETED']

/**
 * Apply one graded-signal evidence event, exactly once.
 *
 * Safe to call repeatedly with the same `eventId` — by `withRetry`, by a
 * replayed request, or by two concurrent workers. Only the first call that
 * reaches the database increments.
 */
export async function applyTopicProgressEvidence(
  db: TopicProgressDb,
  args: TopicProgressEvidenceArgs,
): Promise<EvidenceApplyResult> {
  const { userId, subjectSlug, topicSlug, score, eventId } = args

  // The guarded increment. `OR [null, not eventId]` is required rather than a
  // bare `not`: SQL's `NULL <> 'x'` is NULL, not true, so a row that has never
  // carried a marker would silently fail to match.
  const guardedUpdate = () => db.topicProgress.updateMany({
    where: {
      userId, subjectSlug, topicSlug,
      status: { notIn: CERTIFIED },
      OR: [
        { lastEvidenceMessageId: null },
        { lastEvidenceMessageId: { not: eventId } },
      ],
    },
    data: {
      status: 'IN_PROGRESS',
      masteryPct: score,
      lastScore: score,
      attempts: { increment: 1 },
      lastEvidenceMessageId: eventId,
    },
  })

  const updated = await guardedUpdate()
  if (updated.count > 0) return 'applied'

  // Zero rows matched. Three possible reasons, and they are distinguishable
  // only by looking: no row yet, this event already applied, or certified.
  // Insert only if absent. See TopicProgressDb.createMany for why this is not
  // a `create` in a try/catch: the outcome is identical and this one does not
  // print a caught unique violation to the error log on every turn of an
  // already-certified topic.
  const inserted = await db.topicProgress.createMany({
    data: [{
      userId, subjectSlug, topicSlug,
      status: 'IN_PROGRESS',
      masteryPct: score,
      attempts: 1,
      lastScore: score,
      lastEvidenceMessageId: eventId,
    }],
    skipDuplicates: true,
  })
  if (inserted.count > 0) return 'applied'

  // The row existed after all — either a concurrent writer created it between
  // our update and our insert, or the guard excluded it. Re-run the guarded
  // update: it applies if the stamped marker is a DIFFERENT event, and stays a
  // no-op if it is ours.
  const second = await guardedUpdate()
  if (second.count > 0) return 'applied'

  const row = await db.topicProgress.findUnique({
    where: { userId_subjectSlug_topicSlug: { userId, subjectSlug, topicSlug } },
    select: { status: true },
  })
  return row && CERTIFIED.includes(row.status) ? 'locked' : 'duplicate'
}
