/**
 * Batch: cohomology, homotopy-equivalence, tychonoff (math.top) —
 * 16/23 -> 19/23.
 *
 * Fresh Phase 0 frontier recompute after covering-space, van-kampen, and
 * euler-characteristic were authored: the remaining 7 math.top concepts
 * (all domain leaves) stayed simultaneously ready. This batch closes out
 * homology's remaining unlock (cohomology), homotopy's remaining unlock
 * (homotopy-equivalence), and compactness' remaining unlock (tychonoff),
 * leaving 4 concepts (product-space, quotient-space, separation-axioms,
 * smooth-manifold) for subsequent batches.
 * Transcribed from their frozen Educational Brain entries at educational-
 * brain/concepts/mathematics/math.top.{cohomology,homotopy-equivalence,
 * tychonoff}.md.
 *
 * Grade band: GradeBand.UNDERGRADUATE, matching this domain's established
 * baseline.
 *
 * None of the 3 declare a KG cross-link.
 *
 * All 3 EB entries register exactly 3 formal misconceptions each (full
 * contract, no retargeting needed).
 *
 * Seeded as DRAFT. Promotion stays human.
 */
import { GradeBand, ProbeDifficulty } from '@prisma/client'
import type { SeedExplanation, SeedProbe } from './brainSeedAssets'

const S = 'mathematics'
const eb = (id: string, what: string) =>
  `educational-brain/concepts/mathematics/${id}.md — ${what}`

const COHOMOLOGY = 'math.top.cohomology'
const HOMOTOPY_EQUIVALENCE = 'math.top.homotopy-equivalence'
const TYCHONOFF = 'math.top.tychonoff'

export const MATHEMATICS_TOP_COHOMOLOGY_HOMOTOPY_EQUIVALENCE_TYCHONOFF_EXPLANATIONS: SeedExplanation[] = [
  {
    conceptId: COHOMOLOGY, subjectSlug: S, familyKind: 'core_explanation', gradeBand: GradeBand.UNDERGRADUATE,
    content:
      'Hⁿ(X) IS THE DUAL GROUP Hom(Hₙ(X),Z) — NEVER JUST ANOTHER NAME FOR Hₙ(X): for X=S¹: '
      + 'H₀(S¹)=Z, H₁(S¹)=Z (torsion-free). The universal coefficient theorem gives '
      + 'H⁰(S¹)=Hom(Z,Z)=Z and H¹(S¹)=Hom(Z,Z)=Z — numerically the SAME groups in this '
      + 'torsion-free case, but CONCEPTUALLY different objects: H¹(S¹) consists of homomorphisms '
      + 'FROM H₁(S¹) TO Z (ways of "measuring" the loop), never the loop-classes themselves. '
      + 'Believing Hⁿ(X) is just another notation for Hₙ(X), computed the same way, is WRONG — it '
      + 'is defined as the DUAL group, a conceptually different construction, even when the '
      + 'resulting groups happen to look numerically identical.\n\n'
      + 'THE CUP PRODUCT IS GENUINELY NEW RING STRUCTURE — NEVER JUST THE SAME GROUPS PRESENTED '
      + 'DIFFERENTLY: for X=T² (torus): H¹(T²)≅Z², generated by α,β. The cup product α⌣β∈H²(T²)≅Z '
      + 'is NONZERO (a generator), while α⌣α=0 and β⌣β=0 (forced by anticommutativity on odd '
      + 'degree: α⌣β=−β⌣α, so 2(α⌣α)=0, and torsion-freeness gives α⌣α=0). This multiplicative '
      + 'DISTINCTION has NO counterpart in bare homology groups. Believing cohomology\'s groups '
      + 'alone carry the same information as homology, just presented differently, is WRONG — the '
      + 'cup product makes H*(X)=⊕ₙHⁿ(X) a genuine RING, additional algebraic structure with no '
      + 'natural homology-side analogue.\n\n'
      + 'DE RHAM COHOMOLOGY AND SINGULAR COHOMOLOGY ARE ISOMORPHIC — NEVER UNRELATED INVARIANTS '
      + 'SHARING A NAME: on S¹, the 1-form dθ is CLOSED (d(dθ)=0 trivially) but NOT EXACT (no '
      + 'globally-defined smooth θ exists on S¹ itself — going around, θ increases by 2π) — so '
      + '[dθ] is a NONZERO class in H¹_dR(S¹), matching the nonzero singular class H¹(S¹;R)≅R '
      + 'found combinatorially. Believing de Rham cohomology (differential forms) and singular '
      + 'cohomology (chain complexes) are fundamentally different invariants that merely happen to '
      + 'share a name is WRONG — de Rham\'s theorem PROVES Hⁿ_dR(X)≅Hⁿ(X;R): two utterly '
      + 'different-looking constructions (analytic versus combinatorial) computing the IDENTICAL '
      + 'invariant.',
    targetedMisconceptions: [`${COHOMOLOGY}:MC-1`, `${COHOMOLOGY}:MC-2`, `${COHOMOLOGY}:MC-3`],
    source: eb(COHOMOLOGY, 'Core Understanding — Hn(X) being the dual group Hom(Hn(X),Z) never just another name for Hn(X), the cup product being genuinely new ring structure never just the same groups presented differently, and de Rham cohomology and singular cohomology being isomorphic never unrelated invariants sharing a name'),
  },
  {
    conceptId: HOMOTOPY_EQUIVALENCE, subjectSlug: S, familyKind: 'core_explanation', gradeBand: GradeBand.UNDERGRADUATE,
    content:
      'HOMOTOPY EQUIVALENCE IS STRICTLY WEAKER THAN HOMEOMORPHISM — NEVER THE SAME RELATION: [0,1] '
      + 'is contractible via H(x,t)=(1−t)x, giving the identity on [0,1] homotopic to the constant '
      + 'map at 0 — so [0,1] is homotopy equivalent to {0}. But [0,1] is NOT homeomorphic to {0} '
      + '(different numbers of points entirely). Homotopy equivalence allows "crushing" dimensions '
      + 'and structure that homeomorphism strictly forbids — every homeomorphism IS a homotopy '
      + 'equivalence (take g=f⁻¹, both compositions literally equal the identity), but the '
      + 'converse fails dramatically, as this example demonstrates.\n\n'
      + 'A DEFORMATION RETRACT REQUIRES CHECKING BOTH DIRECTIONS — NEVER JUST THE RETRACTION MAP '
      + 'ALONE: for r:R²\\{0}→S¹, r(x)=x/|x|, with H(x,t)=x/|x|^t: checking H(x,0)=x, H(x,1)=x/|x|'
      + '∈S¹, AND H(u,t)=u for u∈S¹ (since |u|=1) confirms r is a genuine retraction. But a '
      + 'DEFORMATION retract additionally requires i∘r homotopic to the identity on X, where '
      + 'i:S¹↪R²\\{0} is inclusion — the SAME homotopy H witnesses this second condition too. '
      + 'Checking ONLY that r∘i is the identity on the subspace (the "easy," exact direction) while '
      + 'forgetting i∘r is homotopic to the identity (the "up to homotopy" direction) misses half '
      + 'of what a deformation retract requires.\n\n'
      + 'CONTRACTIBLE AND COMPACT ARE LOGICALLY INDEPENDENT — NEVER CONFLATED: Rⁿ is CONTRACTIBLE '
      + '(via H(x,t)=(1−t)x, shrinking everything to the origin) but is NOT compact. Sⁿ is COMPACT '
      + 'but is NOT contractible (it has nontrivial higher homotopy groups, e.g. πₙ(Sⁿ)≅Z). The '
      + 'unit disk D² is BOTH contractible AND compact. All four combinations of {contractible, '
      + 'not contractible} × {compact, not compact} genuinely occur — "contractible" is a purely '
      + 'homotopy-theoretic deformation property, entirely independent of the metric/covering '
      + 'property "compact."',
    targetedMisconceptions: [`${HOMOTOPY_EQUIVALENCE}:MC-1`, `${HOMOTOPY_EQUIVALENCE}:MC-2`, `${HOMOTOPY_EQUIVALENCE}:MC-3`],
    source: eb(HOMOTOPY_EQUIVALENCE, 'Core Understanding — homotopy equivalence being strictly weaker than homeomorphism never the same relation, a deformation retract requiring both directions checked never just the retraction map alone, and contractible and compact being logically independent never conflated'),
  },
  {
    conceptId: TYCHONOFF, subjectSlug: S, familyKind: 'core_explanation', gradeBand: GradeBand.UNDERGRADUATE,
    content:
      'FINITE PRODUCTS EXTEND BY INDUCTION — INFINITE PRODUCTS STRUCTURALLY CANNOT: for three '
      + 'compact spaces X₁,X₂,X₃: compactness of X₁×X₂ follows from the 2-factor case, then '
      + '(X₁×X₂)×X₃ follows by applying the SAME 2-factor result again — a genuine inductive step, '
      + 'repeatable for ANY finite number of factors. But attempting this for INFINITELY many '
      + 'factors X₁,X₂,X₃,… fails structurally: induction only ever finishes after FINITELY many '
      + 'applications — there is no "last" pairing step to perform for an infinite family. '
      + 'Tychonoff\'s theorem for infinite products is NOT "the same induction, continued '
      + 'indefinitely" — it requires a genuinely different, non-inductive argument (via nets or '
      + 'ultrafilters) entirely.\n\n'
      + 'TYCHONOFF\'S THEOREM IS EQUIVALENT TO THE AXIOM OF CHOICE — NEVER MERELY A ONE-WAY '
      + 'CONSEQUENCE OF IT: for the SIMPLEST possible infinite product, the countable product of '
      + '2-point compact discrete spaces {0,1}: confirming compactness via the standard proof '
      + 'technique requires selecting a convergent subnet — built by choosing, for EACH of '
      + 'infinitely many coordinates, a consistent "eventual value" SIMULTANEOUSLY. This is EXACTLY '
      + 'the kind of infinitely-many-uncoordinated-selections operation the Axiom of Choice '
      + 'licenses, and for uncountable index sets is essentially unavoidable. Remarkably, the '
      + 'implication runs BACKWARD too: Tychonoff\'s theorem can itself be used to PROVE the Axiom '
      + 'of Choice — making the two logically EQUIVALENT within ZF, never merely "Choice implies '
      + 'Tychonoff" in one direction.\n\n'
      + 'TYCHONOFF\'S THEOREM IS THE SPECIFIC ENGINE BEHIND BANACH-ALAOGLU — NEVER A PURELY '
      + 'ABSTRACT GENERALIZATION WITH NO PAYOFF: the closed unit ball B* of a normed space V\'s '
      + 'dual V* is embedded into the product of intervals [−‖v‖,‖v‖], one compact interval factor '
      + 'PER VECTOR v∈V (an enormous, often uncountable index set), via φ↦(φ(v))_{v∈V}. Each '
      + 'factor is compact; Tychonoff\'s theorem then DIRECTLY guarantees the ENTIRE product is '
      + 'compact — and B*, embedded as a closed subset, is therefore ALSO compact (via the '
      + 'closed-subset-of-compact fact). This is the SPECIFIC mechanism, not background '
      + 'abstraction, making Banach-Alaoglu\'s surprising infinite-dimensional compactness result '
      + 'possible at all.',
    targetedMisconceptions: [`${TYCHONOFF}:MC-1`, `${TYCHONOFF}:MC-2`, `${TYCHONOFF}:MC-3`],
    source: eb(TYCHONOFF, 'Core Understanding — finite products extending by induction while infinite products structurally cannot, Tychonoff\'s theorem being equivalent to the Axiom of Choice never merely a one-way consequence of it, and Tychonoff\'s theorem being the specific engine behind Banach-Alaoglu never a purely abstract generalization with no payoff'),
  },
]

export const MATHEMATICS_TOP_COHOMOLOGY_HOMOTOPY_EQUIVALENCE_TYCHONOFF_PROBES: SeedProbe[] = [
  // COHOMOLOGY
  {
    conceptId: COHOMOLOGY, subjectSlug: S, probeKind: 'mcq', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.FOUNDATIONAL,
    stem: 'Is Hⁿ(X) just another name or notation for Hₙ(X), computed the same way?',
    choices: [
      { text: "No — Hn(X) is defined as the dual group Hom(Hn(X),Z); for S1, H1(S1)=Z and H1(S1)=Hom(Z,Z)=Z happen to be numerically the same group in this torsion-free case, but H1(S1) consists of homomorphisms FROM H1(S1) TO Z, a conceptually different construction, never the loop-classes themselves", isCorrect: true },
      { text: "Yes, Hn(X) is just another name or notation for Hn(X), computed the same way", isCorrect: false, misconceptionId: `${COHOMOLOGY}:MC-1` },
      { text: "Since the resulting groups often look numerically identical in torsion-free cases, cohomology should be treated as a relabeling of homology rather than a genuinely dual construction", isCorrect: false, misconceptionId: `${COHOMOLOGY}:MC-1` },
    ],
    targetedMisconceptions: [`${COHOMOLOGY}:MC-1`],
    source: eb(COHOMOLOGY, 'Discovery Question 1 as a detection probe (verbatim) — whether Hn(X) is just another name for Hn(X), an answer of "yes" confirming COHOMOLOGY-ASSUMED-SAME-AS-HOMOLOGY'),
  },
  {
    conceptId: COHOMOLOGY, subjectSlug: S, probeKind: 'misconception_probe', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.DEVELOPING,
    stem: 'Does cohomology, as a collection of groups Hⁿ(X), carry exactly the same information as homology, just presented differently?',
    choices: [
      { text: "No — for the torus T2, the cup product α⌣β∈H2(T2)≅Z is nonzero while α⌣α=0 and β⌣β=0, a multiplicative distinction with no counterpart in bare homology groups; the cup product makes H*(X) a genuine ring, additional algebraic structure homology alone cannot see", isCorrect: true },
      { text: "Yes, cohomology's groups alone carry exactly the same information as homology, just presented differently", isCorrect: false, misconceptionId: `${COHOMOLOGY}:MC-2` },
      { text: "Since cohomology is often introduced group-by-group, with the cup product treated as a later add-on, the groups alone should be considered a complete restatement of homology's information", isCorrect: false, misconceptionId: `${COHOMOLOGY}:MC-2` },
    ],
    targetedMisconceptions: [`${COHOMOLOGY}:MC-2`],
    source: eb(COHOMOLOGY, 'Discovery Question 2 as a detection probe (verbatim) — whether cohomology carries the same information as homology just presented differently, an answer of "yes" confirming COHOMOLOGY-ASSUMED-NO-EXTRA-INFORMATION'),
  },
  {
    conceptId: COHOMOLOGY, subjectSlug: S, probeKind: 'mcq', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.PROFICIENT,
    stem: 'Are de Rham cohomology and singular cohomology fundamentally different invariants that merely happen to have similar names?',
    choices: [
      { text: "No — on S1, the 1-form dθ is closed but not exact, giving a nonzero class in H1_dR(S1) matching the nonzero singular class H1(S1;R)≅R found combinatorially; de Rham's theorem PROVES Hn_dR(X)≅Hn(X;R), two utterly different-looking constructions computing the identical invariant", isCorrect: true },
      { text: "Yes, de Rham cohomology and singular cohomology are fundamentally different invariants that merely happen to share a name", isCorrect: false, misconceptionId: `${COHOMOLOGY}:MC-3` },
      { text: "Since one construction is analytic (differential forms) and the other is combinatorial (chain complexes), they should be treated as unrelated invariants rather than checked for an isomorphism", isCorrect: false, misconceptionId: `${COHOMOLOGY}:MC-3` },
    ],
    targetedMisconceptions: [`${COHOMOLOGY}:MC-3`],
    source: eb(COHOMOLOGY, 'Discovery Question 3 as a detection probe (verbatim) — whether de Rham and singular cohomology are fundamentally different invariants, an answer of "yes" confirming DE-RHAM-ASSUMED-UNRELATED-INVARIANT'),
  },
  // HOMOTOPY_EQUIVALENCE
  {
    conceptId: HOMOTOPY_EQUIVALENCE, subjectSlug: S, probeKind: 'mcq', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.FOUNDATIONAL,
    stem: 'If [0,1] and {0} are homotopy equivalent, does that mean they\'re homeomorphic?',
    choices: [
      { text: "No — [0,1] is contractible via H(x,t)=(1-t)x, making it homotopy equivalent to {0}, but [0,1] is NOT homeomorphic to {0} since they have different numbers of points entirely; homotopy equivalence allows crushing structure that homeomorphism strictly forbids", isCorrect: true },
      { text: "Yes, if [0,1] and {0} are homotopy equivalent, they must be homeomorphic", isCorrect: false, misconceptionId: `${HOMOTOPY_EQUIVALENCE}:MC-1` },
      { text: "Since every homeomorphism is a homotopy equivalence, the converse should also hold: a homotopy equivalence should imply the spaces are homeomorphic", isCorrect: false, misconceptionId: `${HOMOTOPY_EQUIVALENCE}:MC-1` },
    ],
    targetedMisconceptions: [`${HOMOTOPY_EQUIVALENCE}:MC-1`],
    source: eb(HOMOTOPY_EQUIVALENCE, 'Discovery Question 1 as a detection probe (verbatim) — whether homotopy equivalent implies homeomorphic, an answer of "yes" confirming HOMOTOPY-EQUIVALENT-MEANS-HOMEOMORPHIC'),
  },
  {
    conceptId: HOMOTOPY_EQUIVALENCE, subjectSlug: S, probeKind: 'misconception_probe', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.DEVELOPING,
    stem: 'Is the retraction r:X→A the only direction that needs checking in a deformation retract?',
    choices: [
      { text: "No — for r:R2\\{0}→S1 with r(x)=x/|x|, checking r is a retraction is necessary but a deformation retract ALSO requires i∘r homotopic to the identity on X, where i is the inclusion of S1; checking only r∘i=identity on the subspace while forgetting the second, up-to-homotopy direction misses half of what's required", isCorrect: true },
      { text: "Yes, the retraction r:X to A is the only direction that needs checking in a deformation retract", isCorrect: false, misconceptionId: `${HOMOTOPY_EQUIVALENCE}:MC-2` },
      { text: "Since the retraction direction is the more visually intuitive one to verify, checking only r∘i=identity should be treated as sufficient to establish a deformation retract", isCorrect: false, misconceptionId: `${HOMOTOPY_EQUIVALENCE}:MC-2` },
    ],
    targetedMisconceptions: [`${HOMOTOPY_EQUIVALENCE}:MC-2`],
    source: eb(HOMOTOPY_EQUIVALENCE, 'Discovery Question 2 as a detection probe (verbatim) — whether the retraction is the only direction needing verification, an answer of "yes" confirming DEFORMATION-RETRACT-DIRECTION-CONFUSED'),
  },
  {
    conceptId: HOMOTOPY_EQUIVALENCE, subjectSlug: S, probeKind: 'mcq', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.PROFICIENT,
    stem: 'Is contractible the same as compact?',
    choices: [
      { text: "No — Rn is contractible (shrinking to the origin) but not compact, Sn is compact but not contractible (nontrivial higher homotopy groups), and D2 is both; all four combinations of contractible/not and compact/not genuinely occur, since the two properties are logically independent", isCorrect: true },
      { text: "Yes, contractible is the same as compact", isCorrect: false, misconceptionId: `${HOMOTOPY_EQUIVALENCE}:MC-3` },
      { text: "Since both properties feel like they describe a space being 'small' or 'simple' in some sense, contractible and compact should be treated as equivalent conditions", isCorrect: false, misconceptionId: `${HOMOTOPY_EQUIVALENCE}:MC-3` },
    ],
    targetedMisconceptions: [`${HOMOTOPY_EQUIVALENCE}:MC-3`],
    source: eb(HOMOTOPY_EQUIVALENCE, 'Discovery Question 3 as a detection probe (verbatim) — whether contractible is the same as compact, an answer of "yes" confirming CONTRACTIBLE-MEANS-COMPACT'),
  },
  // TYCHONOFF
  {
    conceptId: TYCHONOFF, subjectSlug: S, probeKind: 'mcq', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.FOUNDATIONAL,
    stem: 'Does Tychonoff\'s theorem for infinitely many factors follow just by continuing the finite induction indefinitely?',
    choices: [
      { text: "No — for finitely many compact spaces, compactness of the product follows by induction, one pairing step at a time; but induction only ever finishes after finitely many applications, and there is no 'last' pairing step for infinitely many factors, so the infinite case requires a genuinely different, non-inductive argument (via nets or ultrafilters)", isCorrect: true },
      { text: "Yes, Tychonoff's theorem for infinitely many factors follows just by continuing the finite induction indefinitely", isCorrect: false, misconceptionId: `${TYCHONOFF}:MC-1` },
      { text: "Since 'and so on' language is often used when describing induction, extending the finite-product argument to infinitely many factors should be treated as routine", isCorrect: false, misconceptionId: `${TYCHONOFF}:MC-1` },
    ],
    targetedMisconceptions: [`${TYCHONOFF}:MC-1`],
    source: eb(TYCHONOFF, 'Discovery Question 1 as a detection probe (verbatim) — whether the infinite case follows by continuing the finite induction, an answer of "yes" confirming INFINITE-PRODUCT-CASE-ASSUMED-EXTENDED-BY-INDUCTION'),
  },
  {
    conceptId: TYCHONOFF, subjectSlug: S, probeKind: 'misconception_probe', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.DEVELOPING,
    stem: 'Is the Axiom of Choice merely a convenient tool used in one proof of Tychonoff\'s theorem, or is the theorem genuinely equivalent to Choice?',
    choices: [
      { text: "Genuinely equivalent — for the countable product of {0,1} spaces, confirming compactness requires simultaneously choosing a consistent eventual value at each of infinitely many coordinates, exactly the kind of operation Choice licenses; remarkably, Tychonoff's theorem can itself be used to PROVE Choice, making the two logically equivalent within ZF, not a one-way implication", isCorrect: true },
      { text: "The Axiom of Choice is merely a convenient, replaceable tool used in one proof of Tychonoff's theorem, not genuinely equivalent to it", isCorrect: false, misconceptionId: `${TYCHONOFF}:MC-2` },
      { text: "Since Choice is often introduced as just one more axiom used across various proofs, it should be treated as an interchangeable tool rather than checked for a specific logical equivalence with Tychonoff's theorem", isCorrect: false, misconceptionId: `${TYCHONOFF}:MC-2` },
    ],
    targetedMisconceptions: [`${TYCHONOFF}:MC-2`],
    source: eb(TYCHONOFF, 'Discovery Question 2 as a detection probe (verbatim) — whether Choice is merely a convenient tool or genuinely equivalent to Tychonoff\'s theorem, an answer treating it as merely convenient confirming CHOICE-ASSUMED-MERELY-CONVENIENT-NOT-EQUIVALENT'),
  },
  {
    conceptId: TYCHONOFF, subjectSlug: S, probeKind: 'mcq', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.PROFICIENT,
    stem: 'Is Tychonoff\'s theorem a purely abstract generalization with no concrete application?',
    choices: [
      { text: "No — the closed unit ball B* of a normed space's dual embeds into a product of intervals, one compact factor per vector; Tychonoff's theorem directly guarantees the entire product is compact, and B*, embedded as a closed subset, is therefore also compact — this is the specific mechanism behind Banach-Alaoglu's infinite-dimensional compactness result", isCorrect: true },
      { text: "Yes, Tychonoff's theorem is a purely abstract generalization with no concrete application", isCorrect: false, misconceptionId: `${TYCHONOFF}:MC-3` },
      { text: "Since the theorem's statement is phrased in terms of arbitrary index sets, it should be treated as background abstraction rather than a load-bearing mechanism in a specific application", isCorrect: false, misconceptionId: `${TYCHONOFF}:MC-3` },
    ],
    targetedMisconceptions: [`${TYCHONOFF}:MC-3`],
    source: eb(TYCHONOFF, 'Discovery Question 3 as a detection probe (verbatim) — whether Tychonoff\'s theorem is purely abstract with no application, an answer of "yes" confirming TYCHONOFF-ASSUMED-PURELY-ABSTRACT-WITH-NO-APPLICATION'),
  },
]
