/**
 * Batch: measure, measurable-function (math.meas) — 1/13 -> 3/13.
 *
 * Fresh Phase 0 frontier recompute after sigma-algebra opened math.meas:
 * BOTH remaining sole-prerequisite-on-sigma-algebra concepts became ready
 * simultaneously (measure -> {lebesgue-measure, measurable-function};
 * measurable-function -> lebesgue-integral), so this batch closes both at
 * once rather than waiting for a 3-concept batch that isn't yet possible.
 * Transcribed from their frozen Educational Brain entries at educational-
 * brain/concepts/mathematics/math.meas.measure.md and
 * math.meas.measurable-function.md.
 *
 * Grade band: GradeBand.UNDERGRADUATE, matching this domain's established
 * baseline (set on the sigma-algebra batch) and math.cat/math.abst's own
 * precedent for expert-tier pure-mathematics content.
 *
 * measure's KG cross-link (math.prob.probability-measure) IS authored —
 * its own EB entry treats it as a genuine transfer target, directly
 * reusing that concept's countable-additivity axiom template. measurable-
 * function's KG cross-link (math.prob.random-variable) is NOT authored
 * (its own EB entry documents this as a Blueprint/corpus-check discrepancy
 * and uses independence mode) — its probes stay self-contained accordingly.
 *
 * Both EB entries register exactly 3 formal misconceptions each (full
 * contract, no retargeting needed).
 *
 * Seeded as DRAFT. Promotion stays human.
 */
import { GradeBand, ProbeDifficulty } from '@prisma/client'
import type { SeedExplanation, SeedProbe } from './brainSeedAssets'

const S = 'mathematics'
const eb = (id: string, what: string) =>
  `educational-brain/concepts/mathematics/${id}.md — ${what}`

const MEASURE = 'math.meas.measure'
const MEASURABLE_FUNCTION = 'math.meas.measurable-function'

export const MATHEMATICS_MEAS_MEASURE_MEASURABLE_FUNCTION_EXPLANATIONS: SeedExplanation[] = [
  {
    conceptId: MEASURE, subjectSlug: S, familyKind: 'core_explanation', gradeBand: GradeBand.UNDERGRADUATE,
    content:
      'A MEASURE IS A SIZE FUNCTION BUILT ON TOP OF A σ-ALGEBRA, NEVER DEFINED WITHOUT ONE FIRST: a '
      + 'measure μ:F→[0,∞] on a measurable space (X,F) satisfies μ(∅)=0 and COUNTABLE ADDITIVITY '
      + '(μ(∪ₙEₙ)=Σₙμ(Eₙ) for pairwise DISJOINT Eₙ) — μ is only defined on the sets belonging to F, '
      + 'the σ-algebra\'s own collection of "well-behaved enough to measure" subsets.\n\n'
      + 'COUNTABLE ADDITIVITY REQUIRES DISJOINTNESS, EXACTLY AS A PROBABILITY MEASURE\'S OWN AXIOM '
      + 'DID: for length measure on R, [0,1] and [1,2] overlap only at the single point {1} (measure '
      + 'zero), so μ([0,2])=μ([0,1])+μ([1,2])=1+1=2 holds correctly. But [0,2] and [1,3] genuinely '
      + 'OVERLAP on [1,2] (measure 1): naive addition gives μ([0,2])+μ([1,3])=2+2=4, yet '
      + 'μ([0,2]∪[1,3])=μ([0,3])=3≠4 — the additivity axiom was never claimed for overlapping sets, '
      + 'and the corrected inclusion-exclusion formula μ(A)+μ(B)−μ(A∩B)=2+2−1=3 is required instead.\n\n'
      + 'A PROBABILITY MEASURE IS A MEASURE PLUS ONE EXTRA CONSTRAINT, NEVER A DIFFERENT KIND OF '
      + 'OBJECT: every probability measure IS a measure — satisfying μ(∅)=0 and countable additivity '
      + 'exactly as any measure must — with the single ADDITIONAL requirement μ(X)=1. A general '
      + 'measure need not be bounded at all: length measure on R gives μ(R)=∞, a perfectly valid '
      + 'measure, but ∞≠1 so it is NOT a probability measure — the generalization strictly WIDENS '
      + 'the framework, and μ(E)=∞ is a legitimate value, never an error, since the codomain is '
      + 'explicitly [0,∞].',
    targetedMisconceptions: [`${MEASURE}:MC-1`, `${MEASURE}:MC-2`, `${MEASURE}:MC-3`],
    source: eb(MEASURE, 'Core Understanding — a measure as a size function built on a sigma-algebra, countable additivity requiring disjointness exactly as probability measure required, and a probability measure being a measure plus normalization rather than a different kind of object'),
  },
  {
    conceptId: MEASURABLE_FUNCTION, subjectSlug: S, familyKind: 'core_explanation', gradeBand: GradeBand.UNDERGRADUATE,
    content:
      'MEASURABILITY IS THE CONTINUITY DEFINITION, GENERALIZED FROM "OPEN" TO "MEASURABLE": '
      + 'f:(X,F)→(Y,G) is measurable iff f⁻¹(E)∈F for EVERY E∈G — the preimage of every measurable '
      + 'target set lands as a measurable source set, directly paralleling the topological "preimages '
      + 'of open sets are open" definition of continuity, with "measurable" replacing "open."\n\n'
      + 'CHECKING OPEN INTERVALS ALONE SUFFICES FOR THE FULL BOREL TEST — A GENUINE SHORTCUT, NEVER '
      + 'AN APPROXIMATION: since the Borel σ-algebra is GENERATED by open sets, and preimage-taking '
      + 'respects σ-algebra operations (unions, complements), verifying f⁻¹(E) measurable for every '
      + 'open interval E automatically extends to EVERY Borel set. For f(x)=x²: '
      + 'f⁻¹((a,b))=(−√b,−√a)∪(√a,√b) for 0<a<b, a union of open intervals, itself measurable — this '
      + 'pattern holding for every open interval confirms full Borel measurability via the '
      + 'generating-set shortcut alone, with no need to check uncountably many sets individually.\n\n'
      + 'MEASURABLE IS STRICTLY WEAKER THAN CONTINUOUS — CONTINUOUS IMPLIES MEASURABLE, NEVER THE '
      + 'CONVERSE: every continuous f:R→R is automatically Borel measurable, since continuity means '
      + 'f⁻¹(U) is open (hence measurable) for every open U. But the STEP FUNCTION g(x)=0 for x<0, '
      + 'g(x)=1 for x≥0 is measurable (g⁻¹((−0.5,0.5))=(−∞,0) open; g⁻¹((0.5,1.5))=[0,∞) closed, '
      + 'hence still measurable) DESPITE having a genuine jump discontinuity at x=0 — proving '
      + 'measurability is a strictly LARGER, more permissive class than continuity, never equivalent '
      + 'to it.',
    targetedMisconceptions: [`${MEASURABLE_FUNCTION}:MC-1`, `${MEASURABLE_FUNCTION}:MC-2`, `${MEASURABLE_FUNCTION}:MC-3`],
    source: eb(MEASURABLE_FUNCTION, 'Core Understanding — measurability as the continuity definition generalized from open to measurable, open intervals alone sufficing for the full Borel test as a genuine shortcut, and measurability being strictly weaker than continuity via the measurable-but-discontinuous step function'),
  },
]

export const MATHEMATICS_MEAS_MEASURE_MEASURABLE_FUNCTION_PROBES: SeedProbe[] = [
  {
    conceptId: MEASURE, subjectSlug: S, probeKind: 'mcq', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.FOUNDATIONAL,
    stem: 'Does μ(A∪B)=μ(A)+μ(B) hold when A and B genuinely overlap?',
    choices: [
      { text: "No — for A=[0,2] and B=[1,3] under length measure, they overlap on [1,2] (measure 1): naive addition gives 2+2=4, but μ([0,3])=3, so the correct formula for overlapping sets is μ(A)+μ(B)−μ(A∩B)=2+2−1=3, never naive addition", isCorrect: true },
      { text: "Yes, μ(A∪B)=μ(A)+μ(B) holds for any two sets A and B regardless of whether they overlap", isCorrect: false, misconceptionId: `${MEASURE}:MC-1` },
      { text: "Since the additivity axiom is stated for unions in general, it should apply the same way whether or not the sets happen to overlap", isCorrect: false, misconceptionId: `${MEASURE}:MC-1` },
    ],
    targetedMisconceptions: [`${MEASURE}:MC-1`],
    source: eb(MEASURE, 'Discovery Question 1 as a detection probe (verbatim) — whether additivity holds when A and B genuinely overlap, an answer of "yes" confirming ADDITIVITY-APPLIED-TO-OVERLAPPING-SETS'),
  },
  {
    conceptId: MEASURE, subjectSlug: S, probeKind: 'misconception_probe', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.DEVELOPING,
    stem: 'Must every measure satisfy μ(X)=1, or is that specific to probability measures?',
    choices: [
      { text: "That is specific to probability measures — a general measure need not be bounded at all; length measure on R gives μ(R)=∞, a perfectly valid measure that is NOT normalized to 1, showing normalization is an extra constraint, never a default", isCorrect: true },
      { text: "Every measure must satisfy μ(X)=1, since that is the defining normalization property of what makes a function a measure", isCorrect: false, misconceptionId: `${MEASURE}:MC-2` },
      { text: "Since probability is usually the first measure encountered, its total-equals-1 property should generalize as a universal feature of every measure", isCorrect: false, misconceptionId: `${MEASURE}:MC-2` },
    ],
    targetedMisconceptions: [`${MEASURE}:MC-2`],
    source: eb(MEASURE, 'Discovery Question 2 as a detection probe (verbatim) — whether every measure must satisfy total 1, an answer of "yes" confirming MEASURE-ASSUMED-NORMALIZED'),
  },
  {
    conceptId: MEASURE, subjectSlug: S, probeKind: 'mcq', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.PROFICIENT,
    stem: 'Is μ(E)=∞ ever a valid, correct answer for a measure?',
    choices: [
      { text: "Yes — the codomain of a measure is explicitly [0,∞], so μ([0,∞))=∞ under length measure is the correct, meaningful answer, never an error; infinite total size is a fully legitimate outcome (e.g. length measure on all of R)", isCorrect: true },
      { text: "No, μ(E)=∞ should always be treated as an invalid or erroneous computation for a measure", isCorrect: false, misconceptionId: `${MEASURE}:MC-3` },
      { text: "Since numerical answers are generally expected to be finite, an infinite measure value likely indicates a mistake somewhere in the computation", isCorrect: false, misconceptionId: `${MEASURE}:MC-3` },
    ],
    targetedMisconceptions: [`${MEASURE}:MC-3`],
    source: eb(MEASURE, 'Discovery Question 3 as a detection probe (verbatim) — whether infinite measure is ever valid, an answer treating it as invalid confirming INFINITE-MEASURE-TREATED-AS-ERROR'),
  },
  {
    conceptId: MEASURABLE_FUNCTION, subjectSlug: S, probeKind: 'mcq', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.FOUNDATIONAL,
    stem: 'Since every continuous function is measurable, does that mean every measurable function must also be continuous?',
    choices: [
      { text: "No — measurability is strictly WEAKER than continuity; the step function g(x)=0 for x<0, g(x)=1 for x≥0 is measurable (its preimages of open intervals are always open, closed, empty, or all of R) despite a genuine jump discontinuity at x=0", isCorrect: true },
      { text: "Yes, measurable and continuous are equivalent conditions, so every measurable function must also be continuous", isCorrect: false, misconceptionId: `${MEASURABLE_FUNCTION}:MC-1` },
      { text: "Since \"continuous implies measurable\" is the fact most commonly stated, the two properties should generally be treated as interchangeable", isCorrect: false, misconceptionId: `${MEASURABLE_FUNCTION}:MC-1` },
    ],
    targetedMisconceptions: [`${MEASURABLE_FUNCTION}:MC-1`],
    source: eb(MEASURABLE_FUNCTION, 'Discovery Question 1 as a detection probe (verbatim) — whether measurable functions must also be continuous, an answer of "yes" confirming MEASURABLE-ASSUMED-EQUIVALENT-TO-CONTINUOUS'),
  },
  {
    conceptId: MEASURABLE_FUNCTION, subjectSlug: S, probeKind: 'misconception_probe', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.DEVELOPING,
    stem: 'Does verifying measurability require checking the preimage of every individual Borel set, or is there a shortcut?',
    choices: [
      { text: "There is a shortcut — since the Borel σ-algebra is GENERATED by open sets and preimage-taking respects σ-algebra operations, verifying f⁻¹(E) measurable for every open interval E automatically extends to every Borel set, e.g. f(x)=x² checked interval by interval", isCorrect: true },
      { text: "Yes, verifying measurability genuinely requires checking the preimage of every individual Borel set one at a time", isCorrect: false, misconceptionId: `${MEASURABLE_FUNCTION}:MC-2` },
      { text: "Since the formal definition quantifies over every E in the target sigma-algebra, that should be read as requiring exhaustive individual checking before any shortcut applies", isCorrect: false, misconceptionId: `${MEASURABLE_FUNCTION}:MC-2` },
    ],
    targetedMisconceptions: [`${MEASURABLE_FUNCTION}:MC-2`],
    source: eb(MEASURABLE_FUNCTION, 'Discovery Question 2 as a detection probe (verbatim) — whether checking every Borel set individually is required, an answer of "yes" confirming ALL-BOREL-SETS-ASSUMED-TO-REQUIRE-INDIVIDUAL-CHECKING'),
  },
  {
    conceptId: MEASURABLE_FUNCTION, subjectSlug: S, probeKind: 'mcq', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.PROFICIENT,
    stem: 'Is the measurability condition f⁻¹(E)∈F, or is it f(A)∈G?',
    choices: [
      { text: "It is f⁻¹(E)∈F for every E∈G — a PREIMAGE condition, directly analogous to the continuity definition; the forward-image condition f(A)∈G is never the correct definition and need not behave well at all", isCorrect: true },
      { text: "It is f(A)∈G for every A∈F — checking that forward images of measurable source sets land in the target sigma-algebra", isCorrect: false, misconceptionId: `${MEASURABLE_FUNCTION}:MC-3` },
      { text: "Since forward-image notation f(A) is visually simpler and more intuitive than preimage notation f⁻¹(E), it should be the one used to state the measurability condition", isCorrect: false, misconceptionId: `${MEASURABLE_FUNCTION}:MC-3` },
    ],
    targetedMisconceptions: [`${MEASURABLE_FUNCTION}:MC-3`],
    source: eb(MEASURABLE_FUNCTION, 'Discovery Question 3 as a detection probe (verbatim) — whether the measurability condition uses preimages or forward images, an answer choosing forward images confirming MEASURABILITY-DEFINITION-DIRECTION-REVERSED'),
  },
]
