/**
 * Fifteenth math.abst asset batch — alternating-group and field-extension.
 *
 * Continues serving-asset coverage for math.abst (28/36 -> 30/36).
 * Transcribed from the frozen Educational Brain entries at
 * educational-brain/concepts/mathematics/math.abst.alternating-group.md and
 * math.abst.field-extension.md.
 *
 *   ALTGROUP  alternating-group — parity is decided purely by transposition
 *             count, never visual appearance; A_n is not cyclic for n≥4;
 *             A_n is always normal in S_n regardless of the general "most
 *             subgroups aren't normal" pattern.
 *   FIELDEXT  field-extension — the Tower Law multiplies degrees, never
 *             adds them; "simple" means one generator, never small degree;
 *             not every real number is algebraic, transcendentals are a
 *             proven fact.
 *
 * Seeded as DRAFT. Promotion stays human.
 */
import { GradeBand, ProbeDifficulty } from '@prisma/client'
import type { SeedExplanation, SeedProbe } from './brainSeedAssets'

const S = 'mathematics'
const eb = (id: string, what: string) =>
  `educational-brain/concepts/mathematics/${id}.md — ${what}`

const ALTGROUP = 'math.abst.alternating-group'
const FIELDEXT = 'math.abst.field-extension'

export const MATHEMATICS_ABSTRACT_ALGEBRA_ALT_GROUP_FIELD_EXT_EXPLANATIONS: SeedExplanation[] = [
  {
    conceptId: ALTGROUP, subjectSlug: S, familyKind: 'core_explanation', gradeBand: GradeBand.UNDERGRADUATE,
    content:
      'The alternating group A_n is the set of all EVEN permutations in S_n. A permutation\'s '
      + 'PARITY is decided purely by TRANSPOSITION COUNT mod 2 — a k-cycle decomposes into exactly '
      + 'k-1 transpositions — NEVER by how the permutation "looks." |A_n|=n!/2 and A_n⊴S_n: '
      + 'normality follows because A_n is the kernel of the parity homomorphism π:S_n→Z/2Z '
      + '(kernels of homomorphisms are always normal), or equivalently because A_n has index 2 '
      + '(index-2 subgroups are always normal) — never doubted just because "most subgroups aren\'t '
      + 'normal."\n\n'
      + 'A_n\'s structure varies sharply by n: A_3≅Z/3Z is abelian and cyclic (order 3, prime), '
      + 'but for n≥4, A_n is NON-ABELIAN (e.g. (1 2 3)∘(1 2 4)≠(1 2 4)∘(1 2 3) in A_4) and hence '
      + 'NOT cyclic — A_3\'s cyclicity is a coincidence of small size, never a general pattern. '
      + 'Most importantly, A_n IS SIMPLE for n≥5, the single deepest fact about alternating '
      + 'groups.',
    targetedMisconceptions: [`${ALTGROUP}:MC-1`, `${ALTGROUP}:MC-2`, `${ALTGROUP}:MC-3`],
    source: eb(ALTGROUP, 'Core Understanding — parity is decided by transposition count, A_n is not cyclic for n≥4, A_n is always normal in S_n'),
  },
  {
    conceptId: FIELDEXT, subjectSlug: S, familyKind: 'core_explanation', gradeBand: GradeBand.UNDERGRADUATE,
    content:
      'A field extension K/F has degree [K:F]=dim_F(K), the dimension of K as a vector space over '
      + 'F. THE TOWER LAW: for a chain F⊆E⊆K, [K:F]=[K:E]·[E:F] — the degree of the full '
      + 'extension is the PRODUCT, never the sum, of the individual step degrees. Extending by '
      + 'degree 2 then by degree 3 gives total degree 6, never 5 — mirroring how a basis for K '
      + 'over F combines a basis for K over E with a basis for E over F, multiplying '
      + 'corresponding basis elements.\n\n'
      + 'A SIMPLE extension K=F(α) is generated by adjoining a SINGLE element — "simple" refers to '
      + 'the GENERATOR COUNT, never to small degree or ease of understanding; F(α) can still have '
      + 'arbitrarily large degree.\n\n'
      + 'Not every real number is algebraic: an extension is ALGEBRAIC if every element satisfies '
      + 'some polynomial over F, but TRANSCENDENTAL extensions genuinely exist — π satisfies NO '
      + 'polynomial with rational coefficients, a proven theorem (Lindemann, 1882), never merely '
      + 'an open question or an exotic edge case.',
    targetedMisconceptions: [`${FIELDEXT}:MC-1`, `${FIELDEXT}:MC-2`, `${FIELDEXT}:MC-3`],
    source: eb(FIELDEXT, 'Core Understanding — the Tower Law multiplies degrees, simple means one generator not small degree, transcendental numbers genuinely exist'),
  },
]

export const MATHEMATICS_ABSTRACT_ALGEBRA_ALT_GROUP_FIELD_EXT_PROBES: SeedProbe[] = [
  // --- math.abst.alternating-group -------------------------------------------------
  {
    conceptId: ALTGROUP, subjectSlug: S, probeKind: 'mcq', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.FOUNDATIONAL,
    stem: 'A student classifies (1 2)(3 4)(5 6) as "even because it looks symmetric." Is this correct reasoning?',
    choices: [
      { text: 'No — parity is decided purely by transposition count mod 2 (here, 3 transpositions, giving ODD), never by visual appearance or symmetry', isCorrect: true },
      { text: 'Yes — a visually symmetric-looking permutation is always even', isCorrect: false, misconceptionId: `${ALTGROUP}:MC-1` },
      { text: 'Yes, since parity can be judged from the permutation\'s appearance without counting transpositions', isCorrect: false, misconceptionId: `${ALTGROUP}:MC-1` },
    ],
    targetedMisconceptions: [`${ALTGROUP}:MC-1`],
    source: eb(ALTGROUP, 'Assessment gate — parity is decided by transposition count, never visual appearance'),
  },
  {
    conceptId: ALTGROUP, subjectSlug: S, probeKind: 'misconception_probe', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.DEVELOPING,
    stem: 'Is A_n cyclic for every n, the way A_3 is?',
    choices: [
      { text: 'No — A_3≅Z/3Z is cyclic only because of its small prime order; for n≥4, A_n is genuinely non-abelian (verified directly in A_4) and hence not cyclic', isCorrect: true },
      { text: 'Yes — A_n is cyclic for every value of n', isCorrect: false, misconceptionId: `${ALTGROUP}:MC-2` },
      { text: 'Yes, since alternating groups always inherit cyclicity from A_3', isCorrect: false, misconceptionId: `${ALTGROUP}:MC-2` },
    ],
    targetedMisconceptions: [`${ALTGROUP}:MC-2`],
    source: eb(ALTGROUP, 'Misconception register — A_n is not cyclic for n≥4, A_3\'s cyclicity is a coincidence of small size'),
  },
  {
    conceptId: ALTGROUP, subjectSlug: S, probeKind: 'mcq', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.PROFICIENT,
    stem: 'Is A_n genuinely a normal subgroup of S_n, or could it fail to be, like most subgroups?',
    choices: [
      { text: 'A_n is always normal in S_n — it is the kernel of the parity homomorphism (kernels are always normal), and equivalently has index 2 (index-2 subgroups are always normal)', isCorrect: true },
      { text: 'A_n might not be normal, since most subgroups of a group are not normal', isCorrect: false, misconceptionId: `${ALTGROUP}:MC-3` },
      { text: 'A_n\'s normality depends on whether n is prime', isCorrect: false, misconceptionId: `${ALTGROUP}:MC-3` },
    ],
    targetedMisconceptions: [`${ALTGROUP}:MC-3`],
    source: eb(ALTGROUP, 'Transfer probe — A_n is always normal in S_n, via the parity-homomorphism kernel or the index-2 argument'),
  },

  // --- math.abst.field-extension -----------------------------------------------------
  {
    conceptId: FIELDEXT, subjectSlug: S, probeKind: 'mcq', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.FOUNDATIONAL,
    stem: 'Since π is a perfectly ordinary real number, does it satisfy SOME polynomial equation with rational coefficients, the same way √2 does?',
    choices: [
      { text: 'No — π is proven TRANSCENDENTAL (Lindemann, 1882): it satisfies NO polynomial with rational coefficients, unlike √2 which satisfies x²-2=0', isCorrect: true },
      { text: 'Yes — every real number, including π, must satisfy some polynomial equation over the rationals', isCorrect: false, misconceptionId: `${FIELDEXT}:MC-1` },
      { text: 'Yes, since whether π is algebraic remains an unresolved open question', isCorrect: false, misconceptionId: `${FIELDEXT}:MC-1` },
    ],
    targetedMisconceptions: [`${FIELDEXT}:MC-1`],
    source: eb(FIELDEXT, 'Assessment gate — transcendental numbers genuinely exist, a proven fact not merely an open question'),
  },
  {
    conceptId: FIELDEXT, subjectSlug: S, probeKind: 'misconception_probe', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.DEVELOPING,
    stem: 'If you extend by degree 2, then extend again by degree 3, is the total degree 5 or 6?',
    choices: [
      { text: '6 — the Tower Law multiplies degrees across a chain of extensions, [K:F]=[K:E]·[E:F], never adds them', isCorrect: true },
      { text: '5 — the Tower Law adds the degrees of each step', isCorrect: false, misconceptionId: `${FIELDEXT}:MC-2` },
      { text: 'Either 5 or 6, depending on which fields are involved', isCorrect: false, misconceptionId: `${FIELDEXT}:MC-2` },
    ],
    targetedMisconceptions: [`${FIELDEXT}:MC-2`],
    source: eb(FIELDEXT, 'Misconception register — the Tower Law multiplies degrees, never adds them'),
  },
  {
    conceptId: FIELDEXT, subjectSlug: S, probeKind: 'mcq', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.PROFICIENT,
    stem: 'Does "simple" extension mean the extension must have small or easily-computed degree?',
    choices: [
      { text: 'No — "simple" refers strictly to the GENERATOR COUNT (a single element α); F(α) can still have arbitrarily large, even infinite, degree', isCorrect: true },
      { text: 'Yes — a simple extension always has a small, easily-computed degree', isCorrect: false, misconceptionId: `${FIELDEXT}:MC-3` },
      { text: 'Yes, since "simple" and "small degree" are interchangeable terms in field theory', isCorrect: false, misconceptionId: `${FIELDEXT}:MC-3` },
    ],
    targetedMisconceptions: [`${FIELDEXT}:MC-3`],
    source: eb(FIELDEXT, 'Transfer probe — "simple" means one generator, never small degree'),
  },
]
