/**
 * Batch: sigma-algebra (math.meas) — OPENS the math.meas domain (0/13).
 *
 * Fresh Phase 0 frontier recompute after math.stats reached 40/40
 * completion: math.meas is the largest remaining clean-0 domain family
 * member ready to open, with sigma-algebra as its sole root (requires only
 * math.found.set-theory, already authored). The domain's remaining 12
 * concepts form a linear measure-theory dependency chain (sigma-algebra ->
 * measure -> {lebesgue-measure -> measure-zero, abstract-measure-spaces};
 * sigma-algebra -> measurable-function -> simple-function -> lebesgue-
 * integral -> {convergence-theorems, lp-space -> l2-space, product-measure,
 * radon-nikodym}), so only one concept becomes ready at a time from here.
 * Transcribed from its frozen Educational Brain entry at educational-
 * brain/concepts/mathematics/math.meas.sigma-algebra.md.
 *
 * Grade band: GradeBand.UNDERGRADUATE, matching the established convention
 * for expert-tier pure-mathematics domains (math.cat, math.abst) — measure
 * theory's sigma-algebra axioms are genuinely undergraduate/early-graduate
 * real-analysis content.
 *
 * This EB entry registers 3 formal misconceptions (full contract, no
 * retargeting needed).
 *
 * Seeded as DRAFT. Promotion stays human.
 */
import { GradeBand, ProbeDifficulty } from '@prisma/client'
import type { SeedExplanation, SeedProbe } from './brainSeedAssets'

const S = 'mathematics'
const eb = (id: string, what: string) =>
  `educational-brain/concepts/mathematics/${id}.md — ${what}`

const SIGMA_ALGEBRA = 'math.meas.sigma-algebra'

export const MATHEMATICS_MEAS_SIGMA_ALGEBRA_EXPLANATIONS: SeedExplanation[] = [
  {
    conceptId: SIGMA_ALGEBRA, subjectSlug: S, familyKind: 'core_explanation', gradeBand: GradeBand.UNDERGRADUATE,
    content:
      'COUNTABLE INTERSECTION CLOSURE IS A THEOREM, NEVER A FOURTH AXIOM: a σ-algebra satisfies '
      + 'exactly three closure properties: (1) X∈F; (2) A∈F⇒Aᶜ∈F; (3) A₁,A₂,...∈F⇒∪ᵢAᵢ∈F (COUNTABLE '
      + 'union). By De Morgan\'s law, ∩ᵢAᵢ=(∪ᵢAᵢᶜ)ᶜ — each Aᵢᶜ∈F by (2), their union is in F by (3), '
      + 'and its complement is in F by (2) again — countable intersection closure is DERIVED from '
      + 'the other two, never independently assumed.\n\n'
      + 'THE RESTRICTION IS FORCED BY MATHEMATICAL NECESSITY, ONLY ONCE X IS UNCOUNTABLE: for a '
      + 'finite or countably infinite X (like a die-roll Ω={1,...,6}), EVERY subset can safely be '
      + 'assigned a probability — the full power set trivially satisfies all three axioms. For an '
      + 'UNCOUNTABLE X (like R), it is a genuine, deep theorem that no countably additive measure '
      + 'that is translation-invariant and gives every interval its length can be defined on the '
      + 'FULL power set '
      + '— some subsets (non-measurable, e.g. via the Vitali construction) must be excluded. The '
      + 'σ-algebra is exactly the collection of "well-behaved enough to measure" subsets — never '
      + 'arbitrary extra bookkeeping, but a genuine mathematical necessity that only bites for '
      + 'uncountable spaces.\n\n'
      + 'THE BOREL σ-ALGEBRA IS THE STANDARD MEASURABLE STRUCTURE ON R: B(R) is the SMALLEST '
      + 'σ-algebra containing all open sets of R — generated by them, meaning the intersection of '
      + 'every σ-algebra containing those open sets. It includes essentially every subset one would '
      + 'naturally construct (open sets, closed sets, countable sets, all intervals), making (X,F) '
      + 'a genuine MEASURABLE SPACE — the exact structure on which a measure or probability can '
      + 'later be defined.',
    targetedMisconceptions: [`${SIGMA_ALGEBRA}:MC-1`, `${SIGMA_ALGEBRA}:MC-2`, `${SIGMA_ALGEBRA}:MC-3`],
    source: eb(SIGMA_ALGEBRA, 'Core Understanding — countable intersection closure being a theorem never a fourth axiom, the restriction being forced by mathematical necessity only once X is uncountable, and the Borel sigma-algebra being the standard measurable structure on R'),
  },
]

export const MATHEMATICS_MEAS_SIGMA_ALGEBRA_PROBES: SeedProbe[] = [
  {
    conceptId: SIGMA_ALGEBRA, subjectSlug: S, probeKind: 'mcq', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.FOUNDATIONAL,
    stem: 'Does a collection containing X and ∅ automatically qualify as a σ-algebra?',
    choices: [
      { text: "No — for X={1,2,3}, the collection G={∅,{1},{2},X} FAILS: {1}ᶜ={2,3}∉G, despite containing both ∅ and X; every single member must independently satisfy complement and union closure, not just X and the empty set", isCorrect: true },
      { text: "Yes, containing X and the empty set is sufficient for a collection to qualify as a σ-algebra", isCorrect: false, misconceptionId: `${SIGMA_ALGEBRA}:MC-1` },
      { text: "Since X and the empty set are the two extreme cases of any collection, verifying they belong should confirm the closure properties hold for everything in between", isCorrect: false, misconceptionId: `${SIGMA_ALGEBRA}:MC-1` },
    ],
    targetedMisconceptions: [`${SIGMA_ALGEBRA}:MC-1`],
    source: eb(SIGMA_ALGEBRA, 'Discovery Question 1 as a detection probe (verbatim) — whether containing X and the empty set automatically qualifies a collection as a sigma-algebra, an answer of "yes" confirming PARTIAL-AXIOM-CHECK'),
  },
  {
    conceptId: SIGMA_ALGEBRA, subjectSlug: S, probeKind: 'misconception_probe', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.DEVELOPING,
    stem: "Why can't we just use the full power set as the σ-algebra for every set X, including R?",
    choices: [
      { text: "Because for an UNCOUNTABLE X like R, it is a genuine, deep theorem that no countably additive measure that is translation-invariant and gives every interval its length can be defined on the full power set — some subsets (non-measurable, via the Vitali construction) must be excluded; this never mattered for finite/countable X, where the full power set trivially works", isCorrect: true },
      { text: "The σ-algebra restriction is arbitrary extra bookkeeping — the full power set could be used for any set X without genuine mathematical issues", isCorrect: false, misconceptionId: `${SIGMA_ALGEBRA}:MC-2` },
      { text: "Since the full power set worked fine for the finite die-roll example, it should work equally well as a convention for any set, including uncountable ones", isCorrect: false, misconceptionId: `${SIGMA_ALGEBRA}:MC-2` },
    ],
    targetedMisconceptions: [`${SIGMA_ALGEBRA}:MC-2`],
    source: eb(SIGMA_ALGEBRA, 'Discovery Question 2 as a detection probe (verbatim) — why the full power set can\'t be used for every set X including R, an answer dismissing the restriction as arbitrary bookkeeping confirming SIGMA-ALGEBRA-SEEN-AS-UNNECESSARY-FORMALISM'),
  },
  {
    conceptId: SIGMA_ALGEBRA, subjectSlug: S, probeKind: 'mcq', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.PROFICIENT,
    stem: 'Must a σ-algebra be closed under unions of any size, or only countable ones?',
    choices: [
      { text: "Only countable ones — the axioms require closure under COUNTABLE union specifically (A₁,A₂,...∈F⇒∪ᵢAᵢ∈F); an arbitrary (uncountable) union of measurable sets is never guaranteed to remain measurable in general", isCorrect: true },
      { text: "A σ-algebra must be closed under unions of any size, including uncountable ones", isCorrect: false, misconceptionId: `${SIGMA_ALGEBRA}:MC-3` },
      { text: "Since \"closed under union\" is stated without further qualification in casual descriptions, it should be read as covering unions of every size", isCorrect: false, misconceptionId: `${SIGMA_ALGEBRA}:MC-3` },
    ],
    targetedMisconceptions: [`${SIGMA_ALGEBRA}:MC-3`],
    source: eb(SIGMA_ALGEBRA, 'Discovery Question 3 as a detection probe (verbatim) — whether a sigma-algebra must be closed under unions of any size or only countable ones, an answer of "any size" confirming COUNTABLE-UNION-MISTAKEN-FOR-ARBITRARY-UNION'),
  },
]
