/**
 * Eleventh math.abst asset batch — ufd and quotient-ring.
 *
 * Continues serving-asset coverage for math.abst (20/36 -> 22/36).
 * Transcribed from the frozen Educational Brain entries at
 * educational-brain/concepts/mathematics/math.abst.ufd.md and
 * math.abst.quotient-ring.md.
 *
 *   UFD           ufd — the Fundamental Theorem of Arithmetic IS the UFD
 *                 definition applied to Z, never merely analogous; PID
 *                 status proves UFD status automatically; UFD is strictly
 *                 broader than PID (Z[x] separates them).
 *   QUOTIENTRING  quotient-ring — r+I is the entire coset, never a single
 *                 number; the quotient construction needs a genuine
 *                 two-sided ideal, never merely a subring; the ideal's
 *                 type determines the quotient's type.
 *
 * Seeded as DRAFT. Promotion stays human.
 */
import { GradeBand, ProbeDifficulty } from '@prisma/client'
import type { SeedExplanation, SeedProbe } from './brainSeedAssets'

const S = 'mathematics'
const eb = (id: string, what: string) =>
  `educational-brain/concepts/mathematics/${id}.md — ${what}`

const UFD = 'math.abst.ufd'
const QUOTIENTRING = 'math.abst.quotient-ring'

export const MATHEMATICS_ABSTRACT_ALGEBRA_UFD_QUOTIENT_RING_EXPLANATIONS: SeedExplanation[] = [
  {
    conceptId: UFD, subjectSlug: S, familyKind: 'core_explanation', gradeBand: GradeBand.UNDERGRADUATE,
    content:
      'A UFD is an integral domain where every nonzero, non-unit element factors into '
      + 'irreducibles UNIQUELY (up to order and units). This is EXACTLY the Fundamental Theorem '
      + 'of Arithmetic restated in general ring-theoretic language, never merely analogous: Z\'s '
      + 'irreducibles are exactly the primes, and factorization is unique up to order and sign — '
      + 'the SAME claim, general vs. specific.\n\n'
      + 'EVERY PID IS A UFD, using a PID\'s own already-established structural facts (irreducibles '
      + 'equal primes, prime ideals maximal) as the DIRECT proof mechanism. "Every PID is a UFD" '
      + 'is NOT an independent new fact requiring separate machinery — once PID status is known, '
      + 'UFD status follows automatically, with no separate factorization-uniqueness check '
      + 'needed.\n\n'
      + 'UFD is a STRICTLY BROADER class than PID: Z[x] IS a UFD (via Gauss\'s Lemma) but is NOT '
      + 'a PID — the ideal (2,x) cannot be generated by a single element. This confirms the UFD '
      + 'property is implied by, but not equivalent to, the PID property.',
    targetedMisconceptions: [`${UFD}:MC-1`, `${UFD}:MC-2`, `${UFD}:MC-3`],
    source: eb(UFD, 'Core Understanding — FTA is literally the UFD definition applied to Z, PID implies UFD automatically, UFD is strictly broader than PID'),
  },
  {
    conceptId: QUOTIENTRING, subjectSlug: S, familyKind: 'core_explanation', gradeBand: GradeBand.UNDERGRADUATE,
    content:
      'For a ring R and a TWO-SIDED IDEAL I, the quotient ring R/I is the set of cosets '
      + '{r+I : r∈R}. Each coset r+I is an ENTIRE SET {r+i : i∈I}, NOT a single number — either '
      + 'operation must give the SAME answer regardless of which representative is chosen. In '
      + 'Z/4Z, [1]+[3]=[0], verified with different representatives [5]+[7]=[0], matching.\n\n'
      + 'WELL-DEFINEDNESS of multiplication is where I\'s TWO-SIDED absorption is used directly: '
      + 'for different representatives r\'=r+i1, s\'=s+i2, r\'s\'=rs+ri2+i1s+i1i2 — since I '
      + 'absorbs multiplication by ANY ring element on EITHER side, all the extra terms lie in I. '
      + 'This is exactly why the construction needs a genuine two-sided IDEAL, never merely a '
      + 'SUBRING: a subring that does not absorb produces a genuinely undefined multiplication '
      + '(different representatives give different answers).\n\n'
      + 'The IDEAL\'S STRUCTURAL TYPE determines the quotient\'s type: I PRIME iff R/I an integral '
      + 'domain; I MAXIMAL iff R/I a FIELD. Z/6Z (ideal not prime) has zero divisors ([2]·[3]=[0]); '
      + 'Z/5Z (ideal prime and maximal) is a genuine field.',
    targetedMisconceptions: [`${QUOTIENTRING}:MC-1`, `${QUOTIENTRING}:MC-2`, `${QUOTIENTRING}:MC-3`],
    source: eb(QUOTIENTRING, 'Core Understanding — cosets are entire sets not single numbers, the construction needs a genuine two-sided ideal not merely a subring, the ideal type determines the quotient type'),
  },
]

export const MATHEMATICS_ABSTRACT_ALGEBRA_UFD_QUOTIENT_RING_PROBES: SeedProbe[] = [
  // --- math.abst.ufd -----------------------------------------------------------
  {
    conceptId: UFD, subjectSlug: S, probeKind: 'mcq', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.FOUNDATIONAL,
    stem: 'Is the Fundamental Theorem of Arithmetic a separate fact merely analogous to the UFD definition, or literally an instance of it applied to Z?',
    choices: [
      { text: 'It is literally an instance of the UFD definition applied to Z: Z\'s irreducibles are exactly the primes, and factorization is unique up to order and units, exactly matching the general UFD claim', isCorrect: true },
      { text: 'It is a separate fact that merely resembles the UFD definition superficially', isCorrect: false, misconceptionId: `${UFD}:MC-1` },
      { text: 'It is unrelated, since "prime" and "irreducible" are genuinely different concepts', isCorrect: false, misconceptionId: `${UFD}:MC-1` },
    ],
    targetedMisconceptions: [`${UFD}:MC-1`],
    source: eb(UFD, 'Assessment gate — FTA is literally the UFD definition applied to Z, never merely analogous'),
  },
  {
    conceptId: UFD, subjectSlug: S, probeKind: 'misconception_probe', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.DEVELOPING,
    stem: 'If a ring is already known to be a PID, does confirming it is also a UFD require a separate, independent factorization-uniqueness verification?',
    choices: [
      { text: 'No — "every PID is a UFD" follows directly from the PID\'s own already-established structural facts (irreducibles equal primes, prime ideals maximal); no separate check is needed', isCorrect: true },
      { text: 'Yes — UFD status must always be independently re-verified even for a known PID', isCorrect: false, misconceptionId: `${UFD}:MC-2` },
      { text: 'Yes, since PID and UFD structure are established by entirely unrelated proof techniques', isCorrect: false, misconceptionId: `${UFD}:MC-2` },
    ],
    targetedMisconceptions: [`${UFD}:MC-2`],
    source: eb(UFD, 'Misconception register — PID status proves UFD status automatically, no separate verification needed'),
  },
  {
    conceptId: UFD, subjectSlug: S, probeKind: 'mcq', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.PROFICIENT,
    stem: 'Does "every PID is a UFD" mean the two classes of rings are essentially the same, or can a ring be a UFD without being a PID?',
    choices: [
      { text: 'A ring can be a UFD without being a PID — Z[x] is a UFD (via Gauss\'s Lemma) but not a PID, since the ideal (2,x) is not principal; UFD is strictly broader', isCorrect: true },
      { text: 'The two classes are essentially the same, since the implication goes both directions', isCorrect: false, misconceptionId: `${UFD}:MC-3` },
      { text: 'Every UFD is automatically a PID as well, with no known exceptions', isCorrect: false, misconceptionId: `${UFD}:MC-3` },
    ],
    targetedMisconceptions: [`${UFD}:MC-3`],
    source: eb(UFD, 'Transfer probe — UFD is strictly broader than PID, the converse fails'),
  },

  // --- math.abst.quotient-ring -----------------------------------------------------
  {
    conceptId: QUOTIENTRING, subjectSlug: S, probeKind: 'mcq', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.FOUNDATIONAL,
    stem: 'Is r+I a single number, or an entire set?',
    choices: [
      { text: 'An entire set {r+i : i∈I} — e.g. 1+4Z={...,-3,1,5,9,...}; operations depend only on the SET, never a single chosen representative', isCorrect: true },
      { text: 'A single number r, with I just decorating the notation', isCorrect: false, misconceptionId: `${QUOTIENTRING}:MC-1` },
      { text: 'A single number determined uniquely by the smallest element of I', isCorrect: false, misconceptionId: `${QUOTIENTRING}:MC-1` },
    ],
    targetedMisconceptions: [`${QUOTIENTRING}:MC-1`],
    source: eb(QUOTIENTRING, 'Assessment gate — r+I is the entire coset, never a single number'),
  },
  {
    conceptId: QUOTIENTRING, subjectSlug: S, probeKind: 'misconception_probe', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.DEVELOPING,
    stem: 'Does the quotient ring construction work for ANY subring, or does it need something more?',
    choices: [
      { text: 'It needs a genuine two-sided IDEAL — a subring that does not absorb multiplication by the whole ring produces genuinely undefined coset multiplication, since different representatives give different answers', isCorrect: true },
      { text: 'Any subring works equally well, exactly like the quotient-group construction only needs a subgroup', isCorrect: false, misconceptionId: `${QUOTIENTRING}:MC-2` },
      { text: 'Any subring works, since ring multiplication is always well-defined regardless of the substructure chosen', isCorrect: false, misconceptionId: `${QUOTIENTRING}:MC-2` },
    ],
    targetedMisconceptions: [`${QUOTIENTRING}:MC-2`],
    source: eb(QUOTIENTRING, 'Misconception register — the quotient construction needs a genuine two-sided ideal, never merely a subring'),
  },
  {
    conceptId: QUOTIENTRING, subjectSlug: S, probeKind: 'mcq', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.PROFICIENT,
    stem: 'Why does coset multiplication need I to absorb from BOTH sides?',
    choices: [
      { text: 'For different representatives r\'=r+i1, s\'=s+i2, the extra cross-terms ri2, i1s, and i1i2 must all land back in I; this requires both left absorption (ri2) and right absorption (i1s)', isCorrect: true },
      { text: 'Two-sided absorption is only a stylistic convention with no bearing on well-definedness', isCorrect: false, misconceptionId: `${QUOTIENTRING}:MC-3` },
      { text: 'Multiplication of cosets is never actually well-defined, regardless of absorption', isCorrect: false, misconceptionId: `${QUOTIENTRING}:MC-3` },
    ],
    targetedMisconceptions: [`${QUOTIENTRING}:MC-3`],
    source: eb(QUOTIENTRING, 'Transfer probe — two-sided absorption is exactly what makes coset multiplication well-defined'),
  },
]
