/**
 * Second math.abst asset batch — group-operation and cyclic-group.
 *
 * Continues serving-asset coverage for math.abst (2/36 -> 4/36). Transcribed
 * from the frozen Educational Brain entries at
 * educational-brain/concepts/mathematics/math.abst.group-operation.md and
 * math.abst.cyclic-group.md.
 *
 *   GROUPOP   group-operation — a Cayley table's symmetry reads off
 *             commutativity directly; the Latin square property is a
 *             theorem from cancellation, not an assumption; Z/nZ's
 *             identity is 0 and inverse is (n-a) mod n, never raw -a.
 *   CYCLIC    cyclic-group — cyclic groups can be infinite; not every
 *             element of a cyclic group is a generator (gcd criterion);
 *             cyclic implies abelian, but the converse is false (V4).
 *
 * Seeded as DRAFT. Promotion stays human.
 */
import { GradeBand, ProbeDifficulty } from '@prisma/client'
import type { SeedExplanation, SeedProbe } from './brainSeedAssets'

const S = 'mathematics'
const eb = (id: string, what: string) =>
  `educational-brain/concepts/mathematics/${id}.md — ${what}`

const GROUPOP = 'math.abst.group-operation'
const CYCLIC = 'math.abst.cyclic-group'

export const MATHEMATICS_ABSTRACT_ALGEBRA_GROUP_OPS_EXPLANATIONS: SeedExplanation[] = [
  {
    conceptId: GROUPOP, subjectSlug: S, familyKind: 'core_explanation', gradeBand: GradeBand.UNDERGRADUATE,
    content:
      'A Cayley table\'s SYMMETRY directly reads off commutativity: the table is symmetric (entry '
      + '(a,b) equals entry (b,a) for every pair) IF AND ONLY IF the group is ABELIAN. A '
      + 'NON-SYMMETRIC table does NOT indicate a broken group — it indicates a valid NON-ABELIAN '
      + 'group. In D3 (the dihedral group), the entry at (r,s) is rs while the entry at (s,r) is '
      + 'sr=r^2s≠rs — asymmetric at these entries, yet D3 is a completely valid group.\n\n'
      + 'Every Cayley table satisfies the LATIN SQUARE property (each element appears exactly once '
      + 'in every row and column) — this is a THEOREM, not an axiom, following directly from LEFT '
      + 'CANCELLATION: if a·b=a·c, then a^-1·(a·b)=a^-1·(a·c) ⟹ b=c, so no element can repeat in a '
      + 'row.\n\n'
      + 'MODULAR ARITHMETIC computations in Z/nZ must always be REDUCED to the canonical range '
      + '{0,...,n-1}: the identity is genuinely 0 (never n, even though n≡0 mod n), and the '
      + 'inverse of a is (n-a) mod n, NEVER simply -a unreduced.',
    targetedMisconceptions: [`${GROUPOP}:MC-1`, `${GROUPOP}:MC-2`, `${GROUPOP}:MC-3`],
    source: eb(GROUPOP, 'Core Understanding — Cayley table symmetry reads off commutativity, the Latin square property is a theorem, modular identity/inverse must be reduced'),
  },
  {
    conceptId: CYCLIC, subjectSlug: S, familyKind: 'core_explanation', gradeBand: GradeBand.UNDERGRADUATE,
    content:
      'A cyclic group is one GENERATED BY A SINGLE ELEMENT: G=⟨g⟩={g^n : n∈Z} — every element is '
      + 'SOME power of the generator g. A FINITE cyclic group of order n is isomorphic to Z/nZ; an '
      + 'INFINITE cyclic group is isomorphic to (Z,+) itself — (Z,+)=⟨1⟩ is cyclic AND infinite, '
      + 'since "cyclic" never implies "finite."\n\n'
      + 'In Z/nZ, NOT EVERY ELEMENT IS A GENERATOR: an element a generates the whole group EXACTLY '
      + 'WHEN gcd(a,n)=1. In Z/6Z, gcd(1,6)=1 and gcd(5,6)=1 give the two generators; gcd(2,6)=2 '
      + 'means ⟨2⟩={0,2,4}, a proper subgroup, not the whole group.\n\n'
      + 'EVERY CYCLIC GROUP IS ABELIAN: for G=⟨g⟩, any two elements are g^n and g^m, and '
      + 'g^n·g^m=g^(n+m)=g^(m+n)=g^m·g^n — commutativity of integer addition forces commutativity '
      + 'of the group operation. The CONVERSE IS FALSE: the Klein four-group V4=Z/2Z×Z/2Z is '
      + 'abelian (every element has order at most 2) but NOT cyclic — no single element has order '
      + '4.',
    targetedMisconceptions: [`${CYCLIC}:MC-1`, `${CYCLIC}:MC-2`, `${CYCLIC}:MC-3`],
    source: eb(CYCLIC, 'Core Understanding — cyclic groups can be infinite, not every element is a generator, cyclic implies abelian but not conversely'),
  },
]

export const MATHEMATICS_ABSTRACT_ALGEBRA_GROUP_OPS_PROBES: SeedProbe[] = [
  // --- math.abst.group-operation -----------------------------------------------
  {
    conceptId: GROUPOP, subjectSlug: S, probeKind: 'mcq', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.FOUNDATIONAL,
    stem: 'Must every group\'s Cayley table be symmetric, "because multiplication is symmetric"?',
    choices: [
      { text: 'No — an asymmetric table means the group is non-abelian, not broken; D3\'s table is asymmetric at (r,s) vs (s,r) yet D3 is a fully valid group', isCorrect: true },
      { text: 'Yes — a symmetric table is required for any valid group', isCorrect: false, misconceptionId: `${GROUPOP}:MC-1` },
      { text: 'Yes, since an asymmetric table would violate the group axioms', isCorrect: false, misconceptionId: `${GROUPOP}:MC-1` },
    ],
    targetedMisconceptions: [`${GROUPOP}:MC-1`],
    source: eb(GROUPOP, 'Assessment gate — a symmetric Cayley table indicates abelian, asymmetric indicates non-abelian, not invalid'),
  },
  {
    conceptId: GROUPOP, subjectSlug: S, probeKind: 'misconception_probe', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.DEVELOPING,
    stem: 'In Z/6Z, is the identity element 6?',
    choices: [
      { text: 'No — the identity is genuinely 0; even though 6≡0 mod 6, the canonical representative is always 0, never the modulus itself', isCorrect: true },
      { text: 'Yes — the identity in Z/nZ is always n, matching the modulus', isCorrect: false, misconceptionId: `${GROUPOP}:MC-2` },
      { text: 'Yes, since n is the most salient number in the group\'s name', isCorrect: false, misconceptionId: `${GROUPOP}:MC-2` },
    ],
    targetedMisconceptions: [`${GROUPOP}:MC-2`],
    source: eb(GROUPOP, 'Misconception register — the identity in Z/nZ is 0, never n'),
  },
  {
    conceptId: GROUPOP, subjectSlug: S, probeKind: 'mcq', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.PROFICIENT,
    stem: 'Is the inverse of a in Z/nZ always exactly "-a"?',
    choices: [
      { text: 'No — the inverse is (n-a) mod n, reduced to the canonical range {0,...,n-1}; raw -a typically falls outside that range', isCorrect: true },
      { text: 'Yes — -a is always the correct inverse regardless of the modulus', isCorrect: false, misconceptionId: `${GROUPOP}:MC-3` },
      { text: 'Yes, since modular arithmetic never requires reducing negative values', isCorrect: false, misconceptionId: `${GROUPOP}:MC-3` },
    ],
    targetedMisconceptions: [`${GROUPOP}:MC-3`],
    source: eb(GROUPOP, 'Transfer probe — the modular inverse must be reduced to the canonical range, never raw -a'),
  },

  // --- math.abst.cyclic-group ----------------------------------------------------
  {
    conceptId: CYCLIC, subjectSlug: S, probeKind: 'mcq', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.FOUNDATIONAL,
    stem: 'Does a cyclic group have to be finite, since "cyclic" evokes something that wraps around and returns to its start?',
    choices: [
      { text: 'No — (Z,+)=⟨1⟩ is cyclic and infinite; every integer is some multiple of 1, with no finiteness requirement in the definition', isCorrect: true },
      { text: 'Yes — a cyclic group must always have finitely many elements', isCorrect: false, misconceptionId: `${CYCLIC}:MC-1` },
      { text: 'Yes, since a generator\'s powers must eventually repeat', isCorrect: false, misconceptionId: `${CYCLIC}:MC-1` },
    ],
    targetedMisconceptions: [`${CYCLIC}:MC-1`],
    source: eb(CYCLIC, 'Assessment gate — cyclic groups can be infinite, e.g. (Z,+)'),
  },
  {
    conceptId: CYCLIC, subjectSlug: S, probeKind: 'misconception_probe', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.DEVELOPING,
    stem: 'If G=⟨g⟩ is cyclic, does every element of G generate the whole group?',
    choices: [
      { text: 'No — only elements coprime to n generate Z/nZ; e.g. in Z/6Z, ⟨2⟩={0,2,4} is a proper subgroup, not the whole group, since gcd(2,6)=2≠1', isCorrect: true },
      { text: 'Yes — any element of a cyclic group is automatically a generator of the whole group', isCorrect: false, misconceptionId: `${CYCLIC}:MC-2` },
      { text: 'Yes, since having a generator means all elements are equally generating', isCorrect: false, misconceptionId: `${CYCLIC}:MC-2` },
    ],
    targetedMisconceptions: [`${CYCLIC}:MC-2`],
    source: eb(CYCLIC, 'Misconception register — not every element of a cyclic group is a generator, the gcd criterion decides'),
  },
  {
    conceptId: CYCLIC, subjectSlug: S, probeKind: 'mcq', gradeBand: GradeBand.UNDERGRADUATE,
    difficulty: ProbeDifficulty.PROFICIENT,
    stem: 'Could a cyclic group fail to be abelian?',
    choices: [
      { text: 'No — every cyclic group is abelian (g^n·g^m=g^(n+m)=g^m·g^n from integer-addition commutativity), though the converse fails: V4 is abelian but not cyclic', isCorrect: true },
      { text: 'Yes — some cyclic groups can be non-abelian, just like general groups', isCorrect: false, misconceptionId: `${CYCLIC}:MC-3` },
      { text: 'Yes, since "most groups can be non-abelian" applies to cyclic groups too', isCorrect: false, misconceptionId: `${CYCLIC}:MC-3` },
    ],
    targetedMisconceptions: [`${CYCLIC}:MC-3`],
    source: eb(CYCLIC, 'Transfer probe — cyclic implies abelian always, but the converse is false'),
  },
]
