#!/usr/bin/env python3
"""
Curriculum Pipeline — Global Progress Dashboard Generator
=========================================================
Generates docs/CURRICULUM_PROGRESS.md — the campaign-level dashboard
summarizing all five subjects: completed domains, completed concepts,
remaining concepts, latest commit per subject, and overall progress.

Everything is derived from repository state (graph.json + assets.json +
chapters dir per subject + git log), never from conversation memory.

Usage:
  python3 update-global-progress.py <repoRoot> <currentCommit> <outputPath>
"""

import json
import os
import subprocess
import sys
from datetime import datetime

SUBJECTS = [
    ('mathematics',      'Mathematics',      'docs/mathematics'),
    ('physics',          'Physics',          'docs/physics'),
    ('chemistry',        'Chemistry',        'docs/chemistry'),
    ('biology',          'Biology',          'docs/biology'),
    ('computer_science', 'Computer Science', 'docs/computer-science'),
]


def latest_commit_for(repo_root, path):
    try:
        out = subprocess.run(
            ['git', '-C', repo_root, 'log', '--format=%h %ad %s', '--date=short', '-1', '--', path],
            capture_output=True, text=True, check=True
        ).stdout.strip()
        return out or 'n/a'
    except Exception:
        return 'n/a'


def subject_state(repo_root, subject_dir):
    graph_path = os.path.join(repo_root, subject_dir, 'kg', 'graph.json')
    assets_path = os.path.join(repo_root, subject_dir, 'teaching-assets', 'assets.json')
    chapters_dir = os.path.join(repo_root, subject_dir, 'chapters')

    if not os.path.exists(graph_path):
        return None

    with open(graph_path) as f:
        graph = json.load(f)

    assets = {}
    if os.path.exists(assets_path):
        with open(assets_path) as f:
            for a in json.load(f)['assets']:
                assets[a['concept_id']] = a

    chapters = set(os.listdir(chapters_dir)) if os.path.exists(chapters_dir) else set()

    domains = []
    total_concepts = len(graph.get('concepts', []))
    total_drafted = 0
    completed_domains = []
    in_progress_domains = []

    # Normalize the heterogeneous domain schemas across subject KGs:
    #   mathematics: {id_prefix, concept_count, ...}
    #   physics:     {key, name, count} with ids like phys.meas.*
    #   others:      no domains list -> derive from concept id prefixes
    subject_prefix = None
    if graph.get('concepts'):
        subject_prefix = graph['concepts'][0]['id'].split('.')[0]

    raw_domains = graph.get('domains') or []
    norm = []
    for d in raw_domains:
        if not isinstance(d, dict):
            continue
        if 'id_prefix' in d:
            norm.append((d['id_prefix'], d.get('concept_count', 0)))
        elif 'key' in d and subject_prefix:
            norm.append((f"{subject_prefix}.{d['key']}", d.get('count', 0)))
    if not norm and subject_prefix:
        seen = {}
        for c in graph['concepts']:
            parts = c['id'].split('.')
            if len(parts) >= 3:
                p = '.'.join(parts[:2])
                seen[p] = seen.get(p, 0) + 1
        norm = sorted(seen.items())

    for prefix, count in norm:
        drafted = sum(
            1 for c in graph['concepts']
            if c['id'].startswith(prefix + '.') and assets.get(c['id'], {}).get('status') == 'draft'
        )
        total_drafted += drafted
        stem = prefix.split('.')[-1]
        has_chapter = f'{stem}.md' in chapters
        complete = drafted == count and count > 0 and has_chapter
        if complete:
            completed_domains.append(prefix)
        elif drafted > 0:
            in_progress_domains.append(f'{prefix} ({drafted}/{count})')
        domains.append((prefix, drafted, count, complete))

    return {
        'kg_version': graph.get('version'),
        'kg_status': graph.get('status'),
        'total_concepts': total_concepts,
        'total_domains': len(norm),
        'drafted': total_drafted,
        'completed_domains': completed_domains,
        'in_progress_domains': in_progress_domains,
        'domains': domains,
    }


def main():
    if len(sys.argv) != 4:
        print('Usage: python3 update-global-progress.py <repoRoot> <currentCommit> <outputPath>')
        sys.exit(1)

    repo_root, current_commit, output_path = sys.argv[1:]

    lines = []
    lines.append('# Canonical Curriculum — Global Progress Dashboard')
    lines.append('')
    lines.append('> Auto-generated by `scripts/pipeline/update-global-progress.py` from repository')
    lines.append('> state (graph.json + assets.json + chapters/ per subject). Do not edit by hand.')
    lines.append('')
    lines.append(f'Last updated: {datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")} · Commit: `{current_commit}`')
    lines.append('')

    campaign_total = 0
    campaign_drafted = 0
    rows = []

    subject_sections = []
    for sid, name, sdir in SUBJECTS:
        st = subject_state(repo_root, sdir)
        if st is None:
            rows.append((name, '—', '—', '—', 'no KG'))
            continue
        campaign_total += st['total_concepts']
        campaign_drafted += st['drafted']
        pct = round(st['drafted'] / st['total_concepts'] * 100, 1) if st['total_concepts'] else 0
        commit = latest_commit_for(repo_root, sdir)
        status = ('complete' if len(st['completed_domains']) == st['total_domains'] and st['total_domains']
                  else 'in progress' if st['drafted'] else 'not started')
        rows.append((name,
                     f"{len(st['completed_domains'])}/{st['total_domains']}",
                     f"{st['drafted']}/{st['total_concepts']}",
                     f'{pct}%',
                     status))

        sec = [f'## {name}', '']
        sec.append(f"- KG: v{st['kg_version']} ({st['kg_status']}), {st['total_concepts']} concepts, "
                   f"{st['total_domains']} domains")
        sec.append(f"- Completed domains ({len(st['completed_domains'])}): "
                   + (', '.join(f'`{p}`' for p in st['completed_domains']) if st['completed_domains'] else 'none'))
        if st['in_progress_domains']:
            sec.append(f"- In progress: {', '.join(st['in_progress_domains'])}")
        remaining = st['total_concepts'] - st['drafted']
        sec.append(f"- Concepts: {st['drafted']} drafted, {remaining} remaining ({pct}%)")
        sec.append(f'- Latest subject commit: {commit}')
        next_domain = next((p for p, dr, ct, comp in st['domains'] if not comp), None)
        sec.append(f"- Next domain: {'`' + next_domain + '`' if next_domain else 'ALL COMPLETE'}")
        sec.append('')
        subject_sections.extend(sec)

    overall_pct = round(campaign_drafted / campaign_total * 100, 1) if campaign_total else 0

    lines.append('## Campaign Summary')
    lines.append('')
    lines.append('| Subject | Domains complete | Concepts drafted | % | Status |')
    lines.append('|---|---|---|---|---|')
    for r in rows:
        lines.append('| ' + ' | '.join(str(x) for x in r) + ' |')
    lines.append('')
    lines.append(f'**Overall campaign: {campaign_drafted}/{campaign_total} concepts drafted ({overall_pct}%)**')
    lines.append('')
    lines.extend(subject_sections)

    with open(output_path, 'w') as f:
        f.write('\n'.join(lines) + '\n')

    print(f'Global dashboard written to {output_path}')
    print(f'  Campaign: {campaign_drafted}/{campaign_total} ({overall_pct}%)')


if __name__ == '__main__':
    main()
