import type { KnowledgeNode } from './educationTypes'

export const BIOLOGY_KNOWLEDGE_GRAPH: KnowledgeNode[] = [
  // ─── DIVERSITY ───────────────────────────────────────────────
  { id: 'biology.diversity', domain: 'biology', title: 'Biological Classification and Diversity', description: 'Need for classification; Whittaker\'s five kingdom classification; salient features and classification of Monera, Protista, Fungi, Plantae, Animalia; viruses, viroids, prions and lichens; taxonomic hierarchy — species to kingdom; nomenclature', difficulty: 'foundational', prerequisites: [] },
  { id: 'biology.plant_kingdom', domain: 'biology', title: 'Plant Kingdom', description: 'Algae, Bryophytes, Pteridophytes, Gymnosperms, Angiosperms — distinguishing features, alternation of generations; plant life cycles; seeds, fruits; economic importance of each group', difficulty: 'foundational', prerequisites: ['biology.diversity'] },
  { id: 'biology.animal_kingdom', domain: 'biology', title: 'Animal Kingdom', description: 'Basis of classification — symmetry, coelom, segmentation, notochord; non-chordates — Porifera to Echinodermata; chordates — Cyclostomata to Mammalia; salient features and examples of each phylum/class', difficulty: 'foundational', prerequisites: ['biology.diversity'] },

  // ─── CELL BIOLOGY ────────────────────────────────────────────
  { id: 'biology.cell_structure', domain: 'biology', title: 'Cell — The Unit of Life', description: 'Prokaryotic vs eukaryotic cells; cell theory; cell organelles — cell wall, plasma membrane, endoplasmic reticulum, Golgi apparatus, lysosomes, mitochondria, plastids, ribosomes, vacuoles, centrosome; nucleus; microbodies; cytoskeleton', difficulty: 'foundational', prerequisites: ['biology.diversity'] },
  { id: 'biology.biomolecules', domain: 'biology', title: 'Biomolecules', description: 'Types of biomolecules; carbohydrates — monosaccharides, polysaccharides; proteins — amino acids, peptide bond, levels of protein structure; lipids — fats, phospholipids; nucleic acids — DNA and RNA; enzymes — classification, properties, cofactors, inhibition, enzyme kinetics', difficulty: 'developing', prerequisites: ['biology.cell_structure'] },
  { id: 'biology.cell_division', domain: 'biology', title: 'Cell Cycle and Cell Division', description: 'Cell cycle — interphase and M phase; mitosis — stages and significance; meiosis — meiosis I and II, significance; differences between mitosis and meiosis; cell cycle regulation; cancer basics', difficulty: 'developing', prerequisites: ['biology.cell_structure'] },

  // ─── PLANT PHYSIOLOGY ────────────────────────────────────────
  { id: 'biology.transport_plants', domain: 'biology', title: 'Transport in Plants', description: 'Diffusion and osmosis; water potential; plasmolysis; water absorption by roots; ascent of sap; transpiration — stomatal mechanism; translocation in phloem — pressure flow hypothesis; mineral absorption; active transport', difficulty: 'developing', prerequisites: ['biology.cell_structure'] },
  { id: 'biology.mineral_nutrition', domain: 'biology', title: 'Mineral Nutrition', description: 'Essential mineral elements — macro and micronutrients; deficiency symptoms; role of N, P, K, Ca, Mg, S, Fe, Mn, Zn, Cu, Mo, B; nitrogen cycle; biological nitrogen fixation; nitrogen metabolism — nitrate reduction, amination, transamination', difficulty: 'developing', prerequisites: ['biology.transport_plants'] },
  { id: 'biology.photosynthesis', domain: 'biology', title: 'Photosynthesis', description: 'Light reactions — photosystem I and II, Z-scheme, photophosphorylation; Calvin cycle — C3 pathway; C4 pathway and Kranz anatomy; CAM plants; photorespiration; factors affecting photosynthesis; photosynthetic pigments', difficulty: 'proficient', prerequisites: ['biology.biomolecules'] },
  { id: 'biology.respiration_plants', domain: 'biology', title: 'Respiration in Plants', description: 'Aerobic and anaerobic respiration; glycolysis; Krebs cycle; oxidative phosphorylation and ETC; fermentation; amphibolic pathway; respiratory quotient; energy balance sheet', difficulty: 'proficient', prerequisites: ['biology.photosynthesis'] },
  { id: 'biology.plant_growth', domain: 'biology', title: 'Plant Growth and Development', description: 'Growth regulators — auxin, gibberellin, cytokinin, ABA, ethylene; seed dormancy; vernalisation; photoperiodism; flowering; apical dominance; fruit ripening; stress responses; senescence', difficulty: 'proficient', prerequisites: ['biology.mineral_nutrition'] },

  // ─── ANIMAL PHYSIOLOGY ───────────────────────────────────────
  { id: 'biology.digestion', domain: 'biology', title: 'Digestion and Absorption', description: 'Human alimentary canal; digestive glands — salivary, gastric, pancreas, liver; digestion of carbohydrates, proteins and fats; intestinal absorption; peristalsis; digestive disorders — PEM, constipation, vomiting, jaundice, diarrhoea', difficulty: 'developing', prerequisites: ['biology.biomolecules'] },
  { id: 'biology.respiration_animals', domain: 'biology', title: 'Breathing and Gas Exchange', description: 'Respiratory organs in different animals; human respiratory system; mechanism of breathing — inspiration and expiration; pulmonary volumes; transport of oxygen — oxyhaemoglobin; transport of CO₂; regulation of respiration; respiratory disorders', difficulty: 'developing', prerequisites: ['biology.animal_kingdom'] },
  { id: 'biology.circulation', domain: 'biology', title: 'Body Fluids and Circulation', description: 'Blood — composition, blood groups, coagulation; lymph; heart structure — chambers, valves; cardiac cycle; cardiac output; ECG; blood vessels; blood pressure; hypertension; coronary artery disease; lymphatic system', difficulty: 'developing', prerequisites: ['biology.respiration_animals'] },
  { id: 'biology.excretion', domain: 'biology', title: 'Excretory Products and Elimination', description: 'Modes of excretion — ammonotelism, ureotelism, uricotelism; human excretory system; nephron structure; urine formation — filtration, reabsorption, secretion; concentration of urine; regulation — ADH, RAAS; kidney disorders; artificial kidney', difficulty: 'proficient', prerequisites: ['biology.circulation'] },
  { id: 'biology.locomotion', domain: 'biology', title: 'Locomotion and Movement', description: 'Types of movement — amoeboid, ciliary, muscular; muscle types; ultra-structure of sarcomere; sliding filament theory; muscle contraction mechanism; skeletal system — axial and appendicular; joints; bone disorders — osteoporosis, arthritis, gout', difficulty: 'proficient', prerequisites: ['biology.animal_kingdom'] },
  { id: 'biology.neural_control', domain: 'biology', title: 'Neural Control and Coordination', description: 'Neuron structure; types of neurons; synapse; neurotransmitters; resting and action potential; conduction of nerve impulse; human brain — structure and functions; spinal cord; reflex arc; sensory organs — eye and ear', difficulty: 'proficient', prerequisites: ['biology.cell_structure'] },
  { id: 'biology.chemical_coordination', domain: 'biology', title: 'Chemical Coordination and Integration', description: 'Endocrine glands — pituitary, thyroid, parathyroid, adrenal, pancreas, gonads, thymus, pineal; hormones — structure and mechanism; feedback regulation; role of hormones in metabolism, growth, reproduction; diabetes; dwarfism and gigantism', difficulty: 'proficient', prerequisites: ['biology.neural_control'] },

  // ─── REPRODUCTION ────────────────────────────────────────────
  { id: 'biology.reproduction_plants', domain: 'biology', title: 'Reproduction in Plants', description: 'Asexual reproduction — vegetative propagation, budding, fragmentation, sporulation; sexual reproduction in angiosperms — flower structure, microsporogenesis, megasporogenesis, pollination, fertilisation, embryo development, endosperm; apomixis, polyembryony', difficulty: 'developing', prerequisites: ['biology.plant_kingdom'] },
  { id: 'biology.reproduction_humans', domain: 'biology', title: 'Human Reproduction', description: 'Male reproductive system; female reproductive system; gametogenesis — spermatogenesis, oogenesis; menstrual cycle; fertilisation and implantation; pregnancy — placenta, embryonic development; parturition; lactation', difficulty: 'proficient', prerequisites: ['biology.chemical_coordination'] },
  { id: 'biology.reproductive_health', domain: 'biology', title: 'Reproductive Health', description: 'Problems and strategies; birth control — natural, barrier, IUDs, hormonal, surgical; MTP; STIs/STDs; infertility and ART — IVF, ZIFT, GIFT, AI; amniocentesis; population growth', difficulty: 'developing', prerequisites: ['biology.reproduction_humans'] },

  // ─── GENETICS ────────────────────────────────────────────────
  { id: 'biology.mendelian_genetics', domain: 'biology', title: 'Principles of Inheritance — Mendelian Genetics', description: 'Mendel\'s experiments; laws of inheritance — dominance, segregation, independent assortment; monohybrid and dihybrid crosses; incomplete dominance; codominance; multiple alleles and ABO blood groups; pleiotropy; sex determination in humans; sex-linked inheritance', difficulty: 'developing', prerequisites: ['biology.cell_division'] },
  { id: 'biology.molecular_genetics', domain: 'biology', title: 'Molecular Basis of Inheritance', description: 'DNA as genetic material — Griffith\'s experiment, Avery\'s experiment, Hershey-Chase; DNA structure — Watson-Crick model; RNA structure and types; DNA replication; transcription; genetic code; translation; gene regulation — lac operon; human genome project; DNA fingerprinting', difficulty: 'advanced', prerequisites: ['biology.mendelian_genetics', 'biology.biomolecules'] },
  { id: 'biology.evolution', domain: 'biology', title: 'Evolution', description: 'Origin of life — chemical evolution, Miller-Urey experiment; Darwin\'s theory; evidences — palaeontology, biogeography, embryology, comparative anatomy; Hardy-Weinberg principle; mechanisms of evolution — mutation, natural selection, genetic drift; speciation; adaptive radiation; human evolution', difficulty: 'proficient', prerequisites: ['biology.mendelian_genetics'] },

  // ─── APPLIED BIOLOGY ─────────────────────────────────────────
  { id: 'biology.human_health', domain: 'biology', title: 'Human Health and Disease', description: 'Common diseases — typhoid, pneumonia, malaria, amoebiasis, ascariasis, elephantiasis, ringworm; immune system — innate and adaptive immunity; B and T lymphocytes; vaccines; allergies; autoimmunity; AIDS — structure of HIV, transmission, treatment; cancer', difficulty: 'proficient', prerequisites: ['biology.circulation'] },
  { id: 'biology.biotechnology_principles', domain: 'biology', title: 'Biotechnology — Principles and Processes', description: 'Recombinant DNA technology; restriction enzymes; cloning vectors — plasmids and bacteriophages; PCR; gel electrophoresis; transformation; expression of recombinant proteins; bioreactors; downstream processing', difficulty: 'advanced', prerequisites: ['biology.molecular_genetics'] },
  { id: 'biology.biotechnology_applications', domain: 'biology', title: 'Biotechnology and Its Applications', description: 'Genetically modified organisms; Bt crops — Bt toxin, advantages, controversies; golden rice; Gene therapy; molecular diagnosis — ELISA, PCR; transgenic animals; ethical issues; biopiracy; patents', difficulty: 'advanced', prerequisites: ['biology.biotechnology_principles'] },
  { id: 'biology.ecosystem', domain: 'biology', title: 'Ecosystem', description: 'Ecosystem structure; food chains and food webs; trophic levels; ecological pyramids — number, biomass, energy; energy flow — 10% law; primary production — gross and net; decomposition; nutrient cycling — carbon, nitrogen, phosphorus cycles; ecosystem services', difficulty: 'proficient', prerequisites: ['biology.diversity'] },
  { id: 'biology.biodiversity', domain: 'biology', title: 'Biodiversity and Conservation', description: 'Patterns of biodiversity; latitudinal gradients; species-area relationship; importance of biodiversity; biodiversity loss — causes (HIPPO); endangered and extinct species; conservation — in-situ (biosphere reserves, national parks, sanctuaries) and ex-situ (seed banks, zoos); hotspots; Convention on Biological Diversity', difficulty: 'proficient', prerequisites: ['biology.ecosystem'] },
  { id: 'biology.environmental_issues', domain: 'biology', title: 'Environmental Issues', description: 'Air pollution — causes, effects, control; water pollution; solid waste management; agrochemicals and their effects; radioactive waste; greenhouse effect and global warming; ozone depletion; deforestation; people\'s participation; case studies', difficulty: 'developing', prerequisites: ['biology.ecosystem'] },
]

export function getBiologyNode(id: string): KnowledgeNode | undefined {
  return BIOLOGY_KNOWLEDGE_GRAPH.find((n) => n.id === id)
}

export function getBiologyNodesByDomain(domain: string): KnowledgeNode[] {
  return BIOLOGY_KNOWLEDGE_GRAPH.filter((n) => n.domain === domain)
}
