import type { KnowledgeNode } from './educationTypes'

export const CHEMISTRY_KNOWLEDGE_GRAPH: KnowledgeNode[] = [
  // ─── BASIC CONCEPTS ──────────────────────────────────────────
  { id: 'chemistry.basic_concepts', domain: 'chemistry', title: 'Some Basic Concepts of Chemistry', description: 'Matter and its classification; physical and chemical properties; laws of chemical combination; atomic and molecular masses; mole concept and Avogadro\'s number; percentage composition; empirical and molecular formulae; stoichiometry and limiting reagent', difficulty: 'foundational', prerequisites: [] },
  { id: 'chemistry.atomic_structure', domain: 'chemistry', title: 'Structure of Atom', description: 'Discovery of electron, proton, neutron; Rutherford\'s model; Bohr\'s model; quantum mechanical model; quantum numbers — n, l, m, s; shapes of s, p, d orbitals; Aufbau principle, Pauli exclusion principle, Hund\'s rule; electronic configuration', difficulty: 'foundational', prerequisites: ['chemistry.basic_concepts'] },
  { id: 'chemistry.periodic_table', domain: 'chemistry', title: 'Classification of Elements and Periodicity', description: 'Modern periodic law; periods and groups; s, p, d, f blocks; periodic trends — atomic radius, ionic radius, ionisation enthalpy, electron gain enthalpy, electronegativity, valence; anomalous properties of second period elements', difficulty: 'foundational', prerequisites: ['chemistry.atomic_structure'] },

  // ─── BONDING ─────────────────────────────────────────────────
  { id: 'chemistry.chemical_bonding', domain: 'chemistry', title: 'Chemical Bonding and Molecular Structure', description: 'Ionic bond; covalent bond; VSEPR theory; bond parameters — length, angle, energy, order; hybridisation — sp, sp², sp³, sp³d, sp³d²; molecular orbital theory; bond polarity; dipole moment; resonance; hydrogen bonding', difficulty: 'developing', prerequisites: ['chemistry.periodic_table'] },
  { id: 'chemistry.states_of_matter', domain: 'chemistry', title: 'States of Matter', description: 'Intermolecular forces; kinetic molecular theory; gas laws — Boyle\'s, Charles\', Avogadro\'s, Gay-Lussac\'s; ideal gas equation; real gases and van der Waals equation; liquefaction; viscosity and surface tension; liquid crystals', difficulty: 'developing', prerequisites: ['chemistry.chemical_bonding'] },

  // ─── THERMODYNAMICS ──────────────────────────────────────────
  { id: 'chemistry.thermodynamics', domain: 'chemistry', title: 'Thermodynamics', description: 'System and surroundings; exothermic and endothermic reactions; enthalpy; Hess\'s law; standard enthalpy of formation, combustion, atomisation; bond dissociation enthalpy; Gibbs free energy; spontaneity; entropy', difficulty: 'proficient', prerequisites: ['chemistry.states_of_matter'] },
  { id: 'chemistry.equilibrium', domain: 'chemistry', title: 'Equilibrium', description: 'Dynamic equilibrium; law of mass action; Kc and Kp; Le Chatelier\'s principle; factors affecting equilibrium; ionic equilibrium — ionisation of acids and bases; pH; buffer solutions; solubility product; common ion effect', difficulty: 'proficient', prerequisites: ['chemistry.thermodynamics'] },

  // ─── REDOX ───────────────────────────────────────────────────
  { id: 'chemistry.redox', domain: 'chemistry', title: 'Redox Reactions', description: 'Oxidation and reduction; oxidation number; balancing redox reactions — oxidation number method and ion-electron method; electrochemical series; disproportionation reactions', difficulty: 'developing', prerequisites: ['chemistry.chemical_bonding'] },
  { id: 'chemistry.electrochemistry', domain: 'chemistry', title: 'Electrochemistry', description: 'Electrochemical cells — galvanic and electrolytic; EMF; Nernst equation; Faraday\'s laws of electrolysis; conductance and molar conductivity; Kohlrausch\'s law; corrosion; fuel cells; batteries', difficulty: 'advanced', prerequisites: ['chemistry.redox', 'chemistry.equilibrium'] },

  // ─── KINETICS ────────────────────────────────────────────────
  { id: 'chemistry.kinetics', domain: 'chemistry', title: 'Chemical Kinetics', description: 'Rate of reaction; rate law and rate constant; order and molecularity; integrated rate equations — zero, first, second order; half-life; Arrhenius equation; activation energy; collision theory; catalyst', difficulty: 'proficient', prerequisites: ['chemistry.equilibrium'] },

  // ─── SURFACE CHEMISTRY ───────────────────────────────────────
  { id: 'chemistry.surface', domain: 'chemistry', title: 'Surface Chemistry', description: 'Adsorption — physisorption and chemisorption; Freundlich isotherm; catalysis — homogeneous, heterogeneous, enzyme; colloids — types, preparation, properties, Tyndall effect, Brownian motion, coagulation; emulsions', difficulty: 'proficient', prerequisites: ['chemistry.kinetics'] },

  // ─── PERIODIC TABLE CHEMISTRY ────────────────────────────────
  { id: 'chemistry.hydrogen', domain: 'chemistry', title: 'Hydrogen', description: 'Position of hydrogen; isotopes; preparation and properties of hydrogen; hydrides — ionic, covalent, metallic; water — structure, anomalous properties, hard and soft water, heavy water; hydrogen peroxide', difficulty: 'developing', prerequisites: ['chemistry.periodic_table'] },
  { id: 'chemistry.s_block', domain: 'chemistry', title: 's-Block Elements (Alkali and Alkaline Earth Metals)', description: 'General properties; anomalous behaviour of Li and Be; compounds of sodium — NaOH, Na₂CO₃, NaHCO₃, NaCl; CaO, Ca(OH)₂, CaCO₃; biological importance of Na, K, Mg, Ca; Portland cement', difficulty: 'developing', prerequisites: ['chemistry.periodic_table'] },
  { id: 'chemistry.p_block_13_14', domain: 'chemistry', title: 'p-Block Elements — Groups 13 and 14', description: 'General trends; anomalous behaviour of boron and carbon; boron compounds — borax, boric acid, diborane; carbon allotropes; CO, CO₂, carbonate chemistry; silicon — silicates, silicones; aluminium — uses and compounds', difficulty: 'proficient', prerequisites: ['chemistry.chemical_bonding'] },
  { id: 'chemistry.p_block_15_16_17_18', domain: 'chemistry', title: 'p-Block Elements — Groups 15 to 18', description: 'Group 15 — N₂ fixation, ammonia, nitric acid, phosphorus allotropes, oxoacids; Group 16 — oxygen allotropy, ozone, SO₂, H₂SO₄; Group 17 — halogens, halogen acids, interhalogen compounds; Group 18 — noble gas properties, uses', difficulty: 'proficient', prerequisites: ['chemistry.p_block_13_14'] },
  { id: 'chemistry.d_f_block', domain: 'chemistry', title: 'd- and f-Block Elements', description: 'Transition elements — general properties, variable oxidation states, complex formation, colour, magnetic properties, catalytic activity; inner transition elements — lanthanides, actinides; lanthanide contraction; important compounds of Cr, Mn, Fe', difficulty: 'advanced', prerequisites: ['chemistry.p_block_15_16_17_18'] },
  { id: 'chemistry.coordination', domain: 'chemistry', title: 'Coordination Compounds', description: 'Werner\'s theory; terminology — central atom, ligands, coordination number, oxidation state; IUPAC nomenclature; isomerism — structural and stereoisomerism; bonding — VBT and CFT; colour, magnetic properties and stability; importance in biology and industry', difficulty: 'advanced', prerequisites: ['chemistry.d_f_block'] },

  // ─── ORGANIC CHEMISTRY ───────────────────────────────────────
  { id: 'chemistry.organic_basics', domain: 'chemistry', title: 'Organic Chemistry — Basic Principles', description: 'Classification and IUPAC nomenclature; structural and stereoisomerism; reaction intermediates — carbocations, carbanions, free radicals; inductive, resonance and hyperconjugation effects; homolytic and heterolytic fission; reaction types — substitution, addition, elimination', difficulty: 'developing', prerequisites: ['chemistry.chemical_bonding'] },
  { id: 'chemistry.hydrocarbons', domain: 'chemistry', title: 'Hydrocarbons', description: 'Alkanes — nomenclature, conformations, free radical halogenation; alkenes — addition reactions, Markovnikov\'s rule, ozonolysis; alkynes — acidic character, reactions; benzene — aromaticity, electrophilic substitution; petroleum refining', difficulty: 'developing', prerequisites: ['chemistry.organic_basics'] },
  { id: 'chemistry.haloalkanes', domain: 'chemistry', title: 'Haloalkanes and Haloarenes', description: 'Nomenclature; SN1 and SN2 reactions; stereochemistry of SN reactions; elimination reactions; reactions of haloarenes; environmental effects of polyhalogen compounds; DDT, freons', difficulty: 'proficient', prerequisites: ['chemistry.hydrocarbons'] },
  { id: 'chemistry.alcohols_ethers', domain: 'chemistry', title: 'Alcohols, Phenols and Ethers', description: 'Preparation and properties of alcohols; acidity of phenols; reactions of phenols; Williamson synthesis; preparation and reactions of ethers; industrial applications', difficulty: 'proficient', prerequisites: ['chemistry.haloalkanes'] },
  { id: 'chemistry.carbonyl', domain: 'chemistry', title: 'Aldehydes, Ketones and Carboxylic Acids', description: 'Nucleophilic addition reactions; oxidation of aldehydes; Cannizzaro and aldol reactions; tests for aldehydes; preparation and reactions of carboxylic acids; acidity; derivatives — acid chlorides, anhydrides, esters, amides', difficulty: 'proficient', prerequisites: ['chemistry.alcohols_ethers'] },
  { id: 'chemistry.nitrogen_compounds', domain: 'chemistry', title: 'Amines and Diazonium Salts', description: 'Classification and nomenclature of amines; basicity; preparation — Gabriel synthesis, reduction; reactions — alkylation, acylation, Schiff\'s base; carbylamine test; diazonium salts — preparation and reactions; coupling reactions; azo dyes', difficulty: 'advanced', prerequisites: ['chemistry.carbonyl'] },

  // ─── BIOMOLECULES AND POLYMERS ───────────────────────────────
  { id: 'chemistry.biomolecules', domain: 'chemistry', title: 'Biomolecules', description: 'Carbohydrates — classification, glucose structure, anomers, polysaccharides; proteins — amino acids, peptide bond, primary/secondary/tertiary/quaternary structure, denaturation, enzymes; nucleic acids — DNA and RNA structure, base pairing; lipids; vitamins and hormones', difficulty: 'advanced', prerequisites: ['chemistry.carbonyl'] },
  { id: 'chemistry.polymers', domain: 'chemistry', title: 'Polymers', description: 'Classification; addition and condensation polymerisation; natural rubber; synthetic polymers — polyethylene, PVC, Teflon, nylon, polyester, Bakelite; rubber vulcanisation; biodegradable polymers; polymers in medicine', difficulty: 'proficient', prerequisites: ['chemistry.organic_basics'] },
  { id: 'chemistry.everyday_chemistry', domain: 'chemistry', title: 'Chemistry in Everyday Life', description: 'Drugs — analgesics, tranquillisers, antiseptics, disinfectants, antimicrobials, antifertility drugs, antihistamines; food preservatives, artificial sweeteners, antioxidants; soaps and detergents; cleansing action; rocket propellants', difficulty: 'developing', prerequisites: ['chemistry.biomolecules'] },

  // ─── ENVIRONMENTAL ───────────────────────────────────────────
  { id: 'chemistry.environmental', domain: 'chemistry', title: 'Environmental Chemistry', description: 'Environmental pollution — air, water, soil; smog; acid rain; ozone depletion; global warming; greenhouse effect; industrial waste; green chemistry principles; strategies to control pollution', difficulty: 'developing', prerequisites: ['chemistry.basic_concepts'] },
]

export function getChemistryNode(id: string): KnowledgeNode | undefined {
  return CHEMISTRY_KNOWLEDGE_GRAPH.find((n) => n.id === id)
}

export function getChemistryNodesByDomain(domain: string): KnowledgeNode[] {
  return CHEMISTRY_KNOWLEDGE_GRAPH.filter((n) => n.domain === domain)
}
