import type { KnowledgeNode } from './educationTypes'

export const COMPUTER_SCIENCE_KNOWLEDGE_GRAPH: KnowledgeNode[] = [
  // ─── COMPUTER FUNDAMENTALS ───────────────────────────────────
  { id: 'cs.intro_computers', domain: 'cs', title: 'Introduction to Computers', description: 'History and generations of computers; characteristics — speed, accuracy, storage, versatility; types of computers — micro, mini, mainframe, supercomputer; hardware vs software; applications of computers', difficulty: 'foundational', prerequisites: [] },
  { id: 'cs.computer_organisation', domain: 'cs', title: 'Computer Organisation', description: 'CPU components — ALU, CU, registers; memory hierarchy — registers, cache, RAM, secondary storage; input and output devices; buses — data, address, control; fetch-decode-execute cycle', difficulty: 'foundational', prerequisites: ['cs.intro_computers'] },
  { id: 'cs.memory_storage', domain: 'cs', title: 'Memory and Storage', description: 'Primary memory — RAM (DRAM, SRAM), ROM (PROM, EPROM, EEPROM); secondary storage — HDD, SSD, optical discs, flash drives; units of measurement — bit, byte, KB, MB, GB, TB; access time and storage capacity', difficulty: 'foundational', prerequisites: ['cs.computer_organisation'] },
  { id: 'cs.number_systems', domain: 'cs', title: 'Number Systems', description: 'Decimal, binary, octal and hexadecimal number systems; conversion between bases; binary arithmetic — addition, subtraction, multiplication; 1\'s and 2\'s complement; BCD, ASCII, Unicode', difficulty: 'foundational', prerequisites: ['cs.intro_computers'] },
  { id: 'cs.boolean_logic', domain: 'cs', title: 'Boolean Logic and Logic Gates', description: 'Boolean algebra — AND, OR, NOT operations; De Morgan\'s laws; logic gates — AND, OR, NOT, NAND, NOR, XOR, XNOR; truth tables; half adder and full adder circuits; simplification using Boolean identities', difficulty: 'developing', prerequisites: ['cs.number_systems'] },

  // ─── SOFTWARE AND OS ─────────────────────────────────────────
  { id: 'cs.software', domain: 'cs', title: 'Software Concepts', description: 'System software vs application software; types of system software — OS, language translators, utility programs; types of application software; open source vs proprietary; freeware, shareware, firmware', difficulty: 'foundational', prerequisites: ['cs.intro_computers'] },
  { id: 'cs.operating_system', domain: 'cs', title: 'Operating System', description: 'Functions of OS — process management, memory management, file management, I/O management; types — batch, time-sharing, real-time, distributed, mobile; process states and scheduling concepts; Windows vs Linux basics', difficulty: 'developing', prerequisites: ['cs.software', 'cs.computer_organisation'] },

  // ─── ALGORITHMS AND PROBLEM SOLVING ──────────────────────────
  { id: 'cs.problem_solving', domain: 'cs', title: 'Problem Solving Methodology', description: 'Steps in problem solving — problem analysis, algorithm design, coding, testing, documentation; understanding the problem; decomposition; generalisation and abstraction', difficulty: 'foundational', prerequisites: ['cs.intro_computers'] },
  { id: 'cs.algorithms', domain: 'cs', title: 'Algorithms', description: 'Definition and properties of algorithms; representation — natural language, pseudocode, flowcharts; flowchart symbols; sequence, selection and iteration structures; algorithm efficiency — time and space complexity basics', difficulty: 'developing', prerequisites: ['cs.problem_solving'] },
  { id: 'cs.flowcharts', domain: 'cs', title: 'Flowcharts', description: 'Flowchart conventions and symbols; drawing flowcharts for linear, conditional and iterative problems; decision flowcharts; nested loops in flowcharts; converting flowcharts to pseudocode', difficulty: 'developing', prerequisites: ['cs.algorithms'] },

  // ─── PROGRAMMING BASICS ──────────────────────────────────────
  { id: 'cs.programming_intro', domain: 'cs', title: 'Introduction to Programming', description: 'High-level vs low-level languages; compilers, interpreters and assemblers; source code and object code; programming paradigms — procedural, object-oriented, functional; REPL environments', difficulty: 'foundational', prerequisites: ['cs.algorithms'] },
  { id: 'cs.python_basics', domain: 'cs', title: 'Python Basics', description: 'Python history and features; interactive mode vs script mode; tokens — keywords, identifiers, literals, operators, punctuators; comments; print() and input(); IDLE environment; indentation rules', difficulty: 'foundational', prerequisites: ['cs.programming_intro'] },
  { id: 'cs.data_types', domain: 'cs', title: 'Data Types and Variables', description: 'Python data types — int, float, complex, bool, str, None; mutable vs immutable; type() and isinstance(); variable assignment and multiple assignment; type conversion — implicit and explicit (int(), float(), str())', difficulty: 'foundational', prerequisites: ['cs.python_basics'] },
  { id: 'cs.operators', domain: 'cs', title: 'Operators and Expressions', description: 'Arithmetic operators; relational operators; logical operators (and, or, not); bitwise operators; assignment operators; membership operators (in, not in); identity operators (is, is not); operator precedence and associativity', difficulty: 'developing', prerequisites: ['cs.data_types'] },
  { id: 'cs.input_output', domain: 'cs', title: 'Input/Output and Type Casting', description: 'input() function; print() with sep and end parameters; formatted output — % formatting, format(), f-strings; int(), float(), str(), eval(); reading multiple values; output formatting', difficulty: 'developing', prerequisites: ['cs.operators'] },

  // ─── CONTROL STRUCTURES ──────────────────────────────────────
  { id: 'cs.conditionals', domain: 'cs', title: 'Conditional Statements', description: 'if statement; if-else; if-elif-else; nested if; short-circuit evaluation; ternary (conditional) expressions; common patterns — max/min, range checks, grade classification', difficulty: 'developing', prerequisites: ['cs.operators'] },
  { id: 'cs.loops', domain: 'cs', title: 'Loops', description: 'while loop — syntax and flow; for loop — syntax, range(); break, continue, pass; else clause with loops; nested loops; loop patterns — counting, accumulation, flag-controlled; common pitfalls — infinite loops', difficulty: 'developing', prerequisites: ['cs.conditionals'] },

  // ─── DATA STRUCTURES ─────────────────────────────────────────
  { id: 'cs.strings', domain: 'cs', title: 'Strings', description: 'String creation and indexing; positive and negative indexing; slicing; string operators (+, *, in, not in); string methods — len(), upper(), lower(), strip(), split(), replace(), find(), count(), join(); immutability; string traversal', difficulty: 'developing', prerequisites: ['cs.loops'] },
  { id: 'cs.lists', domain: 'cs', title: 'Lists', description: 'List creation, indexing and slicing; list operators; list methods — append(), extend(), insert(), remove(), pop(), sort(), reverse(), index(), count(), copy(); list comprehension; 2D lists; mutability; list as stack and queue', difficulty: 'developing', prerequisites: ['cs.strings'] },
  { id: 'cs.tuples', domain: 'cs', title: 'Tuples', description: 'Tuple creation — with and without parentheses; single-element tuple; indexing, slicing, unpacking; tuple methods — count(), index(); immutability; when to use tuples vs lists; nested tuples', difficulty: 'developing', prerequisites: ['cs.lists'] },
  { id: 'cs.dictionaries', domain: 'cs', title: 'Dictionaries', description: 'Dictionary creation; key-value pairs; accessing, updating, adding and deleting items; dictionary methods — keys(), values(), items(), get(), update(), pop(), clear(), copy(); iterating over dictionaries; nested dictionaries', difficulty: 'developing', prerequisites: ['cs.lists'] },
  { id: 'cs.sets', domain: 'cs', title: 'Sets', description: 'Set creation; set properties — unordered, unique elements; set operators — union, intersection, difference, symmetric difference; set methods — add(), remove(), discard(), pop(), clear(); frozenset', difficulty: 'developing', prerequisites: ['cs.dictionaries'] },

  // ─── FUNCTIONS ───────────────────────────────────────────────
  { id: 'cs.functions', domain: 'cs', title: 'Functions', description: 'Defining and calling functions; parameters and arguments; return statement; default parameters; keyword arguments; variable-length arguments (*args, **kwargs); scope — local vs global; global keyword; docstrings', difficulty: 'proficient', prerequisites: ['cs.loops'] },
  { id: 'cs.recursion', domain: 'cs', title: 'Recursion', description: 'Concept of recursion; base case and recursive case; call stack; recursive solutions — factorial, Fibonacci, power, GCD; tail recursion concept; advantages and disadvantages; recursion vs iteration', difficulty: 'proficient', prerequisites: ['cs.functions'] },
  { id: 'cs.modules', domain: 'cs', title: 'Modules and Libraries', description: 'Creating and importing modules; import, from...import, import...as; Python Standard Library — math, random, statistics, datetime, os, sys; pip and third-party packages; module __name__ attribute', difficulty: 'proficient', prerequisites: ['cs.functions'] },

  // ─── FILE HANDLING ───────────────────────────────────────────
  { id: 'cs.file_handling', domain: 'cs', title: 'File Handling', description: 'Need for file handling; text files vs binary files vs CSV files; open(), close(), with statement; file modes — r, w, a, r+, rb, wb; read(), readline(), readlines(); write(), writelines(); seek(), tell(); file position pointer', difficulty: 'proficient', prerequisites: ['cs.functions'] },
  { id: 'cs.csv_files', domain: 'cs', title: 'CSV File Handling', description: 'CSV format and structure; csv module — reader, writer, DictReader, DictWriter; reading and writing CSV files; handling headers; delimiter and quotechar; practical applications', difficulty: 'proficient', prerequisites: ['cs.file_handling'] },
  { id: 'cs.binary_files', domain: 'cs', title: 'Binary File Handling', description: 'pickle module — dump() and load(); serialisation and deserialisation; storing and retrieving objects; read/write modes for binary files; practical uses — storing student records, data persistence', difficulty: 'proficient', prerequisites: ['cs.file_handling'] },

  // ─── DATA STRUCTURES (ADVANCED) ──────────────────────────────
  { id: 'cs.stacks', domain: 'cs', title: 'Stacks', description: 'Stack concept — LIFO; push and pop operations; stack using list; peek operation; isEmpty check; applications — expression evaluation, backtracking, undo operations; infix to postfix conversion', difficulty: 'proficient', prerequisites: ['cs.lists', 'cs.functions'] },
  { id: 'cs.queues', domain: 'cs', title: 'Queues', description: 'Queue concept — FIFO; enqueue and dequeue operations; queue using list and collections.deque; circular queue concept; applications — scheduling, BFS, print spooling', difficulty: 'proficient', prerequisites: ['cs.stacks'] },
  { id: 'cs.linked_lists', domain: 'cs', title: 'Linked Lists', description: 'Singly linked list — node structure, head pointer; traversal, insertion (beginning, end, after node), deletion; doubly linked list concept; advantages over arrays; memory representation', difficulty: 'advanced', prerequisites: ['cs.queues'] },
  { id: 'cs.searching_sorting', domain: 'cs', title: 'Searching and Sorting Algorithms', description: 'Linear search — algorithm and analysis; binary search — prerequisite of sorted data, algorithm, analysis; bubble sort; insertion sort; selection sort; merge sort concept; O(n), O(log n), O(n²) comparison', difficulty: 'proficient', prerequisites: ['cs.algorithms', 'cs.lists'] },

  // ─── DATABASE AND SQL ─────────────────────────────────────────
  { id: 'cs.database_concepts', domain: 'cs', title: 'Database Concepts', description: 'Data vs information; DBMS advantages over file system; database terminology — schema, instance, relation, tuple, attribute, domain, degree, cardinality; primary key, foreign key, candidate key, super key; types of databases', difficulty: 'proficient', prerequisites: ['cs.data_types'] },
  { id: 'cs.relational_model', domain: 'cs', title: 'Relational Model', description: 'Relational model concepts; tables, rows and columns; integrity constraints — entity integrity, referential integrity; relationships — one-to-one, one-to-many, many-to-many; ER diagram basics; normalisation concepts', difficulty: 'proficient', prerequisites: ['cs.database_concepts'] },
  { id: 'cs.sql_basics', domain: 'cs', title: 'SQL — DDL and DML Basics', description: 'SQL overview and history; DDL commands — CREATE TABLE, ALTER TABLE, DROP TABLE; DML commands — INSERT INTO, SELECT, UPDATE, DELETE; WHERE clause; data types in SQL — INT, VARCHAR, CHAR, DATE, DECIMAL', difficulty: 'proficient', prerequisites: ['cs.relational_model'] },
  { id: 'cs.sql_queries', domain: 'cs', title: 'SQL — Queries and Functions', description: 'SELECT with WHERE, ORDER BY, GROUP BY, HAVING; aggregate functions — COUNT, SUM, AVG, MIN, MAX; DISTINCT; LIKE and wildcards; BETWEEN, IN, IS NULL; arithmetic in SELECT; column aliases', difficulty: 'proficient', prerequisites: ['cs.sql_basics'] },
  { id: 'cs.sql_joins', domain: 'cs', title: 'SQL — Joins and Subqueries', description: 'INNER JOIN, LEFT JOIN, RIGHT JOIN, FULL OUTER JOIN; self join; natural join; subqueries — correlated and non-correlated; EXISTS and NOT EXISTS; UNION; views — CREATE VIEW, DROP VIEW', difficulty: 'advanced', prerequisites: ['cs.sql_queries'] },
  { id: 'cs.mysql_python', domain: 'cs', title: 'MySQL with Python', description: 'mysql.connector module; connecting to database; cursor object; execute() and executemany(); fetchone(), fetchall(), fetchmany(); parameterised queries; commit() and rollback(); closing connections; DML from Python', difficulty: 'advanced', prerequisites: ['cs.sql_queries', 'cs.modules'] },

  // ─── NETWORKING ──────────────────────────────────────────────
  { id: 'cs.networking_basics', domain: 'cs', title: 'Networking Basics', description: 'Need for networking; network types — LAN, MAN, WAN, PAN; network topologies — bus, star, ring, mesh, tree, hybrid; transmission media — wired (twisted pair, coaxial, fibre optic) and wireless; bandwidth and data transfer rates', difficulty: 'proficient', prerequisites: ['cs.computer_organisation'] },
  { id: 'cs.network_protocols', domain: 'cs', title: 'Network Protocols and the Internet', description: 'Protocols — HTTP, HTTPS, FTP, SMTP, POP3, IMAP, TCP/IP; OSI model — 7 layers; IP addressing — IPv4, IPv6, subnetting basics; DNS; DHCP; MAC address; routers, switches, hubs, modems; Internet vs intranet vs extranet', difficulty: 'proficient', prerequisites: ['cs.networking_basics'] },
  { id: 'cs.web_services', domain: 'cs', title: 'Web Services and Cloud', description: 'World Wide Web vs Internet; URL structure; web browsers; HTTP request-response cycle; web hosting; cloud computing — SaaS, PaaS, IaaS; cybersecurity basics — malware, phishing, firewalls, VPN; IT Act 2000', difficulty: 'developing', prerequisites: ['cs.network_protocols'] },

  // ─── CYBERSECURITY AND ETHICS ────────────────────────────────
  { id: 'cs.cyber_ethics', domain: 'cs', title: 'Cyber Ethics and Safety', description: 'Netiquette; digital footprint; cybercrime types — hacking, identity theft, cyberbullying, phishing; safe browsing practices; password security; two-factor authentication; privacy settings; copyright and plagiarism; open source licenses', difficulty: 'developing', prerequisites: ['cs.intro_computers'] },
  { id: 'cs.data_protection', domain: 'cs', title: 'Data Protection and Privacy', description: 'Personal data — types and sensitivity; data protection principles; encryption basics — symmetric and asymmetric; HTTPS and SSL; cookies and tracking; GDPR awareness; safe data handling practices', difficulty: 'proficient', prerequisites: ['cs.cyber_ethics', 'cs.network_protocols'] },

  // ─── OOP ─────────────────────────────────────────────────────
  { id: 'cs.oop_concepts', domain: 'cs', title: 'Object-Oriented Programming Concepts', description: 'OOP paradigm; classes and objects; encapsulation; abstraction; inheritance — single and multiple; polymorphism — method overriding; class vs instance attributes; __init__ constructor; self parameter; __str__ and __repr__', difficulty: 'advanced', prerequisites: ['cs.functions'] },
  { id: 'cs.oop_python', domain: 'cs', title: 'OOP in Python', description: 'Defining classes; creating objects; instance and class methods; access modifiers — public, protected (_), private (__); property decorators; class methods (@classmethod) and static methods (@staticmethod); inheritance in Python; super()', difficulty: 'advanced', prerequisites: ['cs.oop_concepts'] },

  // ─── DATA ANALYSIS ───────────────────────────────────────────
  { id: 'cs.numpy', domain: 'cs', title: 'NumPy for Data Analysis', description: 'NumPy arrays vs Python lists; creating arrays — array(), zeros(), ones(), arange(), linspace(); array operations — arithmetic, broadcasting; array methods — shape, reshape, size, dtype; indexing and slicing; statistical functions', difficulty: 'advanced', prerequisites: ['cs.modules', 'cs.lists'] },
  { id: 'cs.pandas', domain: 'cs', title: 'Pandas for Data Analysis', description: 'Series and DataFrame; creating DataFrames from CSV, dict, lists; read_csv() and to_csv(); data exploration — head(), tail(), info(), describe(), shape; data selection — loc, iloc; filtering; handling missing values; groupby(); merging and joining DataFrames', difficulty: 'advanced', prerequisites: ['cs.numpy', 'cs.csv_files'] },
  { id: 'cs.matplotlib', domain: 'cs', title: 'Data Visualisation with Matplotlib', description: 'matplotlib.pyplot module; line plot, bar chart, horizontal bar, pie chart, histogram, scatter plot; customisation — title, labels, legend, colors, grid; subplots; saving figures; choosing the right chart type', difficulty: 'advanced', prerequisites: ['cs.pandas'] },
]

export function getCSNode(id: string): KnowledgeNode | undefined {
  return COMPUTER_SCIENCE_KNOWLEDGE_GRAPH.find((n) => n.id === id)
}

export function getCSNodesByDomain(domain: string): KnowledgeNode[] {
  return COMPUTER_SCIENCE_KNOWLEDGE_GRAPH.filter((n) => n.domain === domain)
}
