import type { KnowledgeNode } from './educationTypes'

export const GEOGRAPHY_KNOWLEDGE_GRAPH: KnowledgeNode[] = [
  // ─── PHYSICAL GEOGRAPHY ──────────────────────────────────────
  { id: 'geography.earth_interior', domain: 'geography', title: 'Interior of the Earth', description: 'Sources of information — direct (mining, drilling) and indirect (seismic waves); layers — crust, mantle, outer core, inner core; continental and oceanic crust; shadow zones; earthquake waves — P, S, L waves; seismic zones', difficulty: 'foundational', prerequisites: [] },
  { id: 'geography.lithosphere', domain: 'geography', title: 'Lithosphere and Plate Tectonics', description: 'Continental drift — Wegener\'s theory; evidence; plate tectonics; types of plate boundaries — convergent, divergent, transform; earthquakes — causes, measurement, Richter scale, seismic zones; volcanoes — types, distribution, products; landform evolution', difficulty: 'foundational', prerequisites: ['geography.earth_interior'] },
  { id: 'geography.landforms', domain: 'geography', title: 'Landforms and Geomorphic Processes', description: 'Rock types — igneous, sedimentary, metamorphic; weathering — mechanical, chemical, biological; erosion and deposition; landforms produced by rivers, glaciers, wind, waves; karst topography; fluvial cycle of erosion', difficulty: 'developing', prerequisites: ['geography.lithosphere'] },
  { id: 'geography.atmosphere', domain: 'geography', title: 'Atmosphere — Composition and Structure', description: 'Composition of atmosphere; layers — troposphere, stratosphere, mesosphere, thermosphere, exosphere; solar radiation; insolation; terrestrial radiation; heat budget; temperature distribution; lapse rate; inversions', difficulty: 'foundational', prerequisites: [] },
  { id: 'geography.atmospheric_circulation', domain: 'geography', title: 'Atmospheric Circulation and Weather', description: 'Atmospheric pressure; horizontal and vertical pressure belts; pressure gradient force; Coriolis effect; winds — trade winds, westerlies, polar easterlies; monsoon; jet streams; cyclones and anticyclones — tropical and temperate', difficulty: 'developing', prerequisites: ['geography.atmosphere'] },
  { id: 'geography.moisture_precipitation', domain: 'geography', title: 'Moisture, Clouds and Precipitation', description: 'Evaporation and condensation; humidity — absolute and relative; dew point; types of clouds — cirrus, cumulus, stratus, nimbus; precipitation types — rain, drizzle, snow, hail; rainfall distribution; water balance', difficulty: 'developing', prerequisites: ['geography.atmospheric_circulation'] },
  { id: 'geography.climate_zones', domain: 'geography', title: 'World Climates and Biomes', description: 'Köeppen\'s classification; tropical (Am, Aw, As), dry (Bw, Bs), temperate (Cw, Cs, Cf), cold (Dw, Ds, Df), polar (ET, EF); climate change — causes, evidence, impacts, Paris Agreement; biomes — tropical rainforest, savanna, desert, temperate grassland, taiga, tundra', difficulty: 'proficient', prerequisites: ['geography.moisture_precipitation'] },
  { id: 'geography.oceans', domain: 'geography', title: 'Oceans and Ocean Currents', description: 'Ocean floor features — continental shelf, slope, rise, abyssal plains, mid-ocean ridges, trenches; temperature and salinity distribution; ocean currents — causes, Coriolis effect, gyres; major ocean currents; El Niño and La Niña; tides', difficulty: 'developing', prerequisites: ['geography.atmosphere'] },

  // ─── HUMAN GEOGRAPHY ─────────────────────────────────────────
  { id: 'geography.population', domain: 'geography', title: 'Population Geography', description: 'World population growth; demographic transition model; population distribution — factors; population density; age-sex structure; population pyramids; migration — types, push-pull factors; urbanisation; over and under population; population policies', difficulty: 'developing', prerequisites: [] },
  { id: 'geography.settlements', domain: 'geography', title: 'Human Settlements', description: 'Rural settlements — types, patterns; urban settlements — towns, cities, megalopolis; functional classification of towns; hierarchy of settlements — central place theory; urban land use; urban problems — congestion, slums, pollution; smart cities', difficulty: 'developing', prerequisites: ['geography.population'] },
  { id: 'geography.agriculture_world', domain: 'geography', title: 'World Agriculture', description: 'Types of farming — subsistence, commercial, shifting, plantation; major agricultural regions of the world; Green Revolution; agricultural issues — food security, land degradation, GMOs; crop distribution — wheat, rice, cotton, sugarcane, tea, coffee', difficulty: 'developing', prerequisites: ['geography.climate_zones'] },
  { id: 'geography.industries_world', domain: 'geography', title: 'Industries — World Patterns', description: 'Classification of industries; factors of localisation — raw materials, labour, capital, market, transport; footloose industries; iron and steel; textile; automobile; electronics; industrial regions — Western Europe, North America, Russia, Japan, China; industrial pollution', difficulty: 'proficient', prerequisites: ['geography.agriculture_world'] },
  { id: 'geography.transport_trade', domain: 'geography', title: 'Transport, Communication and Trade', description: 'Modes of transport — roadways, railways, waterways, airways, pipelines; importance of each mode; major transport routes — Panama Canal, Suez Canal, Trans-Siberian Railway; telecom revolution; internet geography; world trade — patterns, WTO, globalisation', difficulty: 'developing', prerequisites: ['geography.settlements'] },

  // ─── INDIA PHYSICAL ──────────────────────────────────────────
  { id: 'geography.india_physical', domain: 'geography', title: 'India — Physical Features', description: 'Location and extent; geological structure; physiographic divisions — Himalayan mountains (ranges, trans-Himalaya, sub-ranges, passes), Northern Plains (Bhabar, Terai, Bhangar, Khadar), Peninsular Plateau, Coastal Plains, Islands; significance of each region', difficulty: 'foundational', prerequisites: ['geography.lithosphere'] },
  { id: 'geography.india_drainage', domain: 'geography', title: 'India — Drainage System', description: 'Himalayan rivers — Indus system, Ganga system (tributaries), Brahmaputra; Peninsular rivers — Mahanadi, Godavari, Krishna, Kaveri, Narmada, Tapi; east-flowing vs west-flowing rivers; river disputes; Damodar Valley; interlinking of rivers; lakes', difficulty: 'developing', prerequisites: ['geography.india_physical'] },
  { id: 'geography.india_climate', domain: 'geography', title: 'India — Climate and Monsoon', description: 'Factors affecting India\'s climate; seasons — hot weather, advancing monsoon, retreating monsoon, cold weather; India Meteorological Department; Indian monsoon — ITCZ, Somali Jet, onset; rainfall distribution; Koeppen\'s classification for India; droughts and floods; El Niño effect on India', difficulty: 'proficient', prerequisites: ['geography.atmospheric_circulation', 'geography.india_physical'] },
  { id: 'geography.india_soil_vegetation', domain: 'geography', title: 'India — Soil, Vegetation and Wildlife', description: 'Types of soil — alluvial, black, red, laterite, arid, forest; soil conservation; natural vegetation — tropical evergreen, deciduous, thorny, mangrove, alpine; social forestry; wildlife — endangered species; Project Tiger; biosphere reserves; national parks', difficulty: 'developing', prerequisites: ['geography.india_climate'] },
  { id: 'geography.india_resources', domain: 'geography', title: 'India — Natural Resources', description: 'Classification of resources; mineral resources — iron ore (Jharkhand, Odisha), coal (Damodar Valley, Wardha), petroleum (ONGC, Mumbai High), bauxite, copper, manganese, mica; power resources — conventional and non-conventional; water resources — multipurpose projects', difficulty: 'developing', prerequisites: ['geography.india_physical'] },
  { id: 'geography.india_agriculture', domain: 'geography', title: 'India — Agriculture', description: 'Types of farming in India; major crops — rice, wheat, cotton, jute, sugarcane, oilseeds, pulses; crop seasons — Kharif, Rabi, Zaid; food security; Green Revolution; White Revolution; cropping patterns; agricultural issues — soil degradation, water stress', difficulty: 'developing', prerequisites: ['geography.india_soil_vegetation'] },
  { id: 'geography.india_industries', domain: 'geography', title: 'India — Industries and Infrastructure', description: 'Iron and steel (Jamshedpur, Bhilai, Rourkela, Durgapur); textile — cotton (Mumbai-Ahmedabad) and jute (Kolkata); software industry — Bengaluru, Hyderabad, Chennai, Pune; fertiliser; cement; petrochemicals; industrial corridors; special economic zones', difficulty: 'proficient', prerequisites: ['geography.india_resources'] },
  { id: 'geography.india_population', domain: 'geography', title: 'India — Population and Human Development', description: 'Population distribution and density; literacy; sex ratio; linguistic diversity; census 2011; demographic trends; urbanisation patterns — megacities; migration patterns; Human Development Index — India\'s position; challenges — poverty, inequality', difficulty: 'developing', prerequisites: ['geography.population'] },
  { id: 'geography.environmental_geography', domain: 'geography', title: 'Environmental Issues in Geography', description: 'Land degradation — desertification, waterlogging, soil erosion; water scarcity; air and water pollution; acid rain; ozone hole; global warming — sea level rise, glacier retreat; disaster management — earthquakes, floods, cyclones, droughts; sustainable development goals', difficulty: 'proficient', prerequisites: ['geography.india_resources'] },
]

export function getGeographyNode(id: string): KnowledgeNode | undefined {
  return GEOGRAPHY_KNOWLEDGE_GRAPH.find((n) => n.id === id)
}

export function getGeographyNodesByDomain(domain: string): KnowledgeNode[] {
  return GEOGRAPHY_KNOWLEDGE_GRAPH.filter((n) => n.domain === domain)
}
