// Master Hindi Knowledge Graph — Grammar, Writing, Vocabulary, Reading
// Literature nodes (sahitya) are intentionally excluded; those belong to
// a future sprint once board-specific prose/poetry catalogs are authored.

import type { KnowledgeNode } from './educationTypes'

export const HINDI_KNOWLEDGE_GRAPH: KnowledgeNode[] = [

  // ─── व्याकरण (GRAMMAR) ────────────────────────────────────────────────────

  {
    id: 'hindi.vyakaran.varn_vichar',
    domain: 'hindi.vyakaran',
    title: 'वर्ण-विचार: स्वर, व्यंजन और मात्राएँ',
    description: 'देवनागरी वर्णमाला; स्वर और व्यंजन के भेद; मात्राओं का सही प्रयोग; संयुक्त वर्ण; अनुस्वार और विसर्ग',
    difficulty: 'foundational',
    prerequisites: [],
  },
  {
    id: 'hindi.vyakaran.sangya',
    domain: 'hindi.vyakaran',
    title: 'संज्ञा और उसके भेद',
    description: 'व्यक्तिवाचक, जातिवाचक, भाववाचक, द्रव्यवाचक और समूहवाचक संज्ञा; संज्ञा की पहचान और प्रयोग',
    difficulty: 'foundational',
    prerequisites: ['hindi.vyakaran.varn_vichar'],
  },
  {
    id: 'hindi.vyakaran.sarvanam',
    domain: 'hindi.vyakaran',
    title: 'सर्वनाम और उसके भेद',
    description: 'पुरुषवाचक, निश्चयवाचक, अनिश्चयवाचक, संबंधवाचक, प्रश्नवाचक और निजवाचक सर्वनाम; प्रयोग और अभ्यास',
    difficulty: 'foundational',
    prerequisites: ['hindi.vyakaran.sangya'],
  },
  {
    id: 'hindi.vyakaran.visheshan',
    domain: 'hindi.vyakaran',
    title: 'विशेषण और उसके भेद',
    description: 'गुणवाचक, परिमाणवाचक, संख्यावाचक और सार्वनामिक विशेषण; विशेष्य-विशेषण संबंध; तुलनात्मक रूप',
    difficulty: 'foundational',
    prerequisites: ['hindi.vyakaran.sangya'],
  },
  {
    id: 'hindi.vyakaran.kriya',
    domain: 'hindi.vyakaran',
    title: 'क्रिया और उसके भेद',
    description: 'सकर्मक और अकर्मक क्रिया; धातु और क्रिया-रूप; सहायक क्रिया; प्रेरणार्थक क्रिया; नामधातु',
    difficulty: 'developing',
    prerequisites: ['hindi.vyakaran.sangya'],
  },
  {
    id: 'hindi.vyakaran.kaal',
    domain: 'hindi.vyakaran',
    title: 'काल — वर्तमान, भूत और भविष्य',
    description: 'तीनों कालों के उपभेद; सामान्य, अपूर्ण, पूर्ण और संदिग्ध काल; काल परिवर्तन के नियम',
    difficulty: 'developing',
    prerequisites: ['hindi.vyakaran.kriya'],
  },
  {
    id: 'hindi.vyakaran.kaarak',
    domain: 'hindi.vyakaran',
    title: 'कारक — विभक्तियाँ और परसर्ग',
    description: 'आठ कारक: कर्ता, कर्म, करण, संप्रदान, अपादान, संबंध, अधिकरण, संबोधन; विभक्ति-चिह्न और प्रयोग',
    difficulty: 'developing',
    prerequisites: ['hindi.vyakaran.kriya', 'hindi.vyakaran.sarvanam'],
  },
  {
    id: 'hindi.vyakaran.ling_vachan',
    domain: 'hindi.vyakaran',
    title: 'लिंग और वचन',
    description: 'पुल्लिंग और स्त्रीलिंग के नियम व अपवाद; एकवचन और बहुवचन; लिंग-वचन परिवर्तन में सामान्य त्रुटियाँ',
    difficulty: 'foundational',
    prerequisites: ['hindi.vyakaran.sangya'],
  },
  {
    id: 'hindi.vyakaran.upsarg_pratyay',
    domain: 'hindi.vyakaran',
    title: 'उपसर्ग और प्रत्यय',
    description: 'संस्कृत, हिंदी और उर्दू उपसर्ग; कृत और तद्धित प्रत्यय; उपसर्ग-प्रत्यय से नए शब्दों का निर्माण',
    difficulty: 'developing',
    prerequisites: ['hindi.vyakaran.sangya', 'hindi.vyakaran.kriya'],
  },
  {
    id: 'hindi.vyakaran.sandhi',
    domain: 'hindi.vyakaran',
    title: 'संधि — स्वर, व्यंजन और विसर्ग संधि',
    description: 'स्वर संधि (दीर्घ, गुण, वृद्धि, यण, अयादि); व्यंजन संधि; विसर्ग संधि; संधि-विच्छेद के नियम',
    difficulty: 'proficient',
    prerequisites: ['hindi.vyakaran.varn_vichar', 'hindi.vyakaran.upsarg_pratyay'],
  },
  {
    id: 'hindi.vyakaran.samaas',
    domain: 'hindi.vyakaran',
    title: 'समास — भेद और सामासिक-पद विग्रह',
    description: 'अव्ययीभाव, तत्पुरुष, कर्मधारय, द्विगु, द्वंद्व और बहुव्रीहि समास; सामासिक पद का विग्रह',
    difficulty: 'proficient',
    prerequisites: ['hindi.vyakaran.upsarg_pratyay'],
  },
  {
    id: 'hindi.vyakaran.avyay',
    domain: 'hindi.vyakaran',
    title: 'अव्यय — क्रियाविशेषण, संबंधबोधक और विस्मयादिबोधक',
    description: 'क्रियाविशेषण के भेद; संबंधबोधक अव्यय; समुच्चयबोधक; विस्मयादिबोधक; अव्यय का वाक्य में प्रयोग',
    difficulty: 'developing',
    prerequisites: ['hindi.vyakaran.kriya'],
  },
  {
    id: 'hindi.vyakaran.vakya_bhed',
    domain: 'hindi.vyakaran',
    title: 'वाक्य-भेद — रचना और अर्थ के आधार पर',
    description: 'सरल, मिश्र और संयुक्त वाक्य (रचना के आधार पर); विधानवाचक, निषेधवाचक, प्रश्नवाचक, आज्ञावाचक, विस्मयवाचक वाक्य (अर्थ के आधार पर); वाच्य',
    difficulty: 'proficient',
    prerequisites: ['hindi.vyakaran.kriya', 'hindi.vyakaran.kaarak'],
  },
  {
    id: 'hindi.vyakaran.vakya_shuddhi',
    domain: 'hindi.vyakaran',
    title: 'वाक्य-शुद्धि और अशुद्धि-संशोधन',
    description: 'वर्तनी, लिंग-वचन, कारक और क्रिया संबंधी त्रुटियाँ; वाक्य-शुद्धि के नियम; सामान्य अशुद्धियाँ और उनके शुद्ध रूप',
    difficulty: 'proficient',
    prerequisites: ['hindi.vyakaran.vakya_bhed', 'hindi.vyakaran.ling_vachan'],
  },
  {
    id: 'hindi.vyakaran.muhavare_lokoktiyaan',
    domain: 'hindi.vyakaran',
    title: 'मुहावरे और लोकोक्तियाँ',
    description: 'प्रचलित मुहावरों का अर्थ और वाक्य-प्रयोग; लोकोक्तियाँ और उनका व्यावहारिक अर्थ; मुहावरे और लोकोक्ति में अंतर',
    difficulty: 'developing',
    prerequisites: ['hindi.vyakaran.vakya_bhed'],
  },
  {
    id: 'hindi.vyakaran.shabd_shakti',
    domain: 'hindi.vyakaran',
    title: 'शब्द-शक्ति — अभिधा, लक्षणा और व्यंजना',
    description: 'शब्द की तीन शक्तियाँ; अभिधा (मुख्यार्थ), लक्षणा (लक्ष्यार्थ), व्यंजना (व्यंग्यार्थ); काव्य में शब्द-शक्ति का महत्व',
    difficulty: 'advanced',
    prerequisites: ['hindi.vyakaran.vakya_bhed', 'hindi.vyakaran.muhavare_lokoktiyaan'],
  },
  {
    id: 'hindi.vyakaran.alankar',
    domain: 'hindi.vyakaran',
    title: 'अलंकार — शब्दालंकार और अर्थालंकार',
    description: 'शब्दालंकार: अनुप्रास, यमक, श्लेष; अर्थालंकार: उपमा, रूपक, उत्प्रेक्षा, अतिशयोक्ति, विरोधाभास, मानवीकरण; अलंकार की पहचान और प्रयोग',
    difficulty: 'proficient',
    prerequisites: ['hindi.vyakaran.vakya_bhed'],
  },
  {
    id: 'hindi.vyakaran.ras',
    domain: 'hindi.vyakaran',
    title: 'रस — नौ रस और उनके अंग',
    description: 'श्रृंगार, वीर, करुण, हास्य, रौद्र, भयानक, वीभत्स, अद्भुत और शांत रस; स्थायी भाव, विभाव, अनुभाव और संचारी भाव; उदाहरण-सहित पहचान',
    difficulty: 'proficient',
    prerequisites: ['hindi.vyakaran.alankar'],
  },
  {
    id: 'hindi.vyakaran.chhand',
    domain: 'hindi.vyakaran',
    title: 'छंद — मात्रिक और वार्णिक छंद',
    description: 'मात्रिक छंद: चौपाई, दोहा, सोरठा, रोला, कुंडली; वार्णिक छंद: सवैया, कवित्त; मात्रा गणना और यति-गति',
    difficulty: 'advanced',
    prerequisites: ['hindi.vyakaran.ras'],
  },

  // ─── शब्द भंडार (VOCABULARY) ─────────────────────────────────────────────

  {
    id: 'hindi.shabdavali.paryayvachi_vilom',
    domain: 'hindi.shabdavali',
    title: 'पर्यायवाची और विलोम शब्द',
    description: 'सामान्य प्रचलित शब्दों के पर्यायवाची; विलोम शब्द; समानार्थी शब्दों में सूक्ष्म अंतर; परीक्षोपयोगी शब्द-युग्म',
    difficulty: 'foundational',
    prerequisites: ['hindi.vyakaran.sangya'],
  },
  {
    id: 'hindi.shabdavali.tatsam_tadbhav',
    domain: 'hindi.shabdavali',
    title: 'तत्सम और तद्भव शब्द',
    description: 'तत्सम (संस्कृत मूल) और तद्भव (अपभ्रंश रूप) शब्द; देशज शब्द; परिवर्तन के नियम और उदाहरण',
    difficulty: 'developing',
    prerequisites: ['hindi.shabdavali.paryayvachi_vilom'],
  },
  {
    id: 'hindi.shabdavali.deshaj_videshi',
    domain: 'hindi.shabdavali',
    title: 'देशज और विदेशी शब्द',
    description: 'देशज शब्दों की विशेषताएँ; अरबी, फ़ारसी, अंग्रेज़ी और पुर्तगाली मूल के प्रचलित शब्द; ऋण शब्द और उनका हिंदी में समावेश',
    difficulty: 'developing',
    prerequisites: ['hindi.shabdavali.tatsam_tadbhav'],
  },
  {
    id: 'hindi.shabdavali.anekarthi',
    domain: 'hindi.shabdavali',
    title: 'अनेकार्थी शब्द और श्रुतिसम भिन्नार्थक शब्द',
    description: 'एक शब्द के अनेक अर्थ; संदर्भ के अनुसार सही अर्थ की पहचान; श्रुतिसम भिन्नार्थक शब्द-युग्म (जैसे: अभिराम/अविराम, अनल/अनिल)',
    difficulty: 'proficient',
    prerequisites: ['hindi.shabdavali.paryayvachi_vilom'],
  },
  {
    id: 'hindi.shabdavali.shabd_nirman',
    domain: 'hindi.shabdavali',
    title: 'शब्द-निर्माण: उपसर्ग, प्रत्यय और समास',
    description: 'उपसर्ग और प्रत्यय द्वारा नए शब्दों का निर्माण; सामासिक शब्दों की रचना; शब्द-परिवार बनाना',
    difficulty: 'developing',
    prerequisites: ['hindi.vyakaran.upsarg_pratyay', 'hindi.vyakaran.samaas'],
  },
  {
    id: 'hindi.shabdavali.muhavare_prayog',
    domain: 'hindi.shabdavali',
    title: 'मुहावरे और लोकोक्तियों का संदर्भ-सहित प्रयोग',
    description: 'परीक्षोपयोगी मुहावरों का वाक्य में उचित प्रयोग; लोकोक्तियों का व्यावहारिक प्रयोग; मुहावरे-आधारित लेखन',
    difficulty: 'proficient',
    prerequisites: ['hindi.vyakaran.muhavare_lokoktiyaan'],
  },

  // ─── पठन (READING COMPREHENSION) ──────────────────────────────────────────

  {
    id: 'hindi.padhna.apathit_gadyansh',
    domain: 'hindi.padhna',
    title: 'अपठित गद्यांश — बोध प्रश्न',
    description: 'अपठित गद्य-अवतरण पढ़कर प्रश्नों के उत्तर देना; मुख्य विचार, शीर्षक और सारांश; कठिन शब्दों के अर्थ; लेखक का उद्देश्य समझना',
    difficulty: 'developing',
    prerequisites: ['hindi.vyakaran.vakya_bhed'],
  },
  {
    id: 'hindi.padhna.apathit_padyansh',
    domain: 'hindi.padhna',
    title: 'अपठित पद्यांश — काव्य-बोध',
    description: 'अपठित काव्यांश पढ़कर भाव-सौंदर्य समझना; काव्य में प्रयुक्त अलंकार और रस की पहचान; भाव-विस्तार और सारांश',
    difficulty: 'proficient',
    prerequisites: ['hindi.padhna.apathit_gadyansh', 'hindi.vyakaran.alankar', 'hindi.vyakaran.ras'],
  },
  {
    id: 'hindi.padhna.bodh_prashna',
    domain: 'hindi.padhna',
    title: 'बोध-प्रश्न और गद्यांश-विश्लेषण',
    description: 'परीक्षोपयोगी बोध-प्रश्नों की रणनीति; तथ्यात्मक और अनुमान-आधारित प्रश्न; गद्यांश से शब्दों के अर्थ निकालना; विस्तृत उत्तर लेखन',
    difficulty: 'proficient',
    prerequisites: ['hindi.padhna.apathit_gadyansh'],
  },

  // ─── लेखन (WRITING SKILLS) ────────────────────────────────────────────────

  {
    id: 'hindi.lekhan.anuchhed',
    domain: 'hindi.lekhan',
    title: 'अनुच्छेद लेखन',
    description: 'अनुच्छेद की संरचना; विषय-वाक्य, सहायक वाक्य और निष्कर्ष; 80–150 शब्दों में प्रभावी अनुच्छेद; एकता, क्रमबद्धता और संगति',
    difficulty: 'developing',
    prerequisites: ['hindi.vyakaran.vakya_bhed'],
  },
  {
    id: 'hindi.lekhan.chitra_varnan',
    domain: 'hindi.lekhan',
    title: 'चित्र वर्णन',
    description: 'चित्र देखकर उसका वर्णन करना; दृश्य का क्रमबद्ध वर्णन; उचित भाषा और शब्द-चयन; कल्पनाशीलता का प्रयोग',
    difficulty: 'foundational',
    prerequisites: ['hindi.lekhan.anuchhed'],
  },
  {
    id: 'hindi.lekhan.samvaad',
    domain: 'hindi.lekhan',
    title: 'संवाद लेखन',
    description: 'दो या अधिक पात्रों के बीच संवाद; संवाद में स्वाभाविकता; विभिन्न विषयों पर संवाद (जैसे: परीक्षा, पर्यावरण, स्वास्थ्य); 10–12 पंक्तियों में संवाद',
    difficulty: 'developing',
    prerequisites: ['hindi.lekhan.anuchhed'],
  },
  {
    id: 'hindi.lekhan.patra_anoupcharik',
    domain: 'hindi.lekhan',
    title: 'अनौपचारिक पत्र',
    description: 'मित्र, भाई-बहन, माता-पिता या रिश्तेदारों को पत्र; पत्र की संरचना; स्नेहपूर्ण भाषा; विभिन्न अवसरों पर पत्र (जैसे: बधाई, यात्रा-वर्णन, निमंत्रण)',
    difficulty: 'developing',
    prerequisites: ['hindi.lekhan.anuchhed'],
  },
  {
    id: 'hindi.lekhan.patra_oupcharik',
    domain: 'hindi.lekhan',
    title: 'औपचारिक पत्र',
    description: 'प्रधानाचार्य, संपादक, अधिकारी को पत्र; आवेदन-पत्र; शिकायत-पत्र; अनुरोध-पत्र; औपचारिक भाषा और सही प्रारूप',
    difficulty: 'proficient',
    prerequisites: ['hindi.lekhan.patra_anoupcharik'],
  },
  {
    id: 'hindi.lekhan.nibandh',
    domain: 'hindi.lekhan',
    title: 'निबंध लेखन — वर्णनात्मक, विचारात्मक और भावात्मक',
    description: 'निबंध की संरचना (प्रस्तावना, विषय-विस्तार, उपसंहार); वर्णनात्मक, विचारात्मक और भावात्मक निबंध; 200–300 शब्दों में सुगठित निबंध; भाषा की सुंदरता',
    difficulty: 'proficient',
    prerequisites: ['hindi.lekhan.anuchhed'],
  },
  {
    id: 'hindi.lekhan.vigyapan',
    domain: 'hindi.lekhan',
    title: 'विज्ञापन लेखन',
    description: 'विज्ञापन का उद्देश्य और विशेषताएँ; आकर्षक शीर्षक और स्लोगन; उत्पाद/सेवा का संक्षिप्त परिचय; संपर्क सूचना; रचनात्मक प्रस्तुति',
    difficulty: 'proficient',
    prerequisites: ['hindi.lekhan.anuchhed'],
  },
  {
    id: 'hindi.lekhan.suchna',
    domain: 'hindi.lekhan',
    title: 'सूचना लेखन',
    description: 'सार्वजनिक सूचना का प्रारूप; सूचना की भाषा — स्पष्ट और संक्षिप्त; स्कूल/सामाजिक कार्यक्रमों की सूचना; दिनांक, समय और स्थान का उल्लेख',
    difficulty: 'proficient',
    prerequisites: ['hindi.lekhan.patra_oupcharik'],
  },
  {
    id: 'hindi.lekhan.report',
    domain: 'hindi.lekhan',
    title: 'प्रतिवेदन / रिपोर्ट लेखन',
    description: 'घटना या कार्यक्रम पर रिपोर्ट; समिति / स्कूल-रिपोर्ट का प्रारूप; तथ्यात्मक और निष्पक्ष भाषा; समाचार-रिपोर्ट',
    difficulty: 'proficient',
    prerequisites: ['hindi.lekhan.suchna'],
  },
  {
    id: 'hindi.lekhan.laghu_katha',
    domain: 'hindi.lekhan',
    title: 'लघु कथा लेखन',
    description: 'संकेत-बिंदुओं या शीर्षक के आधार पर कहानी; कहानी के तत्व (पात्र, घटना, संवाद, नैतिक); 150–200 शब्दों में प्रभावी लघु कथा',
    difficulty: 'proficient',
    prerequisites: ['hindi.lekhan.samvaad', 'hindi.lekhan.nibandh'],
  },
  {
    id: 'hindi.lekhan.prabandh_nibandh',
    domain: 'hindi.lekhan',
    title: 'प्रबंध निबंध — विश्लेषणात्मक और तर्कपूर्ण',
    description: '600+ शब्दों का विस्तृत विश्लेषणात्मक निबंध; पक्ष-विपक्ष की प्रस्तुति; तथ्य, तर्क और उदाहरण; भाषा की परिपक्वता; उच्चतर कक्षाओं के लिए',
    difficulty: 'advanced',
    prerequisites: ['hindi.lekhan.nibandh'],
  },
  {
    id: 'hindi.lekhan.aalekh',
    domain: 'hindi.lekhan',
    title: 'आलेख / फ़ीचर लेखन',
    description: 'पत्रकारीय लेखन का परिचय; आलेख की संरचना; सामाजिक/सांस्कृतिक विषयों पर फ़ीचर; रोचक और सूचनात्मक भाषा',
    difficulty: 'advanced',
    prerequisites: ['hindi.lekhan.report', 'hindi.lekhan.nibandh'],
  },
  {
    id: 'hindi.lekhan.sampadak_patra',
    domain: 'hindi.lekhan',
    title: 'संपादक को पत्र',
    description: 'समाचार-पत्र के संपादक को पत्र का प्रारूप; सामाजिक समस्याओं पर मत व्यक्त करना; औपचारिक किंतु प्रभावशाली भाषा; 150–200 शब्द',
    difficulty: 'advanced',
    prerequisites: ['hindi.lekhan.patra_oupcharik', 'hindi.lekhan.nibandh'],
  },
]

export function getHindiNode(id: string): KnowledgeNode | undefined {
  return HINDI_KNOWLEDGE_GRAPH.find((n) => n.id === id)
}
