import type { KnowledgeNode } from './educationTypes'

export const HISTORY_KNOWLEDGE_GRAPH: KnowledgeNode[] = [
  // ─── ANCIENT INDIA ───────────────────────────────────────────
  { id: 'history.indus_valley', domain: 'history', title: 'The Harappan Civilisation', description: 'Discovery and sites — Harappa, Mohenjo-daro, Dholavira, Lothal, Rakhigarhi; urban planning — grid layout, drainage, granaries; material culture; trade; script; decline theories; Harappan society and religion', difficulty: 'foundational', prerequisites: [] },
  { id: 'history.vedic_age', domain: 'history', title: 'The Vedic Age', description: 'Early and Later Vedic periods; Rig Vedic society; varna system; polity; economy; religion — yajnas, polytheism; Upanishadic thought; sixteen Mahajanapadas; urbanisation and second urbanisation; republics and monarchies', difficulty: 'foundational', prerequisites: ['history.indus_valley'] },
  { id: 'history.mauryan_empire', domain: 'history', title: 'The Mauryan Empire', description: 'Rise of Magadha; Chandragupta Maurya and Kautilya; Bindusara; Ashoka — Kalinga war, dhamma policy, edicts; administration; economy; art — pillars, stupas, rock-cut caves; decline of Mauryas', difficulty: 'foundational', prerequisites: ['history.vedic_age'] },
  { id: 'history.post_mauryan', domain: 'history', title: 'Post-Mauryan Period', description: 'Sungas, Kanvas; Indo-Greek, Saka, Kushana; Sangam Age; Satavahanas; trade — silk route; Buddhism — Hinayana, Mahayana; Jainism; art — Gandhara, Mathura, Amaravati styles', difficulty: 'developing', prerequisites: ['history.mauryan_empire'] },
  { id: 'history.gupta_empire', domain: 'history', title: 'The Gupta Empire — Golden Age', description: 'Chandragupta I, Samudragupta (Allahabad Pillar inscription), Chandragupta II; administration; economy; trade; art and architecture — Ajanta, Sarnath, Nalanda; literature — Kalidasa; science — Aryabhata, Varahamihira; decline', difficulty: 'developing', prerequisites: ['history.post_mauryan'] },
  { id: 'history.early_medieval', domain: 'history', title: 'Early Medieval India', description: 'Rise of regional kingdoms — Chalukyas, Pallavas, Rashtrakutas, Pratiharas, Palas; tripartite struggle; Chola empire — Rajaraja I, Rajendra I, administration, Brihadesvara temple; temple architecture — Nagara and Dravida styles', difficulty: 'developing', prerequisites: ['history.gupta_empire'] },

  // ─── MEDIEVAL INDIA ──────────────────────────────────────────
  { id: 'history.delhi_sultanate', domain: 'history', title: 'The Delhi Sultanate', description: 'Arab conquest of Sind; Mahmud of Ghazni; Muhammad Ghori; five dynasties — Slave, Khalji, Tughlaq, Sayyid, Lodi; Iltutmish, Balban, Alauddin Khalji, Muhammad bin Tughlaq, Firuz Shah Tughlaq; administration — iqta system; economy; culture; Mongol invasions', difficulty: 'developing', prerequisites: ['history.early_medieval'] },
  { id: 'history.vijayanagara_bahmanid', domain: 'history', title: 'Vijayanagara and Bahmani Kingdoms', description: 'Vijayanagara — Sangama, Saluva, Tuluva, Aravidu dynasties; Krishnadevaraya; administration, economy, culture; Bahmani kingdom — Gulbarga and Bidar periods; Deccan Sultanates; Hampi architecture', difficulty: 'developing', prerequisites: ['history.delhi_sultanate'] },
  { id: 'history.bhakti_sufi', domain: 'history', title: 'Bhakti and Sufi Movements', description: 'Alvars and Nayanmars; Ramanuja; Madhva; Kabir; Mirabai; Tukaram; Chaitanya; Sufi orders — Chishti, Suhrawardi, Qadiri, Naqshbandi; Silsilas; social impact; syncretic culture', difficulty: 'developing', prerequisites: ['history.delhi_sultanate'] },
  { id: 'history.mughal_empire', domain: 'history', title: 'The Mughal Empire', description: 'Babur and First Battle of Panipat; Humayun; Akbar — Din-i-Ilahi, Mansabdari, Rajput policy, revenue system (Todar Mal); Jahangir; Shah Jahan — Taj Mahal; Aurangzeb — Deccan policy, religious policy; decline of Mughals; Maratha challenge', difficulty: 'proficient', prerequisites: ['history.vijayanagara_bahmanid'] },
  { id: 'history.maratha', domain: 'history', title: 'The Maratha Kingdom', description: 'Shivaji — guerrilla warfare, revenue and military administration, Ashtapradhan; Peshwas; Maratha confederacy; Battle of Panipat 1761; Anglo-Maratha Wars; fall of Maratha power', difficulty: 'proficient', prerequisites: ['history.mughal_empire'] },

  // ─── COLONIAL INDIA ──────────────────────────────────────────
  { id: 'history.european_arrival', domain: 'history', title: 'European Arrival and British Expansion', description: 'Portuguese — Vasco da Gama, Estado da India; Dutch, French, British East India Companies; Battle of Plassey 1757; Battle of Buxar 1764; Diwani of Bengal; dual government; Regulating Act, Pitt\'s India Act, Charter Acts; subsidiary alliance; doctrine of lapse', difficulty: 'developing', prerequisites: ['history.maratha'] },
  { id: 'history.revolt_1857', domain: 'history', title: 'Revolt of 1857', description: 'Causes — political, economic, military, social, religious; Mangal Pandey; major centres and leaders — Bahadur Shah II, Rani Laxmibai, Tantia Tope, Kunwar Singh, Nana Sahib; nature of the revolt; suppression; consequences — Government of India Act 1858', difficulty: 'developing', prerequisites: ['history.european_arrival'] },
  { id: 'history.social_reform', domain: 'history', title: 'Social and Religious Reform Movements', description: 'Brahmo Samaj — Ram Mohan Roy; Prarthana Samaj; Arya Samaj — Dayananda Saraswati; Ramakrishna Mission — Vivekananda; Aligarh Movement — Sir Syed Ahmed Khan; Satyashodhak Samaj — Jyotiba Phule; women\'s reform; widow remarriage; sati abolition', difficulty: 'developing', prerequisites: ['history.revolt_1857'] },
  { id: 'history.independence_movement', domain: 'history', title: 'Indian National Movement', description: 'INC formation 1885; Moderates vs Extremists; Partition of Bengal 1905; Swadeshi movement; Home Rule League; Rowlatt Act; Jallianwala Bagh; Non-cooperation movement; Civil Disobedience — Salt March; Round Table Conferences; Quit India movement 1942; Subhas Chandra Bose and INA; Cabinet Mission; Partition and Independence', difficulty: 'proficient', prerequisites: ['history.social_reform'] },

  // ─── POST-INDEPENDENCE AND WORLD ─────────────────────────────
  { id: 'history.post_independence', domain: 'history', title: 'Post-Independence India', description: 'Integration of princely states; Hyderabad, Junagadh, Kashmir; Constitution framing; first general elections 1952; Nehru era — Non-alignment, Panchsheel; States Reorganisation Act 1956; Green Revolution; Emergency 1975–77; economic reforms 1991', difficulty: 'proficient', prerequisites: ['history.independence_movement'] },
  { id: 'history.world_wars', domain: 'history', title: 'World Wars and Global Order', description: 'Causes of WWI; major battles; Treaty of Versailles; League of Nations; rise of Fascism and Nazism; causes of WWII; Holocaust; atomic bombings; UN formation; Cold War — origins, key events, Non-Aligned Movement; decolonisation of Asia and Africa', difficulty: 'proficient', prerequisites: [] },
  { id: 'history.industrial_revolution', domain: 'history', title: 'Industrial Revolution and Its Impact', description: 'Agricultural Revolution; enclosures; early industrialisation in Britain; factory system; steam power; railways; social changes — urbanisation, working class, child labour; capitalism; socialist ideas — Karl Marx; spread of industrialisation', difficulty: 'developing', prerequisites: ['history.european_arrival'] },
  { id: 'history.nationalism_world', domain: 'history', title: 'Nationalism and Imperialism in the World', description: 'French Revolution — causes, phases, Napoleon; spread of nationalist ideas; unification of Germany and Italy; imperialism — motives, forms; Scramble for Africa; colonialism in Asia; resistance movements; self-determination', difficulty: 'proficient', prerequisites: ['history.industrial_revolution'] },
]

export function getHistoryNode(id: string): KnowledgeNode | undefined {
  return HISTORY_KNOWLEDGE_GRAPH.find((n) => n.id === id)
}

export function getHistoryNodesByDomain(domain: string): KnowledgeNode[] {
  return HISTORY_KNOWLEDGE_GRAPH.filter((n) => n.domain === domain)
}
