import type { KnowledgeNode } from './educationTypes'

export const INFORMATION_TECHNOLOGY_KNOWLEDGE_GRAPH: KnowledgeNode[] = [
  // ─── DIGITAL LITERACY ────────────────────────────────────────
  { id: 'it.digital_literacy', domain: 'it', title: 'Digital Literacy and ICT Basics', description: 'Meaning of ICT; digital vs analog; role of computers in daily life; types of computers and mobile devices; hardware overview — CPU, monitor, keyboard, mouse, printer; software categories; digital divide; impact of ICT on society and economy', difficulty: 'foundational', prerequisites: [] },
  { id: 'it.operating_system_basics', domain: 'it', title: 'Operating System and File Management', description: 'Role of operating system; desktop, icons, taskbar, start menu; file and folder management — create, rename, copy, move, delete; file types and extensions; storage concepts; recycle bin; keyboard shortcuts; accessibility features; OS updates and security', difficulty: 'foundational', prerequisites: ['it.digital_literacy'] },
  { id: 'it.internet_basics', domain: 'it', title: 'Internet and Web Basics', description: 'What is the Internet; ISP; types of connections — broadband, dial-up, Wi-Fi, 4G/5G; browsers — Chrome, Firefox, Edge; URL anatomy; search engines and effective searching; bookmarks; downloading and uploading; cookies; browsing history; incognito mode', difficulty: 'foundational', prerequisites: ['it.digital_literacy'] },

  // ─── OFFICE PRODUCTIVITY ─────────────────────────────────────
  { id: 'it.word_processing', domain: 'it', title: 'Word Processing', description: 'MS Word / LibreOffice Writer; creating, saving and formatting documents; fonts, paragraphs, alignment, line spacing; headers and footers; page setup — margins, orientation, size; bullets and numbering; tables; inserting images; mail merge; track changes; spell check; PDF export', difficulty: 'foundational', prerequisites: ['it.operating_system_basics'] },
  { id: 'it.spreadsheets', domain: 'it', title: 'Spreadsheets', description: 'MS Excel / LibreOffice Calc; cells, rows, columns, worksheets; data entry and formatting; formulas and functions — SUM, AVERAGE, MAX, MIN, COUNT, IF, VLOOKUP; cell referencing — relative and absolute; charts — bar, pie, line; sorting and filtering; conditional formatting; pivot tables basics', difficulty: 'developing', prerequisites: ['it.word_processing'] },
  { id: 'it.presentations', domain: 'it', title: 'Presentations', description: 'MS PowerPoint / LibreOffice Impress; creating slides; themes and layouts; inserting text, images, shapes, SmartArt; transitions and animations; slide show settings; presenter view; notes; exporting to PDF or video; best practices for effective presentations', difficulty: 'foundational', prerequisites: ['it.word_processing'] },
  { id: 'it.database_basics', domain: 'it', title: 'Database Basics with MS Access / LibreOffice Base', description: 'What is a database; tables, records, fields; primary key; creating and editing tables; forms; queries — simple select queries; reports; relationships — one-to-many; advantages of database over spreadsheet; intro to SQL SELECT', difficulty: 'developing', prerequisites: ['it.spreadsheets'] },

  // ─── DIGITAL COMMUNICATION ───────────────────────────────────
  { id: 'it.email_communication', domain: 'it', title: 'Email and Digital Communication', description: 'Creating email accounts; composing, replying, forwarding; CC and BCC; attachments; email etiquette; spam and phishing recognition; email folders; calendar and scheduling; instant messaging — WhatsApp, Telegram; video conferencing — Zoom, Google Meet; netiquette', difficulty: 'foundational', prerequisites: ['it.internet_basics'] },
  { id: 'it.digital_content', domain: 'it', title: 'Digital Content Creation', description: 'Image editing basics — GIMP, Canva; image formats — JPEG, PNG, GIF, SVG; resolution and file size; audio and video editing basics; multimedia formats; copyright and creative commons; digital storytelling; infographics; blogging; content sharing platforms', difficulty: 'developing', prerequisites: ['it.presentations'] },
  { id: 'it.social_media', domain: 'it', title: 'Social Media and Online Collaboration', description: 'Types of social media platforms; responsible use; digital identity and reputation; privacy settings; sharing and intellectual property; collaborative tools — Google Docs, Microsoft 365, Notion; project collaboration — Trello, Asana; cloud storage — Google Drive, OneDrive', difficulty: 'developing', prerequisites: ['it.email_communication'] },

  // ─── CYBER SAFETY ────────────────────────────────────────────
  { id: 'it.cyber_safety', domain: 'it', title: 'Cyber Safety and Security', description: 'Cyber threats — malware, virus, worm, trojan, ransomware, spyware; phishing and social engineering; strong passwords and password managers; two-factor authentication; safe browsing; public Wi-Fi risks; data backup strategies; antivirus software; firewall basics; IT Act 2000 and amendments', difficulty: 'developing', prerequisites: ['it.internet_basics'] },
  { id: 'it.data_privacy', domain: 'it', title: 'Data Privacy and Digital Footprint', description: 'Personal data types; digital footprint — active and passive; privacy policies; GDPR awareness; children\'s online privacy; data collection by apps; location tracking; microphone and camera permissions; right to erasure; responsible sharing', difficulty: 'developing', prerequisites: ['it.cyber_safety'] },

  // ─── WEB TECHNOLOGIES ────────────────────────────────────────
  { id: 'it.html_basics', domain: 'it', title: 'HTML — Structure of Web Pages', description: 'What is HTML; basic structure — html, head, body; headings h1–h6; paragraphs; links; images; lists — ordered and unordered; tables; forms — input types, labels, buttons; semantic elements — header, nav, main, footer, article, section; accessibility basics', difficulty: 'developing', prerequisites: ['it.internet_basics'] },
  { id: 'it.css_basics', domain: 'it', title: 'CSS — Styling Web Pages', description: 'What is CSS; inline, internal, external CSS; selectors — element, class, id; box model — margin, border, padding, content; colors and backgrounds; fonts and typography; display — block, inline, flex; basic layout; responsive design concepts; media queries basics', difficulty: 'developing', prerequisites: ['it.html_basics'] },
  { id: 'it.web_scripting', domain: 'it', title: 'JavaScript — Web Interactivity Basics', description: 'What is JavaScript; adding JS to a page; variables — var, let, const; data types; operators; conditional statements; loops; functions; DOM manipulation — getElementById, querySelector; event listeners — click, submit; form validation; alert, console.log', difficulty: 'proficient', prerequisites: ['it.css_basics'] },
  { id: 'it.web_publishing', domain: 'it', title: 'Web Hosting and Publishing', description: 'Domain names and DNS; web hosting types — shared, VPS, cloud; FTP and SFTP; website builders — WordPress, Wix; deploying static sites — GitHub Pages, Netlify; CMS overview; SSL certificates; website performance basics; SEO fundamentals', difficulty: 'proficient', prerequisites: ['it.web_scripting'] },

  // ─── NETWORKING ──────────────────────────────────────────────
  { id: 'it.networking_concepts', domain: 'it', title: 'Networking Concepts', description: 'Network types — LAN, WAN, MAN, PAN; topologies — star, bus, ring, mesh; networking devices — router, switch, hub, modem, NIC; IP addressing — IPv4, IPv6; MAC address; DHCP; DNS; subnetting basics; wired vs wireless; Wi-Fi standards; Bluetooth; NFC', difficulty: 'developing', prerequisites: ['it.internet_basics'] },
  { id: 'it.network_protocols', domain: 'it', title: 'Protocols and Internet Services', description: 'TCP/IP model vs OSI model; HTTP and HTTPS; FTP; SMTP, POP3, IMAP for email; VoIP; VPN; firewall and proxy; NAT; port numbers; packet switching; bandwidth vs latency; QoS; IoT networking; cloud infrastructure', difficulty: 'proficient', prerequisites: ['it.networking_concepts'] },

  // ─── DATABASES (ADVANCED) ────────────────────────────────────
  { id: 'it.rdbms', domain: 'it', title: 'Relational Database Management Systems', description: 'RDBMS concepts; tables, keys, relationships; MySQL/MariaDB; DDL — CREATE, ALTER, DROP; DML — INSERT, SELECT, UPDATE, DELETE; WHERE, ORDER BY, GROUP BY; aggregate functions; joins — INNER, LEFT; normalisation — 1NF, 2NF, 3NF; transactions and ACID properties', difficulty: 'proficient', prerequisites: ['it.database_basics'] },
  { id: 'it.sql_advanced', domain: 'it', title: 'Advanced SQL and Database Applications', description: 'Subqueries; stored procedures and functions; triggers; views; indexes; database security — users, roles, privileges; backup and recovery; database connectivity from applications; NoSQL introduction — MongoDB concepts; big data overview', difficulty: 'advanced', prerequisites: ['it.rdbms'] },

  // ─── PROGRAMMING IN IT ───────────────────────────────────────
  { id: 'it.python_for_it', domain: 'it', title: 'Python for IT Applications', description: 'Python basics in IT context; file I/O; reading CSV files; parsing JSON; working with APIs — requests library; sending emails with smtplib; automating tasks — shutil, os; web scraping basics — BeautifulSoup; data processing; error handling; logging', difficulty: 'proficient', prerequisites: ['it.web_scripting'] },

  // ─── CYBERSECURITY (ADVANCED) ────────────────────────────────
  { id: 'it.cybersecurity_advanced', domain: 'it', title: 'Cybersecurity — Concepts and Practices', description: 'CIA triad — confidentiality, integrity, availability; types of attacks — DoS, DDoS, MITM, SQL injection, XSS; encryption — symmetric and asymmetric; public key infrastructure; digital signatures and certificates; SSL/TLS; security audits; penetration testing overview; incident response; CERT-In; ethical hacking intro', difficulty: 'advanced', prerequisites: ['it.data_privacy', 'it.network_protocols'] },
  { id: 'it.ethical_legal', domain: 'it', title: 'Ethical and Legal Issues in IT', description: 'IT Act 2000 and amendments; cybercrimes — definitions, sections; intellectual property rights in digital space — copyright, trademark, patents; software piracy; open source licenses; e-commerce law; data protection bill India; GDPR; professional ethics for IT practitioners; environmental impact of IT — e-waste', difficulty: 'proficient', prerequisites: ['it.cyber_safety'] },

  // ─── EMERGING TECHNOLOGIES ───────────────────────────────────
  { id: 'it.emerging_tech', domain: 'it', title: 'Emerging Technologies', description: 'Artificial Intelligence — ML, deep learning, NLP, computer vision; ChatGPT and generative AI; Internet of Things — sensors, actuators, platforms; Blockchain — distributed ledger, cryptocurrency basics; Augmented and Virtual Reality; 3D printing; quantum computing overview; Industry 4.0; ethical AI', difficulty: 'proficient', prerequisites: ['it.networking_concepts'] },
  { id: 'it.cloud_computing', domain: 'it', title: 'Cloud Computing', description: 'Cloud service models — IaaS, PaaS, SaaS; deployment models — public, private, hybrid, community; major providers — AWS, Azure, GCP; cloud storage services; serverless computing; containerisation — Docker basics; microservices concept; cloud security; cost management; future of cloud', difficulty: 'proficient', prerequisites: ['it.network_protocols'] },
  { id: 'it.digital_entrepreneurship', domain: 'it', title: 'Digital Entrepreneurship and Careers', description: 'IT career pathways — developer, network engineer, cybersecurity analyst, data scientist, UX designer, IT manager; freelancing and remote work; startups in IT; digital marketing; e-commerce business models; app development overview; design thinking; agile and scrum basics; portfolio building', difficulty: 'developing', prerequisites: ['it.digital_literacy'] },
]

export function getITNode(id: string): KnowledgeNode | undefined {
  return INFORMATION_TECHNOLOGY_KNOWLEDGE_GRAPH.find((n) => n.id === id)
}

export function getITNodesByDomain(domain: string): KnowledgeNode[] {
  return INFORMATION_TECHNOLOGY_KNOWLEDGE_GRAPH.filter((n) => n.domain === domain)
}
