import type { KnowledgeNode } from './educationTypes'

export const POLITICAL_SCIENCE_KNOWLEDGE_GRAPH: KnowledgeNode[] = [
  // ─── POLITICAL THEORY ────────────────────────────────────────
  { id: 'polsci.political_theory', domain: 'polsci', title: 'Political Theory — Nature and Scope', description: 'What is political theory; political philosophy vs political science; normative vs empirical approaches; importance of studying political theory; key concepts — freedom, equality, justice, power, rights, democracy', difficulty: 'foundational', prerequisites: [] },
  { id: 'polsci.freedom', domain: 'polsci', title: 'Freedom', description: 'Negative and positive freedom; freedom from and freedom to; constraints on freedom; freedom and equality; freedom and authority; limits of freedom — John Stuart Mill\'s harm principle; free speech — scope and limits', difficulty: 'foundational', prerequisites: ['polsci.political_theory'] },
  { id: 'polsci.equality', domain: 'polsci', title: 'Equality', description: 'Natural and social equality; formal and substantive equality; types — political, social, economic, legal equality; equality of opportunity vs equality of outcome; Rawls\' theory of justice; affirmative action and reservations', difficulty: 'developing', prerequisites: ['polsci.freedom'] },
  { id: 'polsci.justice', domain: 'polsci', title: 'Social Justice', description: 'Meaning of justice; theories — Rawls\' veil of ignorance, Nozick\'s libertarianism, utilitarianism; distributive justice; social justice and marginalised groups; justice and positive discrimination; environmental justice', difficulty: 'developing', prerequisites: ['polsci.equality'] },
  { id: 'polsci.rights', domain: 'polsci', title: 'Rights', description: 'Meaning and theories of rights — natural, legal, human rights; civil and political rights; economic and social rights; fundamental rights in India; duty-right correlations; rights of minorities; right to development', difficulty: 'developing', prerequisites: ['polsci.justice'] },
  { id: 'polsci.citizenship', domain: 'polsci', title: 'Citizenship', description: 'Meaning and types of citizenship; rights and duties of citizens; national and global citizenship; refugee and stateless persons; citizenship and identity; CAA; OCI; NRI; voting rights', difficulty: 'developing', prerequisites: ['polsci.rights'] },
  { id: 'polsci.nationalism', domain: 'polsci', title: 'Nationalism', description: 'Nation vs state vs nation-state; theories of nationalism — cultural, liberal, civic; national self-determination; partition and nation-building; nationalism and democracy; nationalism vs cosmopolitanism; minority nationalism', difficulty: 'proficient', prerequisites: ['polsci.citizenship'] },
  { id: 'polsci.secularism', domain: 'polsci', title: 'Secularism', description: 'Western vs Indian model of secularism; separation of state and religion; Nehru\'s conception; communalism; minority rights; personal law and uniform civil code; religion and politics in India', difficulty: 'proficient', prerequisites: ['polsci.nationalism'] },

  // ─── INDIAN CONSTITUTION ─────────────────────────────────────
  { id: 'polsci.constitution_making', domain: 'polsci', title: 'Constitution — Making and Philosophy', description: 'Constituent Assembly; Ambedkar\'s role; Objectives Resolution; sources of Indian Constitution; Preamble — significance, keywords; constitutional values — justice, liberty, equality, fraternity; basic structure doctrine', difficulty: 'foundational', prerequisites: ['polsci.political_theory'] },
  { id: 'polsci.fundamental_rights', domain: 'polsci', title: 'Fundamental Rights and Duties', description: 'Six categories of Fundamental Rights — Articles 12–35; Right to Equality, Right to Freedom (Art 19), Right against Exploitation, Right to Freedom of Religion, Cultural and Educational Rights, Right to Constitutional Remedies (Art 32); writs; Fundamental Duties — Art 51A', difficulty: 'developing', prerequisites: ['polsci.constitution_making'] },
  { id: 'polsci.dpsp', domain: 'polsci', title: 'Directive Principles and State Policy', description: 'Nature of DPSPs — non-justiciable; classification; relationship with Fundamental Rights — 42nd Amendment; importance; implementation — land reform, minimum wage, legal aid, educational and health policy', difficulty: 'developing', prerequisites: ['polsci.fundamental_rights'] },
  { id: 'polsci.parliament', domain: 'polsci', title: 'Legislature — Parliament of India', description: 'Lok Sabha and Rajya Sabha — composition, powers, functions; qualification and disqualification of MPs; Parliamentary procedures — question hour, zero hour, no-confidence motion, bills; Money Bill vs ordinary bill; President\'s role in legislation; anti-defection law', difficulty: 'proficient', prerequisites: ['polsci.constitution_making'] },
  { id: 'polsci.executive', domain: 'polsci', title: 'Executive — President, PM and Council of Ministers', description: 'President — election, powers, role; Vice President; Council of Ministers — Article 74, 75; Prime Minister — appointment, powers; Cabinet system; Governor — Article 153–167; Chief Minister and State Cabinet; President\'s Rule — Article 356', difficulty: 'proficient', prerequisites: ['polsci.parliament'] },
  { id: 'polsci.judiciary', domain: 'polsci', title: 'Judiciary — Supreme Court and High Courts', description: 'Supreme Court — composition, jurisdiction (original, appellate, advisory), judicial review; High Courts — composition, jurisdiction; subordinate courts; judicial independence — collegium system, transfers; PIL; judicial activism vs restraint; NJAC judgment', difficulty: 'proficient', prerequisites: ['polsci.parliament'] },
  { id: 'polsci.federalism', domain: 'polsci', title: 'Federalism in India', description: 'Federal features of Indian Constitution; unitary features; Union-State relations — Articles 245–263, 7th Schedule; Inter-State Council; Finance Commission; GST Council; Sarkaria Commission; special provisions for certain states; cooperative federalism', difficulty: 'proficient', prerequisites: ['polsci.executive'] },
  { id: 'polsci.local_government', domain: 'polsci', title: 'Local Government', description: '73rd and 74th Constitutional Amendments; Panchayati Raj — structure, powers, elections, reservation; Municipalities — types, powers; State Finance Commission; District Planning Committee; urban local bodies — challenges', difficulty: 'developing', prerequisites: ['polsci.federalism'] },

  // ─── ELECTIONS AND PARTIES ───────────────────────────────────
  { id: 'polsci.elections', domain: 'polsci', title: 'Election Commission and Electoral System', description: 'Election Commission of India — composition, role, independence; electoral roll; FPTP system; reservation of seats; EVM and VVPAT; model code of conduct; electoral reforms; coalition government; defection; money in elections', difficulty: 'developing', prerequisites: ['polsci.parliament'] },
  { id: 'polsci.political_parties', domain: 'polsci', title: 'Political Parties and Party System', description: 'Functions of political parties; types of party systems — one-party, two-party, multi-party; Indian party system — dominance of Congress, party competition, coalition era; national and regional parties; party funding; inner-party democracy; role of media', difficulty: 'developing', prerequisites: ['polsci.elections'] },

  // ─── INTERNATIONAL RELATIONS ─────────────────────────────────
  { id: 'polsci.cold_war', domain: 'polsci', title: 'Cold War Era', description: 'Origins of Cold War; bipolar world — USA and USSR; NATO, Warsaw Pact; Korean War; Cuban Missile Crisis; Non-Aligned Movement — Nehru, Nasser, Tito; Bandung Conference; détente; arms race; space race; end of Cold War', difficulty: 'developing', prerequisites: ['polsci.political_theory'] },
  { id: 'polsci.un_international', domain: 'polsci', title: 'United Nations and International Organisations', description: 'UN — structure (General Assembly, Security Council, ICJ, Secretariat, ECOSOC, Trusteeship Council); UN agencies — UNICEF, WHO, UNESCO, UNDP; India in UN; UNSC reform; WTO; IMF; World Bank; G-20; SAARC; ASEAN; EU', difficulty: 'developing', prerequisites: ['polsci.cold_war'] },
  { id: 'polsci.india_foreign_policy', domain: 'polsci', title: 'India\'s Foreign Policy', description: 'Panchsheel principles; Non-Alignment — meaning, evolution, criticism; India-Pakistan relations — wars 1947, 1965, 1971, 1999, terrorism; India-China relations — 1962 war, Doklam, LAC; India-USA relations; India-Russia relations; Look East/Act East policy; BRICS; SCO; nuclear policy', difficulty: 'proficient', prerequisites: ['polsci.un_international'] },
  { id: 'polsci.contemporary_world', domain: 'polsci', title: 'Contemporary World Order', description: 'US hegemony after Cold War; globalisation — political dimensions; rise of China; terrorism and security challenges; environmental politics — Kyoto Protocol, Paris Agreement; refugee crisis; nuclear proliferation — NPT; South-South cooperation; new centres of power', difficulty: 'advanced', prerequisites: ['polsci.india_foreign_policy'] },
]

export function getPoliticalScienceNode(id: string): KnowledgeNode | undefined {
  return POLITICAL_SCIENCE_KNOWLEDGE_GRAPH.find((n) => n.id === id)
}

export function getPoliticalScienceNodesByDomain(domain: string): KnowledgeNode[] {
  return POLITICAL_SCIENCE_KNOWLEDGE_GRAPH.filter((n) => n.domain === domain)
}
