import type { KnowledgeNode } from './educationTypes'

export const PSYCHOLOGY_KNOWLEDGE_GRAPH: KnowledgeNode[] = [
  // ─── INTRODUCTION ────────────────────────────────────────────
  { id: 'psychology.intro', domain: 'psychology', title: 'Introduction to Psychology', description: 'What is psychology; definition and scope; psychology as a science; branches — clinical, counselling, educational, organisational, social, health, developmental, forensic; psychology in everyday life; relationship with biology, sociology, anthropology, philosophy; history — structuralism, functionalism, behaviourism, Gestalt, psychoanalysis, humanistic, cognitive revolution', difficulty: 'foundational', prerequisites: [] },
  { id: 'psychology.research_methods', domain: 'psychology', title: 'Methods of Enquiry in Psychology', description: 'Goals of psychology — describe, explain, predict, control; nature of psychological data; observational method — naturalistic and controlled; case study; survey; psychological testing; experimental method — independent variable, dependent variable, control group; introspection; limitations of each method; ethical issues in research', difficulty: 'foundational', prerequisites: ['psychology.intro'] },

  // ─── BIOLOGICAL BASIS ────────────────────────────────────────
  { id: 'psychology.biological_basis', domain: 'psychology', title: 'Biological Basis of Behaviour', description: 'Neuron structure — dendrites, axon, synapse; neurotransmitters — dopamine, serotonin, acetylcholine, norepinephrine; central and peripheral nervous system; brain structure — cerebrum (lobes), limbic system, brainstem, cerebellum; endocrine system and hormones; heredity and behaviour; evolution and behaviour', difficulty: 'developing', prerequisites: ['psychology.intro'] },

  // ─── DEVELOPMENT ─────────────────────────────────────────────
  { id: 'psychology.human_development', domain: 'psychology', title: 'Human Development', description: 'Principles of development; nature vs nurture debate; stages of development — prenatal, infancy, childhood, adolescence, adulthood, old age; Piaget\'s cognitive development — sensorimotor, pre-operational, concrete, formal operational; Vygotsky — zone of proximal development, scaffolding; Kohlberg\'s moral development; Erikson\'s psychosocial stages; socio-cultural context', difficulty: 'developing', prerequisites: ['psychology.biological_basis'] },

  // ─── SENSATION AND PERCEPTION ────────────────────────────────
  { id: 'psychology.sensation', domain: 'psychology', title: 'Sensation', description: 'Sense organs; stimulus and sensation; absolute threshold; difference threshold — Weber\'s law; signal detection theory; sensory adaptation; vision — eye structure, rods and cones, colour vision; hearing — ear structure, loudness, pitch, timbre; other senses — smell, taste, skin senses, proprioception, vestibular sense', difficulty: 'developing', prerequisites: ['psychology.biological_basis'] },
  { id: 'psychology.perception', domain: 'psychology', title: 'Perception', description: 'Perception vs sensation; perceptual organisation — Gestalt principles (figure-ground, proximity, similarity, closure, continuity); depth perception — monocular and binocular cues; perceptual constancy — shape, size, brightness; perceptual set; illusions; extrasensory perception; cross-cultural differences in perception; top-down vs bottom-up processing', difficulty: 'developing', prerequisites: ['psychology.sensation'] },

  // ─── LEARNING ────────────────────────────────────────────────
  { id: 'psychology.classical_conditioning', domain: 'psychology', title: 'Classical Conditioning', description: 'Pavlov\'s experiments; unconditioned and conditioned stimulus and response; acquisition; extinction; spontaneous recovery; generalisation and discrimination; higher-order conditioning; aversion therapy; phobias; Little Albert experiment; biological preparedness', difficulty: 'developing', prerequisites: ['psychology.intro'] },
  { id: 'psychology.operant_conditioning', domain: 'psychology', title: 'Operant Conditioning', description: 'Thorndike\'s law of effect; Skinner\'s operant conditioning; reinforcement — positive and negative; punishment — positive and negative; schedules of reinforcement — fixed ratio, variable ratio, fixed interval, variable interval; shaping; chaining; token economy; applications in education and therapy', difficulty: 'developing', prerequisites: ['psychology.classical_conditioning'] },
  { id: 'psychology.cognitive_learning', domain: 'psychology', title: 'Cognitive and Observational Learning', description: 'Latent learning — Tolman\'s cognitive maps; insight learning — Kohler\'s experiments; observational learning — Bandura\'s Bobo doll experiment; modelling; self-efficacy; vicarious reinforcement; cognitive behaviour modification; learner characteristics; transfer of learning', difficulty: 'proficient', prerequisites: ['psychology.operant_conditioning'] },

  // ─── MEMORY ──────────────────────────────────────────────────
  { id: 'psychology.memory_models', domain: 'psychology', title: 'Memory — Models and Processes', description: 'Atkinson-Shiffrin three-store model — sensory, short-term, long-term; encoding; storage; retrieval; working memory model (Baddeley); levels of processing (Craik and Lockhart); long-term memory — declarative (episodic, semantic) and non-declarative (procedural, priming); schemas', difficulty: 'proficient', prerequisites: ['psychology.cognitive_learning'] },
  { id: 'psychology.forgetting', domain: 'psychology', title: 'Forgetting and Memory Improvement', description: 'Forgetting curve (Ebbinghaus); theories of forgetting — decay, interference (proactive and retroactive), retrieval failure, repression (Freud), motivated forgetting; amnesia — anterograde and retrograde; mnemonic strategies; method of loci; chunking; elaborative rehearsal; context-dependent and state-dependent memory', difficulty: 'proficient', prerequisites: ['psychology.memory_models'] },

  // ─── THINKING AND LANGUAGE ───────────────────────────────────
  { id: 'psychology.thinking', domain: 'psychology', title: 'Thinking and Problem Solving', description: 'Nature of thought; concepts and categories; problem-solving strategies — algorithms, heuristics; obstacles to problem solving — functional fixedness, mental set, confirmation bias; creative thinking; divergent vs convergent thinking; reasoning — deductive and inductive; decision making — prospect theory, heuristics and biases', difficulty: 'proficient', prerequisites: ['psychology.memory_models'] },
  { id: 'psychology.language', domain: 'psychology', title: 'Language and Communication', description: 'Language properties; language acquisition — LAD (Chomsky), learning theory; stages of language development; Sapir-Whorf hypothesis; language and thought; bilingualism; non-verbal communication; animal communication; language disorders — aphasia; reading and dyslexia', difficulty: 'proficient', prerequisites: ['psychology.thinking'] },

  // ─── INTELLIGENCE ────────────────────────────────────────────
  { id: 'psychology.intelligence', domain: 'psychology', title: 'Intelligence', description: 'Theories — Spearman\'s g, Thurstone\'s primary mental abilities, Gardner\'s multiple intelligences, Sternberg\'s triarchic theory; emotional intelligence (Goleman); IQ — history, Binet-Simon scale, Stanford-Binet; WAIS and WISC; reliability and validity; nature vs nurture in intelligence; giftedness; intellectual disability; cultural bias in tests', difficulty: 'proficient', prerequisites: ['psychology.thinking'] },

  // ─── MOTIVATION AND EMOTION ──────────────────────────────────
  { id: 'psychology.motivation', domain: 'psychology', title: 'Motivation', description: 'Instincts; drive reduction theory; Maslow\'s hierarchy of needs; intrinsic and extrinsic motivation; achievement motivation (McClelland); self-determination theory; hunger, thirst, sex — biological drives; cognitive theories of motivation; attribution theory; goal-setting theory; applications in education and work', difficulty: 'developing', prerequisites: ['psychology.human_development'] },
  { id: 'psychology.emotion', domain: 'psychology', title: 'Emotion', description: 'Theories — James-Lange, Cannon-Bard, Schachter-Singer two-factor, Lazarus cognitive appraisal; facial feedback hypothesis; universality of basic emotions (Ekman); emotional regulation; stress and coping; frustration-aggression hypothesis; positive psychology; happiness research; emotional intelligence', difficulty: 'proficient', prerequisites: ['psychology.motivation'] },

  // ─── PERSONALITY ─────────────────────────────────────────────
  { id: 'psychology.personality_theories', domain: 'psychology', title: 'Personality — Theories', description: 'Freud\'s psychoanalytic theory — id, ego, superego; defence mechanisms — repression, projection, rationalisation, displacement, sublimation; stages — oral, anal, phallic, latency, genital; Neo-Freudians — Adler, Jung; trait theories — Allport, Cattell\'s 16PF, Big Five (OCEAN); social-cognitive — Bandura, Mischel; humanistic — Rogers, Maslow; Indian perspective on personality — Guna theory', difficulty: 'proficient', prerequisites: ['psychology.human_development'] },
  { id: 'psychology.personality_assessment', domain: 'psychology', title: 'Personality Assessment', description: 'Self-report inventories — MMPI, NEO-PI; projective tests — Rorschach inkblot, TAT; behavioural assessment; interview; observation; cultural influences on personality; cross-cultural personality research; stability vs change in personality; temperament; person-situation debate', difficulty: 'proficient', prerequisites: ['psychology.personality_theories'] },

  // ─── PSYCHOLOGICAL DISORDERS ─────────────────────────────────
  { id: 'psychology.abnormal_psychology', domain: 'psychology', title: 'Abnormal Behaviour — Concepts', description: 'What is abnormal — statistical infrequency, deviation from norms, personal distress, disability, danger; historical perspectives; medical model; DSM-5 classification; ICD-11; cultural context of mental disorders; prevalence in India; stigma; neurodevelopmental disorders — ADHD, autism spectrum; mental health legislation in India', difficulty: 'proficient', prerequisites: ['psychology.emotion'] },
  { id: 'psychology.disorders_types', domain: 'psychology', title: 'Psychological Disorders — Types', description: 'Anxiety disorders — GAD, phobias, panic disorder, OCD, PTSD; mood disorders — MDD, bipolar disorder; schizophrenia — positive and negative symptoms; dissociative disorders; somatic symptom disorders; eating disorders — anorexia, bulimia; personality disorders — BPD, ASPD; substance-related disorders; causes — biological, psychological, social (biopsychosocial model)', difficulty: 'advanced', prerequisites: ['psychology.abnormal_psychology'] },

  // ─── THERAPEUTIC APPROACHES ──────────────────────────────────
  { id: 'psychology.therapies', domain: 'psychology', title: 'Therapeutic Approaches', description: 'Biological therapies — psychopharmacology (antidepressants, antipsychotics, anxiolytics); ECT; psychosurgery (lobotomy — historical); psychodynamic therapies — psychoanalysis, free association, dream analysis; humanistic therapies — Rogers\' client-centred therapy; cognitive therapies — CBT (Beck), REBT (Ellis); behaviour therapies — systematic desensitisation, exposure, aversion; group therapy; family therapy; effectiveness of psychotherapy; culturally sensitive therapy', difficulty: 'advanced', prerequisites: ['psychology.disorders_types'] },

  // ─── SOCIAL PSYCHOLOGY ───────────────────────────────────────
  { id: 'psychology.attitude', domain: 'psychology', title: 'Attitude and Social Cognition', description: 'Nature and components of attitude — ABC model; attitude formation — classical conditioning, operant conditioning, social learning, direct experience; attitude change — persuasion, cognitive dissonance (Festinger); social cognition; attribution theory — internal vs external; fundamental attribution error; self-serving bias; impression formation; stereotypes and prejudice', difficulty: 'proficient', prerequisites: ['psychology.cognitive_learning'] },
  { id: 'psychology.social_influence', domain: 'psychology', title: 'Social Influence and Group Processes', description: 'Conformity — Asch\'s line experiment; normative and informational influence; obedience — Milgram\'s experiments; compliance — foot-in-the-door, door-in-the-face, low-balling; group dynamics — social facilitation, social loafing, groupthink, group polarisation; leadership styles; cooperation and competition; intergroup conflict and prejudice reduction', difficulty: 'advanced', prerequisites: ['psychology.attitude'] },
  { id: 'psychology.prosocial', domain: 'psychology', title: 'Prosocial Behaviour and Aggression', description: 'Altruism; bystander effect — Darley and Latané; diffusion of responsibility; empathy-altruism hypothesis; cooperation; aggression — instinct theory (Freud, Lorenz), frustration-aggression hypothesis, social learning of aggression; media and aggression; domestic violence; bullying; cyber-aggression; reducing aggression', difficulty: 'proficient', prerequisites: ['psychology.social_influence'] },

  // ─── APPLIED PSYCHOLOGY ──────────────────────────────────────
  { id: 'psychology.stress_health', domain: 'psychology', title: 'Psychology and Health — Stress', description: 'Stressors — types; physiological response to stress — general adaptation syndrome (Selye); cognitive appraisal (Lazarus); effects of stress — physical and psychological; stress and immune system; coping — problem-focused and emotion-focused; social support; burnout; wellness and positive psychology; mindfulness; yoga and meditation; health psychology in India', difficulty: 'proficient', prerequisites: ['psychology.emotion'] },
  { id: 'psychology.applied_fields', domain: 'psychology', title: 'Psychology in Applied Fields', description: 'Environmental psychology — crowding, noise, pollution effects on behaviour; industrial and organisational psychology — selection, training, motivation, leadership, work stress; sport psychology — arousal and performance; military psychology; legal and forensic psychology; consumer psychology; educational applications; cross-cultural psychology; psychologists\' roles and ethics', difficulty: 'developing', prerequisites: ['psychology.intro'] },
]

export function getPsychologyNode(id: string): KnowledgeNode | undefined {
  return PSYCHOLOGY_KNOWLEDGE_GRAPH.find((n) => n.id === id)
}

export function getPsychologyNodesByDomain(domain: string): KnowledgeNode[] {
  return PSYCHOLOGY_KNOWLEDGE_GRAPH.filter((n) => n.domain === domain)
}
