// Master Sanskrit Knowledge Graph — Grammar, Sandhi, Samasa, Shabda-roopa, Dhaatu-roopa, Comprehension

import type { KnowledgeNode } from './educationTypes'

export const SANSKRIT_KNOWLEDGE_GRAPH: KnowledgeNode[] = [

  // ─── व्याकरण (GRAMMAR) ────────────────────────────────────────────────────

  {
    id: 'sanskrit.vyakarana.varna_vichar',
    domain: 'sanskrit.vyakarana',
    title: 'वर्ण विचार — स्वर, व्यंजन और उच्चारण',
    description: 'देवनागरी वर्णमाला में स्वर और व्यंजन के भेद; ह्रस्व-दीर्घ स्वर; उच्चारण-स्थान (कण्ठ्य, तालव्य, मूर्धन्य, दन्त्य, ओष्ठ्य); अनुस्वार और विसर्ग का प्रयोग',
    difficulty: 'foundational',
    prerequisites: [],
  },
  {
    id: 'sanskrit.vyakarana.shabda_bhed',
    domain: 'sanskrit.vyakarana',
    title: 'शब्द भेद — सुबन्त, तिङन्त और अव्यय',
    description: 'संस्कृत शब्दों के मुख्य भेद: सुबन्त (विभक्ति-युक्त नाम-शब्द), तिङन्त (क्रिया-पद) और अव्यय (अपरिवर्तित शब्द); इन भेदों की पहचान',
    difficulty: 'foundational',
    prerequisites: ['sanskrit.vyakarana.varna_vichar'],
  },
  {
    id: 'sanskrit.vyakarana.linga',
    domain: 'sanskrit.vyakarana',
    title: 'लिंग — पुंलिंग, स्त्रीलिंग और नपुंसकलिंग',
    description: 'संस्कृत में तीन लिंगों की पहचान; शब्द के अंत्य स्वर/व्यंजन के आधार पर लिंग-निर्धारण के सामान्य संकेत; विशेषण और संज्ञा के लिंग-साम्य',
    difficulty: 'foundational',
    prerequisites: ['sanskrit.vyakarana.shabda_bhed'],
  },
  {
    id: 'sanskrit.vyakarana.vachana',
    domain: 'sanskrit.vyakarana',
    title: 'वचन — एकवचन, द्विवचन और बहुवचन',
    description: 'संस्कृत की विशिष्ट त्रि-वचन व्यवस्था (एकवचन, द्विवचन, बहुवचन); द्विवचन के प्रयोग के नियम और उदाहरण; हिन्दी की द्वि-वचन व्यवस्था से तुलना',
    difficulty: 'foundational',
    prerequisites: ['sanskrit.vyakarana.shabda_bhed'],
  },
  {
    id: 'sanskrit.vyakarana.karak_vibhakti',
    domain: 'sanskrit.vyakarana',
    title: 'कारक एवं विभक्ति — आठ कारकों का परिचय',
    description: 'आठ कारक (कर्ता, कर्म, करण, सम्प्रदान, अपादान, सम्बन्ध, अधिकरण, सम्बोधन) और उनकी सात विभक्तियाँ; प्रत्येक विभक्ति का अर्थ और वाक्य में प्रयोग',
    difficulty: 'developing',
    prerequisites: ['sanskrit.vyakarana.linga', 'sanskrit.vyakarana.vachana'],
  },
  {
    id: 'sanskrit.vyakarana.upasarga',
    domain: 'sanskrit.vyakarana',
    title: 'उपसर्ग — अर्थ-परिवर्तन और शब्द-निर्माण',
    description: 'प्र, परा, अप, सम्, अनु आदि प्रमुख उपसर्ग; उपसर्ग जोड़ने से धातु/शब्द के अर्थ में होने वाला परिवर्तन; उपसर्ग-युक्त शब्दों के उदाहरण',
    difficulty: 'developing',
    prerequisites: ['sanskrit.vyakarana.shabda_bhed'],
  },
  {
    id: 'sanskrit.vyakarana.pratyaya',
    domain: 'sanskrit.vyakarana',
    title: 'प्रत्यय — कृत् और तद्धित प्रत्यय का परिचय',
    description: 'धातु से नया शब्द बनाने वाले कृत् प्रत्यय (जैसे तव्यत्, अनीयर्, क्त) और शब्द से नया शब्द बनाने वाले तद्धित प्रत्यय का प्रारम्भिक परिचय; नए शब्दों के निर्माण के उदाहरण',
    difficulty: 'developing',
    prerequisites: ['sanskrit.vyakarana.shabda_bhed'],
  },
  {
    id: 'sanskrit.vyakarana.vachya',
    domain: 'sanskrit.vyakarana',
    title: 'वाच्य — कर्तृवाच्य, कर्मवाच्य और भाववाच्य',
    description: 'कर्तृवाच्य, कर्मवाच्य और भाववाच्य के बीच अंतर; वाक्य में कर्ता/कर्म की प्रधानता के अनुसार क्रिया और विभक्ति में परिवर्तन; पहचान और रूपांतरण के उदाहरण',
    difficulty: 'proficient',
    prerequisites: ['sanskrit.vyakarana.karak_vibhakti'],
  },
  {
    id: 'sanskrit.vyakarana.vakya_rachana_anuvad',
    domain: 'sanskrit.vyakarana',
    title: 'वाक्य रचना एवं अनुवाद — हिन्दी-संस्कृत',
    description: 'संस्कृत वाक्य-रचना का सामान्य क्रम (कर्ता-कर्म-क्रिया); सरल हिन्दी वाक्यों का संस्कृत में और संस्कृत वाक्यों का हिन्दी में अनुवाद करने के नियम और अभ्यास',
    difficulty: 'developing',
    prerequisites: ['sanskrit.vyakarana.karak_vibhakti'],
  },
  {
    id: 'sanskrit.vyakarana.chhanda_parichay',
    domain: 'sanskrit.vyakarana',
    title: 'छन्द परिचय — मात्रा, गण और प्रमुख छन्द',
    description: 'छन्द के मूल तत्त्व — लघु-गुरु मात्राएँ और गण; अनुष्टुप् जैसे प्रचलित छन्दों का सामान्य परिचय; पद्य में छन्द पहचानने का प्रारम्भिक अभ्यास',
    difficulty: 'proficient',
    prerequisites: ['sanskrit.vyakarana.varna_vichar'],
  },

  // ─── संधि (SANDHI) ────────────────────────────────────────────────────────

  {
    id: 'sanskrit.sandhi.parichay',
    domain: 'sanskrit.sandhi',
    title: 'संधि परिचय — स्वर, व्यंजन और विसर्ग संधि',
    description: 'संधि का अर्थ (दो वर्णों के मिलने पर होने वाला परिवर्तन) और इसके तीन मुख्य प्रकारों — स्वर संधि, व्यंजन संधि, विसर्ग संधि — का सामान्य परिचय; संधि-विच्छेद की अवधारणा',
    difficulty: 'foundational',
    prerequisites: ['sanskrit.vyakarana.varna_vichar'],
  },
  {
    id: 'sanskrit.sandhi.deergha',
    domain: 'sanskrit.sandhi',
    title: 'स्वर संधि — दीर्घ संधि',
    description: 'समान स्वरों (अ/आ, इ/ई, उ/ऊ) के मिलने पर दीर्घ स्वर बनने का नियम; उदाहरणों सहित संधि और संधि-विच्छेद का अभ्यास',
    difficulty: 'developing',
    prerequisites: ['sanskrit.sandhi.parichay'],
  },
  {
    id: 'sanskrit.sandhi.guna',
    domain: 'sanskrit.sandhi',
    title: 'स्वर संधि — गुण संधि',
    description: 'अ/आ के बाद इ/ई, उ/ऊ, ऋ आने पर क्रमशः ए, ओ, अर् होने का नियम; उदाहरणों सहित संधि और संधि-विच्छेद का अभ्यास',
    difficulty: 'developing',
    prerequisites: ['sanskrit.sandhi.parichay'],
  },
  {
    id: 'sanskrit.sandhi.yan',
    domain: 'sanskrit.sandhi',
    title: 'स्वर संधि — यण् संधि',
    description: 'इ/ई, उ/ऊ, ऋ के बाद असमान स्वर आने पर क्रमशः य्, व्, र् में बदलने का नियम; उदाहरणों सहित संधि और संधि-विच्छेद का अभ्यास',
    difficulty: 'developing',
    prerequisites: ['sanskrit.sandhi.parichay'],
  },
  {
    id: 'sanskrit.sandhi.ayadi',
    domain: 'sanskrit.sandhi',
    title: 'स्वर संधि — अयादि संधि',
    description: 'ए, ऐ, ओ, औ के बाद कोई स्वर आने पर क्रमशः अय्, आय्, अव्, आव् होने का नियम; उदाहरणों सहित संधि और संधि-विच्छेद का अभ्यास',
    difficulty: 'developing',
    prerequisites: ['sanskrit.sandhi.parichay'],
  },
  {
    id: 'sanskrit.sandhi.vyanjan',
    domain: 'sanskrit.sandhi',
    title: 'व्यंजन संधि',
    description: 'व्यंजन के साथ स्वर या अन्य व्यंजन के मिलने पर होने वाले परिवर्तन (जैसे त् का द् होना, म् का अनुस्वार में बदलना); प्रमुख नियम और उदाहरण',
    difficulty: 'proficient',
    prerequisites: ['sanskrit.sandhi.parichay'],
  },
  {
    id: 'sanskrit.sandhi.visarga',
    domain: 'sanskrit.sandhi',
    title: 'विसर्ग संधि',
    description: 'विसर्ग (:) के बाद स्वर या व्यंजन आने पर होने वाले परिवर्तन (जैसे विसर्ग का ओ, र् या श्/ष्/स् में बदलना); प्रमुख नियम और उदाहरण',
    difficulty: 'proficient',
    prerequisites: ['sanskrit.sandhi.parichay'],
  },

  // ─── समास (SAMASA) ────────────────────────────────────────────────────────

  {
    id: 'sanskrit.samasa.parichay',
    domain: 'sanskrit.samasa',
    title: 'समास परिचय — समास-विग्रह की अवधारणा',
    description: 'समास का अर्थ (दो या अधिक पदों का मिलकर एक नया पद बनना) और समास-विग्रह (समस्त पद को अलग-अलग पदों में विभाजित करना) की प्रक्रिया का परिचय',
    difficulty: 'foundational',
    prerequisites: ['sanskrit.vyakarana.shabda_bhed'],
  },
  {
    id: 'sanskrit.samasa.avyayibhava',
    domain: 'sanskrit.samasa',
    title: 'अव्ययीभाव समास',
    description: 'जिस समास में पहला पद अव्यय हो और समस्त पद भी अव्यय की तरह प्रयुक्त हो (जैसे यथाशक्ति, प्रतिदिन); पहचान और उदाहरण',
    difficulty: 'developing',
    prerequisites: ['sanskrit.samasa.parichay'],
  },
  {
    id: 'sanskrit.samasa.tatpurusha',
    domain: 'sanskrit.samasa',
    title: 'तत्पुरुष समास',
    description: 'जिस समास में उत्तर पद प्रधान हो और पूर्व पद की विभक्ति समास में लुप्त हो जाए (जैसे राजपुरुष — राजा का पुरुष); विभक्ति के अनुसार तत्पुरुष के भेद और उदाहरण',
    difficulty: 'developing',
    prerequisites: ['sanskrit.samasa.parichay', 'sanskrit.vyakarana.karak_vibhakti'],
  },
  {
    id: 'sanskrit.samasa.karmadharaya',
    domain: 'sanskrit.samasa',
    title: 'कर्मधारय समास',
    description: 'जिस समास में पूर्व पद विशेषण और उत्तर पद विशेष्य हो और दोनों में समान विभक्ति हो (जैसे नीलकमल — नीला कमल); पहचान और उदाहरण',
    difficulty: 'developing',
    prerequisites: ['sanskrit.samasa.parichay'],
  },
  {
    id: 'sanskrit.samasa.dvigu',
    domain: 'sanskrit.samasa',
    title: 'द्विगु समास',
    description: 'जिस समास का पूर्व पद संख्यावाचक हो और समस्त पद किसी समूह या समाहार का बोध कराए (जैसे त्रिलोक — तीन लोकों का समूह); कर्मधारय से अंतर',
    difficulty: 'developing',
    prerequisites: ['sanskrit.samasa.karmadharaya'],
  },
  {
    id: 'sanskrit.samasa.dvandva',
    domain: 'sanskrit.samasa',
    title: 'द्वंद्व समास',
    description: 'जिस समास में दोनों पद प्रधान हों और उनके बीच "और" का अर्थ निहित हो (जैसे माता-पिता, सुख-दुःख); विग्रह में "च" के प्रयोग का नियम',
    difficulty: 'developing',
    prerequisites: ['sanskrit.samasa.parichay'],
  },
  {
    id: 'sanskrit.samasa.bahuvrihi',
    domain: 'sanskrit.samasa',
    title: 'बहुव्रीहि समास',
    description: 'जिस समास में कोई भी पद प्रधान न हो और समस्त पद किसी अन्य (तीसरे) पद के विशेषण का काम करे (जैसे पीताम्बर — पीला वस्त्र पहनने वाला, अर्थात् कृष्ण); तत्पुरुष व कर्मधारय से अंतर',
    difficulty: 'proficient',
    prerequisites: ['sanskrit.samasa.tatpurusha', 'sanskrit.samasa.karmadharaya'],
  },

  // ─── शब्द-रूप (SHABDA-ROOPA / DECLENSION) ─────────────────────────────────

  {
    id: 'sanskrit.shabda_roopa.parichay',
    domain: 'sanskrit.shabda_roopa',
    title: 'शब्द-रूप परिचय — सुप् प्रत्यय और रूप-रचना',
    description: 'संज्ञा/सर्वनाम शब्दों में सात विभक्तियों और तीन वचनों के संयोग से बनने वाली रूप-संरचना (शब्द-रूप) की अवधारणा; शब्द-रूप सीखने का व्यवस्थित तरीका',
    difficulty: 'foundational',
    prerequisites: ['sanskrit.vyakarana.linga', 'sanskrit.vyakarana.vachana', 'sanskrit.vyakarana.karak_vibhakti'],
  },
  {
    id: 'sanskrit.shabda_roopa.akaranta_pum',
    domain: 'sanskrit.shabda_roopa',
    title: 'शब्द-रूप: अकारांत पुंलिंग (राम-प्रकार)',
    description: '"राम" जैसे अकारांत पुंलिंग शब्दों के शब्द-रूप; इस वर्ग में आने वाले सामान्य पुंलिंग संज्ञा-शब्दों की पहचान और प्रयोग का अभ्यास',
    difficulty: 'developing',
    prerequisites: ['sanskrit.shabda_roopa.parichay'],
  },
  {
    id: 'sanskrit.shabda_roopa.akaranta_napunsak',
    domain: 'sanskrit.shabda_roopa',
    title: 'शब्द-रूप: अकारांत नपुंसकलिंग (फल-प्रकार)',
    description: '"फल" जैसे अकारांत नपुंसकलिंग शब्दों के शब्द-रूप; पुंलिंग रूपों से अंतर मुख्यतः प्रथमा और द्वितीया विभक्ति में',
    difficulty: 'developing',
    prerequisites: ['sanskrit.shabda_roopa.parichay'],
  },
  {
    id: 'sanskrit.shabda_roopa.akaranta_stri',
    domain: 'sanskrit.shabda_roopa',
    title: 'शब्द-रूप: आकारांत स्त्रीलिंग (लता-प्रकार)',
    description: '"लता" जैसे आकारांत स्त्रीलिंग शब्दों के शब्द-रूप; इस वर्ग के सामान्य स्त्रीलिंग शब्दों की पहचान और प्रयोग का अभ्यास',
    difficulty: 'developing',
    prerequisites: ['sanskrit.shabda_roopa.parichay'],
  },
  {
    id: 'sanskrit.shabda_roopa.ikaranta_ukaranta',
    domain: 'sanskrit.shabda_roopa',
    title: 'शब्द-रूप: इकारांत और उकारांत शब्द (मुनि, गुरु)',
    description: '"मुनि" (इकारांत पुंलिंग) और "गुरु" (उकारांत पुंलिंग) जैसे शब्दों के शब्द-रूप; अकारांत रूपों से अंतर',
    difficulty: 'proficient',
    prerequisites: ['sanskrit.shabda_roopa.akaranta_pum'],
  },
  {
    id: 'sanskrit.shabda_roopa.sarvanam_tad_yad_etad',
    domain: 'sanskrit.shabda_roopa',
    title: 'सर्वनाम शब्द-रूप: तद्, यद्, एतद्',
    description: '"तद्" (वह), "यद्" (जो) और "एतद्" (यह) सर्वनामों के तीनों लिंगों में शब्द-रूप; सामान्य संज्ञा-रूपों से इनके अंतर',
    difficulty: 'developing',
    prerequisites: ['sanskrit.shabda_roopa.parichay'],
  },
  {
    id: 'sanskrit.shabda_roopa.sarvanam_kim',
    domain: 'sanskrit.shabda_roopa',
    title: 'सर्वनाम शब्द-रूप: किम् (प्रश्नवाचक)',
    description: '"किम्" (क्या/कौन) प्रश्नवाचक सर्वनाम के तीनों लिंगों में शब्द-रूप; प्रश्न-वाक्य बनाने में इसका प्रयोग',
    difficulty: 'developing',
    prerequisites: ['sanskrit.shabda_roopa.sarvanam_tad_yad_etad'],
  },
  {
    id: 'sanskrit.shabda_roopa.asmad_yushmad',
    domain: 'sanskrit.shabda_roopa',
    title: 'सर्वनाम शब्द-रूप: अस्मद् और युष्मद्',
    description: '"अस्मद्" (मैं/हम) और "युष्मद्" (तू/तुम) पुरुषवाचक सर्वनामों के शब्द-रूप; तीनों वचनों में प्रयोग का अभ्यास',
    difficulty: 'proficient',
    prerequisites: ['sanskrit.shabda_roopa.parichay'],
  },

  // ─── धातु-रूप (DHAATU-ROOPA / CONJUGATION) ────────────────────────────────

  {
    id: 'sanskrit.dhaatu_roopa.parichay',
    domain: 'sanskrit.dhaatu_roopa',
    title: 'धातु-रूप परिचय — धातु, लकार और पुरुष',
    description: 'धातु (क्रिया का मूल रूप), लकार (काल/अर्थ सूचक रूप-समूह) और पुरुष (प्रथम, मध्यम, उत्तम) की अवधारणा; दस गणों का सामान्य परिचय और भ्वादि गण की प्रमुखता',
    difficulty: 'foundational',
    prerequisites: ['sanskrit.vyakarana.shabda_bhed'],
  },
  {
    id: 'sanskrit.dhaatu_roopa.lat_lakar',
    domain: 'sanskrit.dhaatu_roopa',
    title: 'धातु-रूप: लट् लकार (वर्तमान काल)',
    description: 'वर्तमान काल को दर्शाने वाला लट् लकार; भ्वादि गण की धातुओं के तीनों पुरुषों और वचनों में रूप; वाक्य में वर्तमानकालिक क्रिया का प्रयोग',
    difficulty: 'developing',
    prerequisites: ['sanskrit.dhaatu_roopa.parichay'],
  },
  {
    id: 'sanskrit.dhaatu_roopa.lot_lakar',
    domain: 'sanskrit.dhaatu_roopa',
    title: 'धातु-रूप: लोट् लकार (आज्ञार्थ)',
    description: 'आज्ञा, अनुरोध या उपदेश व्यक्त करने वाला लोट् लकार; भ्वादि गण की धातुओं के रूप; आज्ञार्थक वाक्य बनाने का अभ्यास',
    difficulty: 'developing',
    prerequisites: ['sanskrit.dhaatu_roopa.lat_lakar'],
  },
  {
    id: 'sanskrit.dhaatu_roopa.lang_lakar',
    domain: 'sanskrit.dhaatu_roopa',
    title: 'धातु-रूप: लङ् लकार (भूत काल)',
    description: 'सामान्य भूतकाल को दर्शाने वाला लङ् लकार; भ्वादि गण की धातुओं के रूप; लट् लकार से रूप-परिवर्तन की पहचान',
    difficulty: 'proficient',
    prerequisites: ['sanskrit.dhaatu_roopa.lat_lakar'],
  },
  {
    id: 'sanskrit.dhaatu_roopa.lrt_lakar',
    domain: 'sanskrit.dhaatu_roopa',
    title: 'धातु-रूप: लृट् लकार (भविष्य काल)',
    description: 'सामान्य भविष्यकाल को दर्शाने वाला लृट् लकार; भ्वादि गण की धातुओं के रूप; "स्य"/"इष्य" प्रत्यय की पहचान',
    difficulty: 'proficient',
    prerequisites: ['sanskrit.dhaatu_roopa.lat_lakar'],
  },
  {
    id: 'sanskrit.dhaatu_roopa.vidhiling_lakar',
    domain: 'sanskrit.dhaatu_roopa',
    title: 'धातु-रूप: विधिलिङ् लकार (चाहिए/उचित)',
    description: 'कर्तव्य, सम्भावना या सुझाव ("करना चाहिए") व्यक्त करने वाला विधिलिङ् लकार; भ्वादि गण की धातुओं के रूप; लोट् लकार से अंतर',
    difficulty: 'proficient',
    prerequisites: ['sanskrit.dhaatu_roopa.lat_lakar'],
  },
  {
    id: 'sanskrit.dhaatu_roopa.bhu_as',
    domain: 'sanskrit.dhaatu_roopa',
    title: 'प्रमुख धातुएँ: भू और अस् (होना)',
    description: '"होना" अर्थ वाली भू (भ्वादि गण) और अस् (अदादि गण) धातुओं के लट् लकार के रूप; दोनों के प्रयोग में अंतर',
    difficulty: 'developing',
    prerequisites: ['sanskrit.dhaatu_roopa.lat_lakar'],
  },
  {
    id: 'sanskrit.dhaatu_roopa.gam_path',
    domain: 'sanskrit.dhaatu_roopa',
    title: 'प्रमुख धातुएँ: गम् (जाना) और पठ् (पढ़ना)',
    description: 'गम् और पठ् धातुओं के लट् लकार के रूप और इनसे बने सामान्य वाक्य; पढ़ने-लिखने और आने-जाने से जुड़ी रोज़मर्रा की क्रियाएँ',
    difficulty: 'developing',
    prerequisites: ['sanskrit.dhaatu_roopa.lat_lakar'],
  },
  {
    id: 'sanskrit.dhaatu_roopa.kri_vad',
    domain: 'sanskrit.dhaatu_roopa',
    title: 'प्रमुख धातुएँ: कृ (करना) और वद् (बोलना)',
    description: 'कृ (तनादि गण) और वद् (भ्वादि गण) धातुओं के लट् लकार के रूप; "करना" और "बोलना" से जुड़े सामान्य वाक्यों का अभ्यास',
    difficulty: 'developing',
    prerequisites: ['sanskrit.dhaatu_roopa.lat_lakar'],
  },

  // ─── गद्य (PROSE COMPREHENSION & TRANSLATION) ─────────────────────────────

  {
    id: 'sanskrit.gadya.apathit_avbodh',
    domain: 'sanskrit.gadya',
    title: 'अपठित गद्यांश अवबोधन',
    description: 'अनदेखे संस्कृत गद्यांश को पढ़कर उसका अर्थ समझना; गद्यांश पर आधारित प्रश्नों के उत्तर देने का अभ्यास',
    difficulty: 'developing',
    prerequisites: ['sanskrit.vyakarana.vakya_rachana_anuvad'],
  },
  {
    id: 'sanskrit.gadya.shabda_arth_prashna',
    domain: 'sanskrit.gadya',
    title: 'गद्यांश-आधारित शब्दार्थ एवं प्रश्नोत्तर',
    description: 'गद्यांश में आए कठिन शब्दों के अर्थ; गद्यांश के आधार पर संस्कृत में सरल प्रश्नों के उत्तर लिखने का अभ्यास',
    difficulty: 'foundational',
    prerequisites: ['sanskrit.gadya.apathit_avbodh'],
  },
  {
    id: 'sanskrit.gadya.hindi_se_sanskrit',
    domain: 'sanskrit.gadya',
    title: 'अनुवाद: हिन्दी से संस्कृत',
    description: 'सरल हिन्दी वाक्यों को संस्कृत में अनुवादित करने का अभ्यास; उपयुक्त शब्द-रूप, धातु-रूप और कारक का चयन',
    difficulty: 'developing',
    prerequisites: ['sanskrit.vyakarana.vakya_rachana_anuvad', 'sanskrit.dhaatu_roopa.lat_lakar'],
  },
  {
    id: 'sanskrit.gadya.sanskrit_se_hindi',
    domain: 'sanskrit.gadya',
    title: 'अनुवाद: संस्कृत से हिन्दी',
    description: 'सरल संस्कृत वाक्यों और गद्यांशों को हिन्दी में अनुवादित करने का अभ्यास; शब्द-रूप और धातु-रूप की पहचान के आधार पर अर्थ-निर्धारण',
    difficulty: 'developing',
    prerequisites: ['sanskrit.vyakarana.vakya_rachana_anuvad', 'sanskrit.shabda_roopa.akaranta_pum'],
  },
  {
    id: 'sanskrit.gadya.samvad_lekhan',
    domain: 'sanskrit.gadya',
    title: 'संवाद लेखन — सरल संस्कृत वार्तालाप',
    description: 'दैनिक जीवन की स्थितियों (अभिवादन, परिचय, बाज़ार) पर आधारित सरल संस्कृत संवाद की रचना; उचित सर्वनाम और धातु-रूपों का प्रयोग',
    difficulty: 'developing',
    prerequisites: ['sanskrit.gadya.hindi_se_sanskrit'],
  },

  // ─── पद्य (VERSE COMPREHENSION) ───────────────────────────────────────────

  {
    id: 'sanskrit.padya.subhashitani',
    domain: 'sanskrit.padya',
    title: 'सूक्तियाँ एवं सुभाषितानि',
    description: 'पाठ्यपुस्तकों में प्रचलित नैतिक एवं ज्ञानवर्धक सुभाषित-श्लोकों का पठन, अर्थ-बोध और स्मरण; जीवन-मूल्यों से इनका संबंध',
    difficulty: 'foundational',
    prerequisites: ['sanskrit.vyakarana.varna_vichar'],
  },
  {
    id: 'sanskrit.padya.apathit_padyansh',
    domain: 'sanskrit.padya',
    title: 'अपठित पद्यांश अवबोधन',
    description: 'अनदेखे संस्कृत पद्यांश (श्लोक) को पढ़कर उसका भावार्थ समझना; पद्यांश पर आधारित प्रश्नों के उत्तर देने का अभ्यास',
    difficulty: 'developing',
    prerequisites: ['sanskrit.vyakarana.chhanda_parichay', 'sanskrit.gadya.apathit_avbodh'],
  },
  {
    id: 'sanskrit.padya.chhanda_yukt_path',
    domain: 'sanskrit.padya',
    title: 'छन्दयुक्त पाठ — छन्द-बोध',
    description: 'पद्यांश में प्रयुक्त छन्द (जैसे अनुष्टुप्) की पहचान; छन्द के आधार पर पाठ के पढ़ने और भाव-बोध में सहायता',
    difficulty: 'proficient',
    prerequisites: ['sanskrit.vyakarana.chhanda_parichay', 'sanskrit.padya.apathit_padyansh'],
  },
  {
    id: 'sanskrit.padya.shlok_arth_bodh',
    domain: 'sanskrit.padya',
    title: 'श्लोक अर्थ-बोध एवं कण्ठस्थीकरण',
    description: 'पाठ्यपुस्तक में निर्धारित श्लोकों का शब्दशः एवं भावार्थ-बोध; शुद्ध उच्चारण के साथ कण्ठस्थीकरण (याद करना) का अभ्यास',
    difficulty: 'developing',
    prerequisites: ['sanskrit.padya.subhashitani'],
  },
]

export function getSanskritNode(id: string): KnowledgeNode | undefined {
  return SANSKRIT_KNOWLEDGE_GRAPH.find((n) => n.id === id)
}
