// Master Science Knowledge Graph
// Domains: Physics, Chemistry, Biology, Earth Science, Environmental Science

import type { KnowledgeNode } from './educationTypes'

export const SCIENCE_KNOWLEDGE_GRAPH: KnowledgeNode[] = [

  // ─── PHYSICS ─────────────────────────────────────────────────

  { id: 'physics.measurement.units', domain: 'physics.measurement', title: 'Units and Measurement', description: 'SI units, fundamental and derived units, significant figures, errors and uncertainty, dimensional analysis', difficulty: 'foundational', prerequisites: [] },
  { id: 'physics.kinematics.motion_1d', domain: 'physics.kinematics', title: 'Motion in a Straight Line', description: 'Distance, displacement, speed, velocity, acceleration; equations of motion; distance-time and velocity-time graphs', difficulty: 'foundational', prerequisites: ['physics.measurement.units'] },
  { id: 'physics.kinematics.motion_2d', domain: 'physics.kinematics', title: 'Motion in a Plane', description: 'Vectors, relative velocity, projectile motion, circular motion — uniform and non-uniform', difficulty: 'developing', prerequisites: ['physics.kinematics.motion_1d'] },
  { id: 'physics.forces.laws_of_motion', domain: 'physics.forces', title: 'Laws of Motion', description: 'Newton\'s three laws, inertia, momentum, impulse, friction — static and kinetic', difficulty: 'developing', prerequisites: ['physics.kinematics.motion_1d'] },
  { id: 'physics.forces.friction_circular', domain: 'physics.forces', title: 'Friction and Circular Dynamics', description: 'Laws of friction, rolling friction, dynamics of circular motion, banking of roads', difficulty: 'proficient', prerequisites: ['physics.forces.laws_of_motion'] },
  { id: 'physics.work_energy.basics', domain: 'physics.work_energy', title: 'Work, Energy and Power', description: 'Work done by constant and variable force, kinetic and potential energy, work-energy theorem, conservation of energy, power', difficulty: 'developing', prerequisites: ['physics.forces.laws_of_motion'] },
  { id: 'physics.rotational_motion.torque_angular', domain: 'physics.rotational_motion', title: 'Rotational Motion and Torque', description: 'Centre of mass, torque, angular momentum, moment of inertia, conservation of angular momentum, rolling bodies', difficulty: 'advanced', prerequisites: ['physics.work_energy.basics'] },
  { id: 'physics.gravitation.universal', domain: 'physics.gravitation', title: 'Gravitation', description: 'Universal law of gravitation, gravitational field and potential, escape velocity, orbital velocity, Kepler\'s laws, satellites', difficulty: 'proficient', prerequisites: ['physics.forces.laws_of_motion'] },
  { id: 'physics.mechanical_properties.solids_fluids', domain: 'physics.mechanical_properties', title: 'Mechanical Properties of Solids and Fluids', description: 'Elasticity, stress-strain, Hooke\'s law; pressure, buoyancy, Archimedes, Bernoulli, viscosity, surface tension', difficulty: 'proficient', prerequisites: ['physics.forces.laws_of_motion'] },
  { id: 'physics.thermodynamics.heat_temperature', domain: 'physics.thermodynamics', title: 'Thermal Properties and Temperature', description: 'Heat and temperature, thermal expansion, specific heat capacity, calorimetry, change of state, latent heat', difficulty: 'developing', prerequisites: ['physics.measurement.units'] },
  { id: 'physics.thermodynamics.laws', domain: 'physics.thermodynamics', title: 'Laws of Thermodynamics', description: 'Zeroth, first and second laws; heat engines, Carnot cycle, efficiency, entropy', difficulty: 'advanced', prerequisites: ['physics.thermodynamics.heat_temperature', 'physics.work_energy.basics'] },
  { id: 'physics.waves_oscillations.shm', domain: 'physics.waves_oscillations', title: 'Oscillations and SHM', description: 'Simple harmonic motion, restoring force, amplitude, period, frequency, energy in SHM, pendulum, damping', difficulty: 'proficient', prerequisites: ['physics.forces.laws_of_motion'] },
  { id: 'physics.waves_oscillations.waves', domain: 'physics.waves_oscillations', title: 'Waves — Sound and Properties', description: 'Types of waves, wave equation, superposition, standing waves, resonance, Doppler effect, speed of sound', difficulty: 'proficient', prerequisites: ['physics.waves_oscillations.shm'] },
  { id: 'physics.optics.reflection_refraction', domain: 'physics.optics', title: 'Reflection and Refraction of Light', description: 'Laws of reflection, plane and spherical mirrors; Snell\'s law, total internal reflection, lenses — power and ray diagrams', difficulty: 'developing', prerequisites: ['physics.measurement.units'] },
  { id: 'physics.optics.human_eye', domain: 'physics.optics', title: 'Human Eye and Optical Instruments', description: 'Structure of the eye, defects of vision, microscope, telescope, prism and dispersion', difficulty: 'proficient', prerequisites: ['physics.optics.reflection_refraction'] },
  { id: 'physics.optics.wave_optics', domain: 'physics.optics', title: 'Wave Optics', description: 'Huygens principle, interference (Young\'s double slit), diffraction, polarisation', difficulty: 'advanced', prerequisites: ['physics.optics.reflection_refraction', 'physics.waves_oscillations.waves'] },
  { id: 'physics.electricity.electrostatics', domain: 'physics.electricity', title: 'Electrostatics', description: 'Coulomb\'s law, electric field, potential, capacitance, dielectrics, energy stored in capacitor', difficulty: 'proficient', prerequisites: ['physics.forces.laws_of_motion'] },
  { id: 'physics.electricity.current_circuits', domain: 'physics.electricity', title: 'Current Electricity', description: 'Ohm\'s law, resistance, series and parallel circuits, Kirchhoff\'s laws, power, heating effect, Wheatstone bridge', difficulty: 'proficient', prerequisites: ['physics.electricity.electrostatics'] },
  { id: 'physics.electricity.electromagnetic_induction', domain: 'physics.electricity', title: 'Electromagnetic Induction and AC', description: 'Faraday\'s law, Lenz\'s law, inductance, transformer, AC circuits, LCR, resonance', difficulty: 'advanced', prerequisites: ['physics.electricity.current_circuits', 'physics.magnetism.moving_charges'] },
  { id: 'physics.magnetism.moving_charges', domain: 'physics.magnetism', title: 'Moving Charges and Magnetism', description: 'Magnetic force, Biot-Savart law, Ampere\'s law, solenoid, toroid, galvanometer', difficulty: 'advanced', prerequisites: ['physics.electricity.current_circuits'] },
  { id: 'physics.magnetism.permanent', domain: 'physics.magnetism', title: 'Magnetism and Magnetic Materials', description: 'Bar magnet, magnetic field lines, earth\'s magnetism, diamagnetic/paramagnetic/ferromagnetic materials', difficulty: 'proficient', prerequisites: ['physics.electricity.electrostatics'] },
  { id: 'physics.modern_physics.dual_nature', domain: 'physics.modern_physics', title: 'Dual Nature of Radiation and Matter', description: 'Photoelectric effect, Einstein\'s equation, de Broglie wavelength, Davisson-Germer experiment', difficulty: 'advanced', prerequisites: ['physics.optics.wave_optics'] },
  { id: 'physics.modern_physics.atoms_nuclei', domain: 'physics.modern_physics', title: 'Atoms, Nuclei and Radioactivity', description: 'Bohr model, atomic spectra, nuclear binding energy, radioactive decay, fission and fusion', difficulty: 'advanced', prerequisites: ['physics.modern_physics.dual_nature'] },
  { id: 'physics.semiconductors.devices', domain: 'physics.semiconductors', title: 'Semiconductor Devices', description: 'p-n junction, diode, rectifier, transistor, logic gates, communication systems basics', difficulty: 'advanced', prerequisites: ['physics.electricity.current_circuits'] },

  // ─── CHEMISTRY ───────────────────────────────────────────────

  { id: 'chemistry.matter_mixtures.matter', domain: 'chemistry.matter_mixtures', title: 'Matter — Properties and Classification', description: 'States of matter, physical and chemical changes, pure substances, mixtures, separation techniques', difficulty: 'foundational', prerequisites: [] },
  { id: 'chemistry.matter_mixtures.solutions', domain: 'chemistry.matter_mixtures', title: 'Solutions and Colloids', description: 'Solute, solvent, concentration, solubility, colligative properties, colloids, suspensions', difficulty: 'proficient', prerequisites: ['chemistry.matter_mixtures.matter'] },
  { id: 'chemistry.atomic_structure.basics', domain: 'chemistry.atomic_structure', title: 'Structure of the Atom', description: 'Subatomic particles, Bohr\'s model, electronic configuration, valence electrons, isotopes, atomic mass', difficulty: 'foundational', prerequisites: ['chemistry.matter_mixtures.matter'] },
  { id: 'chemistry.atomic_structure.quantum', domain: 'chemistry.atomic_structure', title: 'Quantum Mechanical Model of the Atom', description: 'Quantum numbers, orbitals (s, p, d, f), Aufbau principle, Hund\'s rule, Pauli exclusion principle', difficulty: 'advanced', prerequisites: ['chemistry.atomic_structure.basics'] },
  { id: 'chemistry.periodic_table.trends', domain: 'chemistry.periodic_table', title: 'Periodic Table and Periodic Properties', description: 'Modern periodic law, groups and periods, periodicity of properties (atomic radius, ionisation energy, electronegativity)', difficulty: 'developing', prerequisites: ['chemistry.atomic_structure.basics'] },
  { id: 'chemistry.chemical_bonding.ionic_covalent', domain: 'chemistry.chemical_bonding', title: 'Chemical Bonding — Ionic and Covalent', description: 'Electrovalent bond, covalent bond, Lewis structures, VSEPR theory, molecular geometry, polarity', difficulty: 'proficient', prerequisites: ['chemistry.periodic_table.trends'] },
  { id: 'chemistry.chemical_reactions.equations', domain: 'chemistry.chemical_reactions', title: 'Chemical Reactions and Equations', description: 'Writing and balancing equations, types of reactions (combination, decomposition, displacement, redox)', difficulty: 'developing', prerequisites: ['chemistry.atomic_structure.basics'] },
  { id: 'chemistry.chemical_reactions.stoichiometry', domain: 'chemistry.chemical_reactions', title: 'Stoichiometry and Mole Concept', description: 'Mole, molar mass, Avogadro number, empirical and molecular formula, limiting reagent, yield', difficulty: 'proficient', prerequisites: ['chemistry.chemical_reactions.equations'] },
  { id: 'chemistry.acids_bases_salts.basics', domain: 'chemistry.acids_bases_salts', title: 'Acids, Bases and Salts', description: 'Properties of acids and bases, pH scale, neutralisation, types of salts, indicators', difficulty: 'developing', prerequisites: ['chemistry.chemical_reactions.equations'] },
  { id: 'chemistry.acids_bases_salts.equilibrium', domain: 'chemistry.acids_bases_salts', title: 'Chemical Equilibrium and Ionic Equilibrium', description: 'Reversible reactions, Le Chatelier\'s principle, Kc and Kp, buffer solutions, hydrolysis', difficulty: 'advanced', prerequisites: ['chemistry.acids_bases_salts.basics', 'chemistry.chemical_reactions.stoichiometry'] },
  { id: 'chemistry.metals_nonmetals.reactivity', domain: 'chemistry.metals_nonmetals', title: 'Metals, Non-metals and Reactivity Series', description: 'Properties of metals and non-metals, reactivity series, extraction of metals (ores, reduction, refining)', difficulty: 'proficient', prerequisites: ['chemistry.chemical_reactions.equations'] },
  { id: 'chemistry.thermochemistry.basics', domain: 'chemistry.thermochemistry', title: 'Thermochemistry and Chemical Energetics', description: 'Exothermic and endothermic reactions, enthalpy, Hess\'s law, bond energies', difficulty: 'advanced', prerequisites: ['chemistry.chemical_reactions.stoichiometry'] },
  { id: 'chemistry.electrochemistry.basics', domain: 'chemistry.electrochemistry', title: 'Electrochemistry', description: 'Electrolytic and galvanic cells, electrode potential, EMF, Nernst equation, corrosion, electrolysis', difficulty: 'advanced', prerequisites: ['chemistry.acids_bases_salts.equilibrium'] },
  { id: 'chemistry.organic_chemistry.basics', domain: 'chemistry.organic_chemistry', title: 'Carbon and Its Compounds', description: 'Bonding in carbon, hydrocarbons (alkanes, alkenes, alkynes), functional groups, IUPAC nomenclature', difficulty: 'proficient', prerequisites: ['chemistry.chemical_bonding.ionic_covalent'] },
  { id: 'chemistry.organic_chemistry.reactions', domain: 'chemistry.organic_chemistry', title: 'Organic Reactions and Functional Groups', description: 'Substitution, addition, elimination; alcohols, aldehydes, ketones, carboxylic acids, amines, polymers', difficulty: 'advanced', prerequisites: ['chemistry.organic_chemistry.basics'] },
  { id: 'chemistry.biochemistry.biomolecules', domain: 'chemistry.biochemistry', title: 'Biomolecules and Biochemistry', description: 'Carbohydrates, proteins, lipids, nucleic acids; enzymes, vitamins, hormones', difficulty: 'advanced', prerequisites: ['chemistry.organic_chemistry.reactions'] },
  { id: 'chemistry.environmental_chemistry.pollution', domain: 'chemistry.environmental_chemistry', title: 'Environmental Chemistry', description: 'Air and water pollution, greenhouse effect, acid rain, ozone depletion, green chemistry', difficulty: 'proficient', prerequisites: ['chemistry.matter_mixtures.matter'] },

  // ─── BIOLOGY ─────────────────────────────────────────────────

  { id: 'biology.cell.structure', domain: 'biology.cell', title: 'Cell — Structure and Function', description: 'Cell theory, prokaryotic and eukaryotic cells, cell organelles, plasma membrane, cell wall', difficulty: 'foundational', prerequisites: [] },
  { id: 'biology.cell.division', domain: 'biology.cell', title: 'Cell Division — Mitosis and Meiosis', description: 'Cell cycle, phases of mitosis and meiosis, significance of each type of division', difficulty: 'proficient', prerequisites: ['biology.cell.structure'] },
  { id: 'biology.plant_physiology.nutrition', domain: 'biology.plant_physiology', title: 'Plant Nutrition and Photosynthesis', description: 'Autotrophic nutrition, photosynthesis — light and dark reactions, Calvin cycle, mineral nutrition, nitrogen fixation', difficulty: 'developing', prerequisites: ['biology.cell.structure'] },
  { id: 'biology.plant_physiology.transport', domain: 'biology.plant_physiology', title: 'Transport in Plants', description: 'Osmosis, diffusion, transpiration, water potential, xylem and phloem transport, translocation', difficulty: 'proficient', prerequisites: ['biology.plant_physiology.nutrition'] },
  { id: 'biology.plant_physiology.growth', domain: 'biology.plant_physiology', title: 'Plant Growth and Development', description: 'Growth regulators (auxins, gibberellins, cytokinins, ABA, ethylene), tropisms, photoperiodism, vernalisation', difficulty: 'advanced', prerequisites: ['biology.plant_physiology.transport'] },
  { id: 'biology.animal_physiology.digestion', domain: 'biology.animal_physiology', title: 'Digestion and Nutrition in Animals', description: 'Human digestive system, enzymes, absorption, assimilation, nutritional disorders', difficulty: 'developing', prerequisites: ['biology.cell.structure'] },
  { id: 'biology.animal_physiology.respiration', domain: 'biology.animal_physiology', title: 'Respiration and Gas Exchange', description: 'Aerobic and anaerobic respiration, human respiratory system, breathing mechanism, transport of gases', difficulty: 'developing', prerequisites: ['biology.animal_physiology.digestion'] },
  { id: 'biology.animal_physiology.circulation', domain: 'biology.animal_physiology', title: 'Circulation and Body Fluids', description: 'Blood composition, blood groups, human heart, cardiac cycle, blood vessels, lymphatic system', difficulty: 'proficient', prerequisites: ['biology.animal_physiology.respiration'] },
  { id: 'biology.animal_physiology.nervous_endocrine', domain: 'biology.animal_physiology', title: 'Neural Control and Endocrine System', description: 'Neuron structure, nerve impulse, brain and spinal cord, reflex arc; glands, hormones and their functions', difficulty: 'proficient', prerequisites: ['biology.animal_physiology.circulation'] },
  { id: 'biology.animal_physiology.excretion', domain: 'biology.animal_physiology', title: 'Excretion and Osmoregulation', description: 'Modes of excretion, human excretory system, structure and function of nephron, urine formation, regulation of kidney function, dialysis', difficulty: 'proficient', prerequisites: ['biology.animal_physiology.circulation'] },
  { id: 'biology.animal_physiology.locomotion', domain: 'biology.animal_physiology', title: 'Locomotion and Movement', description: 'Types of movement, skeletal system, joints, muscle structure and contraction (sliding filament theory), disorders of the muscular and skeletal system', difficulty: 'proficient', prerequisites: ['biology.animal_physiology.nervous_endocrine'] },
  { id: 'biology.reproduction.plants_animals', domain: 'biology.reproduction', title: 'Reproduction in Plants and Animals', description: 'Asexual and sexual reproduction in plants; human reproductive system, fertilisation, embryonic development', difficulty: 'proficient', prerequisites: ['biology.cell.division'] },
  { id: 'biology.reproduction.human_health', domain: 'biology.reproduction', title: 'Human Health and Disease', description: 'Common diseases (bacterial, viral, protozoan), immunity, vaccines, drugs and alcohol, cancer', difficulty: 'proficient', prerequisites: ['biology.animal_physiology.circulation'] },
  { id: 'biology.genetics.mendel', domain: 'biology.genetics', title: 'Mendelian Genetics and Inheritance', description: 'Mendel\'s laws, monohybrid and dihybrid crosses, dominance, codominance, sex-linked inheritance', difficulty: 'proficient', prerequisites: ['biology.cell.division'] },
  { id: 'biology.genetics.molecular', domain: 'biology.genetics', title: 'Molecular Basis of Inheritance', description: 'DNA structure and replication, transcription, translation, genetic code, mutations', difficulty: 'advanced', prerequisites: ['biology.genetics.mendel'] },
  { id: 'biology.evolution.darwinism', domain: 'biology.evolution', title: 'Evolution and Natural Selection', description: 'Darwin\'s theory, evidence for evolution, natural selection, speciation, human evolution', difficulty: 'proficient', prerequisites: ['biology.genetics.mendel'] },
  { id: 'biology.ecology.ecosystems', domain: 'biology.ecology', title: 'Ecology and Ecosystems', description: 'Biotic and abiotic factors, food chains and webs, energy flow, nutrient cycling, ecological pyramids', difficulty: 'proficient', prerequisites: ['biology.cell.structure'] },
  { id: 'biology.taxonomy.classification', domain: 'biology.taxonomy', title: 'Classification of Living Organisms', description: 'Five kingdoms, binomial nomenclature, major phyla and classes, viruses and bacteria', difficulty: 'developing', prerequisites: ['biology.cell.structure'] },
  { id: 'biology.biotechnology.basics', domain: 'biology.biotechnology', title: 'Biotechnology — Principles and Applications', description: 'Recombinant DNA technology, restriction enzymes, PCR, gel electrophoresis, GM organisms, bioreactors', difficulty: 'advanced', prerequisites: ['biology.genetics.molecular'] },

  // ─── EARTH SCIENCE ───────────────────────────────────────────

  { id: 'earth_science.solar_system.planets', domain: 'earth_science.solar_system', title: 'The Solar System and Universe', description: 'Sun, planets, moons, asteroids, comets; stars, galaxies, Big Bang theory, celestial coordinates', difficulty: 'foundational', prerequisites: [] },
  { id: 'earth_science.earth_structure.layers', domain: 'earth_science.earth_structure', title: 'Structure of the Earth', description: 'Crust, mantle, core; plate tectonics, earthquakes, volcanoes, rock cycle', difficulty: 'developing', prerequisites: ['earth_science.solar_system.planets'] },
  { id: 'earth_science.climate_weather.atmosphere', domain: 'earth_science.climate_weather', title: 'Atmosphere and Weather', description: 'Layers of atmosphere, atmospheric pressure, wind systems, cloud formation, rainfall, monsoon, climate change', difficulty: 'developing', prerequisites: ['earth_science.earth_structure.layers'] },

  // ─── ENVIRONMENTAL SCIENCE ───────────────────────────────────

  { id: 'environmental_science.natural_resources.management', domain: 'environmental_science.natural_resources', title: 'Natural Resources and Their Management', description: 'Water, forest, wildlife, mineral and energy resources; sustainable use, conservation strategies', difficulty: 'developing', prerequisites: ['biology.ecology.ecosystems'] },
  { id: 'environmental_science.pollution.types', domain: 'environmental_science.pollution', title: 'Environmental Pollution', description: 'Air, water and soil pollution — causes, effects, control measures; noise pollution; e-waste', difficulty: 'proficient', prerequisites: ['environmental_science.natural_resources.management'] },
  { id: 'environmental_science.conservation.biodiversity', domain: 'environmental_science.conservation', title: 'Biodiversity and Conservation', description: 'Levels of biodiversity, hotspots, endangered species, in-situ and ex-situ conservation, protected areas', difficulty: 'proficient', prerequisites: ['biology.ecology.ecosystems'] },
]

export function getScienceNode(id: string): KnowledgeNode | undefined {
  return SCIENCE_KNOWLEDGE_GRAPH.find((n) => n.id === id)
}
