import type { KnowledgeNode } from './educationTypes'

export const SOCIOLOGY_KNOWLEDGE_GRAPH: KnowledgeNode[] = [
  // ─── INTRODUCTION TO SOCIOLOGY ───────────────────────────────
  { id: 'sociology.intro', domain: 'sociology', title: 'Introduction to Sociology', description: 'What is sociology; relationship with other social sciences — history, economics, political science, psychology, anthropology; sociological perspective; common sense vs sociological thinking; emergence of sociology in the context of modernity and industrialisation', difficulty: 'foundational', prerequisites: [] },
  { id: 'sociology.research_methods', domain: 'sociology', title: 'Sociological Research Methods', description: 'Scientific method in sociology; quantitative vs qualitative methods; primary data — survey, interview, observation, participant observation; secondary data — documents, census, official statistics; case study; ethnography; social surveys; sampling; reliability and validity', difficulty: 'developing', prerequisites: ['sociology.intro'] },

  // ─── SOCIETY AND SOCIAL STRUCTURE ────────────────────────────
  { id: 'sociology.society', domain: 'sociology', title: 'Society — Structure and Functions', description: 'Meaning and types of society; social structure — status, role, norms, values, institutions; functions of society; social solidarity — mechanical and organic (Durkheim); manifest and latent functions (Merton); dysfunction; social system', difficulty: 'foundational', prerequisites: ['sociology.intro'] },
  { id: 'sociology.social_groups', domain: 'sociology', title: 'Social Groups', description: 'Meaning and types of groups — primary (Cooley) and secondary; in-group and out-group; reference groups; peer groups; community vs association; characteristics of groups; group dynamics; social networks; impact of social media on group behaviour', difficulty: 'developing', prerequisites: ['sociology.society'] },
  { id: 'sociology.culture', domain: 'sociology', title: 'Culture', description: 'Meaning and characteristics of culture; components — norms, values, beliefs, symbols, language, material and non-material culture; cultural relativism vs ethnocentrism; subculture and counterculture; popular culture; multiculturalism; cultural lag; Sapir-Whorf hypothesis', difficulty: 'developing', prerequisites: ['sociology.society'] },
  { id: 'sociology.socialisation', domain: 'sociology', title: 'Socialisation', description: 'Meaning, types and agents of socialisation — family, peer group, school, media, religion; primary and secondary socialisation; Mead\'s theory of self — I, me, generalised other; Cooley\'s looking-glass self; Erikson\'s stages; re-socialisation and de-socialisation; gender socialisation', difficulty: 'developing', prerequisites: ['sociology.culture'] },

  // ─── SOCIAL STRATIFICATION ───────────────────────────────────
  { id: 'sociology.stratification', domain: 'sociology', title: 'Social Stratification', description: 'Meaning and forms of stratification; universality vs variability; closed and open systems; theories — functionalist (Davis and Moore), conflict (Marx), Weber\'s three dimensions (class, status, party); social mobility — types and factors; inequality and life chances', difficulty: 'proficient', prerequisites: ['sociology.society'] },
  { id: 'sociology.caste', domain: 'sociology', title: 'Caste System', description: 'Features of caste — birth, endogamy, commensality, occupation, purity-pollution; varna vs jati; untouchability; caste and Hinduism; theories — Ghurye, Hutton, Ambedkar; caste and politics; caste and economy; caste mobility; Dominant Caste (M.N. Srinivas); reservation policy and debates; dalit movement', difficulty: 'proficient', prerequisites: ['sociology.stratification'] },
  { id: 'sociology.class', domain: 'sociology', title: 'Class and Class Inequality', description: 'Marx\'s theory of class — bourgeoisie and proletariat; class consciousness; Weber on class; measuring class — income, occupation, education, lifestyle; middle class in India; working class; poverty — absolute and relative; underclass; class and mobility', difficulty: 'proficient', prerequisites: ['sociology.stratification'] },
  { id: 'sociology.gender', domain: 'sociology', title: 'Gender and Patriarchy', description: 'Sex vs gender; gender roles; patriarchy — meaning and types; theories of gender inequality — functionalism, conflict, feminist perspectives; gender socialisation; women\'s movement in India; gender and work; gender and education; gender violence; legal framework — domestic violence act, dowry prohibition', difficulty: 'proficient', prerequisites: ['sociology.socialisation'] },
  { id: 'sociology.tribe_ethnicity', domain: 'sociology', title: 'Tribal Communities and Ethnicity', description: 'Characteristics of tribes in India; problems — land alienation, displacement, forest rights; tribal policy — isolation, assimilation, integration; tribal identity and nationalism; ethnicity — meaning, types; ethnic conflicts; minority groups; communalism; Northeast India', difficulty: 'proficient', prerequisites: ['sociology.stratification'] },

  // ─── SOCIAL INSTITUTIONS ─────────────────────────────────────
  { id: 'sociology.family', domain: 'sociology', title: 'Family and Kinship', description: 'Functions of family; types — nuclear, joint, extended; kinship — consanguinity and affinity; rules of descent — patrilineal, matrilineal, bilateral; marriage — types and rules; changes in family — urbanisation, industrialisation, women\'s employment; family in India; divorce and single-parent families', difficulty: 'developing', prerequisites: ['sociology.social_groups'] },
  { id: 'sociology.marriage', domain: 'sociology', title: 'Marriage', description: 'Definitions and functions of marriage; rules — endogamy, exogamy, hypergamy, hypogamy; forms — monogamy, polygyny, polyandry, group marriage; levirate and sororate; inter-caste and inter-religious marriages; Special Marriage Act; live-in relationships; same-sex relationships; child marriage', difficulty: 'developing', prerequisites: ['sociology.family'] },
  { id: 'sociology.religion', domain: 'sociology', title: 'Religion and Society', description: 'Sociological perspectives on religion — Durkheim (sacred-profane, totemism), Marx (opium of masses), Weber (Protestant ethic and capitalism); functions of religion — social solidarity, social control; religion and social change; communalism; secularism in India; fundamentalism; religious minorities', difficulty: 'proficient', prerequisites: ['sociology.culture'] },
  { id: 'sociology.education_institution', domain: 'sociology', title: 'Education as a Social Institution', description: 'Functions of education — socialisation, social selection, cultural transmission; functionalist and conflict perspectives; Bowles and Gintis — hidden curriculum; Illich — deschooling; education and social mobility; inequality in education — class, caste, gender, region; Right to Education Act; NEP 2020', difficulty: 'proficient', prerequisites: ['sociology.socialisation'] },
  { id: 'sociology.economy_work', domain: 'sociology', title: 'Economy, Work and Society', description: 'Sociological perspective on economy; formal and informal sectors; division of labour; alienation (Marx); automation and work; occupational structure in India; labour markets and gender; migration and work; gig economy; trade unions; MGNREGA; globalisation and work', difficulty: 'proficient', prerequisites: ['sociology.class'] },

  // ─── INDIAN SOCIETY ──────────────────────────────────────────
  { id: 'sociology.indian_society', domain: 'sociology', title: 'Indian Society — Structure and Diversity', description: 'Unity in diversity; demographic diversity; religious diversity; linguistic diversity; regional diversity; India as a plural society; colonial experience and its impact on Indian society; partition and its social consequences; national integration', difficulty: 'developing', prerequisites: ['sociology.society'] },
  { id: 'sociology.rural_society', domain: 'sociology', title: 'Rural Society in India', description: 'Characteristics of rural society; agrarian class structure; land reforms; village community — Panchayati Raj; rural-urban continuum; Green Revolution and social change; bonded labour; agricultural labour; farmer suicides; rural credit; MGNREGA; migration from rural areas', difficulty: 'proficient', prerequisites: ['sociology.caste', 'sociology.class'] },
  { id: 'sociology.urban_society', domain: 'sociology', title: 'Urban Society and Urbanism', description: 'Meaning of urbanism; Wirth\'s urbanism as a way of life; growth of cities in India; metropolitan areas; slums — causes and problems; housing; urban poverty; informal economy in cities; urban governance; smart cities; gentrification; gated communities; urban environmental issues', difficulty: 'proficient', prerequisites: ['sociology.rural_society'] },
  { id: 'sociology.community_movements', domain: 'sociology', title: 'Social Movements in India', description: 'Meaning and types of social movements — reform, revolutionary, reactionary; peasant movements; labour movements; women\'s movements; environmental movements — Chipko, Narmada Bachao; dalit movements — Ambedkar; tribal movements; backward class movements — Mandal; right to information movement; new social movements', difficulty: 'advanced', prerequisites: ['sociology.indian_society'] },

  // ─── SOCIAL CHANGE ───────────────────────────────────────────
  { id: 'sociology.social_change', domain: 'sociology', title: 'Social Change', description: 'Meaning and factors of social change — technology, ideology, economic factors, political processes; theories of social change — evolutionary (Spencer, Comte), cyclical (Spengler, Toynbee), conflict (Marx), functionalist; sanskritisation (Srinivas); westernisation; modernisation; secularisation; spread effects', difficulty: 'proficient', prerequisites: ['sociology.society'] },
  { id: 'sociology.globalisation_society', domain: 'sociology', title: 'Globalisation and Indian Society', description: 'Meaning and dimensions of globalisation — economic, cultural, political; MNCs and global production; cultural globalisation — McDonaldisation, Americanisation, cultural hybridity; impact on India — economy, culture, inequality; anti-globalisation movements; digital divide; migration and diaspora', difficulty: 'advanced', prerequisites: ['sociology.social_change'] },
  { id: 'sociology.environment_society', domain: 'sociology', title: 'Environment and Society', description: 'Sociological perspective on environment; social construction of nature; environmental sociology; industrialisation and environmental degradation; common property resources; sustainable development; environmental justice; green movements; Chipko, Silent Valley; indigenous knowledge; policy responses', difficulty: 'advanced', prerequisites: ['sociology.social_change'] },

  // ─── SOCIAL PROBLEMS ─────────────────────────────────────────
  { id: 'sociology.deviance', domain: 'sociology', title: 'Deviance and Social Control', description: 'Meaning of deviance; theories — Merton\'s strain theory, labelling theory (Becker), differential association (Sutherland), functionalist; crime; juvenile delinquency; drug and alcohol abuse; social control — formal and informal; crime statistics in India; prison system; rehabilitation', difficulty: 'proficient', prerequisites: ['sociology.socialisation'] },
  { id: 'sociology.poverty_exclusion', domain: 'sociology', title: 'Poverty and Social Exclusion', description: 'Absolute vs relative poverty; social exclusion — Sen\'s capabilities approach; poverty in India — causes and measurement; poverty line debates; BPL; scheduled castes and tribals; discrimination; exclusion in education, healthcare, housing; welfare state; government anti-poverty programmes — PMAY, PM-KISAN, NFSA', difficulty: 'proficient', prerequisites: ['sociology.caste', 'sociology.class'] },
]

export function getSociologyNode(id: string): KnowledgeNode | undefined {
  return SOCIOLOGY_KNOWLEDGE_GRAPH.find((n) => n.id === id)
}

export function getSociologyNodesByDomain(domain: string): KnowledgeNode[] {
  return SOCIOLOGY_KNOWLEDGE_GRAPH.filter((n) => n.domain === domain)
}
