// Master Social Science Knowledge Graph

import type { KnowledgeNode } from './educationTypes'

export const SOCIAL_SCIENCE_KNOWLEDGE_GRAPH: KnowledgeNode[] = [

  // ─── HISTORY ─────────────────────────────────────────────────

  { id: 'history.ancient_india.harappan', domain: 'history.ancient_india', title: 'Harappan (Indus Valley) Civilisation', description: 'Major sites (Harappa, Mohenjo-daro, Lothal), urban planning, trade, decline, script and religion', difficulty: 'foundational', prerequisites: [] },
  { id: 'history.ancient_india.vedic_period', domain: 'history.ancient_india', title: 'Vedic Period and Early Kingdoms', description: 'Early and Later Vedic period, Vedas and Upanishads, varna system, janapadas and mahajanapadas, rise of Magadha', difficulty: 'foundational', prerequisites: ['history.ancient_india.harappan'] },
  { id: 'history.ancient_india.maurya_gupta', domain: 'history.ancient_india', title: 'Maurya and Gupta Empires', description: 'Chandragupta Maurya, Ashoka and Dhamma, Mauryan administration; Gupta golden age, science and culture, Samudragupta', difficulty: 'developing', prerequisites: ['history.ancient_india.vedic_period'] },
  { id: 'history.ancient_india.buddhism_jainism', domain: 'history.ancient_india', title: 'Buddhism, Jainism and Religious Movements', description: 'Life of Buddha and Mahavira, Four Noble Truths, Eightfold Path, Jain principles, Bhakti and Sufi movements', difficulty: 'developing', prerequisites: ['history.ancient_india.vedic_period'] },
  { id: 'history.ancient_world.greece_rome', domain: 'history.ancient_world', title: 'Ancient Civilisations — Greece and Rome', description: 'Greek city-states, democracy in Athens, Macedonian empire (Alexander); Roman Republic and Empire', difficulty: 'developing', prerequisites: [] },
  { id: 'history.medieval_india.delhi_sultanate', domain: 'history.medieval_india', title: 'Delhi Sultanate', description: 'Establishment, major dynasties (Slave, Khalji, Tughlaq, Sayyid, Lodi), administration, culture, Ibn Battuta', difficulty: 'developing', prerequisites: ['history.ancient_india.maurya_gupta'] },
  { id: 'history.medieval_india.mughal_empire', domain: 'history.medieval_india', title: 'Mughal Empire', description: 'Babur to Aurangzeb, Akbar\'s administration and Din-i-Ilahi, Mansabdari system, Mughal art and architecture, decline', difficulty: 'developing', prerequisites: ['history.medieval_india.delhi_sultanate'] },
  { id: 'history.medieval_india.regional_kingdoms', domain: 'history.medieval_india', title: 'Regional Kingdoms and Cultural Traditions', description: 'Vijayanagara, Rajputs, Marathas; regional bhakti traditions; trade and crafts; temples and monuments', difficulty: 'developing', prerequisites: ['history.medieval_india.delhi_sultanate'] },
  { id: 'history.medieval_india.bhakti_sufi', domain: 'history.medieval_india', title: 'Bhakti and Sufi Traditions', description: 'Bhakti movement saints (Kabir, Mirabai, Guru Nanak, Tulsidas), Nirguna and Saguna traditions; Sufism, silsilas and khanqahs; syncretic culture in medieval India', difficulty: 'developing', prerequisites: ['history.medieval_india.delhi_sultanate'] },
  { id: 'history.world_history.french_revolution', domain: 'history.world_history', title: 'French Revolution and Age of Revolutions', description: 'Causes and phases of French Revolution, Napoleon, ideas of liberty, equality, fraternity', difficulty: 'proficient', prerequisites: [] },
  { id: 'history.world_history.industrialisation', domain: 'history.world_history', title: 'Industrial Revolution and Colonialism', description: 'Origins in Britain, factory system, urbanisation, capitalism; colonialism in Asia and Africa', difficulty: 'proficient', prerequisites: ['history.world_history.french_revolution'] },
  { id: 'history.world_history.world_wars', domain: 'history.world_history', title: 'World Wars and Rise of Nazism', description: 'Causes and consequences of WWI, Treaty of Versailles; rise of Hitler and Nazism; WWII — causes, turning points, aftermath, Holocaust', difficulty: 'proficient', prerequisites: ['history.world_history.industrialisation'] },
  { id: 'history.modern_india.colonial_period', domain: 'history.modern_india', title: 'British Rule in India', description: 'Establishment of British power, economic impact of colonialism, land revenue systems, revolt of 1857, social reforms', difficulty: 'proficient', prerequisites: ['history.medieval_india.mughal_empire'] },
  { id: 'history.modern_india.independence_movement', domain: 'history.modern_india', title: 'Indian Independence Movement', description: 'Early nationalism, Indian National Congress, Gandhi and mass movements (Non-Cooperation, Civil Disobedience, Quit India), partition', difficulty: 'proficient', prerequisites: ['history.modern_india.colonial_period'] },
  { id: 'history.post_independence.constitution', domain: 'history.post_independence', title: 'India After Independence — Nation Building', description: 'Partition and its aftermath, framing the Constitution, integration of princely states, linguistic reorganisation, first general elections', difficulty: 'advanced', prerequisites: ['history.modern_india.independence_movement'] },
  { id: 'history.post_independence.contemporary', domain: 'history.post_independence', title: 'Contemporary India — Politics and Society', description: 'Congress dominance, five-year plans, Emergency period, coalition politics, economic reforms, India\'s foreign policy, regional aspirations', difficulty: 'advanced', prerequisites: ['history.post_independence.constitution'] },

  // ─── GEOGRAPHY ────────────────────────────────────────────────

  { id: 'geography.earth_globe.basics', domain: 'geography.earth_globe', title: 'The Earth — Shape, Size and Motions', description: 'Shape and size of Earth, rotation and revolution, seasons, day and night, solstices and equinoxes', difficulty: 'foundational', prerequisites: [] },
  { id: 'geography.maps.reading', domain: 'geography.maps', title: 'Maps — Types and Reading', description: 'Types of maps (physical, political, thematic), scale, directions, symbols, grid system, latitudes and longitudes, time zones', difficulty: 'foundational', prerequisites: ['geography.earth_globe.basics'] },
  { id: 'geography.earth_globe.landforms', domain: 'geography.earth_globe', title: 'Major Landforms and Ocean Features', description: 'Continents and oceans, mountains, plateaus, plains, rivers; ocean floor features', difficulty: 'foundational', prerequisites: ['geography.earth_globe.basics'] },
  { id: 'geography.world_physical.climate_biomes', domain: 'geography.world_physical', title: 'World Climate and Natural Vegetation', description: 'Climate zones (tropical, temperate, polar, arid), major biomes, vegetation types', difficulty: 'developing', prerequisites: ['geography.earth_globe.landforms'] },
  { id: 'geography.india_physical.relief_drainage', domain: 'geography.india_physical', title: 'India — Physical Features and Drainage', description: 'Himalayan mountains, Indo-Gangetic Plains, Peninsular Plateau, coastal plains, islands; major river systems', difficulty: 'developing', prerequisites: ['geography.earth_globe.landforms'] },
  { id: 'geography.india_physical.climate_vegetation', domain: 'geography.india_physical', title: 'India — Climate, Vegetation and Wildlife', description: 'Factors affecting India\'s climate, monsoon mechanism, seasons; forest types; wildlife sanctuaries and national parks', difficulty: 'developing', prerequisites: ['geography.india_physical.relief_drainage'] },
  { id: 'geography.india_resources.agriculture', domain: 'geography.india_resources', title: 'India — Agriculture and Land Use', description: 'Cropping patterns, major crops (rice, wheat, cotton, jute, sugarcane), green revolution, irrigation systems, food security', difficulty: 'proficient', prerequisites: ['geography.india_physical.climate_vegetation'] },
  { id: 'geography.india_resources.minerals_energy', domain: 'geography.india_resources', title: 'India — Minerals and Energy Resources', description: 'Distribution of minerals (iron, coal, petroleum, bauxite), conventional and non-conventional energy sources', difficulty: 'proficient', prerequisites: ['geography.india_physical.relief_drainage'] },
  { id: 'geography.india_resources.industries_transport', domain: 'geography.india_resources', title: 'India — Industries, Transport and Trade', description: 'Major industries (textiles, iron and steel, IT), industrial regions; transport networks; international trade', difficulty: 'proficient', prerequisites: ['geography.india_resources.agriculture'] },
  { id: 'geography.human_geography.population', domain: 'geography.human_geography', title: 'Human Geography — Population and Settlement', description: 'World and India population distribution, density, growth rate; demographic transition; rural and urban settlements; migration', difficulty: 'proficient', prerequisites: ['geography.india_physical.relief_drainage'] },
  { id: 'geography.human_geography.development', domain: 'geography.human_geography', title: 'Human Development and Sustainable Development', description: 'HDI, development indicators, regional disparities; environmental degradation and sustainable development', difficulty: 'advanced', prerequisites: ['geography.human_geography.population'] },

  // ─── CIVICS / POLITICAL SCIENCE ───────────────────────────────

  { id: 'civics.government_systems.democracy', domain: 'civics.government_systems', title: 'Government Systems and Democracy', description: 'Types of government, meaning of democracy, features of democratic government, why democracy', difficulty: 'foundational', prerequisites: [] },
  { id: 'civics.local_government.panchayati_raj', domain: 'civics.local_government', title: 'Panchayati Raj and Urban Local Bodies', description: 'Three-tier Panchayati Raj system; urban local bodies; 73rd and 74th amendments', difficulty: 'developing', prerequisites: ['civics.government_systems.democracy'] },
  { id: 'civics.constitution.rights_duties', domain: 'civics.constitution', title: 'Indian Constitution — Rights and Duties', description: 'Making of the Constitution, Preamble, Fundamental Rights (Articles 12–35), Directive Principles, Fundamental Duties', difficulty: 'proficient', prerequisites: ['civics.government_systems.democracy'] },
  { id: 'civics.national_government.parliament', domain: 'civics.national_government', title: 'Indian Parliament and Legislature', description: 'Lok Sabha and Rajya Sabha — composition, powers and functions; legislative process; role of Speaker', difficulty: 'proficient', prerequisites: ['civics.constitution.rights_duties'] },
  { id: 'civics.national_government.executive_judiciary', domain: 'civics.national_government', title: 'Executive and Judiciary', description: 'President and Vice-President; Prime Minister and Council of Ministers; Supreme Court, High Courts; judicial review, PIL', difficulty: 'proficient', prerequisites: ['civics.national_government.parliament'] },
  { id: 'civics.constitution.federalism', domain: 'civics.constitution', title: 'Federalism and Centre-State Relations', description: 'Federal features of India, division of powers (Union/State/Concurrent lists), Governor, emergency provisions', difficulty: 'advanced', prerequisites: ['civics.national_government.executive_judiciary'] },
  { id: 'civics.international_relations.un', domain: 'civics.international_relations', title: 'International Relations and UN', description: 'UN structure and agencies, UNICEF, WHO, UNESCO; India\'s foreign policy, Non-Aligned Movement, SAARC, globalisation', difficulty: 'advanced', prerequisites: ['civics.national_government.executive_judiciary'] },
  { id: 'civics.international_relations.cold_war', domain: 'civics.international_relations', title: 'The Cold War Era and World Politics', description: 'Cold War rivalry between USA and USSR, emergence of two power blocs, NATO and Warsaw Pact, arms race, Non-Aligned Movement, end of bipolarity and the contemporary world order', difficulty: 'advanced', prerequisites: ['history.world_history.world_wars'] },

  // ─── ECONOMICS ────────────────────────────────────────────────

  { id: 'economics.basic_economics.wants_scarcity', domain: 'economics.basic_economics', title: 'Basic Economics — Wants, Scarcity and Choice', description: 'Economic problem, wants and resources, scarcity, choice and opportunity cost, basic economic questions', difficulty: 'foundational', prerequisites: [] },
  { id: 'economics.indian_economy.sectors', domain: 'economics.indian_economy', title: 'Sectors of the Indian Economy', description: 'Primary, secondary and tertiary sectors; organised and unorganised sectors; formal and informal employment; GDP contribution', difficulty: 'developing', prerequisites: ['economics.basic_economics.wants_scarcity'] },
  { id: 'economics.development.poverty', domain: 'economics.development', title: 'Development and Poverty', description: 'Economic development vs growth, human development, poverty line, absolute and relative poverty, government schemes, food security', difficulty: 'developing', prerequisites: ['economics.indian_economy.sectors'] },
  { id: 'economics.markets.supply_demand', domain: 'economics.markets', title: 'Markets and Price Mechanism', description: 'Types of markets, demand and supply, factors affecting demand and supply, market equilibrium, price determination', difficulty: 'proficient', prerequisites: ['economics.basic_economics.wants_scarcity'] },
  { id: 'economics.money_banking.currency', domain: 'economics.money_banking', title: 'Money, Banking and Credit', description: 'Functions of money, formal and informal credit, banking system (RBI, commercial banks), self-help groups, microfinance', difficulty: 'proficient', prerequisites: ['economics.markets.supply_demand'] },
  { id: 'economics.globalisation.trade', domain: 'economics.globalisation', title: 'Globalisation and Indian Economy', description: 'Liberalisation, privatisation and globalisation (LPG reforms 1991); MNCs, FDI, WTO, impact on Indian industry, agriculture and consumers', difficulty: 'advanced', prerequisites: ['economics.money_banking.currency'] },
  { id: 'economics.indian_economy.planning', domain: 'economics.indian_economy', title: 'Indian Economic Planning and Development', description: 'Five-year plans, NITI Aayog, industrial policy, agricultural reforms (Green Revolution), economic liberalisation', difficulty: 'advanced', prerequisites: ['economics.development.poverty'] },
  { id: 'economics.statistics.data', domain: 'economics.statistics', title: 'Statistics for Economics', description: 'Collection, organisation and presentation of data; measures of central tendency and dispersion; index numbers; correlation', difficulty: 'advanced', prerequisites: ['economics.basic_economics.wants_scarcity'] },

  // ─── SOCIETY & CULTURE ────────────────────────────────────────

  { id: 'society.social_institutions.family', domain: 'society.social_institutions', title: 'Social Institutions — Family, Community and Caste', description: 'Types of family, kinship, community life, urban and rural differences; caste system — origins, features and social impact', difficulty: 'foundational', prerequisites: [] },
  { id: 'society.social_inequality.gender_caste', domain: 'society.social_inequality', title: 'Social Inequality — Gender, Caste and Class', description: 'Patriarchy and gender discrimination, women\'s rights and empowerment; caste discrimination (untouchability); class inequality; marginalisation', difficulty: 'developing', prerequisites: ['society.social_institutions.family'] },
  { id: 'society.social_change.reform', domain: 'society.social_change', title: 'Social Reform Movements and Change', description: '19th-century reform movements (Raja Ram Mohan Roy, Jyotirao Phule, B.R. Ambedkar), women\'s movement, social legislation', difficulty: 'proficient', prerequisites: ['society.social_inequality.gender_caste'] },
]

export function getSocialScienceNode(id: string): KnowledgeNode | undefined {
  return SOCIAL_SCIENCE_KNOWLEDGE_GRAPH.find((n) => n.id === id)
}
