import type { BoardSubjectCatalog } from './educationTypes'

export const UP_ENGLISH_CATALOG: BoardSubjectCatalog = {
  boardId: 'up_board',
  subjectSlug: 'english',
  subjectName: 'English',
  grades: [
    {
      grade: 5,
      chapters: [
        { id: 'up.eng.5.ch1', order: 1, title: 'The Alphabet and Phonics', kgNodeIds: ['grammar.alphabet_phonics.sounds'] },
        { id: 'up.eng.5.ch2', order: 2, title: 'Nouns and Their Kinds', kgNodeIds: ['grammar.parts_of_speech.nouns_pronouns'] },
        { id: 'up.eng.5.ch3', order: 3, title: 'My Family and Home (Vocabulary)', kgNodeIds: ['vocabulary.basic_words.everyday'] },
        { id: 'up.eng.5.ch4', order: 4, title: 'Simple Sentences', kgNodeIds: ['grammar.sentences.types_structure'] },
        { id: 'up.eng.5.ch5', order: 5, title: 'Pronouns', kgNodeIds: ['grammar.parts_of_speech.nouns_pronouns'] },
        { id: 'up.eng.5.ch6', order: 6, title: 'Reading Short Passages', kgNodeIds: ['reading.comprehension_basic.main_idea'] },
        { id: 'up.eng.5.ch7', order: 7, title: 'Punctuation Marks', kgNodeIds: ['grammar.punctuation.basics'] },
        { id: 'up.eng.5.ch8', order: 8, title: 'Stories and Poems', kgNodeIds: ['literature.prose.stories', 'literature.poetry.basic'] },
        { id: 'up.eng.5.ch9', order: 9, title: 'Describing Words (Adjectives)', kgNodeIds: ['grammar.parts_of_speech.adjectives_adverbs'] },
        { id: 'up.eng.5.ch10', order: 10, title: 'Writing Sentences and Short Paragraphs', kgNodeIds: ['writing.sentences_paragraphs.basics'] },
        { id: 'up.eng.5.ch11', order: 11, title: 'Articles — A, An and The', kgNodeIds: ['grammar.articles.usage'] },
      ],
    },
    {
      grade: 6,
      chapters: [
        { id: 'up.eng.6.ch1', order: 1, title: 'Nouns — Common, Proper and Collective', kgNodeIds: ['grammar.parts_of_speech.nouns_pronouns'] },
        { id: 'up.eng.6.ch2', order: 2, title: 'Verbs — Action and Linking', kgNodeIds: ['grammar.parts_of_speech.verbs'] },
        { id: 'up.eng.6.ch3', order: 3, title: 'Adjectives and Degrees of Comparison', kgNodeIds: ['grammar.parts_of_speech.adjectives_adverbs'] },
        { id: 'up.eng.6.ch4', order: 4, title: 'Present Tense', kgNodeIds: ['grammar.tenses.present_past'] },
        { id: 'up.eng.6.ch5', order: 5, title: 'Synonyms and Antonyms', kgNodeIds: ['vocabulary.synonyms_antonyms.relationships'] },
        { id: 'up.eng.6.ch6', order: 6, title: 'Comprehension Passages', kgNodeIds: ['reading.comprehension_basic.main_idea'] },
        { id: 'up.eng.6.ch7', order: 7, title: 'Prose — Lessons from Textbook', kgNodeIds: ['literature.prose.stories'] },
        { id: 'up.eng.6.ch8', order: 8, title: 'Poetry — Poems from Textbook', kgNodeIds: ['literature.poetry.basic'] },
        { id: 'up.eng.6.ch9', order: 9, title: 'Paragraph Writing', kgNodeIds: ['writing.sentences_paragraphs.basics'] },
        { id: 'up.eng.6.ch10', order: 10, title: 'Adverbs', kgNodeIds: ['grammar.parts_of_speech.adjectives_adverbs'] },
        { id: 'up.eng.6.ch11', order: 11, title: 'Prepositions', kgNodeIds: ['grammar.parts_of_speech.prepositions_conjunctions'] },
        { id: 'up.eng.6.ch12', order: 12, title: 'Word Formation — Prefixes and Suffixes', kgNodeIds: ['vocabulary.word_formation.affixes'] },
        { id: 'up.eng.6.ch13', order: 13, title: 'Articles — Definite and Indefinite Usage', kgNodeIds: ['grammar.articles.usage'] },
      ],
    },
    {
      grade: 7,
      chapters: [
        { id: 'up.eng.7.ch1', order: 1, title: 'Parts of Speech — Revision and Extension', kgNodeIds: ['grammar.parts_of_speech.verbs', 'grammar.parts_of_speech.adjectives_adverbs'] },
        { id: 'up.eng.7.ch2', order: 2, title: 'Past Tense — Simple and Continuous', kgNodeIds: ['grammar.tenses.present_past'] },
        { id: 'up.eng.7.ch3', order: 3, title: 'Future Tense', kgNodeIds: ['grammar.tenses.future_advanced'] },
        { id: 'up.eng.7.ch4', order: 4, title: 'Types of Sentences — Transformation', kgNodeIds: ['grammar.sentences.types_structure'] },
        { id: 'up.eng.7.ch5', order: 5, title: 'Conjunctions and Interjections', kgNodeIds: ['grammar.parts_of_speech.prepositions_conjunctions'] },
        { id: 'up.eng.7.ch6', order: 6, title: 'Modal Verbs', kgNodeIds: ['grammar.modals.usage'] },
        { id: 'up.eng.7.ch7', order: 7, title: 'Reading Comprehension — Inference', kgNodeIds: ['reading.comprehension_basic.main_idea', 'reading.strategies.skim_scan'] },
        { id: 'up.eng.7.ch8', order: 8, title: 'Prose — Lessons from Textbook', kgNodeIds: ['literature.prose.stories'] },
        { id: 'up.eng.7.ch9', order: 9, title: 'Poetry — Rhyme and Rhythm', kgNodeIds: ['literature.poetry.basic'] },
        { id: 'up.eng.7.ch10', order: 10, title: 'Descriptive Paragraph and Essay', kgNodeIds: ['writing.essay_types.descriptive_narrative'] },
        { id: 'up.eng.7.ch11', order: 11, title: 'Letter Writing — Informal', kgNodeIds: ['writing.formal_informal.letters'] },
        { id: 'up.eng.7.ch12', order: 12, title: 'Idioms and Phrases', kgNodeIds: ['vocabulary.idioms_phrases.fixed_expressions'] },
        { id: 'up.eng.7.ch13', order: 13, title: 'Pronunciation and Speaking Skills', kgNodeIds: ['communication.speaking.pronunciation'] },
      ],
    },
    {
      grade: 8,
      chapters: [
        { id: 'up.eng.8.ch1', order: 1, title: 'Perfect Tenses — Present and Past', kgNodeIds: ['grammar.tenses.present_past'] },
        { id: 'up.eng.8.ch2', order: 2, title: 'Active and Passive Voice', kgNodeIds: ['grammar.voice.active_passive'] },
        { id: 'up.eng.8.ch3', order: 3, title: 'Direct and Indirect Speech', kgNodeIds: ['grammar.narration.direct_indirect'] },
        { id: 'up.eng.8.ch4', order: 4, title: 'Clauses — Main and Subordinate', kgNodeIds: ['grammar.clauses_phrases.clause_types'] },
        { id: 'up.eng.8.ch5', order: 5, title: 'One Word Substitution and Synonyms', kgNodeIds: ['vocabulary.synonyms_antonyms.relationships'] },
        { id: 'up.eng.8.ch6', order: 6, title: 'Comprehension — Unseen Passages', kgNodeIds: ['reading.comprehension_basic.main_idea'] },
        { id: 'up.eng.8.ch7', order: 7, title: 'Prose — Lessons and Biographies', kgNodeIds: ['literature.prose.stories'] },
        { id: 'up.eng.8.ch8', order: 8, title: 'Poetry — Poetic Devices', kgNodeIds: ['literature.poetry.basic'] },
        { id: 'up.eng.8.ch9', order: 9, title: 'Narrative and Descriptive Essays', kgNodeIds: ['writing.essay_types.descriptive_narrative'] },
        { id: 'up.eng.8.ch10', order: 10, title: 'Formal Letter and Application Writing', kgNodeIds: ['writing.formal_informal.letters'] },
        { id: 'up.eng.8.ch11', order: 11, title: 'Listening Comprehension', kgNodeIds: ['communication.listening.comprehension'] },
        { id: 'up.eng.8.ch12', order: 12, title: 'Story Writing', kgNodeIds: ['writing.creative.story_poem'] },
      ],
    },
    {
      grade: 9,
      chapters: [
        { id: 'up.eng.9.ch1', order: 1, title: 'Grammar — Tenses Revision and Advanced Uses', kgNodeIds: ['grammar.tenses.future_advanced'] },
        { id: 'up.eng.9.ch2', order: 2, title: 'Active and Passive Voice — All Tenses', kgNodeIds: ['grammar.voice.active_passive'] },
        { id: 'up.eng.9.ch3', order: 3, title: 'Reported Speech', kgNodeIds: ['grammar.narration.direct_indirect'] },
        { id: 'up.eng.9.ch4', order: 4, title: 'Conditionals', kgNodeIds: ['grammar.conditionals.types'] },
        { id: 'up.eng.9.ch5', order: 5, title: 'Clauses and Phrases — Advanced', kgNodeIds: ['grammar.clauses_phrases.clause_types'] },
        { id: 'up.eng.9.ch6', order: 6, title: 'Unseen Comprehension Passages', kgNodeIds: ['reading.comprehension_advanced.inference'] },
        { id: 'up.eng.9.ch7', order: 7, title: 'Reading Strategies — Skimming and Scanning', kgNodeIds: ['reading.strategies.skim_scan'] },
        { id: 'up.eng.9.ch8', order: 8, title: 'Prose — Main Course Book', kgNodeIds: ['literature.prose.stories'] },
        { id: 'up.eng.9.ch9', order: 9, title: 'Supplementary Reader', kgNodeIds: ['literature.prose.stories'] },
        { id: 'up.eng.9.ch10', order: 10, title: 'Poetry — Analysis and Appreciation', kgNodeIds: ['literature.poetry.basic'] },
        { id: 'up.eng.9.ch11', order: 11, title: 'Essay Writing — Descriptive and Expository', kgNodeIds: ['writing.essay_types.descriptive_narrative', 'writing.essay_types.expository_argumentative'] },
        { id: 'up.eng.9.ch12', order: 12, title: 'Letter and Application Writing', kgNodeIds: ['writing.formal_informal.letters'] },
        { id: 'up.eng.9.ch13', order: 13, title: 'Creative Writing — Stories and Dialogues', kgNodeIds: ['writing.creative.story_poem'] },
      ],
    },
    {
      grade: 10,
      chapters: [
        { id: 'up.eng.10.ch1', order: 1, title: 'Grammar — Comprehensive Revision', kgNodeIds: ['grammar.voice.active_passive', 'grammar.narration.direct_indirect'] },
        { id: 'up.eng.10.ch2', order: 2, title: 'Conditionals and Wishes', kgNodeIds: ['grammar.conditionals.types'] },
        { id: 'up.eng.10.ch3', order: 3, title: 'Modals — Meaning and Use', kgNodeIds: ['grammar.modals.usage'] },
        { id: 'up.eng.10.ch4', order: 4, title: 'Unseen Comprehension — Prose and Poetry', kgNodeIds: ['reading.comprehension_advanced.inference'] },
        { id: 'up.eng.10.ch5', order: 5, title: 'Prose — Main Course Book', kgNodeIds: ['literature.prose.stories'] },
        { id: 'up.eng.10.ch6', order: 6, title: 'Supplementary Reader — Longer Texts', kgNodeIds: ['literature.prose.stories'] },
        { id: 'up.eng.10.ch7', order: 7, title: 'Poetry — Poetic Devices and Appreciation', kgNodeIds: ['literature.poetry.basic', 'reading.literary_analysis.elements'] },
        { id: 'up.eng.10.ch8', order: 8, title: 'Essay Writing — Argumentative and Narrative', kgNodeIds: ['writing.essay_types.expository_argumentative'] },
        { id: 'up.eng.10.ch9', order: 9, title: 'Formal Writing — Letters, Reports, Notices', kgNodeIds: ['writing.formal_informal.letters'] },
        { id: 'up.eng.10.ch10', order: 10, title: 'Word Power — Vocabulary Building', kgNodeIds: ['vocabulary.idioms_phrases.fixed_expressions', 'vocabulary.word_formation.affixes'] },
        { id: 'up.eng.10.ch11', order: 11, title: 'Grammar — Error Correction and Editing', kgNodeIds: ['grammar.sentences.types_structure', 'grammar.punctuation.basics', 'grammar.articles.usage'] },
        { id: 'up.eng.10.ch12', order: 12, title: 'Speaking and Listening', kgNodeIds: ['communication.speaking.pronunciation', 'communication.listening.comprehension'] },
      ],
    },
    {
      grade: 11,
      chapters: [
        { id: 'up.eng.11.ch1', order: 1, title: 'Reading Comprehension — Factual and Literary', kgNodeIds: ['reading.comprehension_advanced.inference'] },
        { id: 'up.eng.11.ch2', order: 2, title: 'Reading Comprehension — Discursive Passages', kgNodeIds: ['reading.comprehension_advanced.inference', 'reading.strategies.skim_scan'] },
        { id: 'up.eng.11.ch3', order: 3, title: 'Note Making and Summarising', kgNodeIds: ['reading.strategies.skim_scan'] },
        { id: 'up.eng.11.ch4', order: 4, title: 'Prose — Hornbill (Main Textbook)', kgNodeIds: ['literature.prose.stories'] },
        { id: 'up.eng.11.ch5', order: 5, title: 'Prose — Snapshots (Supplementary Reader)', kgNodeIds: ['literature.prose.stories'] },
        { id: 'up.eng.11.ch6', order: 6, title: 'Poetry — Hornbill', kgNodeIds: ['literature.poetry.basic', 'literature.poetry.advanced'] },
        { id: 'up.eng.11.ch7', order: 7, title: 'Advanced Grammar — Clauses and Structures', kgNodeIds: ['grammar.clauses_phrases.clause_types'] },
        { id: 'up.eng.11.ch8', order: 8, title: 'Writing — Factual Description and Process', kgNodeIds: ['writing.essay_types.descriptive_narrative'] },
        { id: 'up.eng.11.ch9', order: 9, title: 'Writing — Analytical Paragraph', kgNodeIds: ['writing.formal_informal.advanced'] },
        { id: 'up.eng.11.ch10', order: 10, title: 'Writing — Report and Article', kgNodeIds: ['writing.formal_informal.letters', 'writing.formal_informal.advanced'] },
        { id: 'up.eng.11.ch11', order: 11, title: 'Academic Vocabulary and Word Study', kgNodeIds: ['vocabulary.academic.subject_specific'] },
        { id: 'up.eng.11.ch12', order: 12, title: 'Literary Analysis — Elements of Fiction', kgNodeIds: ['reading.literary_analysis.elements'] },
        { id: 'up.eng.11.ch13', order: 13, title: 'Debate and Discussion', kgNodeIds: ['communication.debate.discussion'] },
      ],
    },
    {
      grade: 12,
      chapters: [
        { id: 'up.eng.12.ch1', order: 1, title: 'Reading Comprehension — Unseen Prose', kgNodeIds: ['reading.comprehension_advanced.inference'] },
        { id: 'up.eng.12.ch2', order: 2, title: 'Reading Comprehension — Unseen Poetry', kgNodeIds: ['reading.comprehension_advanced.inference', 'literature.poetry.advanced'] },
        { id: 'up.eng.12.ch3', order: 3, title: 'Prose — Flamingo (Main Textbook)', kgNodeIds: ['literature.prose.advanced'] },
        { id: 'up.eng.12.ch4', order: 4, title: 'Prose — Vistas (Supplementary Reader)', kgNodeIds: ['literature.prose.advanced'] },
        { id: 'up.eng.12.ch5', order: 5, title: 'Poetry — Flamingo', kgNodeIds: ['literature.poetry.advanced'] },
        { id: 'up.eng.12.ch6', order: 6, title: 'Advanced Grammar — Error Correction', kgNodeIds: ['grammar.voice.active_passive', 'grammar.narration.direct_indirect', 'grammar.conditionals.types'] },
        { id: 'up.eng.12.ch7', order: 7, title: 'Writing — Argumentative Essay', kgNodeIds: ['writing.essay_types.expository_argumentative'] },
        { id: 'up.eng.12.ch8', order: 8, title: 'Writing — Speech and Debate', kgNodeIds: ['writing.formal_informal.advanced'] },
        { id: 'up.eng.12.ch9', order: 9, title: 'Writing — Email, Minutes and Press Release', kgNodeIds: ['writing.formal_informal.advanced'] },
        { id: 'up.eng.12.ch10', order: 10, title: 'Literary Analysis — Advanced Prose and Poetry', kgNodeIds: ['reading.literary_analysis.elements', 'literature.prose.advanced', 'literature.poetry.advanced'] },
        { id: 'up.eng.12.ch11', order: 11, title: 'Drama — Reading and Analysis', kgNodeIds: ['literature.drama.plays'] },
        { id: 'up.eng.12.ch12', order: 12, title: 'Academic Writing and Research Skills', kgNodeIds: ['vocabulary.academic.subject_specific', 'writing.essay_types.expository_argumentative'] },
      ],
    },
  ],
}

export function getUPEnglishChapters(grade: number) {
  return UP_ENGLISH_CATALOG.grades.find((g) => g.grade === grade)?.chapters ?? []
}
