import type { BoardSubjectCatalog } from './educationTypes'

export const UP_MATH_CATALOG: BoardSubjectCatalog = {
  boardId: 'up_board',
  subjectSlug: 'mathematics',
  subjectName: 'Mathematics',
  grades: [
    {
      grade: 5,
      chapters: [
        { id: 'up.math.5.ch1', order: 1, title: 'Numbers up to 9 Digits', kgNodeIds: ['arithmetic.counting_numbers'] },
        { id: 'up.math.5.ch2', order: 2, title: 'Addition and Subtraction', kgNodeIds: ['arithmetic.addition_subtraction'] },
        { id: 'up.math.5.ch3', order: 3, title: 'Multiplication', kgNodeIds: ['arithmetic.multiplication_division'] },
        { id: 'up.math.5.ch4', order: 4, title: 'Division', kgNodeIds: ['arithmetic.multiplication_division'] },
        { id: 'up.math.5.ch5', order: 5, title: 'Fractions', kgNodeIds: ['fractions.introduction'] },
        { id: 'up.math.5.ch6', order: 6, title: 'Decimals', kgNodeIds: ['decimals.introduction'] },
        { id: 'up.math.5.ch7', order: 7, title: 'Measurement — Length, Weight, Capacity', kgNodeIds: ['arithmetic.counting_numbers'] },
        { id: 'up.math.5.ch8', order: 8, title: 'Geometry — Shapes and Figures', kgNodeIds: ['geometry.basic_shapes'] },
        { id: 'up.math.5.ch9', order: 9, title: 'Perimeter and Area', kgNodeIds: ['mensuration.perimeter_area_2d'] },
        { id: 'up.math.5.ch10', order: 10, title: 'Data Handling', kgNodeIds: ['statistics.data_collection'] },
        { id: 'up.math.5.ch11', order: 11, title: 'Patterns and Symmetry', kgNodeIds: ['geometry.symmetry'] },
        { id: 'up.math.5.ch12', order: 12, title: 'Roman Numerals', kgNodeIds: ['arithmetic.counting_numbers'] },
      ],
    },
    {
      grade: 6,
      chapters: [
        { id: 'up.math.6.ch1', order: 1, title: 'Knowing Our Numbers', kgNodeIds: ['number_systems.whole_natural'] },
        { id: 'up.math.6.ch2', order: 2, title: 'Whole Numbers', kgNodeIds: ['number_systems.whole_natural'] },
        { id: 'up.math.6.ch3', order: 3, title: 'Playing with Numbers (LCM and HCF)', kgNodeIds: ['arithmetic.lcm_hcf'] },
        { id: 'up.math.6.ch4', order: 4, title: 'Basic Geometrical Ideas', kgNodeIds: ['geometry.basic_shapes'] },
        { id: 'up.math.6.ch5', order: 5, title: 'Understanding Elementary Shapes', kgNodeIds: ['geometry.basic_shapes'] },
        { id: 'up.math.6.ch6', order: 6, title: 'Integers', kgNodeIds: ['number_systems.integers'] },
        { id: 'up.math.6.ch7', order: 7, title: 'Fractions', kgNodeIds: ['fractions.introduction'] },
        { id: 'up.math.6.ch8', order: 8, title: 'Decimals', kgNodeIds: ['decimals.introduction'] },
        { id: 'up.math.6.ch9', order: 9, title: 'Data Handling', kgNodeIds: ['statistics.data_collection'] },
        { id: 'up.math.6.ch10', order: 10, title: 'Mensuration', kgNodeIds: ['mensuration.perimeter_area_2d'] },
        { id: 'up.math.6.ch11', order: 11, title: 'Algebra — Introduction', kgNodeIds: ['algebra.introduction'] },
        { id: 'up.math.6.ch12', order: 12, title: 'Ratio and Proportion', kgNodeIds: ['ratios_proportions.ratio_basics'] },
        { id: 'up.math.6.ch13', order: 13, title: 'Symmetry', kgNodeIds: ['geometry.symmetry'] },
        { id: 'up.math.6.ch14', order: 14, title: 'Practical Geometry', kgNodeIds: ['geometry.constructions'] },
      ],
    },
    {
      grade: 7,
      chapters: [
        { id: 'up.math.7.ch1', order: 1, title: 'Integers', kgNodeIds: ['number_systems.integers'] },
        { id: 'up.math.7.ch2', order: 2, title: 'Fractions and Decimals', kgNodeIds: ['fractions.operations', 'decimals.operations'] },
        { id: 'up.math.7.ch3', order: 3, title: 'Data Handling', kgNodeIds: ['statistics.data_collection'] },
        { id: 'up.math.7.ch4', order: 4, title: 'Simple Equations', kgNodeIds: ['algebra.linear_equations_1var'] },
        { id: 'up.math.7.ch5', order: 5, title: 'Lines and Angles', kgNodeIds: ['geometry.basic_shapes'] },
        { id: 'up.math.7.ch6', order: 6, title: 'The Triangle and Its Properties', kgNodeIds: ['geometry.triangles'] },
        { id: 'up.math.7.ch7', order: 7, title: 'Congruence of Triangles', kgNodeIds: ['geometry.triangles'] },
        { id: 'up.math.7.ch8', order: 8, title: 'Comparing Quantities', kgNodeIds: ['ratios_proportions.ratio_basics', 'percentages.basics'] },
        { id: 'up.math.7.ch9', order: 9, title: 'Rational Numbers', kgNodeIds: ['number_systems.rational'] },
        { id: 'up.math.7.ch10', order: 10, title: 'Practical Geometry', kgNodeIds: ['geometry.constructions'] },
        { id: 'up.math.7.ch11', order: 11, title: 'Perimeter and Area', kgNodeIds: ['mensuration.perimeter_area_2d'] },
        { id: 'up.math.7.ch12', order: 12, title: 'Algebraic Expressions', kgNodeIds: ['algebra.introduction'] },
        { id: 'up.math.7.ch13', order: 13, title: 'Exponents and Powers', kgNodeIds: ['exponents_powers.basics'] },
        { id: 'up.math.7.ch14', order: 14, title: 'Symmetry', kgNodeIds: ['geometry.symmetry'] },
        { id: 'up.math.7.ch15', order: 15, title: 'Visualising Solid Shapes', kgNodeIds: ['mensuration.surface_area_volume'] },
      ],
    },
    {
      grade: 8,
      chapters: [
        { id: 'up.math.8.ch1', order: 1, title: 'Rational Numbers', kgNodeIds: ['number_systems.rational'] },
        { id: 'up.math.8.ch2', order: 2, title: 'Linear Equations in One Variable', kgNodeIds: ['algebra.linear_equations_1var'] },
        { id: 'up.math.8.ch3', order: 3, title: 'Understanding Quadrilaterals', kgNodeIds: ['geometry.quadrilaterals'] },
        { id: 'up.math.8.ch4', order: 4, title: 'Practical Geometry', kgNodeIds: ['geometry.constructions'] },
        { id: 'up.math.8.ch5', order: 5, title: 'Data Handling', kgNodeIds: ['statistics.data_collection', 'statistics.central_tendency'] },
        { id: 'up.math.8.ch6', order: 6, title: 'Squares and Square Roots', kgNodeIds: ['exponents_powers.basics'] },
        { id: 'up.math.8.ch7', order: 7, title: 'Cubes and Cube Roots', kgNodeIds: ['exponents_powers.basics'] },
        { id: 'up.math.8.ch8', order: 8, title: 'Comparing Quantities', kgNodeIds: ['percentages.applications', 'percentages.interest'] },
        { id: 'up.math.8.ch9', order: 9, title: 'Algebraic Expressions and Identities', kgNodeIds: ['algebra.polynomials'] },
        { id: 'up.math.8.ch10', order: 10, title: 'Visualising Solid Shapes', kgNodeIds: ['mensuration.surface_area_volume'] },
        { id: 'up.math.8.ch11', order: 11, title: 'Mensuration', kgNodeIds: ['mensuration.surface_area_volume'] },
        { id: 'up.math.8.ch12', order: 12, title: 'Exponents and Powers', kgNodeIds: ['exponents_powers.basics'] },
        { id: 'up.math.8.ch13', order: 13, title: 'Direct and Inverse Proportions', kgNodeIds: ['ratios_proportions.ratio_basics'] },
        { id: 'up.math.8.ch14', order: 14, title: 'Factorisation', kgNodeIds: ['algebra.polynomials'] },
        { id: 'up.math.8.ch15', order: 15, title: 'Introduction to Graphs', kgNodeIds: ['coordinate_geometry.cartesian_plane'] },
        { id: 'up.math.8.ch16', order: 16, title: 'Playing with Numbers', kgNodeIds: ['arithmetic.lcm_hcf'] },
      ],
    },
    {
      grade: 9,
      chapters: [
        { id: 'up.math.9.ch1', order: 1, title: 'Number Systems', kgNodeIds: ['number_systems.real_irrational'] },
        { id: 'up.math.9.ch2', order: 2, title: 'Polynomials', kgNodeIds: ['algebra.polynomials'] },
        { id: 'up.math.9.ch3', order: 3, title: 'Coordinate Geometry', kgNodeIds: ['coordinate_geometry.cartesian_plane'] },
        { id: 'up.math.9.ch4', order: 4, title: 'Linear Equations in Two Variables', kgNodeIds: ['algebra.linear_equations_2var'] },
        { id: 'up.math.9.ch5', order: 5, title: 'Introduction to Euclid\'s Geometry', kgNodeIds: ['geometry.basic_shapes'] },
        { id: 'up.math.9.ch6', order: 6, title: 'Lines and Angles', kgNodeIds: ['geometry.basic_shapes'] },
        { id: 'up.math.9.ch7', order: 7, title: 'Triangles', kgNodeIds: ['geometry.triangles'] },
        { id: 'up.math.9.ch8', order: 8, title: 'Quadrilaterals', kgNodeIds: ['geometry.quadrilaterals'] },
        { id: 'up.math.9.ch9', order: 9, title: 'Areas of Parallelograms and Triangles', kgNodeIds: ['mensuration.perimeter_area_2d'] },
        { id: 'up.math.9.ch10', order: 10, title: 'Circles', kgNodeIds: ['geometry.circles'] },
        { id: 'up.math.9.ch11', order: 11, title: 'Constructions', kgNodeIds: ['geometry.constructions'] },
        { id: 'up.math.9.ch12', order: 12, title: 'Heron\'s Formula', kgNodeIds: ['mensuration.perimeter_area_2d'] },
        { id: 'up.math.9.ch13', order: 13, title: 'Surface Areas and Volumes', kgNodeIds: ['mensuration.surface_area_volume'] },
        { id: 'up.math.9.ch14', order: 14, title: 'Statistics', kgNodeIds: ['statistics.central_tendency'] },
        { id: 'up.math.9.ch15', order: 15, title: 'Probability', kgNodeIds: ['probability.basics'] },
      ],
    },
    {
      grade: 10,
      chapters: [
        { id: 'up.math.10.ch1', order: 1, title: 'Real Numbers', kgNodeIds: ['number_systems.real_irrational'] },
        { id: 'up.math.10.ch2', order: 2, title: 'Polynomials', kgNodeIds: ['algebra.polynomials'] },
        { id: 'up.math.10.ch3', order: 3, title: 'Pair of Linear Equations in Two Variables', kgNodeIds: ['algebra.linear_equations_2var'] },
        { id: 'up.math.10.ch4', order: 4, title: 'Quadratic Equations', kgNodeIds: ['algebra.quadratic_equations'] },
        { id: 'up.math.10.ch5', order: 5, title: 'Arithmetic Progressions', kgNodeIds: ['algebra.arithmetic_progressions'] },
        { id: 'up.math.10.ch6', order: 6, title: 'Triangles', kgNodeIds: ['geometry.similarity'] },
        { id: 'up.math.10.ch7', order: 7, title: 'Coordinate Geometry', kgNodeIds: ['coordinate_geometry.cartesian_plane'] },
        { id: 'up.math.10.ch8', order: 8, title: 'Introduction to Trigonometry', kgNodeIds: ['trigonometry.ratios_basics'] },
        { id: 'up.math.10.ch9', order: 9, title: 'Some Applications of Trigonometry', kgNodeIds: ['trigonometry.heights_distances'] },
        { id: 'up.math.10.ch10', order: 10, title: 'Circles', kgNodeIds: ['geometry.circles'] },
        { id: 'up.math.10.ch11', order: 11, title: 'Constructions', kgNodeIds: ['geometry.constructions'] },
        { id: 'up.math.10.ch12', order: 12, title: 'Areas Related to Circles', kgNodeIds: ['mensuration.perimeter_area_2d'] },
        { id: 'up.math.10.ch13', order: 13, title: 'Surface Areas and Volumes', kgNodeIds: ['mensuration.surface_area_volume'] },
        { id: 'up.math.10.ch14', order: 14, title: 'Statistics', kgNodeIds: ['statistics.central_tendency'] },
        { id: 'up.math.10.ch15', order: 15, title: 'Probability', kgNodeIds: ['probability.basics'] },
      ],
    },
    {
      grade: 11,
      chapters: [
        { id: 'up.math.11.ch1', order: 1, title: 'Sets', kgNodeIds: ['algebra.introduction'] },
        { id: 'up.math.11.ch2', order: 2, title: 'Relations and Functions', kgNodeIds: ['functions.introduction'] },
        { id: 'up.math.11.ch3', order: 3, title: 'Trigonometric Functions', kgNodeIds: ['trigonometry.functions_identities'] },
        { id: 'up.math.11.ch4', order: 4, title: 'Principle of Mathematical Induction', kgNodeIds: ['combinatorics.permutations_combinations'] },
        { id: 'up.math.11.ch5', order: 5, title: 'Complex Numbers and Quadratic Equations', kgNodeIds: ['algebra.quadratic_equations'] },
        { id: 'up.math.11.ch6', order: 6, title: 'Linear Inequalities', kgNodeIds: ['algebra.inequalities'] },
        { id: 'up.math.11.ch7', order: 7, title: 'Permutations and Combinations', kgNodeIds: ['combinatorics.permutations_combinations'] },
        { id: 'up.math.11.ch8', order: 8, title: 'Binomial Theorem', kgNodeIds: ['combinatorics.permutations_combinations'] },
        { id: 'up.math.11.ch9', order: 9, title: 'Sequences and Series', kgNodeIds: ['algebra.arithmetic_progressions'] },
        { id: 'up.math.11.ch10', order: 10, title: 'Straight Lines', kgNodeIds: ['coordinate_geometry.straight_lines'] },
        { id: 'up.math.11.ch11', order: 11, title: 'Conic Sections', kgNodeIds: ['coordinate_geometry.conics'] },
        { id: 'up.math.11.ch12', order: 12, title: 'Introduction to Three-Dimensional Geometry', kgNodeIds: ['coordinate_geometry.cartesian_plane'] },
        { id: 'up.math.11.ch13', order: 13, title: 'Limits and Derivatives', kgNodeIds: ['calculus.limits_continuity'] },
        { id: 'up.math.11.ch14', order: 14, title: 'Mathematical Reasoning', kgNodeIds: ['algebra.introduction'] },
        { id: 'up.math.11.ch15', order: 15, title: 'Statistics', kgNodeIds: ['statistics.dispersion'] },
        { id: 'up.math.11.ch16', order: 16, title: 'Probability', kgNodeIds: ['probability.advanced'] },
      ],
    },
    {
      grade: 12,
      chapters: [
        { id: 'up.math.12.ch1', order: 1, title: 'Relations and Functions', kgNodeIds: ['functions.inverse_composition'] },
        { id: 'up.math.12.ch2', order: 2, title: 'Inverse Trigonometric Functions', kgNodeIds: ['trigonometry.functions_identities'] },
        { id: 'up.math.12.ch3', order: 3, title: 'Matrices', kgNodeIds: ['matrices.basics'] },
        { id: 'up.math.12.ch4', order: 4, title: 'Determinants', kgNodeIds: ['matrices.basics'] },
        { id: 'up.math.12.ch5', order: 5, title: 'Continuity and Differentiability', kgNodeIds: ['calculus.differentiation'] },
        { id: 'up.math.12.ch6', order: 6, title: 'Application of Derivatives', kgNodeIds: ['calculus.applications_derivatives'] },
        { id: 'up.math.12.ch7', order: 7, title: 'Integrals', kgNodeIds: ['calculus.integration'] },
        { id: 'up.math.12.ch8', order: 8, title: 'Application of Integrals', kgNodeIds: ['calculus.integration'] },
        { id: 'up.math.12.ch9', order: 9, title: 'Differential Equations', kgNodeIds: ['calculus.differential_equations'] },
        { id: 'up.math.12.ch10', order: 10, title: 'Vector Algebra', kgNodeIds: ['vectors.basics'] },
        { id: 'up.math.12.ch11', order: 11, title: 'Three-Dimensional Geometry', kgNodeIds: ['coordinate_geometry.straight_lines'] },
        { id: 'up.math.12.ch12', order: 12, title: 'Linear Programming', kgNodeIds: ['algebra.inequalities'] },
        { id: 'up.math.12.ch13', order: 13, title: 'Probability', kgNodeIds: ['probability.advanced'] },
      ],
    },
  ],
}

export function getUPMathChapters(grade: number) {
  return UP_MATH_CATALOG.grades.find((g) => g.grade === grade)?.chapters ?? []
}

export function getUPMathChapter(id: string) {
  for (const grade of UP_MATH_CATALOG.grades) {
    const chapter = grade.chapters.find((c) => c.id === id)
    if (chapter) return chapter
  }
  return undefined
}
