import type { BoardSubjectCatalog } from './educationTypes'

export const UP_SCIENCE_CATALOG: BoardSubjectCatalog = {
  boardId: 'up_board',
  subjectSlug: 'science',
  subjectName: 'Science',
  grades: [
    {
      grade: 5,
      chapters: [
        { id: 'up.sci.5.ch1', order: 1, title: 'Plants — Our Green Friends', kgNodeIds: ['biology.plant_physiology.nutrition'] },
        { id: 'up.sci.5.ch2', order: 2, title: 'Animals — Habitat and Adaptation', kgNodeIds: ['biology.ecology.ecosystems'] },
        { id: 'up.sci.5.ch3', order: 3, title: 'Human Body', kgNodeIds: ['biology.animal_physiology.digestion'] },
        { id: 'up.sci.5.ch4', order: 4, title: 'Food and Nutrition', kgNodeIds: ['biology.animal_physiology.digestion'] },
        { id: 'up.sci.5.ch5', order: 5, title: 'Water and Its Uses', kgNodeIds: ['chemistry.matter_mixtures.matter'] },
        { id: 'up.sci.5.ch6', order: 6, title: 'Air — Properties and Uses', kgNodeIds: ['chemistry.matter_mixtures.matter'] },
        { id: 'up.sci.5.ch7', order: 7, title: 'Our Earth and the Solar System', kgNodeIds: ['earth_science.solar_system.planets'] },
        { id: 'up.sci.5.ch8', order: 8, title: 'Light and Shadow', kgNodeIds: ['physics.optics.reflection_refraction'] },
        { id: 'up.sci.5.ch9', order: 9, title: 'Forces and Simple Machines', kgNodeIds: ['physics.forces.laws_of_motion'] },
        { id: 'up.sci.5.ch10', order: 10, title: 'Environment and Pollution', kgNodeIds: ['environmental_science.pollution.types'] },
      ],
    },
    {
      grade: 6,
      chapters: [
        { id: 'up.sci.6.ch1', order: 1, title: 'Food — Where Does It Come From?', kgNodeIds: ['biology.plant_physiology.nutrition'] },
        { id: 'up.sci.6.ch2', order: 2, title: 'Components of Food', kgNodeIds: ['biology.animal_physiology.digestion'] },
        { id: 'up.sci.6.ch3', order: 3, title: 'Fibre to Fabric', kgNodeIds: ['chemistry.matter_mixtures.matter'] },
        { id: 'up.sci.6.ch4', order: 4, title: 'Sorting Materials into Groups', kgNodeIds: ['chemistry.matter_mixtures.matter'] },
        { id: 'up.sci.6.ch5', order: 5, title: 'Separation of Substances', kgNodeIds: ['chemistry.matter_mixtures.matter'] },
        { id: 'up.sci.6.ch6', order: 6, title: 'Changes Around Us', kgNodeIds: ['chemistry.chemical_reactions.equations'] },
        { id: 'up.sci.6.ch7', order: 7, title: 'Getting to Know Plants', kgNodeIds: ['biology.plant_physiology.nutrition'] },
        { id: 'up.sci.6.ch8', order: 8, title: 'Body Movements', kgNodeIds: ['biology.animal_physiology.digestion'] },
        { id: 'up.sci.6.ch9', order: 9, title: 'The Living Organisms — Characteristics and Habitats', kgNodeIds: ['biology.cell.structure'] },
        { id: 'up.sci.6.ch10', order: 10, title: 'Motion and Measurement of Distances', kgNodeIds: ['physics.kinematics.motion_1d'] },
        { id: 'up.sci.6.ch11', order: 11, title: 'Light, Shadows and Reflections', kgNodeIds: ['physics.optics.reflection_refraction'] },
        { id: 'up.sci.6.ch12', order: 12, title: 'Electricity and Circuits', kgNodeIds: ['physics.electricity.current_circuits'] },
        { id: 'up.sci.6.ch13', order: 13, title: 'Fun with Magnets', kgNodeIds: ['physics.magnetism.permanent'] },
        { id: 'up.sci.6.ch14', order: 14, title: 'Water', kgNodeIds: ['environmental_science.natural_resources.management'] },
        { id: 'up.sci.6.ch15', order: 15, title: 'Air Around Us', kgNodeIds: ['earth_science.climate_weather.atmosphere'] },
        { id: 'up.sci.6.ch16', order: 16, title: 'Garbage In, Garbage Out', kgNodeIds: ['environmental_science.pollution.types'] },
      ],
    },
    {
      grade: 7,
      chapters: [
        { id: 'up.sci.7.ch1', order: 1, title: 'Nutrition in Plants', kgNodeIds: ['biology.plant_physiology.nutrition'] },
        { id: 'up.sci.7.ch2', order: 2, title: 'Nutrition in Animals', kgNodeIds: ['biology.animal_physiology.digestion'] },
        { id: 'up.sci.7.ch3', order: 3, title: 'Fibre to Fabric', kgNodeIds: ['chemistry.matter_mixtures.matter'] },
        { id: 'up.sci.7.ch4', order: 4, title: 'Heat', kgNodeIds: ['physics.thermodynamics.heat_temperature'] },
        { id: 'up.sci.7.ch5', order: 5, title: 'Acids, Bases and Salts', kgNodeIds: ['chemistry.acids_bases_salts.basics'] },
        { id: 'up.sci.7.ch6', order: 6, title: 'Physical and Chemical Changes', kgNodeIds: ['chemistry.chemical_reactions.equations'] },
        { id: 'up.sci.7.ch7', order: 7, title: 'Weather, Climate and Adaptations', kgNodeIds: ['earth_science.climate_weather.atmosphere'] },
        { id: 'up.sci.7.ch8', order: 8, title: 'Winds, Storms and Cyclones', kgNodeIds: ['earth_science.climate_weather.atmosphere'] },
        { id: 'up.sci.7.ch9', order: 9, title: 'Soil', kgNodeIds: ['earth_science.earth_structure.layers'] },
        { id: 'up.sci.7.ch10', order: 10, title: 'Respiration in Organisms', kgNodeIds: ['biology.animal_physiology.respiration'] },
        { id: 'up.sci.7.ch11', order: 11, title: 'Transportation in Animals and Plants', kgNodeIds: ['biology.plant_physiology.transport', 'biology.animal_physiology.circulation'] },
        { id: 'up.sci.7.ch12', order: 12, title: 'Reproduction in Plants', kgNodeIds: ['biology.reproduction.plants_animals'] },
        { id: 'up.sci.7.ch13', order: 13, title: 'Motion and Time', kgNodeIds: ['physics.kinematics.motion_1d'] },
        { id: 'up.sci.7.ch14', order: 14, title: 'Electric Current and Its Effects', kgNodeIds: ['physics.electricity.current_circuits'] },
        { id: 'up.sci.7.ch15', order: 15, title: 'Light', kgNodeIds: ['physics.optics.reflection_refraction'] },
        { id: 'up.sci.7.ch16', order: 16, title: 'Water — A Precious Resource', kgNodeIds: ['environmental_science.natural_resources.management'] },
        { id: 'up.sci.7.ch17', order: 17, title: 'Forests — Our Lifeline', kgNodeIds: ['biology.ecology.ecosystems'] },
        { id: 'up.sci.7.ch18', order: 18, title: 'Wastewater Story', kgNodeIds: ['environmental_science.pollution.types'] },
      ],
    },
    {
      grade: 8,
      chapters: [
        { id: 'up.sci.8.ch1', order: 1, title: 'Crop Production and Management', kgNodeIds: ['biology.plant_physiology.nutrition'] },
        { id: 'up.sci.8.ch2', order: 2, title: 'Microorganisms — Friends and Foe', kgNodeIds: ['biology.taxonomy.classification'] },
        { id: 'up.sci.8.ch3', order: 3, title: 'Synthetic Fibres and Plastics', kgNodeIds: ['chemistry.organic_chemistry.basics'] },
        { id: 'up.sci.8.ch4', order: 4, title: 'Materials — Metals and Non-metals', kgNodeIds: ['chemistry.metals_nonmetals.reactivity'] },
        { id: 'up.sci.8.ch5', order: 5, title: 'Coal and Petroleum', kgNodeIds: ['chemistry.organic_chemistry.basics'] },
        { id: 'up.sci.8.ch6', order: 6, title: 'Combustion and Flame', kgNodeIds: ['chemistry.chemical_reactions.equations'] },
        { id: 'up.sci.8.ch7', order: 7, title: 'Conservation of Plants and Animals', kgNodeIds: ['environmental_science.conservation.biodiversity'] },
        { id: 'up.sci.8.ch8', order: 8, title: 'Cell — Structure and Functions', kgNodeIds: ['biology.cell.structure'] },
        { id: 'up.sci.8.ch9', order: 9, title: 'Reproduction in Animals', kgNodeIds: ['biology.reproduction.plants_animals'] },
        { id: 'up.sci.8.ch10', order: 10, title: 'Reaching the Age of Adolescence', kgNodeIds: ['biology.animal_physiology.nervous_endocrine'] },
        { id: 'up.sci.8.ch11', order: 11, title: 'Force and Pressure', kgNodeIds: ['physics.forces.laws_of_motion'] },
        { id: 'up.sci.8.ch12', order: 12, title: 'Friction', kgNodeIds: ['physics.forces.friction_circular'] },
        { id: 'up.sci.8.ch13', order: 13, title: 'Sound', kgNodeIds: ['physics.waves_oscillations.waves'] },
        { id: 'up.sci.8.ch14', order: 14, title: 'Chemical Effects of Electric Current', kgNodeIds: ['chemistry.electrochemistry.basics'] },
        { id: 'up.sci.8.ch15', order: 15, title: 'Some Natural Phenomena — Lightning and Earthquakes', kgNodeIds: ['earth_science.earth_structure.layers'] },
        { id: 'up.sci.8.ch16', order: 16, title: 'Light', kgNodeIds: ['physics.optics.reflection_refraction'] },
        { id: 'up.sci.8.ch17', order: 17, title: 'Stars and the Solar System', kgNodeIds: ['earth_science.solar_system.planets'] },
        { id: 'up.sci.8.ch18', order: 18, title: 'Pollution of Air and Water', kgNodeIds: ['environmental_science.pollution.types'] },
      ],
    },
    {
      grade: 9,
      chapters: [
        { id: 'up.sci.9.ch1', order: 1, title: 'Matter in Our Surroundings', kgNodeIds: ['chemistry.matter_mixtures.matter'] },
        { id: 'up.sci.9.ch2', order: 2, title: 'Is Matter Around Us Pure?', kgNodeIds: ['chemistry.matter_mixtures.solutions'] },
        { id: 'up.sci.9.ch3', order: 3, title: 'Atoms and Molecules', kgNodeIds: ['chemistry.atomic_structure.basics'] },
        { id: 'up.sci.9.ch4', order: 4, title: 'Structure of the Atom', kgNodeIds: ['chemistry.atomic_structure.basics'] },
        { id: 'up.sci.9.ch5', order: 5, title: 'The Fundamental Unit of Life', kgNodeIds: ['biology.cell.structure'] },
        { id: 'up.sci.9.ch6', order: 6, title: 'Tissues', kgNodeIds: ['biology.cell.structure'] },
        { id: 'up.sci.9.ch7', order: 7, title: 'Diversity in Living Organisms', kgNodeIds: ['biology.taxonomy.classification'] },
        { id: 'up.sci.9.ch8', order: 8, title: 'Motion', kgNodeIds: ['physics.kinematics.motion_1d'] },
        { id: 'up.sci.9.ch9', order: 9, title: 'Force and Laws of Motion', kgNodeIds: ['physics.forces.laws_of_motion'] },
        { id: 'up.sci.9.ch10', order: 10, title: 'Gravitation', kgNodeIds: ['physics.gravitation.universal'] },
        { id: 'up.sci.9.ch11', order: 11, title: 'Work and Energy', kgNodeIds: ['physics.work_energy.basics'] },
        { id: 'up.sci.9.ch12', order: 12, title: 'Sound', kgNodeIds: ['physics.waves_oscillations.waves'] },
        { id: 'up.sci.9.ch13', order: 13, title: 'Why Do We Fall Ill?', kgNodeIds: ['biology.reproduction.human_health'] },
        { id: 'up.sci.9.ch14', order: 14, title: 'Natural Resources', kgNodeIds: ['environmental_science.natural_resources.management'] },
        { id: 'up.sci.9.ch15', order: 15, title: 'Improvement in Food Resources', kgNodeIds: ['biology.plant_physiology.nutrition'] },
      ],
    },
    {
      grade: 10,
      chapters: [
        { id: 'up.sci.10.ch1', order: 1, title: 'Chemical Reactions and Equations', kgNodeIds: ['chemistry.chemical_reactions.equations'] },
        { id: 'up.sci.10.ch2', order: 2, title: 'Acids, Bases and Salts', kgNodeIds: ['chemistry.acids_bases_salts.basics'] },
        { id: 'up.sci.10.ch3', order: 3, title: 'Metals and Non-metals', kgNodeIds: ['chemistry.metals_nonmetals.reactivity'] },
        { id: 'up.sci.10.ch4', order: 4, title: 'Carbon and Its Compounds', kgNodeIds: ['chemistry.organic_chemistry.basics'] },
        { id: 'up.sci.10.ch5', order: 5, title: 'Periodic Classification of Elements', kgNodeIds: ['chemistry.periodic_table.trends'] },
        { id: 'up.sci.10.ch6', order: 6, title: 'Life Processes', kgNodeIds: ['biology.animal_physiology.digestion', 'biology.plant_physiology.nutrition'] },
        { id: 'up.sci.10.ch7', order: 7, title: 'Control and Coordination', kgNodeIds: ['biology.animal_physiology.nervous_endocrine'] },
        { id: 'up.sci.10.ch8', order: 8, title: 'How Do Organisms Reproduce?', kgNodeIds: ['biology.reproduction.plants_animals'] },
        { id: 'up.sci.10.ch9', order: 9, title: 'Heredity and Evolution', kgNodeIds: ['biology.genetics.mendel', 'biology.evolution.darwinism'] },
        { id: 'up.sci.10.ch10', order: 10, title: 'Light — Reflection and Refraction', kgNodeIds: ['physics.optics.reflection_refraction'] },
        { id: 'up.sci.10.ch11', order: 11, title: 'Human Eye and the Colourful World', kgNodeIds: ['physics.optics.human_eye'] },
        { id: 'up.sci.10.ch12', order: 12, title: 'Electricity', kgNodeIds: ['physics.electricity.current_circuits'] },
        { id: 'up.sci.10.ch13', order: 13, title: 'Magnetic Effects of Electric Current', kgNodeIds: ['physics.magnetism.moving_charges'] },
        { id: 'up.sci.10.ch14', order: 14, title: 'Sources of Energy', kgNodeIds: ['physics.work_energy.basics'] },
        { id: 'up.sci.10.ch15', order: 15, title: 'Our Environment', kgNodeIds: ['biology.ecology.ecosystems'] },
        { id: 'up.sci.10.ch16', order: 16, title: 'Sustainable Management of Natural Resources', kgNodeIds: ['environmental_science.natural_resources.management'] },
      ],
    },
    {
      grade: 11,
      chapters: [
        // Physics
        { id: 'up.sci.11.phy1', order: 1, title: '[Physics] Physical World and Measurement', kgNodeIds: ['physics.measurement.units'] },
        { id: 'up.sci.11.phy2', order: 2, title: '[Physics] Kinematics', kgNodeIds: ['physics.kinematics.motion_1d', 'physics.kinematics.motion_2d'] },
        { id: 'up.sci.11.phy3', order: 3, title: '[Physics] Laws of Motion', kgNodeIds: ['physics.forces.laws_of_motion'] },
        { id: 'up.sci.11.phy4', order: 4, title: '[Physics] Work, Energy and Power', kgNodeIds: ['physics.work_energy.basics'] },
        { id: 'up.sci.11.phy5', order: 5, title: '[Physics] Motion of System of Particles', kgNodeIds: ['physics.rotational_motion.torque_angular'] },
        { id: 'up.sci.11.phy6', order: 6, title: '[Physics] Gravitation', kgNodeIds: ['physics.gravitation.universal'] },
        { id: 'up.sci.11.phy7', order: 7, title: '[Physics] Properties of Bulk Matter', kgNodeIds: ['physics.mechanical_properties.solids_fluids'] },
        { id: 'up.sci.11.phy8', order: 8, title: '[Physics] Thermodynamics', kgNodeIds: ['physics.thermodynamics.laws'] },
        { id: 'up.sci.11.phy9', order: 9, title: '[Physics] Behaviour of Perfect Gas and Kinetic Theory', kgNodeIds: ['physics.thermodynamics.heat_temperature'] },
        { id: 'up.sci.11.phy10', order: 10, title: '[Physics] Oscillations and Waves', kgNodeIds: ['physics.waves_oscillations.shm', 'physics.waves_oscillations.waves'] },
        // Chemistry
        { id: 'up.sci.11.chem1', order: 11, title: '[Chemistry] Some Basic Concepts of Chemistry', kgNodeIds: ['chemistry.chemical_reactions.stoichiometry'] },
        { id: 'up.sci.11.chem2', order: 12, title: '[Chemistry] Structure of Atom', kgNodeIds: ['chemistry.atomic_structure.quantum'] },
        { id: 'up.sci.11.chem3', order: 13, title: '[Chemistry] Classification of Elements and Periodicity', kgNodeIds: ['chemistry.periodic_table.trends'] },
        { id: 'up.sci.11.chem4', order: 14, title: '[Chemistry] Chemical Bonding and Molecular Structure', kgNodeIds: ['chemistry.chemical_bonding.ionic_covalent'] },
        { id: 'up.sci.11.chem5', order: 15, title: '[Chemistry] States of Matter', kgNodeIds: ['chemistry.matter_mixtures.matter'] },
        { id: 'up.sci.11.chem6', order: 16, title: '[Chemistry] Thermodynamics', kgNodeIds: ['chemistry.thermochemistry.basics'] },
        { id: 'up.sci.11.chem7', order: 17, title: '[Chemistry] Equilibrium', kgNodeIds: ['chemistry.acids_bases_salts.equilibrium'] },
        { id: 'up.sci.11.chem8', order: 18, title: '[Chemistry] Redox Reactions', kgNodeIds: ['chemistry.chemical_reactions.equations'] },
        { id: 'up.sci.11.chem9', order: 19, title: '[Chemistry] Hydrogen', kgNodeIds: ['chemistry.metals_nonmetals.reactivity'] },
        { id: 'up.sci.11.chem10', order: 20, title: '[Chemistry] The s-Block Elements', kgNodeIds: ['chemistry.periodic_table.trends'] },
        { id: 'up.sci.11.chem11', order: 21, title: '[Chemistry] The p-Block Elements', kgNodeIds: ['chemistry.periodic_table.trends'] },
        { id: 'up.sci.11.chem12', order: 22, title: '[Chemistry] Organic Chemistry — Basic Principles', kgNodeIds: ['chemistry.organic_chemistry.basics'] },
        { id: 'up.sci.11.chem13', order: 23, title: '[Chemistry] Hydrocarbons', kgNodeIds: ['chemistry.organic_chemistry.basics'] },
        { id: 'up.sci.11.chem14', order: 24, title: '[Chemistry] Environmental Chemistry', kgNodeIds: ['chemistry.environmental_chemistry.pollution'] },
        // Biology
        { id: 'up.sci.11.bio1', order: 25, title: '[Biology] The Living World', kgNodeIds: ['biology.taxonomy.classification'] },
        { id: 'up.sci.11.bio2', order: 26, title: '[Biology] Biological Classification', kgNodeIds: ['biology.taxonomy.classification'] },
        { id: 'up.sci.11.bio3', order: 27, title: '[Biology] Plant Kingdom', kgNodeIds: ['biology.taxonomy.classification'] },
        { id: 'up.sci.11.bio4', order: 28, title: '[Biology] Animal Kingdom', kgNodeIds: ['biology.taxonomy.classification'] },
        { id: 'up.sci.11.bio5', order: 29, title: '[Biology] Morphology of Flowering Plants', kgNodeIds: ['biology.plant_physiology.nutrition'] },
        { id: 'up.sci.11.bio6', order: 30, title: '[Biology] Anatomy of Flowering Plants', kgNodeIds: ['biology.plant_physiology.transport'] },
        { id: 'up.sci.11.bio7', order: 31, title: '[Biology] Structural Organisation in Animals', kgNodeIds: ['biology.cell.structure'] },
        { id: 'up.sci.11.bio8', order: 32, title: '[Biology] Cell — The Unit of Life', kgNodeIds: ['biology.cell.structure'] },
        { id: 'up.sci.11.bio9', order: 33, title: '[Biology] Biomolecules', kgNodeIds: ['chemistry.biochemistry.biomolecules'] },
        { id: 'up.sci.11.bio10', order: 34, title: '[Biology] Cell Cycle and Cell Division', kgNodeIds: ['biology.cell.division'] },
        { id: 'up.sci.11.bio11', order: 35, title: '[Biology] Transport in Plants', kgNodeIds: ['biology.plant_physiology.transport'] },
        { id: 'up.sci.11.bio12', order: 36, title: '[Biology] Mineral Nutrition', kgNodeIds: ['biology.plant_physiology.nutrition'] },
        { id: 'up.sci.11.bio13', order: 37, title: '[Biology] Photosynthesis in Higher Plants', kgNodeIds: ['biology.plant_physiology.nutrition'] },
        { id: 'up.sci.11.bio14', order: 38, title: '[Biology] Respiration in Plants', kgNodeIds: ['biology.animal_physiology.respiration'] },
        { id: 'up.sci.11.bio15', order: 39, title: '[Biology] Plant Growth and Development', kgNodeIds: ['biology.plant_physiology.growth'] },
        { id: 'up.sci.11.bio16', order: 40, title: '[Biology] Digestion and Absorption', kgNodeIds: ['biology.animal_physiology.digestion'] },
        { id: 'up.sci.11.bio17', order: 41, title: '[Biology] Breathing and Exchange of Gases', kgNodeIds: ['biology.animal_physiology.respiration'] },
        { id: 'up.sci.11.bio18', order: 42, title: '[Biology] Body Fluids and Circulation', kgNodeIds: ['biology.animal_physiology.circulation'] },
        { id: 'up.sci.11.bio19', order: 43, title: '[Biology] Excretory Products and Their Elimination', kgNodeIds: ['biology.animal_physiology.excretion'] },
        { id: 'up.sci.11.bio20', order: 44, title: '[Biology] Locomotion and Movement', kgNodeIds: ['biology.animal_physiology.locomotion'] },
        { id: 'up.sci.11.bio21', order: 45, title: '[Biology] Neural Control and Coordination', kgNodeIds: ['biology.animal_physiology.nervous_endocrine'] },
        { id: 'up.sci.11.bio22', order: 46, title: '[Biology] Chemical Coordination and Integration', kgNodeIds: ['biology.animal_physiology.nervous_endocrine'] },
      ],
    },
    {
      grade: 12,
      chapters: [
        // Physics
        { id: 'up.sci.12.phy1', order: 1, title: '[Physics] Electrostatics', kgNodeIds: ['physics.electricity.electrostatics'] },
        { id: 'up.sci.12.phy2', order: 2, title: '[Physics] Current Electricity', kgNodeIds: ['physics.electricity.current_circuits'] },
        { id: 'up.sci.12.phy3', order: 3, title: '[Physics] Moving Charges and Magnetism', kgNodeIds: ['physics.magnetism.moving_charges'] },
        { id: 'up.sci.12.phy4', order: 4, title: '[Physics] Magnetism and Matter', kgNodeIds: ['physics.magnetism.permanent'] },
        { id: 'up.sci.12.phy5', order: 5, title: '[Physics] Electromagnetic Induction', kgNodeIds: ['physics.electricity.electromagnetic_induction'] },
        { id: 'up.sci.12.phy6', order: 6, title: '[Physics] Alternating Current', kgNodeIds: ['physics.electricity.electromagnetic_induction'] },
        { id: 'up.sci.12.phy7', order: 7, title: '[Physics] Electromagnetic Waves', kgNodeIds: ['physics.waves_oscillations.waves'] },
        { id: 'up.sci.12.phy8', order: 8, title: '[Physics] Ray Optics and Optical Instruments', kgNodeIds: ['physics.optics.human_eye'] },
        { id: 'up.sci.12.phy9', order: 9, title: '[Physics] Wave Optics', kgNodeIds: ['physics.optics.wave_optics'] },
        { id: 'up.sci.12.phy10', order: 10, title: '[Physics] Dual Nature of Radiation and Matter', kgNodeIds: ['physics.modern_physics.dual_nature'] },
        { id: 'up.sci.12.phy11', order: 11, title: '[Physics] Atoms', kgNodeIds: ['physics.modern_physics.atoms_nuclei'] },
        { id: 'up.sci.12.phy12', order: 12, title: '[Physics] Nuclei', kgNodeIds: ['physics.modern_physics.atoms_nuclei'] },
        { id: 'up.sci.12.phy13', order: 13, title: '[Physics] Semiconductor Electronics', kgNodeIds: ['physics.semiconductors.devices'] },
        { id: 'up.sci.12.phy14', order: 14, title: '[Physics] Communication Systems', kgNodeIds: ['physics.semiconductors.devices'] },
        // Chemistry
        { id: 'up.sci.12.chem1', order: 15, title: '[Chemistry] The Solid State', kgNodeIds: ['chemistry.matter_mixtures.matter'] },
        { id: 'up.sci.12.chem2', order: 16, title: '[Chemistry] Solutions', kgNodeIds: ['chemistry.matter_mixtures.solutions'] },
        { id: 'up.sci.12.chem3', order: 17, title: '[Chemistry] Electrochemistry', kgNodeIds: ['chemistry.electrochemistry.basics'] },
        { id: 'up.sci.12.chem4', order: 18, title: '[Chemistry] Chemical Kinetics', kgNodeIds: ['chemistry.chemical_reactions.stoichiometry'] },
        { id: 'up.sci.12.chem5', order: 19, title: '[Chemistry] Surface Chemistry', kgNodeIds: ['chemistry.matter_mixtures.solutions'] },
        { id: 'up.sci.12.chem6', order: 20, title: '[Chemistry] General Principles of Isolation of Elements', kgNodeIds: ['chemistry.metals_nonmetals.reactivity'] },
        { id: 'up.sci.12.chem7', order: 21, title: '[Chemistry] The p-Block Elements', kgNodeIds: ['chemistry.periodic_table.trends'] },
        { id: 'up.sci.12.chem8', order: 22, title: '[Chemistry] The d and f Block Elements', kgNodeIds: ['chemistry.periodic_table.trends'] },
        { id: 'up.sci.12.chem9', order: 23, title: '[Chemistry] Coordination Compounds', kgNodeIds: ['chemistry.chemical_bonding.ionic_covalent'] },
        { id: 'up.sci.12.chem10', order: 24, title: '[Chemistry] Haloalkanes and Haloarenes', kgNodeIds: ['chemistry.organic_chemistry.reactions'] },
        { id: 'up.sci.12.chem11', order: 25, title: '[Chemistry] Alcohols, Phenols and Ethers', kgNodeIds: ['chemistry.organic_chemistry.reactions'] },
        { id: 'up.sci.12.chem12', order: 26, title: '[Chemistry] Aldehydes, Ketones and Carboxylic Acids', kgNodeIds: ['chemistry.organic_chemistry.reactions'] },
        { id: 'up.sci.12.chem13', order: 27, title: '[Chemistry] Organic Compounds Containing Nitrogen', kgNodeIds: ['chemistry.organic_chemistry.reactions'] },
        { id: 'up.sci.12.chem14', order: 28, title: '[Chemistry] Biomolecules', kgNodeIds: ['chemistry.biochemistry.biomolecules'] },
        { id: 'up.sci.12.chem15', order: 29, title: '[Chemistry] Polymers', kgNodeIds: ['chemistry.organic_chemistry.reactions'] },
        { id: 'up.sci.12.chem16', order: 30, title: '[Chemistry] Chemistry in Everyday Life', kgNodeIds: ['chemistry.biochemistry.biomolecules'] },
        // Biology
        { id: 'up.sci.12.bio1', order: 31, title: '[Biology] Reproduction in Organisms', kgNodeIds: ['biology.reproduction.plants_animals'] },
        { id: 'up.sci.12.bio2', order: 32, title: '[Biology] Sexual Reproduction in Flowering Plants', kgNodeIds: ['biology.reproduction.plants_animals'] },
        { id: 'up.sci.12.bio3', order: 33, title: '[Biology] Human Reproduction', kgNodeIds: ['biology.reproduction.plants_animals'] },
        { id: 'up.sci.12.bio4', order: 34, title: '[Biology] Reproductive Health', kgNodeIds: ['biology.reproduction.human_health'] },
        { id: 'up.sci.12.bio5', order: 35, title: '[Biology] Principles of Inheritance and Variation', kgNodeIds: ['biology.genetics.mendel'] },
        { id: 'up.sci.12.bio6', order: 36, title: '[Biology] Molecular Basis of Inheritance', kgNodeIds: ['biology.genetics.molecular'] },
        { id: 'up.sci.12.bio7', order: 37, title: '[Biology] Evolution', kgNodeIds: ['biology.evolution.darwinism'] },
        { id: 'up.sci.12.bio8', order: 38, title: '[Biology] Human Health and Disease', kgNodeIds: ['biology.reproduction.human_health'] },
        { id: 'up.sci.12.bio9', order: 39, title: '[Biology] Strategies for Enhancement in Food Production', kgNodeIds: ['biology.biotechnology.basics'] },
        { id: 'up.sci.12.bio10', order: 40, title: '[Biology] Microbes in Human Welfare', kgNodeIds: ['biology.taxonomy.classification'] },
        { id: 'up.sci.12.bio11', order: 41, title: '[Biology] Biotechnology — Principles and Processes', kgNodeIds: ['biology.biotechnology.basics'] },
        { id: 'up.sci.12.bio12', order: 42, title: '[Biology] Biotechnology and Its Applications', kgNodeIds: ['biology.biotechnology.basics'] },
        { id: 'up.sci.12.bio13', order: 43, title: '[Biology] Organisms and Populations', kgNodeIds: ['biology.ecology.ecosystems'] },
        { id: 'up.sci.12.bio14', order: 44, title: '[Biology] Ecosystem', kgNodeIds: ['biology.ecology.ecosystems'] },
        { id: 'up.sci.12.bio15', order: 45, title: '[Biology] Biodiversity and Conservation', kgNodeIds: ['environmental_science.conservation.biodiversity'] },
        { id: 'up.sci.12.bio16', order: 46, title: '[Biology] Environmental Issues', kgNodeIds: ['environmental_science.pollution.types'] },
      ],
    },
  ],
}

export function getUPScienceChapters(grade: number) {
  return UP_SCIENCE_CATALOG.grades.find((g) => g.grade === grade)?.chapters ?? []
}
