import type { BoardSubjectCatalog } from './educationTypes'

export const UP_SOCIAL_SCIENCE_CATALOG: BoardSubjectCatalog = {
  boardId: 'up_board',
  subjectSlug: 'social_science',
  subjectName: 'Social Science',
  grades: [
    {
      grade: 5,
      chapters: [
        { id: 'up.sst.5.ch1', order: 1, title: 'Our Earth — Shape and Movements', kgNodeIds: ['geography.earth_globe.basics'] },
        { id: 'up.sst.5.ch2', order: 2, title: 'Maps and Directions', kgNodeIds: ['geography.maps.reading'] },
        { id: 'up.sst.5.ch3', order: 3, title: 'Our Country India', kgNodeIds: ['geography.india_physical.relief_drainage'] },
        { id: 'up.sst.5.ch4', order: 4, title: 'Our Family and Community', kgNodeIds: ['society.social_institutions.family'] },
        { id: 'up.sst.5.ch5', order: 5, title: 'Our Government — Gram Panchayat', kgNodeIds: ['civics.government_systems.democracy'] },
        { id: 'up.sst.5.ch6', order: 6, title: 'Ancient Civilisations', kgNodeIds: ['history.ancient_india.harappan'] },
        { id: 'up.sst.5.ch7', order: 7, title: 'Our Needs and Resources', kgNodeIds: ['economics.basic_economics.wants_scarcity'] },
        { id: 'up.sst.5.ch8', order: 8, title: 'Festivals and Traditions', kgNodeIds: ['society.social_institutions.family'] },
      ],
    },
    {
      grade: 6,
      chapters: [
        { id: 'up.sst.6.ch1', order: 1, title: 'The Earth and Its Movements', kgNodeIds: ['geography.earth_globe.basics'] },
        { id: 'up.sst.6.ch2', order: 2, title: 'Globe and Maps', kgNodeIds: ['geography.maps.reading'] },
        { id: 'up.sst.6.ch3', order: 3, title: 'Major Landforms', kgNodeIds: ['geography.earth_globe.landforms'] },
        { id: 'up.sst.6.ch4', order: 4, title: 'The Harappan Civilisation', kgNodeIds: ['history.ancient_india.harappan'] },
        { id: 'up.sst.6.ch5', order: 5, title: 'Vedic Period', kgNodeIds: ['history.ancient_india.vedic_period'] },
        { id: 'up.sst.6.ch6', order: 6, title: 'Early Kingdoms and Mahajanapadas', kgNodeIds: ['history.ancient_india.vedic_period'] },
        { id: 'up.sst.6.ch7', order: 7, title: 'Our Government and Democracy', kgNodeIds: ['civics.government_systems.democracy'] },
        { id: 'up.sst.6.ch8', order: 8, title: 'Local Self-Government', kgNodeIds: ['civics.local_government.panchayati_raj'] },
        { id: 'up.sst.6.ch9', order: 9, title: 'Wants, Needs and Economic Activities', kgNodeIds: ['economics.basic_economics.wants_scarcity'] },
        { id: 'up.sst.6.ch10', order: 10, title: 'Family and Social Life', kgNodeIds: ['society.social_institutions.family'] },
      ],
    },
    {
      grade: 7,
      chapters: [
        { id: 'up.sst.7.ch1', order: 1, title: 'Inside the Earth — Structure', kgNodeIds: ['geography.earth_globe.landforms'] },
        { id: 'up.sst.7.ch2', order: 2, title: 'Climates of the World', kgNodeIds: ['geography.world_physical.climate_biomes'] },
        { id: 'up.sst.7.ch3', order: 3, title: 'Natural Vegetation and Wildlife', kgNodeIds: ['geography.world_physical.climate_biomes'] },
        { id: 'up.sst.7.ch4', order: 4, title: 'Maurya and Gupta Empires', kgNodeIds: ['history.ancient_india.maurya_gupta'] },
        { id: 'up.sst.7.ch5', order: 5, title: 'Buddhism and Jainism', kgNodeIds: ['history.ancient_india.buddhism_jainism'] },
        { id: 'up.sst.7.ch6', order: 6, title: 'Delhi Sultanate', kgNodeIds: ['history.medieval_india.delhi_sultanate'] },
        { id: 'up.sst.7.ch7', order: 7, title: 'The Indian Constitution — Rights', kgNodeIds: ['civics.constitution.rights_duties'] },
        { id: 'up.sst.7.ch8', order: 8, title: 'Panchayati Raj', kgNodeIds: ['civics.local_government.panchayati_raj'] },
        { id: 'up.sst.7.ch9', order: 9, title: 'Sectors of the Economy', kgNodeIds: ['economics.indian_economy.sectors'] },
        { id: 'up.sst.7.ch10', order: 10, title: 'Social Inequality and Marginalisation', kgNodeIds: ['society.social_inequality.gender_caste'] },
        { id: 'up.sst.7.ch11', order: 11, title: 'Human Environment and Settlement', kgNodeIds: ['geography.human_geography.population'] },
      ],
    },
    {
      grade: 8,
      chapters: [
        { id: 'up.sst.8.ch1', order: 1, title: 'Resources — Types and Conservation', kgNodeIds: ['geography.india_resources.minerals_energy'] },
        { id: 'up.sst.8.ch2', order: 2, title: 'Land Use and Agriculture', kgNodeIds: ['geography.india_resources.agriculture'] },
        { id: 'up.sst.8.ch3', order: 3, title: 'Mughal Empire', kgNodeIds: ['history.medieval_india.mughal_empire'] },
        { id: 'up.sst.8.ch4', order: 4, title: 'Regional Kingdoms and Culture', kgNodeIds: ['history.medieval_india.regional_kingdoms'] },
        { id: 'up.sst.8.ch5', order: 5, title: 'British Rule in India', kgNodeIds: ['history.modern_india.colonial_period'] },
        { id: 'up.sst.8.ch6', order: 6, title: 'The Indian Parliament', kgNodeIds: ['civics.national_government.parliament'] },
        { id: 'up.sst.8.ch7', order: 7, title: 'Understanding Laws and the Judiciary', kgNodeIds: ['civics.national_government.executive_judiciary'] },
        { id: 'up.sst.8.ch8', order: 8, title: 'Poverty and Development', kgNodeIds: ['economics.development.poverty'] },
        { id: 'up.sst.8.ch9', order: 9, title: 'Social Reform Movements', kgNodeIds: ['society.social_change.reform'] },
        { id: 'up.sst.8.ch10', order: 10, title: 'Industries and Transport in India', kgNodeIds: ['geography.india_resources.industries_transport'] },
      ],
    },
    {
      grade: 9,
      chapters: [
        { id: 'up.sst.9.hist1', order: 1, title: '[History] French Revolution', kgNodeIds: ['history.world_history.french_revolution'] },
        { id: 'up.sst.9.hist2', order: 2, title: '[History] Russian Revolution and Socialism', kgNodeIds: ['history.world_history.industrialisation'] },
        { id: 'up.sst.9.hist3', order: 3, title: '[History] Nazism and the Rise of Hitler', kgNodeIds: ['history.world_history.world_wars'] },
        { id: 'up.sst.9.hist4', order: 4, title: '[History] Forest Society and Colonialism', kgNodeIds: ['history.modern_india.colonial_period'] },
        { id: 'up.sst.9.hist5', order: 5, title: '[History] Pastoralists in the Modern World', kgNodeIds: ['history.modern_india.colonial_period'] },
        { id: 'up.sst.9.geo1', order: 6, title: '[Geography] India — Size and Location', kgNodeIds: ['geography.india_physical.relief_drainage'] },
        { id: 'up.sst.9.geo2', order: 7, title: '[Geography] Physical Features of India', kgNodeIds: ['geography.india_physical.relief_drainage'] },
        { id: 'up.sst.9.geo3', order: 8, title: '[Geography] Drainage — Rivers and Lakes', kgNodeIds: ['geography.india_physical.relief_drainage'] },
        { id: 'up.sst.9.geo4', order: 9, title: '[Geography] Climate of India', kgNodeIds: ['geography.india_physical.climate_vegetation'] },
        { id: 'up.sst.9.geo5', order: 10, title: '[Geography] Natural Vegetation and Wildlife', kgNodeIds: ['geography.india_physical.climate_vegetation'] },
        { id: 'up.sst.9.geo6', order: 11, title: '[Geography] Population', kgNodeIds: ['geography.human_geography.population'] },
        { id: 'up.sst.9.civ1', order: 12, title: '[Civics] What is Democracy? Why Democracy?', kgNodeIds: ['civics.government_systems.democracy'] },
        { id: 'up.sst.9.civ2', order: 13, title: '[Civics] Constitutional Design', kgNodeIds: ['civics.constitution.rights_duties'] },
        { id: 'up.sst.9.civ3', order: 14, title: '[Civics] Electoral Politics', kgNodeIds: ['civics.national_government.parliament'] },
        { id: 'up.sst.9.civ4', order: 15, title: '[Civics] Working of Institutions', kgNodeIds: ['civics.national_government.executive_judiciary'] },
        { id: 'up.sst.9.civ5', order: 16, title: '[Civics] Democratic Rights', kgNodeIds: ['civics.constitution.rights_duties'] },
        { id: 'up.sst.9.eco1', order: 17, title: '[Economics] The Story of Village Palampur', kgNodeIds: ['economics.indian_economy.sectors'] },
        { id: 'up.sst.9.eco2', order: 18, title: '[Economics] People as Resource', kgNodeIds: ['economics.development.poverty'] },
        { id: 'up.sst.9.eco3', order: 19, title: '[Economics] Poverty as a Challenge', kgNodeIds: ['economics.development.poverty'] },
        { id: 'up.sst.9.eco4', order: 20, title: '[Economics] Food Security in India', kgNodeIds: ['economics.development.poverty'] },
      ],
    },
    {
      grade: 10,
      chapters: [
        { id: 'up.sst.10.hist1', order: 1, title: '[History] The Rise of Nationalism in Europe', kgNodeIds: ['history.world_history.french_revolution'] },
        { id: 'up.sst.10.hist2', order: 2, title: '[History] Nationalism in India', kgNodeIds: ['history.modern_india.independence_movement'] },
        { id: 'up.sst.10.hist3', order: 3, title: '[History] The Making of a Global World', kgNodeIds: ['history.world_history.industrialisation'] },
        { id: 'up.sst.10.hist4', order: 4, title: '[History] The Age of Industrialisation', kgNodeIds: ['history.world_history.industrialisation'] },
        { id: 'up.sst.10.hist5', order: 5, title: '[History] Print Culture and the Modern World', kgNodeIds: ['history.world_history.industrialisation'] },
        { id: 'up.sst.10.geo1', order: 6, title: '[Geography] Resources and Development', kgNodeIds: ['geography.india_resources.agriculture'] },
        { id: 'up.sst.10.geo2', order: 7, title: '[Geography] Forest and Wildlife Resources', kgNodeIds: ['geography.india_physical.climate_vegetation'] },
        { id: 'up.sst.10.geo3', order: 8, title: '[Geography] Water Resources', kgNodeIds: ['geography.india_resources.agriculture'] },
        { id: 'up.sst.10.geo4', order: 9, title: '[Geography] Agriculture in India', kgNodeIds: ['geography.india_resources.agriculture'] },
        { id: 'up.sst.10.geo5', order: 10, title: '[Geography] Minerals and Energy Resources', kgNodeIds: ['geography.india_resources.minerals_energy'] },
        { id: 'up.sst.10.geo6', order: 11, title: '[Geography] Manufacturing Industries', kgNodeIds: ['geography.india_resources.industries_transport'] },
        { id: 'up.sst.10.geo7', order: 12, title: '[Geography] Lifelines of National Economy', kgNodeIds: ['geography.india_resources.industries_transport'] },
        { id: 'up.sst.10.civ1', order: 13, title: '[Civics] Power Sharing', kgNodeIds: ['civics.constitution.federalism'] },
        { id: 'up.sst.10.civ2', order: 14, title: '[Civics] Federalism', kgNodeIds: ['civics.constitution.federalism'] },
        { id: 'up.sst.10.civ3', order: 15, title: '[Civics] Democracy and Diversity', kgNodeIds: ['civics.government_systems.democracy'] },
        { id: 'up.sst.10.civ4', order: 16, title: '[Civics] Gender, Religion and Caste', kgNodeIds: ['society.social_inequality.gender_caste'] },
        { id: 'up.sst.10.civ5', order: 17, title: '[Civics] Popular Struggles and Movements', kgNodeIds: ['civics.constitution.rights_duties'] },
        { id: 'up.sst.10.civ6', order: 18, title: '[Civics] Political Parties', kgNodeIds: ['civics.national_government.parliament'] },
        { id: 'up.sst.10.civ7', order: 19, title: '[Civics] Outcomes of Democracy', kgNodeIds: ['civics.government_systems.democracy'] },
        { id: 'up.sst.10.civ8', order: 20, title: '[Civics] Challenges to Democracy', kgNodeIds: ['civics.government_systems.democracy'] },
        { id: 'up.sst.10.eco1', order: 21, title: '[Economics] Development', kgNodeIds: ['economics.development.poverty'] },
        { id: 'up.sst.10.eco2', order: 22, title: '[Economics] Sectors of the Indian Economy', kgNodeIds: ['economics.indian_economy.sectors'] },
        { id: 'up.sst.10.eco3', order: 23, title: '[Economics] Money and Credit', kgNodeIds: ['economics.money_banking.currency'] },
        { id: 'up.sst.10.eco4', order: 24, title: '[Economics] Globalisation and the Indian Economy', kgNodeIds: ['economics.globalisation.trade'] },
        { id: 'up.sst.10.eco5', order: 25, title: '[Economics] Consumer Rights', kgNodeIds: ['economics.markets.supply_demand'] },
      ],
    },
    {
      grade: 11,
      chapters: [
        { id: 'up.sst.11.hist1', order: 1, title: '[History] From the Beginning of Time', kgNodeIds: ['history.ancient_world.greece_rome'] },
        { id: 'up.sst.11.hist2', order: 2, title: '[History] Early Societies — Writing and City Life', kgNodeIds: ['history.ancient_india.harappan'] },
        { id: 'up.sst.11.hist3', order: 3, title: '[History] An Empire Across Three Continents (Rome)', kgNodeIds: ['history.ancient_world.greece_rome'] },
        { id: 'up.sst.11.hist4', order: 4, title: '[History] The Central Islamic Lands', kgNodeIds: ['history.medieval_india.delhi_sultanate'] },
        { id: 'up.sst.11.hist5', order: 5, title: '[History] Nomadic Empires', kgNodeIds: ['history.medieval_india.mughal_empire'] },
        { id: 'up.sst.11.hist6', order: 6, title: '[History] The Three Orders (Medieval Europe)', kgNodeIds: ['history.world_history.french_revolution'] },
        { id: 'up.sst.11.hist7', order: 7, title: '[History] Changing Cultural Traditions — Renaissance', kgNodeIds: ['history.world_history.french_revolution'] },
        { id: 'up.sst.11.hist8', order: 8, title: '[History] Confrontation of Cultures — Colonialism', kgNodeIds: ['history.world_history.industrialisation'] },
        { id: 'up.sst.11.hist9', order: 9, title: '[History] The Industrial Revolution', kgNodeIds: ['history.world_history.industrialisation'] },
        { id: 'up.sst.11.hist10', order: 10, title: '[History] Displacing Indigenous Peoples', kgNodeIds: ['history.world_history.industrialisation'] },
        { id: 'up.sst.11.hist11', order: 11, title: '[History] Paths to Modernisation', kgNodeIds: ['history.world_history.world_wars'] },
        { id: 'up.sst.11.geo1', order: 12, title: '[Geography] Geography as a Discipline', kgNodeIds: ['geography.earth_globe.basics'] },
        { id: 'up.sst.11.geo2', order: 13, title: '[Geography] The Origin and Evolution of the Earth', kgNodeIds: ['geography.earth_globe.landforms'] },
        { id: 'up.sst.11.geo3', order: 14, title: '[Geography] Interior of the Earth', kgNodeIds: ['geography.earth_globe.landforms'] },
        { id: 'up.sst.11.geo4', order: 15, title: '[Geography] Distribution of Oceans and Continents', kgNodeIds: ['geography.earth_globe.landforms'] },
        { id: 'up.sst.11.geo5', order: 16, title: '[Geography] Minerals and Rocks', kgNodeIds: ['geography.india_resources.minerals_energy'] },
        { id: 'up.sst.11.geo6', order: 17, title: '[Geography] Geomorphic Processes', kgNodeIds: ['geography.earth_globe.landforms'] },
        { id: 'up.sst.11.geo7', order: 18, title: '[Geography] Landforms and Their Evolution', kgNodeIds: ['geography.earth_globe.landforms'] },
        { id: 'up.sst.11.geo8', order: 19, title: '[Geography] Atmosphere — Composition and Structure', kgNodeIds: ['geography.world_physical.climate_biomes'] },
        { id: 'up.sst.11.geo9', order: 20, title: '[Geography] Solar Radiation, Heat Balance and Temperature', kgNodeIds: ['geography.world_physical.climate_biomes'] },
        { id: 'up.sst.11.geo10', order: 21, title: '[Geography] Atmospheric Circulation and Weather Systems', kgNodeIds: ['geography.world_physical.climate_biomes'] },
        { id: 'up.sst.11.geo11', order: 22, title: '[Geography] Water in the Atmosphere', kgNodeIds: ['geography.world_physical.climate_biomes'] },
        { id: 'up.sst.11.geo12', order: 23, title: '[Geography] World Climate and Climate Change', kgNodeIds: ['geography.world_physical.climate_biomes'] },
        { id: 'up.sst.11.geo13', order: 24, title: '[Geography] Water (Oceans)', kgNodeIds: ['geography.earth_globe.landforms'] },
        { id: 'up.sst.11.geo14', order: 25, title: '[Geography] Movements of Ocean Water', kgNodeIds: ['geography.earth_globe.landforms'] },
        { id: 'up.sst.11.geo15', order: 26, title: '[Geography] Life on the Earth', kgNodeIds: ['geography.world_physical.climate_biomes'] },
        { id: 'up.sst.11.pol1', order: 27, title: '[Political Science] Political Theory — An Introduction', kgNodeIds: ['civics.government_systems.democracy'] },
        { id: 'up.sst.11.pol2', order: 28, title: '[Political Science] Freedom', kgNodeIds: ['civics.constitution.rights_duties'] },
        { id: 'up.sst.11.pol3', order: 29, title: '[Political Science] Equality', kgNodeIds: ['civics.constitution.rights_duties'] },
        { id: 'up.sst.11.pol4', order: 30, title: '[Political Science] Social Justice', kgNodeIds: ['society.social_inequality.gender_caste'] },
        { id: 'up.sst.11.pol5', order: 31, title: '[Political Science] Rights', kgNodeIds: ['civics.constitution.rights_duties'] },
        { id: 'up.sst.11.pol6', order: 32, title: '[Political Science] Citizenship', kgNodeIds: ['civics.constitution.rights_duties'] },
        { id: 'up.sst.11.pol7', order: 33, title: '[Political Science] Nationalism', kgNodeIds: ['history.post_independence.constitution'] },
        { id: 'up.sst.11.pol8', order: 34, title: '[Political Science] Secularism', kgNodeIds: ['civics.constitution.rights_duties'] },
        { id: 'up.sst.11.pol9', order: 35, title: '[Political Science] Peace', kgNodeIds: ['civics.international_relations.un'] },
        { id: 'up.sst.11.pol10', order: 36, title: '[Political Science] Development', kgNodeIds: ['geography.human_geography.development'] },
        { id: 'up.sst.11.eco1', order: 37, title: '[Economics] Introduction to Statistics', kgNodeIds: ['economics.statistics.data'] },
        { id: 'up.sst.11.eco2', order: 38, title: '[Economics] Collection of Data', kgNodeIds: ['economics.statistics.data'] },
        { id: 'up.sst.11.eco3', order: 39, title: '[Economics] Organisation of Data', kgNodeIds: ['economics.statistics.data'] },
        { id: 'up.sst.11.eco4', order: 40, title: '[Economics] Presentation of Data', kgNodeIds: ['economics.statistics.data'] },
        { id: 'up.sst.11.eco5', order: 41, title: '[Economics] Measures of Central Tendency', kgNodeIds: ['economics.statistics.data'] },
        { id: 'up.sst.11.eco6', order: 42, title: '[Economics] Measures of Dispersion', kgNodeIds: ['economics.statistics.data'] },
        { id: 'up.sst.11.eco7', order: 43, title: '[Economics] Correlation', kgNodeIds: ['economics.statistics.data'] },
        { id: 'up.sst.11.eco8', order: 44, title: '[Economics] Index Numbers', kgNodeIds: ['economics.statistics.data'] },
        { id: 'up.sst.11.eco9', order: 45, title: '[Economics] Use of Statistical Tools', kgNodeIds: ['economics.statistics.data'] },
        { id: 'up.sst.11.eco10', order: 46, title: '[Economics] Indian Economy on the Eve of Independence', kgNodeIds: ['economics.indian_economy.planning'] },
        { id: 'up.sst.11.eco11', order: 47, title: '[Economics] Indian Economy 1950–1990', kgNodeIds: ['economics.indian_economy.planning'] },
        { id: 'up.sst.11.eco12', order: 48, title: '[Economics] Liberalisation, Privatisation and Globalisation', kgNodeIds: ['economics.globalisation.trade'] },
        { id: 'up.sst.11.eco13', order: 49, title: '[Economics] Poverty', kgNodeIds: ['economics.development.poverty'] },
        { id: 'up.sst.11.eco14', order: 50, title: '[Economics] Human Capital Formation in India', kgNodeIds: ['economics.development.poverty'] },
        { id: 'up.sst.11.eco15', order: 51, title: '[Economics] Rural Development', kgNodeIds: ['economics.indian_economy.planning'] },
        { id: 'up.sst.11.eco16', order: 52, title: '[Economics] Employment — Growth, Informalisation', kgNodeIds: ['economics.indian_economy.sectors'] },
        { id: 'up.sst.11.eco17', order: 53, title: '[Economics] Infrastructure', kgNodeIds: ['geography.india_resources.industries_transport'] },
        { id: 'up.sst.11.eco18', order: 54, title: '[Economics] Environment and Sustainable Development', kgNodeIds: ['geography.human_geography.development'] },
        { id: 'up.sst.11.eco19', order: 55, title: '[Economics] Comparative Development of India, China and Pakistan', kgNodeIds: ['economics.development.poverty'] },
      ],
    },
    {
      grade: 12,
      chapters: [
        { id: 'up.sst.12.hist1', order: 1, title: '[History] Bricks, Beads and Bones — Harappan Civilisation', kgNodeIds: ['history.ancient_india.harappan'] },
        { id: 'up.sst.12.hist2', order: 2, title: '[History] Kings, Farmers and Towns — Early States', kgNodeIds: ['history.ancient_india.maurya_gupta'] },
        { id: 'up.sst.12.hist3', order: 3, title: '[History] Kinship, Caste and Class — Early Societies', kgNodeIds: ['history.ancient_india.vedic_period'] },
        { id: 'up.sst.12.hist4', order: 4, title: '[History] Thinkers, Beliefs and Buildings — Buddhism', kgNodeIds: ['history.ancient_india.buddhism_jainism'] },
        { id: 'up.sst.12.hist5', order: 5, title: '[History] Through the Eyes of Travellers — Medieval India', kgNodeIds: ['history.medieval_india.mughal_empire'] },
        { id: 'up.sst.12.hist6', order: 6, title: '[History] Bhakti-Sufi Traditions', kgNodeIds: ['history.ancient_india.buddhism_jainism'] },
        { id: 'up.sst.12.hist7', order: 7, title: '[History] An Imperial Capital — Vijayanagara', kgNodeIds: ['history.medieval_india.regional_kingdoms'] },
        { id: 'up.sst.12.hist8', order: 8, title: '[History] Peasants, Zamindars and the State', kgNodeIds: ['history.medieval_india.mughal_empire'] },
        { id: 'up.sst.12.hist9', order: 9, title: '[History] Kings and Chronicles — Mughal Court', kgNodeIds: ['history.medieval_india.mughal_empire'] },
        { id: 'up.sst.12.hist10', order: 10, title: '[History] Colonialism and the Countryside', kgNodeIds: ['history.modern_india.colonial_period'] },
        { id: 'up.sst.12.hist11', order: 11, title: '[History] Rebels and the Raj — 1857 Revolt', kgNodeIds: ['history.modern_india.colonial_period'] },
        { id: 'up.sst.12.hist12', order: 12, title: '[History] Colonial Cities — Urbanisation and Architecture', kgNodeIds: ['history.modern_india.colonial_period'] },
        { id: 'up.sst.12.hist13', order: 13, title: '[History] Mahatma Gandhi and the Nationalist Movement', kgNodeIds: ['history.modern_india.independence_movement'] },
        { id: 'up.sst.12.hist14', order: 14, title: '[History] Understanding Partition', kgNodeIds: ['history.post_independence.constitution'] },
        { id: 'up.sst.12.hist15', order: 15, title: '[History] Framing the Constitution', kgNodeIds: ['history.post_independence.constitution'] },
        { id: 'up.sst.12.geo1', order: 16, title: '[Geography] Human Geography — Nature and Scope', kgNodeIds: ['geography.human_geography.population'] },
        { id: 'up.sst.12.geo2', order: 17, title: '[Geography] The World Population — Distribution and Growth', kgNodeIds: ['geography.human_geography.population'] },
        { id: 'up.sst.12.geo3', order: 18, title: '[Geography] Population Composition', kgNodeIds: ['geography.human_geography.population'] },
        { id: 'up.sst.12.geo4', order: 19, title: '[Geography] Human Development', kgNodeIds: ['geography.human_geography.development'] },
        { id: 'up.sst.12.geo5', order: 20, title: '[Geography] Primary Activities — Agriculture and Gathering', kgNodeIds: ['geography.india_resources.agriculture'] },
        { id: 'up.sst.12.geo6', order: 21, title: '[Geography] Secondary Activities — Manufacturing', kgNodeIds: ['geography.india_resources.industries_transport'] },
        { id: 'up.sst.12.geo7', order: 22, title: '[Geography] Tertiary and Quaternary Activities', kgNodeIds: ['geography.india_resources.industries_transport'] },
        { id: 'up.sst.12.geo8', order: 23, title: '[Geography] Transport and Communication', kgNodeIds: ['geography.india_resources.industries_transport'] },
        { id: 'up.sst.12.geo9', order: 24, title: '[Geography] International Trade', kgNodeIds: ['economics.globalisation.trade'] },
        { id: 'up.sst.12.geo10', order: 25, title: '[Geography] Human Settlements', kgNodeIds: ['geography.human_geography.population'] },
        { id: 'up.sst.12.geo11', order: 26, title: '[Geography] India — Population Distribution and Growth', kgNodeIds: ['geography.human_geography.population'] },
        { id: 'up.sst.12.geo12', order: 27, title: '[Geography] Migration — Types, Causes and Consequences', kgNodeIds: ['geography.human_geography.population'] },
        { id: 'up.sst.12.geo13', order: 28, title: '[Geography] Human Development in India', kgNodeIds: ['geography.human_geography.development'] },
        { id: 'up.sst.12.geo14', order: 29, title: '[Geography] Land Resources and Agriculture', kgNodeIds: ['geography.india_resources.agriculture'] },
        { id: 'up.sst.12.geo15', order: 30, title: '[Geography] Water Resources', kgNodeIds: ['geography.india_resources.agriculture'] },
        { id: 'up.sst.12.geo16', order: 31, title: '[Geography] Mineral and Energy Resources', kgNodeIds: ['geography.india_resources.minerals_energy'] },
        { id: 'up.sst.12.geo17', order: 32, title: '[Geography] Manufacturing Industries', kgNodeIds: ['geography.india_resources.industries_transport'] },
        { id: 'up.sst.12.geo18', order: 33, title: '[Geography] Planning and Sustainable Development', kgNodeIds: ['geography.human_geography.development'] },
        { id: 'up.sst.12.pol1', order: 34, title: '[Political Science] The Cold War Era', kgNodeIds: ['history.post_independence.contemporary'] },
        { id: 'up.sst.12.pol2', order: 35, title: '[Political Science] The End of Bipolarity', kgNodeIds: ['history.post_independence.contemporary'] },
        { id: 'up.sst.12.pol3', order: 36, title: '[Political Science] US Hegemony in World Politics', kgNodeIds: ['civics.international_relations.un'] },
        { id: 'up.sst.12.pol4', order: 37, title: '[Political Science] Alternative Centres of Power', kgNodeIds: ['civics.international_relations.un'] },
        { id: 'up.sst.12.pol5', order: 38, title: '[Political Science] Contemporary South Asia', kgNodeIds: ['civics.international_relations.un'] },
        { id: 'up.sst.12.pol6', order: 39, title: '[Political Science] International Organisations', kgNodeIds: ['civics.international_relations.un'] },
        { id: 'up.sst.12.pol7', order: 40, title: '[Political Science] Security in the Contemporary World', kgNodeIds: ['civics.international_relations.un'] },
        { id: 'up.sst.12.pol8', order: 41, title: '[Political Science] Environment and Natural Resources', kgNodeIds: ['geography.human_geography.development'] },
        { id: 'up.sst.12.pol9', order: 42, title: '[Political Science] Globalisation', kgNodeIds: ['economics.globalisation.trade'] },
        { id: 'up.sst.12.pol10', order: 43, title: '[Political Science] Era of One-Party Dominance', kgNodeIds: ['history.post_independence.contemporary'] },
        { id: 'up.sst.12.pol11', order: 44, title: '[Political Science] Nation Building and Its Problems', kgNodeIds: ['history.post_independence.constitution'] },
        { id: 'up.sst.12.pol12', order: 45, title: '[Political Science] Politics of Planned Development', kgNodeIds: ['economics.indian_economy.planning'] },
        { id: 'up.sst.12.pol13', order: 46, title: '[Political Science] India\'s External Relations', kgNodeIds: ['civics.international_relations.un'] },
        { id: 'up.sst.12.pol14', order: 47, title: '[Political Science] Challenges to the Congress System', kgNodeIds: ['history.post_independence.contemporary'] },
        { id: 'up.sst.12.pol15', order: 48, title: '[Political Science] Crisis of the Democratic Order', kgNodeIds: ['history.post_independence.contemporary'] },
        { id: 'up.sst.12.pol16', order: 49, title: '[Political Science] Rise of Popular Movements', kgNodeIds: ['history.post_independence.contemporary'] },
        { id: 'up.sst.12.pol17', order: 50, title: '[Political Science] Regional Aspirations', kgNodeIds: ['civics.constitution.federalism'] },
        { id: 'up.sst.12.pol18', order: 51, title: '[Political Science] Recent Developments in Indian Politics', kgNodeIds: ['history.post_independence.contemporary'] },
      ],
    },
  ],
}

export function getUPSocialScienceChapters(grade: number) {
  return UP_SOCIAL_SCIENCE_CATALOG.grades.find((g) => g.grade === grade)?.chapters ?? []
}
