import type { KnowledgeNode } from './educationTypes'

export const URDU_KNOWLEDGE_GRAPH: KnowledgeNode[] = [
  // ─── SCRIPT AND PHONOLOGY ────────────────────────────────────
  { id: 'urdu.script_nastaliq', domain: 'urdu', title: 'Urdu Script — Nastaliq', description: 'Nastaliq script — right-to-left writing; Urdu alphabet — 36 letters; haroof-e-tehajji; matra system — zabar, zer, pesh, tanwin; nuqta (dot) system; shaddah and sukun; ligatures; joiners and non-joiners; difference between similar letters; Urdu keyboard and digital writing', difficulty: 'foundational', prerequisites: [] },
  { id: 'urdu.phonology', domain: 'urdu', title: 'Urdu Phonology and Pronunciation', description: 'Urdu sounds — vowels and consonants; short and long vowels (maddah); aspirated and non-aspirated consonants; retroflex sounds; nasal sounds (ghunna); sounds unique to Urdu — qaf, ghain, ain, ha; relationship between script and sound; correct pronunciation practice', difficulty: 'foundational', prerequisites: ['urdu.script_nastaliq'] },

  // ─── VOCABULARY ──────────────────────────────────────────────
  { id: 'urdu.vocabulary_basics', domain: 'urdu', title: 'Urdu Vocabulary — Roots and Word Formation', description: 'Arabic, Persian and Hindi/Sanskrit roots in Urdu; singular and plural (mufrad and jamaa); masculine and feminine (muzakkar and muannas); word families; synonyms (muradif); antonyms (mutazad); compound words (murakkab); loanwords; formal and informal vocabulary', difficulty: 'foundational', prerequisites: ['urdu.script_nastaliq'] },
  { id: 'urdu.muhavare_lokokti', domain: 'urdu', title: 'Muhavare and Lokokti (Idioms and Proverbs)', description: 'Common Urdu idioms (muhavare); Urdu proverbs (lokokti and mahavre); figurative vs literal meaning; using idioms in sentences; cultural context of Urdu expressions; classical phrases from poetry; role of idioms in Urdu literature', difficulty: 'developing', prerequisites: ['urdu.vocabulary_basics'] },

  // ─── GRAMMAR ─────────────────────────────────────────────────
  { id: 'urdu.grammar_parts_of_speech', domain: 'urdu', title: 'Parts of Speech — Kalam ke Ajza', description: 'Ism (noun) — common and proper, abstract, collective; zamir (pronoun); fail (verb) — transitive and intransitive; sifat (adjective); zaroof (adverb); huroof (prepositions, conjunctions, interjections); ilm-ul-sarf basics; role of each part in sentences', difficulty: 'developing', prerequisites: ['urdu.vocabulary_basics'] },
  { id: 'urdu.grammar_sentence', domain: 'urdu', title: 'Sentence Structure — Jumla', description: 'Simple sentence (mufrad jumla); compound sentence (murakkab jumla); complex sentence; subject (fail) and predicate (khabar); direct and indirect object; active and passive voice (malooma and majhool); reported speech (naql-e-kalam); sentence transformation', difficulty: 'developing', prerequisites: ['urdu.grammar_parts_of_speech'] },
  { id: 'urdu.grammar_tense', domain: 'urdu', title: 'Tenses and Verb Forms', description: 'Present tense (haal); past tense (mazi) — simple, habitual, continuous, perfect; future tense (mustaqbil); auxiliary verbs — hona, karna; negative sentences; interrogative forms; conditional sentences (sharth-o-jaza); verb agreement with subject in gender and number', difficulty: 'proficient', prerequisites: ['urdu.grammar_sentence'] },

  // ─── READING AND COMPREHENSION ───────────────────────────────
  { id: 'urdu.nasr_comprehension', domain: 'urdu', title: 'Nasr (Prose) Reading and Comprehension', description: 'Reading Urdu prose fluently; identifying main idea and supporting details; inferential comprehension; summarising passages; author\'s tone and purpose; formal prose — essays, articles; functional prose — letters, reports; annotating text; close reading strategies', difficulty: 'developing', prerequisites: ['urdu.phonology'] },
  { id: 'urdu.nasr_types', domain: 'urdu', title: 'Types of Urdu Prose', description: 'Mazameen (essays) — types and structure; afsana (short story) — plot, character, setting; dastan (folk narrative); safarnaama (travelogue); khutoot (letters); sawaneh umri (biography/autobiography); insha (creative prose); reportage; characteristics and examples of each genre', difficulty: 'proficient', prerequisites: ['urdu.nasr_comprehension'] },

  // ─── POETRY ──────────────────────────────────────────────────
  { id: 'urdu.poetry_basics', domain: 'urdu', title: 'Introduction to Urdu Poetry — Aruz', description: 'Characteristics of Urdu poetry; meter (bahre-aruz) — concept of taqtee; rhyme (qafiya); refrain (radif); foot (rukn); matla (opening couplet); maqta (closing couplet); basic poetic vocabulary — shair, shayari, misra, sher', difficulty: 'developing', prerequisites: ['urdu.script_nastaliq'] },
  { id: 'urdu.ghazal', domain: 'urdu', title: 'Ghazal', description: 'Structure of ghazal — matla, maqta, qafiya, radif; unity and independence of couplets; themes — ishq (love), firaaq (separation), zindagi, falsafa; major ghazal poets — Mir Taqi Mir, Ghalib, Daagh, Faiz, Jigar; reading and appreciating classical and modern ghazals; takhallus', difficulty: 'proficient', prerequisites: ['urdu.poetry_basics'] },
  { id: 'urdu.nazm', domain: 'urdu', title: 'Nazm (Poem)', description: 'Types of nazm — pabandh (structured), aazad (free verse), nasri (prose poem); unity of theme; narrative and lyric nazm; major nazm poets — Iqbal, Josh, Faiz, Majaz, Sahir; patriotic nazm; social nazm; nature poetry; nazm vs ghazal comparison; appreciating imagery and symbolism', difficulty: 'proficient', prerequisites: ['urdu.poetry_basics'] },
  { id: 'urdu.qasida_marsiya', domain: 'urdu', title: 'Qasida, Marsiya and Rubai', description: 'Qasida — panegyric poetry, structure, historical context; Marsiya — elegy, Karbala tradition, Anees and Dabeer; Rubai — quatrain form (Rumi, Omar Khayyam tradition in Urdu); Masnavi — narrative poem, Mir Hasan, Rumi\'s Masnavi; classical poetic forms and their social functions', difficulty: 'advanced', prerequisites: ['urdu.ghazal'] },
  { id: 'urdu.literary_devices', domain: 'urdu', title: 'Literary Devices — Sanaat-e-Shairi', description: 'Tasbeeh (simile); istiara (metaphor); kinaya (allusion); majaz (metonymy); tashkhees (personification); mubalaagha (hyperbole); husn-e-taleel (creative causation); iham (pun); tazaad (antithesis); repetition; imagery; symbolism; identifying and analysing these in poetry', difficulty: 'proficient', prerequisites: ['urdu.ghazal', 'urdu.nazm'] },

  // ─── WRITING SKILLS ──────────────────────────────────────────
  { id: 'urdu.khat_nigari', domain: 'urdu', title: 'Khat Nigari — Letter Writing', description: 'Types of letters — formal (rasmi) and informal (ghair rasmi); letter format — mukhatib, salam, mazmoon, khata-tam; personal letters; official letters; application writing; complaint letters; business correspondence; government letters; tone and register; salutations in Urdu', difficulty: 'developing', prerequisites: ['urdu.grammar_sentence'] },
  { id: 'urdu.insha_nigari', domain: 'urdu', title: 'Insha Nigari — Essay Writing', description: 'Essay types — descriptive, narrative, argumentative, reflective; essay structure — introduction, body paragraphs, conclusion; choosing a title; outlining; topic sentences; coherence and cohesion; Urdu essay style — classical and modern; editing and proofreading; writing on social, environmental and national themes', difficulty: 'proficient', prerequisites: ['urdu.nasr_comprehension'] },
  { id: 'urdu.khulasa_tafseel', domain: 'urdu', title: 'Khulasa and Tafseel — Summary and Expansion', description: 'Writing khulasa (summary) — identifying key points, reducing to one-third, own words; writing tafseel (expansion) — expanding a proverb or couplet into a paragraph; paraphrasing; avoiding plagiarism; maintaining meaning fidelity; formal register in summaries', difficulty: 'proficient', prerequisites: ['urdu.insha_nigari'] },
  { id: 'urdu.report_writing', domain: 'urdu', title: 'Khabar and Report Writing', description: 'News report structure — headline, dateline, lead paragraph, body; journalistic Urdu style; objectivity vs subjectivity; feature writing; review writing — book, film; narrative reports; school magazine writing; formal report structure for examinations', difficulty: 'advanced', prerequisites: ['urdu.insha_nigari'] },

  // ─── LITERATURE ──────────────────────────────────────────────
  { id: 'urdu.classical_literature', domain: 'urdu', title: 'Classical Urdu Literature', description: 'History of Urdu literature — Dakkan period (Quli Qutb Shah, Wali Dakhani); Delhi School — Mir Taqi Mir, Mir Dard; Lucknow School — Nasikh, Atish; Fort William College; reform movement — Ghalib; Sir Syed and Aligarh movement; Hali and Shibli; the divan tradition', difficulty: 'proficient', prerequisites: ['urdu.ghazal'] },
  { id: 'urdu.modern_literature', domain: 'urdu', title: 'Modern Urdu Literature', description: 'Progressive Writers\' Movement (Anjuman Taraqqi Pasand Musannifeen); Ismat Chughtai; Saadat Hasan Manto; Krishan Chander; Rajinder Singh Bedi; feminist writers; post-partition literature; contemporary Urdu fiction; Urdu in the digital age; Bollywood and Urdu poetry', difficulty: 'advanced', prerequisites: ['urdu.classical_literature'] },
  { id: 'urdu.major_poets', domain: 'urdu', title: 'Major Urdu Poets — Life and Works', description: 'Mirza Ghalib — life, diwan, letters, philosophy; Allama Iqbal — Bang-e-Dara, Armaghaan-e-Hijaz, philosophy of khudi; Faiz Ahmed Faiz — revolutionary poetry; Josh Malihabadi; Sahir Ludhianvi; Kaifi Azmi; regional poets; literary criticism of their works; contextualising poets in history', difficulty: 'proficient', prerequisites: ['urdu.ghazal', 'urdu.nazm'] },
  { id: 'urdu.major_writers', domain: 'urdu', title: 'Major Urdu Prose Writers', description: 'Munshi Premchand — Godaan, Kafan, Shatranj ke Khiladi; Sir Syed Ahmed Khan — essays on education and society; Altaf Hussain Hali — Musaddas; Maulana Abul Kalam Azad; Rashid Ahmed Siddiqui — humour; Ibn-e-Safi — detective fiction; reading and analysing selected texts', difficulty: 'proficient', prerequisites: ['urdu.nasr_types'] },

  // ─── FUNCTIONAL URDU ─────────────────────────────────────────
  { id: 'urdu.functional_language', domain: 'urdu', title: 'Functional and Communicative Urdu', description: 'Formal and informal registers; spoken vs written Urdu; Urdu in media — newspapers, TV, radio; Urdu in judiciary and administration; official language status; Devanagari Urdu; transliteration; SMS and social media Urdu; Roman Urdu; code-switching in speech; listening comprehension', difficulty: 'developing', prerequisites: ['urdu.grammar_sentence'] },
  { id: 'urdu.translation', domain: 'urdu', title: 'Translation — Tarjuma', description: 'Urdu to Hindi translation; Hindi to Urdu translation; principles of translation — equivalence, naturalness, accuracy; cultural untranslatables; literary translation vs literal translation; translating poetry — challenges; practice passages for examination; bilingual vocabulary building', difficulty: 'proficient', prerequisites: ['urdu.vocabulary_basics', 'urdu.grammar_sentence'] },
]

export function getUrduNode(id: string): KnowledgeNode | undefined {
  return URDU_KNOWLEDGE_GRAPH.find((n) => n.id === id)
}

export function getUrduNodesByDomain(domain: string): KnowledgeNode[] {
  return URDU_KNOWLEDGE_GRAPH.filter((n) => n.domain === domain)
}
